<!-- Footnotes-->
<div id="footnotes"> <?php footNote('J',2,1); ?> paras 82 and 87,<em> Mosley v News Group Newspapers Ltd</em> [2008] EWHC QB 1777</p>
 <?php footNote('J',2,2); ?> p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Kelvin-MacKenzie.pdf">Kelvin-MacKenzie.pdf</a></p>
 <?php footNote('J',2,3); ?> p9, line 8, Ian Hislop, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-18-January-2012.pdf">Transcript-of-Morning-Hearing-18-January-2012.pdf</a></p>
 <?php footNote('J',2,4); ?> pp55-56, lines 7-14, Michael Gove, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-29-May-2012.pdf">Transcript-of-Afternoon-Hearing-29-May-2012.pdf</a></p>
 <?php footNote('J',2,5); ?> <?php internalChapterLink('../../','E',4); ?></p>
 <?php footNote('J',2,6); ?> Home Office Large Major Enquiry System</p>
 <?php footNote('J',2,7); ?> s8 et seq of the Police and Criminal Evidence Act 1984 (PACE)</p>
 <?php footNote('J',2,8); ?> s19 PACE</p>
 <?php footNote('J',2,9); ?> Appendix 4</p>
 <?php footNote('J',2,10); ?> pp1-2, para 3 and pp3-4, para 7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Second-Witness-Statement-of-DAC-Sue-Akers1.pdf">Second-Witness-Statement-of-DAC-Sue-Akers1.pdf</a></p>
 <?php footNote('J',2,11); ?> pp12-13, lines 24-8, Sue Akers, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-6-February-2012.pdf">Transcript-of-Morning-Hearing-6-February-2012.pdf</a></p>
 <?php footNote('J',2,12); ?> As I have made clear in <?php internalChapterLink('../../','E',5); ?>, there is an issue about the way in which the relationship between theManagement and Standards Committee and the MPS has recently developed. I repeat that I am satisfied that it is notappropriate to elaborate further although the assistance upon which the police have had to depend only serves tomake the point that this Chapter identifies</p>
 <?php footNote('J',2,13); ?> <?php internalChapterLink('../../','E',4); ?></p>
 <?php footNote('J',2,14); ?> <em> R v. Bristol Crown Court, ex parte Bristol Press and Picture Agency Ltd</em> [1986] 85 Cr App R 190 per Glidewell LJ at 196and R v. Central Criminal Court ex parte Bright and others [2001] 1 WLR 662 per Judge LJ (as he then was) at p679 </p>
 <?php footNote('J',2,15); ?> <?php internalChapterLink('../../','E',4); ?></p>
 <?php footNote('J',2,16); ?> EC Regulation 561/2006 on drivers&#8217; hours and tachographs (together with regulations 3820/85, 3821/85, 3314/90,3688/92, 2479/95, read with the regulations relating to driver&#8217;s hours and recording equipment, in particular SI2006/1117, SI 2007/1819 and Part VI of the Transport Act 1968 as amended</p>
 <?php footNote('J',2,17); ?> For example, the majority of organisations operating as financial services markets, exchanges and firms which areregulated by the Financial Services Authority, and firms defined as the regulated sector under the Proceeds of CrimeAct 2002 commonly have compliance departments</p>
 <?php footNote('J',2,18); ?> For example, note the self-reporting and notification requirements imposed and encouraged by the Solicitors Regulatory Authority in relation to the conduct of solicitors. See also the legal obligation imposed on banks and other financial services firms to report suspicious activity in the context of money laundering and terrorist financing to the Serious Organised Crime Agency if they know or suspect, or have reasonable grounds to know or suspect, that another individual or person is engaged in money laundering; and the information came to them in the course of their business in the regulated sector. It is an offence for an individual working in the regulated sector not to report to their &#8216;Nominated Officer&#8217; or SOCA if the conditions for reporting have been met. The Proceeds of Crime Act 2002 also makes it an offence for a nominated officer not to disclose to SOCA if the conditions for reporting have been met (see sections 330 and 331) </p>
 <?php footNote('J',2,19); ?> <?php internalChapterLink('../../','J',3); ?></p>
 <?php footNote('J',2,20); ?> Part E</p>
 <?php footNote('J',2,21); ?> pp71-71, lines 8-3, Sheryl Gascoigne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-23-November-20111.pdf">Transcript-of-Morning-Hearing-23-November-20111.pdf</a></p>
 <?php footNote('J',2,22); ?> pp11-12, lines 15-17, Sienna Miller, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-24-November-2011.pdf">Transcript-of-Morning-Hearing-24-November-2011.pdf</a></p>
 <?php footNote('J',2,23); ?> The majority of the press core participants have argued in favour of a public interest defence for journalists, seefor example News International closing submissions at para 64, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-News-International.pdf">Closing-Submission-from-News-International.pdf</a>, Associated Newspapers closing submissionsat para 31 <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-Associated-Newspapers-Ltd.pdf">Closing-Submission-from-Associated-Newspapers-Ltd.pdf</a>, Guardian News closing submissions at para 17 <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-Guardian-News-and-Media-Ltd.pdf">Closing-Submission-from-Guardian-News-and-Media-Ltd.pdf</a>. See also part 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Media-Standards-Trust.pdf">Submission-by-Media-Standards-Trust.pdf</a>; Part 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Professor-Roy-Greenslade-of-City-University.pdf">Submission-by-Professor-Roy-Greenslade-of-City-University.pdf</a> which support a general public interest defence for journalists </p>
 <?php footNote('J',2,24); ?> pp56-57, lines 21-6, Will Lewis, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-10-January-2012.pdf">Transcript-of-Afternoon-Hearing-10-January-2012.pdf</a>; para 31.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-William-Lewis.pdf">Witness-Statement-of-William-Lewis.pdf</a></p>
 <?php footNote('J',2,25); ?> Details contained in the judgment of the Court of Appeal [2012] EWCA Crim 1243</p>
 <?php footNote('J',2,26); ?> HC Hansard, Debates, 29 January 1951<em> ,</em> vol 483, col 681</p>
 <?php footNote('J',2,27); ?> paras 12-13, http://cps.gov.uk/publications/code_for_crown_prosecutors/index.html</p>
 <?php footNote('J',2,28); ?> p23, lines 2-17, Keir Starmer QC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-8-February-2012.pdf">Transcript-of-Afternoon-Hearing-8-February-2012.pdf</a></p>
 <?php footNote('J',2,29); ?> http://www.cps.gov.uk/legal/d_to_g/guidance_for_prosecutors_on_assessing_the_public_interest_in_cases_affecting_the_media_/</p>
 <?php footNote('J',2,30); ?> [1992] 14 EHRR 123</p>
 <?php footNote('J',2,31); ?> [2002] UKHL 11</p>
 <?php footNote('J',2,32); ?> [2004] EWCA Crim 868</p>
 <?php footNote('J',2,33); ?> Reference is made to Article 8 of the ECHR</p>
 <?php footNote('J',2,34); ?> Goodwin v UK (1996) 22 EHRR 123 paragraph 39; see also Ashworth Hospital Authority v MGN Ltd [2002] 1 WLR2003 and Mersey Care NHS Trust v Ackroyd [2007] EWCA Civ 101</p>
 <?php footNote('J',2,35); ?> p23, line 13, Keir Starmer QC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-8-February-2012.pdf">Transcript-of-Afternoon-Hearing-8-February-2012.pdf</a></p>
 <?php footNote('J',2,36); ?> See<em> R v. FB, R v. AB, R v. JC</em> [2010] EWCA Crim 1857 and the cases therein cited and<em> R v. SH</em> [2010] EWCA Crim 1931</p>
 <?php footNote('J',2,37); ?> See, for example,<em> R v. Horseferry Road Magistrates&#8217; Court ex parte Bennett</em> [1994] 1 AC 42,<em> R v. Mullen</em> [2000] QB 520</p>
 <?php footNote('J',2,38); ?> Per Lord Steyn in<em> R v. Latif</em> [1996] 1 WLR 104 at page 112</p>
 <?php footNote('J',2,39); ?> See<em> R v. Grant</em> [2006] QB 60 per Laws LJ at para 54</p>
 <?php footNote('J',2,40); ?> The exception is, of course, where the penalty is fixed by law: effectively, this only applies in relation to murder</p>
 <?php footNote('J',2,41); ?> This recommendation is dealt with at length in <?php internalChapterLink('../../','H',5); ?></p>
 <?php footNote('J',2,42); ?> s120(6)(d) of the Coroners and Justice Act 2009</p>
 <?php footNote('J',2,43); ?> <?php internalChapterLink('../../','E',5); ?></p>
 <?php footNote('J',2,44); ?> <em> Sugar v British Broadcasting Corporation</em> [2012] UKSC 4 per Lord Phillips (at para 67) &#8220;Information should only befound to be held for the purposes of journalism ... if an immediate object of holding the information is to use it forone of those purposes&#8221;; Lord Walker (at para. 84) &#8220;The question whether information is held for the purposes of journalism should thus be considered in a relatively narrow rather than a relatively wide way&#8221;; Lord Brown (at par 106) that &#8220;the central question to be asked ... will be ... whether there remains any sufficiently direct link between the BBC&#8217;s continuing holding of the information and the achievement of its journalistic purposes&#8221;. See also para 6.4 of the Annex of Legal Framework </p>
 <?php footNote('J',2,45); ?> pp12-13, paras 3.2-3.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-submussion-from-MPS.pdf">Closing-submussion-from-MPS.pdf</a></p>
 <?php footNote('J',2,46); ?> Para 6 of Schedule 5 of the Terrorism Act 2005</p>
 <?php footNote('J',2,47); ?> I do not ignore the considerations that flow from Article 10 of the ECHR and s. 10 of the Contempt of Court Act 1981(as to which there is no material difference in principle: see Camelot Group plc v Centaur Communications [1999] QB  124 at 138G per Thorpe LJ). The courts will continue to have to consider these provisions and carry out a balancing  exercise in any case involving the press even if the material is neither journalistic material or excluded within the  PACE definitions: a summary of the position can be found in Shiv Malik v Manchester Crown Court [2008] EWHC 1362  (Admin) per Dyson LJ (as he then was) at paras 48 et seq </p>
 </div>
