<div class="content" id="contentPartBChapter4">
<h1 id="top">CHAPTER 4<br/>THE RESPONSIBILITIES OF THE PRESS</h1>
  <?php sectionAnchor('B',4,1); ?>Context</h2>
 <?php paragraphLink('B',4,1,1); ?>The idea that freedom of expression comes with responsibilities is both obvious and entirely familiar. Article 10(2) of the ECHR provides that the right to freedom of expression &#8220;carries with it duties and responsibilities&#8221;. In part, this is because, as discussed in Chapter 3, unrestricted speech has the power to harm competing public interests, including the free speech of others. It is also because the press is an institution of considerable power and the exercise of power in a democratic context brings with it proportionate responsibility for the consequences of choices to do so. Moreover, where power is exercised purportedly in the public interest, then there is a particularly acute responsibility to account for the exercise of that power to the public in whose name it is exercised.</p>
  <?php sectionAnchor('B',4,2); ?>Press power and the impact on society</h2>
 <?php paragraphLink('B',4,2,1); ?>In order to understand the responsibilities incumbent on the press, it is necessary to consider the nature of press power and the potential it has to impact on society. One obvious aspect of the power wielded by the press is its capacity for mass communication :1 &#8220;Mass communication has powers that local, individual, communication does not. Mass communication allows others to criticize, to inform of the failings, crimes, and deceit of the powerful. Mass communication allows agents to assemble, to unite, to form dissident movements, to organize and oppose those in power.&#8221; </p>
  <?php paragraphLink('B',4,2,2); ?>It is on account of this capacity of the press to communicate to large audiences, that the idea of the &#8220;megaphone effect&#8221; of the press was invoked with such frequency throughout the Inquiry. The megaphone effect of the press has a tremendous capacity to serve the public interest. It is because of the ability of the press to reach a wide audience that it is taken seriously by, and therefore able to stand up to, other institutions of power.<?php footnoteRef('B',4,2); ?></p>
<blockquote>&#8220;[O]ne aspect of the public interest in a free press is that it provides an essential set of checks and balances on power (and, more importantly, the abuse of power): in all too many parts of the world the state routinely tortures and murders its citizens, though reporting of such facts is strictly prohibited. This can help a vicious regime retain an air of legitimacy, or, in some cases, even to present the air of democratic legitimacy (there are putative democracies which have serious restrictions on press freedom). Similarly, the there is a public interest in learning of dangers and risks, even where others may wish to conceal them. A powerful industrialist might wish to conceal the fact that his factories are polluting the water supply, or that his company&#8217;s product is carcinogenic. A free press, free of the censorship and restrictions imposed by the powerful, thus serves the public interest by its investigative and communicative roles.&#8221;</blockquote>
  <?php paragraphLink('B',4,2,3); ?>This power of the press to reach a wide audience, whilst having the capacity to do great good, carries certain risks:<?php footnoteRef('B',4,3); ?>
<blockquote>&#8220;Communication is a relational process, taking place between speaker (or writer) and audiences. A powerful media, even a powerful free media, can effectively block dissenting voices&#8221;.</blockquote> Mass communication by the press can block dissenting voices in a number of ways. One is by preventing access to audiences. Access to audiences is integral to the ability of individuals to experience the communicative aspects of free speech:<?php footnoteRef('B',4,4); ?></p>
<blockquote>&#8220;Expression can be done by a lone individual, but communication is essentially relational, and involves others. Individual speakers have an interest in being accessible to audiences. Communication can be stifled, not by blocking speech, but by blocking access to audiences. For example, suppose a cunning King permits dissenting political views to be expressed, but only at the bottom of a deep mine shaft. Though here, strictly speaking, one has an opportunity to express one&#8217;s views, one is not free to have them heard. Not only do we have an interest in there being an audience for our speech, we also have an interest in our being the audience to others&#8217; speech.&#8221; </blockquote>
  <?php paragraphLink('B',4,2,4); ?>Clearly, if a particular individual or group of individuals are denied access to the press to promote their views, their ability to reach audiences is diminished:<?php footnoteRef('B',4,5); ?></p>
<blockquote>&#8220;Writers of such columns in the press can seek to mitigate these criticisms by endeavouring to articulate what they take to be important or widespread lines of thought. But this still points to the fact that in terms of self-expression the press only allows a select few to promulgate their views. Although absence of censorship allows others to set up press outlets, in principle the resources required to do this effectively limit this opportunity. This argument could be taken further and it could be said that the public interest in freedom of expression can even be adversely affected by a free press, if certain other conditions hold such that some voices get much more prominence than others. In those conditions the power of the press as a medium of expression may lead to certain views dominating the public sphere and other views being squeezed out.&#8221; </blockquote>
  <?php paragraphLink('B',4,2,5); ?>One consequence is that views expressed through the press megaphone are more likely to predominate: &#8220;Whether something&#8217;s liable to be noticed, what effects it&#8217;s liable to have on other people&#8217;s perceptions must be very relevant&#8221;;<?php footnoteRef('B',4,6); ?> &#8220;Financial power ensures that one sort of idea is more likely to be promoted in the newspapers people read than another sort of idea&#8221;.<?php footnoteRef('B',4,7); ?></p>
  <?php paragraphLink('B',4,2,6); ?>The tendency of views expressed in the press to prevail can be also be explained by a second, and related, facet of press power. There is no doubt that the press is considered a voice of authority in society. In many quarters, it has rightly earned a reputation for accurate and vigorous reporting, independence and holding power to account. It is because of the authoritative quality of the press, combined with its access to mass audiences, that communication by the press, as an institution of considerable power, has a significant impact on society. It can set the news agenda, shape culture and change perceptions:<?php footnoteRef('B',4,8); ?> <?php footnoteRef('B',4,9); ?> <?php footnoteRef('B',4,10); ?> </p>
  <blockquote>&#8220;There is a great deal of difference between &#8216;a bloke down the pub&#8217; claiming, to his fellow drinkers, that the MMR vaccine causes autism, and a broadsheet newspaper doing the same thing. Media institutions can shape public opinion, they can entrench, or change, public opinion in a way that individual speakers cannot.&#8221;</blockquote>
  <?php paragraphLink('B',4,2,7); ?>The existence of a press with such significant power is a potent antidote to the dominance of big business and government; but it also has potential to do great harm if not exercised with responsibility:<?php footnoteRef('B',4,11); ?></p>
<blockquote>&#8220;If someone in a position of moral or political authority makes a statement about race or about gender, it isn&#8217;t simply that there will be a wider audience for that but also that the opinion comes with a greater degree of &#8211; with an imprimatur, or seems to, and that itself is problematic. That&#8217;s why positions of responsibility in society are very difficult, because you have to take a lot of care about what you say because people pay attention to it.&#8221; </blockquote>
  <?php paragraphLink('B',4,2,8); ?>The press has the power to cultivate stereotypes, not just as a matter of the megaphone effect, but by cumulative effect also:<?php footnoteRef('B',4,12); ?></p>
<blockquote>&#8220;there is an asymmetry between the individual case and the case of the press. One of the reasons we tolerate the fairly broad-ranging right of individual expression is that individuals&#8217; remarks are typically limited in their impact&#8230; But &#8230;this megaphone effect is a kind of culture-shaping effect &#8230; It exerts much greater influence and power on people, how they&#8217;re perceived by others, creating stereotypes or creating certain assumptions in society.&#8221;<?php footnoteRef('B',4,13); ?> <br/>&#8220;It means that publications in the press are peculiarly vulnerable to promoting stereotypes, because it&#8217;s &#8211; what&#8217;s heard is widely heard. If it&#8217;s assumed that a member of a group is portrayed as a typical member of that group, then attitudes at large towards the group will be affected.&#8221;<?php footnoteRef('B',4,14); ?></blockquote>
  <?php sectionAnchor('B',4,3); ?>Communication: truth, comment and &#8216;assessability&#8217;</h2>
 <?php paragraphLink('B',4,3,1); ?>The role of a free press as an agency of free communication (rather than of self-expression), of constituting a public forum of views and ideas, is an important one to focus on. The term &#8216;media&#8217; implies both a conduit or market-place role (the means by which material is communicated) and also the freedoms of the press to comment, in a partisan way, on the material that they publish (the message is editorially &#8216;mediated&#8217;). The vocal power and reach of the press, and its freedoms to mediate, are what make it a mighty force.</p>
  <?php paragraphLink('B',4,3,2); ?>A free press performs its communication role in a democracy in a myriad ways, day in and day out. It is by no means only through political journalism and holding authority to account that the press proves its value in this way (although those are very important aspects in their own right). All forms of journalistic content potentially perform this vital role. Debate and comment, information and speculation, news and opinion, education and entertainment, all play their part. It is exactly this multifunctional and multifaceted package of content, produced with such verve and to deadline week in, week out, which makes the press such a marvel, such a matter of pride.</p>
  <?php paragraphLink('B',4,3,3); ?>The different functions of the press, though, have different implications. We care about them in different ways and for different reasons. We apply different standards to them. So, for example, we might say we wanted the TV listings and football results to be &#8216;accurate&#8217;; the editorial to be &#8216;opinionated&#8217; (perhaps to confirm or challenge, or help us form, our own opinions); the sports reporting to be &#8216;lively&#8217; (and reasonably fair), the travel writing to be inspiring but not misleading, the crossword to be challenging but not impossible, and so on. And above all, we want it all to be accessible and a good read, as we all think of that in our different ways. This communication function is, in other words, an extremely complex and sophisticated exchange between editor and reader.</p>
  <?php paragraphLink('B',4,3,4); ?>Nowhere is that more the case than in the role of the media in conveying news. It is here that both the demands and expectations of readers are particularly complex. We know that some news is more important than others, but we vary in our judgments about that. We want to know the facts, but we also want to know how people experienced them and what people think about them. We want the spirit as well as the letter of events &#8211; the emotion, the meaning, the drama, the implications. We have an instinct that different kinds of news should be communicated in different ways (a politician&#8217;s mistake, an outbreak of disease, a missing child, a disappointing new film, another rape in the town), but we will not find it easy to articulate those differences with any great precision.</p>
  <?php paragraphLink('B',4,3,5); ?>We also know about the editorial inflection, the world-view, of the newspaper we read. For some, if not most, that is very much part of why it is their newspaper of choice. That does not mean we always agree with it. But we are familiar with it, and that familiarity is at some level part of the attraction. Newspaper readership is remarkably loyal. We want the news in the press to be true and accurate; we do not want to be misled or lied to. But we want, or are content for, it to be presented in a partisan way. We want a measure of balance and context, but we also want a perspective. We want the truth, but we understand that there are many versions of the truth, and incompleteness in all versions. Notwithstanding the emphasis put by both the industry and its critics on the difference between &#8216;fact&#8217; and &#8216;comment&#8217; these are by no means distinct and watertight categories. The very act of describing a fact is to comment on it. All forms of recording are selective.</p>
  <?php paragraphLink('B',4,3,6); ?>What authentic communication between editor and reader needs in these circumstances is no more, but no less, than a measure of shared understanding of what is going on in that act of communication. In most cases, that is easy and obvious. There will be a common expectation of complete accuracy in the TV listings; mistakes will irritate and inconvenience readers and ultimately drive them to look elsewhere. A newspaper urging readers to support a particular party in the run-up to a General Election can be expected to be more sympathetic to that party&#8217;s outlook and objectives than another&#8217;s, and to reflect that sympathy editorially elsewhere in its pages.</p>
  <?php paragraphLink('B',4,3,7); ?>But in some cases, it will be neither easy nor obvious for readers to orientate themselves in relation to material they read in the press. Some important examples were put before the Inquiry in the course of the evidence. They included, for example:
  <ol type="a">
  <li>science and health reporting, where most non-specialist readers cannot easily judge for themselves what experts are telling us;</li>
  <li>consumer journalism such as property or travel reporting and restaurant reviewing, where we might not know whether a journalist has been an objective &#8216;mystery shopper&#8217; or whether he or she has in fact been treated to holidays or meals by the organisations being reviewed, or owns a property in the same square as the house being praised in the newspaper;</li>
  <li>&#8216;PR&#8217; journalism, in which what is effectively commercially-produced advertising material is reproduced as editorial without mediation at all;</li>
  <li>the reporting of identity issues (gender, ethnicity, sexual orientation, religion, age, disability, appearance and so on) where the fact and manner of bringing such issues into coverage has a potential to implant a relevance for them in readers which they have not chosen.</li>
  </ol> 
  </p>
  <?php paragraphLink('B',4,3,8); ?>In all these cases, that is to say the inaccessible expertise, the conflicts of interest, the subliminal, or the simply misleadingly incomplete, the reader cannot straightforwardly make up his or her mind about what the newspaper is saying. Professor Baroness Onora O&#8217;Neill, who gave the Inquiry her views as a leading expert in the field of public thinking on the role of the media, describes the need for readers to be able to &#8216;orientate&#8217; themselves in relation to what they read as &#8220;assessability&#8221;. Mostly, readers know where they stand with what the papers say, and can make their own minds up about it. But not always. Where they cannot do so unaided, more is needed for the press to fulfil its proper role.</p>
  <?php paragraphLink('B',4,3,9); ?>This point about the importance of authentic communication by the press, which respects the needs of readers to be able to make their own minds up about what they are reading, was made to the Inquiry in a number of ways. Examples include:</p><blockquote>&#8220;Those who aim to communicate must aspire to standards which are inapplicable for those who aim only to express their own views.&#8221;<?php footnoteRef('B',4,15); ?> <br/>&#8220;The public interest in a free press is not confined to the public interest in a press that reports matters of fact accurately and observes the disciplines of truth seeking needed for various sorts of inquiry. It also includes an interest in having a press that communicates other sorts of content &#8211; eg music and art, puzzles and stories &#8211; that do not make truth claims. Nevertheless, where truth claims are made, there is a particularly strong public interest in standards of media communication that meet the relevant requirements for truth seeking &#8211; accuracy about evidence and its limitations; distinctions between different sorts of evidence; the inclusion of necessary qualifications, and many others.&#8221;<?php footnoteRef('B',4,16); ?> <br/>
  &#8220;Good public interest journalism enables the public to judge what is being said. There may be cases where one has to hold back on the source of certain information, but good public interest journalism seeks to make the sources and the evidence as available to the public as is feasible, given certain other constraints.&#8221;<?php footnoteRef('B',4,17); ?> <br/>
&#8220;I think the default in favour of openness is actually what good journalism does. They try to give the sources where they can. The difficulty about confidential sources is the problem that the reader has in knowing (a) was there any source at all and (b) was it a reliable source?&#8221;<?php footnoteRef('B',4,18); ?> <br/>
&#8220;One aspect of the public interest &#8230; is the public interest in <u>truthfulness</u> &#8230; Here there are two kinds of interest. There is the direct interest that individuals have in not being <u>deceived or misled.</u> &#8230;But there is also a second indirect interest in truthfulness, an interest in maintaining a culture of trust. If communication is believed to be untruthful (or inaccurate), then trust in communication may diminish.&#8221;<?php footnoteRef('B',4,19); ?> <br/>
&#8220;Simply requiring accuracy or truthfulness does not preclude a free press from misleading, distorting, or, in some cases, from covertly serving or promoting vested interests.&#8221;<?php footnoteRef('B',4,20); ?><br/>
 &#8220;News media are often <u>intermediaries.</u> They play the role of communicating facts that have been discovered, established or claimed by others. The evidence, warrant or other justification for such claims may be lacking, or suspect. The intermediary may not be competent to assess the claim, or have access to the evidence. They may be willing to pass on claims made by other self-interested parties in an uncritical way. &#8230;&#8221;<?php footnoteRef('B',4,21); ?> <br/>
&#8220;Knowing the <u>source</u> of a story is relevant to how we interpret it. Audiences&#8217; reactions to an article on a &#8216;new wonder drug&#8217; that &#8216;combats cancer&#8217; might be less favourable if they knew that the copy was verbatim from a press release by the company making the &#8216;wonder drug&#8217;. Our response to &#8216;advertorials&#8217; may (or at least ought to be) different from our response to news stories.&#8221;<?php footnoteRef('B',4,22); ?> <br/>
&#8220;With regard to truthfulness and other norms of communication, the arguments offered here are not that this or that claim ought to be made but rather, that the appropriate procedures and mechanisms need to be in place to ensure that what is said (whatever it is) is justifiable, assessable and evaluable with regard to its source. &#8230; Ensuring &#8230;communicative adequacy does not determine or constrain content, except insofar as content is unjustified, misleading and untraceable.&#8221;<?php footnoteRef('B',4,23); ?></blockquote>
  <?php sectionAnchor('B',4,4); ?>Press ethics and the role of a code of ethics</h2>
 <?php paragraphLink('B',4,4,1); ?>Press ethics, to which the Inquiry was directed by its Terms of Reference, can be understood at a simple level by reference to the choices available to a free press, where those choices may have consequences for the benefit or harm of others, whether individuals, groups or the public as a whole. These are the choices by which newspapers and journalists can exercise their freedoms so as to fulfil the unique and important role of the press in a democracy or indeed to undermine it, to promote or restrict public communication and debate, to enhance or harm civil liberties and the autonomy of individuals.</p>
  <?php paragraphLink('B',4,4,2); ?>These are choices which fall to be made within the framework of the law. Compliance with the law (criminal, civil and regulatory) does not necessarily exhaust the ethical choices to be made by a free press, nor does consideration of legal risk and consequence exhaust the responsibilities of a press aiming at journalism in the public interest, which takes into account ethical risks and consequences.</p>
  <?php paragraphLink('B',4,4,3); ?>The choices that a responsible and ethical press will make, then, flow from precisely those aspects of a free press which give it a unique role and privileges in a democracy, and from an awareness of its power to affect the public in general, and individual members of the public, for better or worse. The following are examples. 
  <ol type="a">
  <li>If a free press in a democracy has a special role in facilitating free communication and in constituting a public forum, then an ethical press will want to comply with good standards of communication. It will want to enable people to recognise and assess the material being provided. Where it provides information, that information will be reasonably intelligible and accurate.</li> 
  <li>If a free press in a democracy has special privileges to keep its sources secret, then an ethical press will be mindful of the reasons for and effects of that privilege and will exercise it only for those reasons, and bearing in mind those effects. It will want to ensure that the protection of sources is used to enhance the free flow of significant information and especially to protect those seeking to help hold power to account. It will not use it merely to constrain or control sources, nor will it abuse the privilege to mask the weakness or absence of sources or the existence of conflicts of interest, or to hide its own wrongdoing. </li>
  <li>If a free press in a democracy has a special place because of its ability to hold power to account, an ethical press will consider itself to have responsibilities to do just that. It will not collude with the powerful at the expense of the public. It will challenge all kinds of sources of power, both public and private. It will be mindful of the power of the press itself, and seek to hold that power to account no less than other sources of power. And it will support others with responsibilities for holding power to account in doing so, including in the case of the media itself. </li>
  <li>Further, a free and autonomous press within a democracy will be mindful of the democratic freedoms and autonomies of others. All such freedoms and choices, after all, stem from the same sources of democratic authority and accountability. And all ethical systems have at their core a sense of respect for the individuality and self- determination of others.<?php footnoteRef('B',4,24); ?> People are the stock-in-trade of journalism. An ethical press will therefore be especially mindful of the need to ensure that the individuals it deals with, both as sources of information and as the content written about, are treated as subjects and not objects, and both as subjects in their own right and as subjects in context, with families, connections and group identities which may be affected by the treatment of the individual.</li>
  </ol>
  </p>
  <?php paragraphLink('B',4,4,4); ?>All of this is to re-emphasise that the freedom of the press, even the freedom of the press within the limitations and accountabilities under the law, is not enough by itself to secure the important democratic benefits for which press freedom is a prerequisite. To become an authentically free press of the kind valued and privileged in a democracy, the press must also exercise its freedoms effectively for that purpose. It must actively choose that role and live out its implications. That point was made to the Inquiry in many ways; examples include:</p>
  <blockquote>&#8220;The duties or responsibilities of the press follow straightforwardly from the reasons we have for wanting a free press. So if one of the main reasons for wanting a free press is that we be fully informed as citizens, then there are responsibilities on the press to be accurate, honest, open and accountable.&#8221;<?php footnoteRef('B',4,25); ?><br/>
 &#8220;Clearly though, a press which is free in the sense of not being controlled centrally, not censored, will only be meeting a necessary condition for serving its purposes of informing and scrutinising. In order for the press to serve these public interests it will also need to pursue its work with accuracy and rigour, to be concerned for the truth, to seek to avoid bias or serving particular interests, to make wise judgments as to what is worthy of public attention and what not, and perhaps to be courageous in pursuing these goals. (And it may well also be &#8230; that in order to serve its purpose the press needs to communicate in ways that are intelligible and assessable).&#8221;<?php footnoteRef('B',4,26); ?><br/>
 &#8220;Freedom is not licensed, and that&#8217;s the way in which all these responsibilities bear on how you exercise your freedom. So you have those guiding aims of the media &#8230; &#8211; holding people accountable and presenting information &#8211; serving those roles and then these constraints.&#8221;<?php footnoteRef('B',4,27); ?><br/>
 &#8220;The strategy here has been to focus on the valuable ends that a free press is meant to serve and then to point out (a) that a free press need <u>not</u> secure those ends; (b) that a free press can even stand as an <u>obstacle</u> to the achievement of those ends. This is not to argue in favour of censorship but to point out ways in which a free press can <u>fail</u> to contribute towards the public interest, and, as such, public-interest based justifications will fail to apply.&#8221;<?php footnoteRef('B',4,28); ?><br/>
 &#8220;it is important for good judgment that the press is clear not only on the nature of the purposes it serves in a free and democratic society but on their partial contribution to public interest as a whole and the independent significance of other components of the public interest. &#8230; In my view the press itself at present assumes too quickly that freedom of the press (and free expression to the extent that is related to press freedom) is sufficient to guarantee that the press serves its distinctive role in contributing to the public interest. On the one hand this is problematic because press freedom is only a <u>necessary</u> condition for the press to make its distinctive contribution to the public interest. Treating it as a <u>sufficient</u> condition is making the press insensitive to all the other factors that are critical to this &#8211; accuracy and rigour, avoidance of partiality, bias, conflict of interest, and the other factors mentioned above. All these must receive appropriate attention. But this is also problematic because assuming that a process (a free press) will achieve a beneficial goal allows journalists and editors to fail to address carefully the question of what exactly that distinctive purpose is, or how it relates to other parts of the public interest.&#8221;<?php footnoteRef('B',4,29); ?><br/>
 &#8220;While it is important to protect genuine investigative journalism into matters of public interest &#8230; it is also important to distinguish the genuine article from purported investigative journalism that ignores or flouts the relevant disciplines of truth seeking, or is not directed at any matters of public interest. Pseudo public interest journalism discredits the genuine article, is not assessable by its audiences and damages the reputation of the media.&#8221;<?php footnoteRef('B',4,30); ?><br/>
 &#8220;The moral justification for a media organisation&#8217;s rights of expression and communication &#8230; turns on the role of media organisations&#8217; rights in constituting a public sphere that gives appropriate status and respect to individual people, and on the related instrumental grounds [of constraining power and enabling democratic deliberation and decision-making].&#8221;<?php footnoteRef('B',4,31); ?><br/>
 &#8220;The public interest is not just in a free but a diverse press, and also &#8211; given the press&#8217;s power and its central role within the public sphere of democratic policy-making &#8211; an accountable press too.&#8221;<?php footnoteRef('B',4,32); ?><br/>
 &#8220;The fact that the press has certain investigative powers doesn&#8217;t mean automatically that it has carte blanche to do whatever it wishes to find things out.&#8221;<?php footnoteRef('B',4,33); ?><br/>
 &#8220;Freedom and responsibility are not incompatible notions. &#8230; Principally behind the notion of freedom in my account is freedom from censorship, from authorities coming in and telling the press what they may or may not say with respect to output, but they may nonetheless have a number of responsibilities they need to respect in producing those outputs. I think that&#8217;s very important. No, I don&#8217;t see them as inconsistent.&#8221;<?php footnoteRef('B',4,34); ?></blockquote>
  <?php paragraphLink('B',4,4,5); ?>The point was also made more narrowly, to underline that the freedom of the press, and the value inherent in its freedom to publish, is the beginning and not the end of the questions about the public interest:</p> <blockquote>&#8220;The fact that freedom of expression is in the public interest &#8211; and it clearly is &#8211; it doesn&#8217;t follow that every instance of expression is in the public interest.&#8221;<?php footnoteRef('B',4,35); ?><br/>
 &#8220;I think a kind of slippage can happen in which this freedom of expression is seen to be the primary public interest the public has in the press, and then that can then seem as liable to trump many of the other side constraints. &#8230; So, and if one&#8217;s a journalist and one values being allowed to write what one thinks is important, &#8230; there&#8217;s a kind of, as I say, a natural slippage in which this freedom of expression can be seen to be the dominating aspect of one&#8217;s code.&#8221;<?php footnoteRef('B',4,36); ?></blockquote>
  <?php paragraphLink('B',4,4,6); ?>I set these thoughts out to underline, and indeed to risk labouring, the point that ethical standards are not inconsistent with a free press but necessary for it fully to realise the value of its freedom. Ethical standards and behaviour are about valuing the freedom of the press for what it is, and seeking to promote all that is good about that freedom, and not just about avoiding the shoddy and the disreputable (far less just the unlawful). A free press certainly has choices which it can exercise in ways which undermine the premises of its freedom and work contrary to the public interest. An ethical press will not choose to exercise its freedoms in that way.</p>
  <?php paragraphLink('B',4,4,7); ?>With freedom, rights and privilege therefore come choices, and with choices, responsibilities as to how they are exercised and with what consequences. With choices which affect the public sphere, come also public accountabilities.</p>
  <?php paragraphLink('B',4,4,8); ?>The private interests of the press industry, or of organisations within it, can be expected to be strongly aligned with the public interest for just this reason: it is what the free press in a democracy is all about. But there will also be powerful motivations of a contrary nature to be overcome by an ethical press. An ethical approach requires a culture of care and awareness, but deadlines are short and time is money. A diverse and plural press will also be a highly competitive one, contesting among its titles for readership and reputation. And the pressures of public demand, real or perceived, are by no means a reliable guide to the public interest.</p>
  <?php paragraphLink('B',4,4,9); ?>This latter point is a well-worn one: the fundamental difference between the public interest and what interests the public. It is nevertheless a point which it is important to stress once again, if only because of the seeming indefatigability of the argument in some quarters that whatever sells newspapers must ipso facto be a good thing, since newspapers are a good thing in themselves. The argument is sometimes put more subtly: that newspapers should simply meet the demands and expectations they perceive their readers to have or be capable of having in a non-judgmental way, and that the flourishing of newspapers by such means directly supports their ability to fulfil the higher purposes and freedoms of the press. But this is simply a further restatement of the error that because it is good for the press both to flourish and to be free to make choices, its exercise of those choices in its own perceived interests will itself necessarily be good. The fallacy of this line of reasoning was emphasised to the Inquiry in a number of ways:</p>
 <blockquote>&#8220;The key point here is that the fact that people have a (vicious) curiosity clearly does not entail a <u>right</u> to know those things, nor does it automatically excuse those who breach other norms in the service of that curiosity.&#8221;<?php footnoteRef('B',4,37); ?><br/>
 &#8220;<u>There is no ethical duty at all to provide audiences with whatever they want</u>, even if there are good economic reasons for doing so.&#8221;<?php footnoteRef('B',4,38); ?><br/>
 &#8220;The &#8216;we are only providing people with what they want&#8217; may appear to have a whiff of nobility about it, but where people&#8217;s wants are vicious, it is little more than an admission of lack of moral sensitivity.&#8221;<?php footnoteRef('B',4,39); ?><br/>
 &#8220;[The idea of the public&#8217;s &#8216;right to know&#8217;] is puzzling and problematic for many reasons. First, it is not clear what the scope of the right is (right to know <u>what</u>?). Second, the very idea of a right to know is problematic. If it is a negative claim right (no one is permitted to <u>stop</u> me from knowing) then this does not entail any correlative right of publication or communication. But a <u>positive</u> right to know (others are obliged to ensure that I know) is not feasible: I might not believe them, even if they tell me the truth. Worst still, it doesn&#8217;t tell us anything at all about whom the obligation to inform might fall upon.&#8221;<?php footnoteRef('B',4,40); ?></blockquote>
  <?php paragraphLink('B',4,4,10); ?>The commercial interests of the press in supplying or stimulating demands for particular kinds of content are not therefore either identical to, or even necessarily aligned with, the public interest in a free press. More than that, in an industry with people as its stock in trade, and assuming an evident and growing public appetite for information about other people which is contrary to the public interest because of the way in which it affects the personal autonomy or individual rights of those people, the commercial interests of the press have a clear potential to act contrary to the public interest.</p>
  <?php paragraphLink('B',4,4,11); ?>There are other respects in which the commercial interests of the press have a clear potential to tend contrary to the public interest. They include the instances discussed above in which the private interests of individual journalists, editors or proprietors may be engaged in editorial content in ways which may not be apparent to their readership.<?php footnoteRef('B',4,41); ?> They also include incentives to anti-competitive business practices and cartel behaviour, that is to say practices which may benefit one organisation at the expense of the diversity of the sector as a whole, or which may seek to unite the industry against healthy competitive disciplines and external scrutiny capable of benefiting readers and the public as a whole.</p>
  <?php paragraphLink('B',4,4,12); ?>There was some emphasis throughout the Inquiry on the place of ethical codes in supporting an ethical press. I put the matter that way with care. No code of ethics can make an unethical organisation or sector an ethical one. An unethical organisation will simply find ways round or disregard any code it purports to apply to itself when motivated to do so. An ethical organisation, on the other hand, will be helped and guided by a code of ethics, but that will be on the basis that the code is simply a clear encapsulation of the values and practices of the organisation in any event.</p>
  <?php paragraphLink('B',4,4,13); ?>This is a very fundamental issue about culture, practices and ethics, and the way they relate to each other. Professor Christopher Megone, who has worked extensively with industry bodies (mainly in finance and engineering) on issues of workplace ethics, put the matter this way to the Inquiry:</p>
<blockquote>&#8220;Of course an ethical media organisation needs to have an ethical code, one which reflects the distinctive mission of the organisation as part of the press (and thus is aware of the key role of the press regarding the public interest), and one which is sensitive to the particular ethical challenges that may arise for editors, journalists, etc in pursuit of their mission.<br/>
 &#8220;However, even more critical to the existence of an ethical media organisation is culture. &#8230; If there is an unhealthy culture then an organisation can have an ethical code but it will have little influence. Members of the organisation can undergo &#8216;ethics training&#8217; but it will have little effect. As soon as they return from the training to their desk or office, the pervasive culture will dominate their decision-making. The culture brings to bear all sorts of &#8216;accepted norms&#8217; which an afternoon&#8217;s training will be relatively powerless to affect. (I do not, of course, think that good &#8216;ethics training&#8217; is pointless, but simply that its effectiveness depends on whether, or to what extent, other factors are in place in the organisation.) &#8230;<br/>
 &#8220;&#8230; there are a number of critical factors that could be expected to bear on ethical culture in a media organisation. First, tone from the top &#8211; leadership &#8211; is of tremendous importance. The role of owners and editors here will be crucial. Certainly the organisation needs to have its ethical code, but that code needs to be fully understood and endorsed by its owners and editors, and these people need to live out that code day in and day out. This is a decisive factor in that code having meaning for all who work in the organisation. But their living it out means thinking about how they can convey the code through their practice right across the organisation, how they interact with employees right across the organisation in a way that makes it resonant for them. &#8230;<br/>
 &#8220;Secondly, an ethical organisation needs to have an open and honest culture in which it is possible for members of the organisation to raise their concerns about practices and to discuss them with colleagues and senior staff. &#8230; [S]taff need to feel confident that if they perceive unsatisfactory practices to be developing, or face a challenging situation, they can raise the matter with colleagues or senior staff. And they need to be confident that they can do so, and have a proper discussion, without fear of mockery or retribution. &#8216;Accepted norms&#8217; need to be open to challenge. &#8230;<br/>
 &#8220;Amongst other things, developing an open culture in a press/media organisation will require sensitivity to the particular kinds of pressure that journalists and other employees are bound to be under.&#8221;</blockquote>
  <?php paragraphLink('B',4,4,14); ?>Against this background, an operative code of ethics therefore would have a number of potential functions. 
  <ol type="a">
  <li>It would serve as a reminder of the special importance and roles, the freedoms and privileges, the power and responsibilities of the press. It would, in other words, provide a full context for the choices which fall to be made in practice so that they can be made in accordance with the principles to be derived from this context. It would, in short, explain what ethical (or, as it is sometimes described, &#8216;public interest&#8217;) journalism is. </li>
  <li>It would help journalists to understand the circumstances in which they are called upon to make ethical decisions. It would help them to make the right choices in practice. It would do this not as a matter of rigid and disconnected prescriptions and prohibitions, but by promoting &#8220;a stable disposition to act in certain ways for the right reasons&#8221;.<?php footnoteRef('B',4,42); ?> </li>
  <li>It would recognise and explain the circumstances in which the temptations and motivations to act unethically (including commercial motivations) may be especially strong, and why they need to be resisted, in order to change the incentive structure in such cases.<?php footnoteRef('B',4,43); ?></li>
  <li>It would seek to provide clarity, and would focus on practical applicability to everyday decision-making.</li>
<li>It would not expect to stand alone. It would take its place in a context of ethical culture, sources of advice and guidance both generally and at the particular levels of training, reinforcement, management and feedback.</li>
<li> It would be authoritative and respected. It would have consequences in terms of how individuals and organisations are perceived, in terms of rewards and sanctions.</li>
</ol>
</p>
  <?php paragraphLink('B',4,4,15); ?>The Inquiry asked a number of its witnesses specifically, and through its website the public more generally, what would be the distinguishing features of the culture and practices of a media industry, or any organisation which was a part of that industry, which would make it a recognisably &#8216;ethical&#8217; one. I was particularly interested to hear in response about Professor Baroness O&#8217;Neill&#8217;s suggested &#8216;six principles of openness&#8217;<?php footnoteRef('B',4,44); ?> for identifying ethical journalism which seem to me to have much to recommend them:<?php footnoteRef('B',4,45); ?> (a) openness about payments from others (b) openness about payments to others (c) openness about the interests (financial or otherwise) of owners, editors, programme- makers and journalists (d) openness about errors (e) openness about (most) sources, with an adequately drawn test of the public interest to allow sources to be kept secret, for specific reasons and in particular situations (f) openness about comments from members of the public.</p>
  <?php paragraphLink('B',4,4,16); ?>It is also worth setting out extracts from some of the answers to this question which appear to me to be particularly illuminative. </p>
  <blockquote>&#8220;I do not mean a media industry driven by ethical goals in the way that a charity like Oxfam is. I mean, rather, a media industry whose members and whose regulatory framework, while driven by a range of diverse goals that are not necessarily &#8216;ethical&#8217; in a narrow sense, are nonetheless deeply sensitive to the industry&#8217;s pivotal role in the liberal public sphere &#8230; A free press within an ethical media industry in this sense would have the following features, among others:
   <br/>&#8211; a sense of journalism as a profession with its own aims and values, including respect for the truth, respect for those about whom the press writes, respect for readers; <br/>
   &#8211; poor practices (unethical, illegal, or contrary to the reasons supporting press freedom) are regarded as shameful and their practitioners are ashamed of them;- whistle-blowers are supported; <br/>
   &#8211; journalists, editors and proprietors grasp the complexity of the moral role of the press (as, perhaps, politicians since the expenses scandal grasp the moral complexity of their own role); <br/>
   &#8211; the wider public is willing to pay the comparatively high costs (e.g. of ethical investigative methods) to support a press that upholds a liberal public sphere.<?php footnoteRef('B',4,46); ?>&#8221; In my view media organisations are ethical if they genuinely try to communicate in ways that enable intended audiences to understand and to assess what they publish, while respecting the legitimate claims of those on whom they comment and of those affected by their reporting. 
   <br/>These are demanding aims. To meet them the media need not only to refrain from unlawful speech acts (threatening, bribing, defaming, breaches of data protection, breaches of confidentiality &#8211; and many others) but to meet adequate ethical and epistemic standards in journalistic, editorial and business practice.&#8221;<?php footnoteRef('B',4,47); ?> &#8220;  
   <ol>
   <li>There is a need for an aspirational code, not simply a list of prohibitions against failings which those in the media fall into. </li>
   <li>Such a code needs to be presented in the context of the specific critical contribution that a free press can make to the public interest... </li>
   <li>The code could then be developed in terms of the duties to the key parties with whom the press/media interact in ethically relevant ways. </li>
   <li>A code by itself is not worth the paper it is written on unless it is a lived code. To make a code a lived code, media organisations need to attend to the critical factors that can bring about an ethical organisation, or promote integrity in an organisation. These factors include tone from the top (or leadership), an open and honest culture, and so on. &#8230; </li>
   <li>Part of developing such an ethically reflective organisation might be to introduce governance reports which press/media would produce annually, writing such reports in light of the requirements of the code. The reports might reflect both on the ethical culture of the organisation and on the organisation&#8217;s contribution to the public interest. Any such governance reporting would need to avoid either being overburdensome or being a mere ritual in order to be both effective and meaningful&#8230;&#8221;<?php footnoteRef('B',4,48); ?></li>
   </ol>
   &#8220;In order for a code of conduct to be properly effective it has to be, not only coherent and justified in terms of its normative content, but such that there is something about the social, institutional, legal or practical context that motivates and secures compliance.&#8221;<?php footnoteRef('B',4,49); ?></blockquote>
  <?php paragraphLink('B',4,4,17); ?>I conclude this analysis by recognising the risks that this Inquiry must confront. The Editor-in-Chief of the Mail titles, Paul Dacre, identified these risks, and the challenges the Inquiry faces, in this way:<?php footnoteRef('B',4,50); ?></p>
<blockquote>&#8220;...I would argue that Britain&#8217;s commercially viable free press, because it&#8217;s in hock to nobody, is the only real free media in this country. Over-regulate that press, and you put democracy itself in peril.&#8221; </blockquote>
<p>I have always been keenly aware of the dangers of going too far; and I have been continually reminded as the Inquiry has progressed. In short, it has not been difficult for me to remain alive to this critical risk. I go further. The public interest in a press which is free, which is viable, and which is diverse cannot be too highly valued. Without investigative journalism, and the ability of the press to scour hidden places, the domain of the powerful, for potential wrongdoing, our democracy would be severely impoverished. Nothing I shall recommend will fail to hold to these principles.</p>
  </div>
  
