<div class="content" id="contentPartDChapter2">
<h1 id="top">CHAPTER 2<br/>SELF-REGULATION OF THE PRESS</h1>
 <?php sectionAnchor('D',2,1); ?>Introduction</h2>
 <?php paragraphLink('D',2,1,1); ?>This Chapter of the Report will look at the Press Complaints Commission (PCC) as the system of self-regulation that has existed for the press since 1990. Having examined the establishment of the PCC in the context of the publication of the first report into the press by Sir David Calcutt QC in June of that year, it will then look, in turn, at the powers, operation and standards of the PCC before considering both the role of Press Standards Board of Finance, which was established with the express purpose of providing sufficient funding for the PCC, and the Code Committee which is responsible for the promulgation, implementation and amendment of the Editors&#8217; Code of Practice, the cornerstone of self-regulation through the PCC.</p>
  <?php paragraphLink('D',2,1,2); ?>This Chapter will also look at the operation of the Editors&#8217; Code of Practice, together with the services that it offers to the public; this includes the anti-harassment hotline and its role as a complaints handling body.</p>
  <?php paragraphLink('D',2,1,3); ?>The purpose of this Part of the Report is to review the position of the PCC very much from the perspective of its own witnesses, rather than from that of those who are more critical of what it has done since January 1991. Some criticisms are reflected but are mentioned only. A more critical perspective requires a detailed analysis of the response of the PCC to allegations of systemic press misconduct (such as that which arose in relation to data protection following Operation Motorman and then to phone hacking following Operation Caryatid). That exercise has therefore been deferred until these incidents (covering a number of years) have been fully ventilated: the Report therefore returns to the PCC below.<?php footnoteRef('D',2,1); ?></p>
  <?php sectionAnchor('D',2,2); ?>The establishment of the pCC</h2>
 <?php paragraphLink('D',2,2,1); ?>As has already been explained above,<?php footnoteRef('D',2,2); ?> the PCC was set up following the first report into privacy and the press by Sir David Calcutt QC, published in 1990.</p>
  <?php paragraphLink('D',2,2,2); ?>The broad scope of Sir David&#8217;s Departmental Committee had reflected a growing concern in Parliament, as well as among the public more widely, about the behaviour of some parts of the press and the perceived failure of the Press Council, then the self-regulatory body for the press, to take effective action to deal with such behaviour.</p>
  <?php paragraphLink('D',2,2,3); ?>Sir David&#8217;s first report was published in June 1990. At that stage, he did not advocate the introduction of statutory controls. Rather, he recommended that the existing, and by this point largely discredited, Press Council should be abolished and replaced with a new self- regulatory organisation, the Press Complaints Commission, which should deal with the many and substantive concerns that had been raised around the behaviour of some parts of the press. The new PCC would have 18 months to demonstrate &#8220;that non-statutory self-regulation can be made to work effectively.&#8221; </p>
  <?php paragraphLink('D',2,2,4); ?>As a result, in the spring of 1990, the five publishing associations in the UK (the Newspaper Publishers Association, the Newspaper Society, the Periodical Publishers&#8217; Association, Scottish Newspaper Publishers Association and the Scottish Daily Newspaper Society) worked together to establish the Press Standards Board of Finance (PressBoF) for the specific purpose of funding the PCC. The PCC was itself incorporated on 1 January 1991.</p>
  <?php paragraphLink('D',2,2,5); ?>The primary function of the newly incorporated PCC was to provide an effective means of redress for complaints made by members of the public against the press, including the ability to consider accusations of unfair treatment and unwarranted infringements of privacy. In addition, the Commission was to <q>&#8220;publish, monitor and implement a comprehensive code of practice for the guidance of both the press and the public&#8221;</q>, as well as to operate a 24-hour hotline for complainants. Sir David made clear that the adjudication of complaints should be a clear and fast process and that, where a newspaper was demonstrated to be in breach of the code, an apology should be given to the complainant. Sir David also recommended that the PCC should be able to advise on the form and placing of replies or corrections.</p>
  <?php paragraphLink('D',2,2,6); ?>I now turn to the Editors&#8217; Code of Practice. This set out standards of behaviour that journalists and editors should seek to uphold and also set down the rules by which the newspaperindustry should adhere. The Editors&#8217; Code of Practice was formulated by a Code Committee, formally a sub-committee of PressBoF which was made up of serving editors of both newspapers and magazines. The Code is explored in more detail below. Further, in a determined break with the past, the newly formed PCC also took a more proactive approach to dealing with some of the more challenging issues facing the press, producing a range of guidance which is valued by editors, particularly in the regional press.</p>
  <?php paragraphLink('D',2,2,7); ?>However, although the industry had moved quickly to set up the PCC, standards of press behaviour remained a concern to both politicians and members of the public who did not discern any immediate improvement in that behaviour. Reflecting that widespread concern, the then Home Office Minister, David Mellor QC MP, made clear his view in a television interview in 1989, describing the press as drinking in the &#8220;last chance saloon&#8221;. In July 1992, Sir David Calcutt was asked by Mr Mellor to prepare a second report analysing the record of self-regulation by the press since the formation of the PCC in January 1991. In that report, which was published in January 1993, Sir David argued that self-regulation by the PCC had failed and called for the introduction of a statutory Press Complaints Tribunal.</p>
  <?php paragraphLink('D',2,2,8); ?>Reiterating the history set out above, the PCC and the industry more widely both rejected the analysis of Sir David. However, the PCC did accept that some reform was required and changes were made to some of its policies and procedures in the light of the first 18 months of operational experience. Further changes were made in 1995, after the Government had published its eventual response to Sir David&#8217;s second report and the PCC has continued to keep its practices under review since then.</p>
  <h3>Purpose of the PCC</h3>
 <?php paragraphLink('D',2,2,9); ?>The primary purpose of the PCC is set out in its Articles of Association.<?php footnoteRef('D',2,3); ?> Article 53.1 of the Articles states that:<?php footnoteRef('D',2,4); ?></p>
<blockquote>&#8220;The primary function of the Commission shall be to consider, and adjudicate, conciliate and resolve or settle by reference to the Press Code of Practice promulgated by PressBoF for the time being in force complaints from the public of unjust or unfair treatment by newspapers, periodicals or magazines and unwarranted infringements of privacy through material published in newspapers, periodicals or magazines (in each case excluding advertising by third parties) or in connection with the obtaining of such material but shall not consider complaints of any other nature.&#8221; </blockquote>
  <?php paragraphLink('D',2,2,10); ?>This is again set out in plain English on the PCC website in the form of a mission statement.<?php footnoteRef('D',2,5); ?> In that statement, it is said that the PCC is:<?php footnoteRef('D',2,6); ?></p>
<blockquote>&#8220;an independent body which administers the system of self-regulation for the press. It does so primarily by dealing with complaints, framed within the terms of the Editors&#8217; Code of Practice, about the editorial content of newspapers and magazines &#8230; and the conduct of journalists.&#8221; </blockquote>
  <?php paragraphLink('D',2,2,11); ?>It is clear from this that the PCC understood itself to be a de-facto regulator and presented itself publicly as such. This difference between this perception and the reality is explored below.<?php footnoteRef('D',2,7); ?></p>
  <?php sectionAnchor('D',2,3); ?>Current powers, operations and standards</h2>
 <?php paragraphLink('D',2,3,1); ?>Since its foundation in January 1990, there has been five Chairs of the PCC. These were Lord MacGregor (1991&#8211;1994); Lord Wakeham (1995&#8211;2002); Sir Christopher Meyer (2003-2009); Baroness Buscombe (2009-2011); and Lord Hunt (since 17 October 2011). Professor Robert Pinker served as Acting Chair from July to October 2011.</p>
  <h3>Membership of the PCC</h3>
 <?php paragraphLink('D',2,3,2); ?>Membership of the PCC is voluntary and as such there is no system of sanctions or incentives in place to induce those newspapers and magazines who do not subscribe to the PCC to do so. Currently, the majority of national newspapers do subscribe to the PCC but there are important and significant omissions to that membership. In particular, the Northern and Shell group withdrew its membership in January 2011 and, as a consequence, the Star and Express titles have not been subject to any system of self-regulation since then (although Dawn Neesom, the editor of The Star, explained in her evidence that staff at both titles continued to abide by the terms of the Editors&#8217; Code of Practice during this period).</p>
  <?php paragraphLink('D',2,3,3); ?>In addition to the majority of national newspapers, all regional titles and most magazine titles are currently members of the PCC.<?php footnoteRef('D',2,8); ?> Subscription to the PCC is organised through the five print trade associations: the Newspaper Publishers Association, the Newspaper Society, the Periodical Publishers&#8217; Association and the Scottish Daily Newspaper Society.</p>
  <h3>The structure of the PCC</h3>
 <?php paragraphLink('D',2,3,4); ?>The framework for the membership of the PCC and appointments to the PCC are set out in Articles 5-9 of the Articles of Association. There are a number of classes of member of the PCC, as set out at Article 6 which also established the appointments process for each class. The three classes of members of the Commission are as follows (see Article 6.1): 
 <ol type="a">
 <li>the Chairman;<?php footnoteRef('D',2,9); ?></li>
 
 <li>public members; and</li>
 <li>press (or editorial) members.</li>
 </ol>
 
 
 Article 5 provides that there shall at any time be between nine and 17 members of the PCC. It also makes clear that at all times a majority of the members shall be Public Members rather than Press Members. Commissioners also serve as Directors of the PCC. There are at present 17 members of the PCC.<?php footnoteRef('D',2,10); ?></p>
  <h4>Appointment of members</h4>
 <?php paragraphLink('D',2,3,5); ?>The Chair of the PCC is appointed by PressBoF. It is of critical importance to note that, under the Articles of Association, PressBoF has absolute discretion to appoint the Chair on whatever terms it sees fit, and to vary or revoke that appointment. The most significant of the Articles of Association in this regard is Article 6.2, which provides that &#8220;the Chairman shall not be engaged in or connected with or interested in the business of publishing newspapers, periodicals or magazines (other than through his appointment as Chairman)&#8221;.</p>
  <?php paragraphLink('D',2,3,6); ?>It is clear that candidates for the post of PCC Chair are expected to have knowledge and expertise of the working of the press and also of regulation. For example, Sir Christopher Meyer was Press Secretary to Sir John Major from 1994 to 1997; during his tenure as Prime Minister and, before his appointment, Lord Hunt had prepared a report on the future regulation of solicitors for the Law Society of England; prior to that, he had led the first review of the Financial Ombusdman Service.</p>
  <?php paragraphLink('D',2,3,7); ?>In addition, the Inquiry has been told that a belief in the superiority of self-regulation above other forms of regulation is a requirement for all candidates applying for the post. The evidence submitted by Lord Hunt included a copy of the advertisement for the post of PCC Chair as it was advertised in 2011. The advertisement stated that candidates for the post of PCC Chair:<?php footnoteRef('D',2,11); ?></p>
<blockquote>&#8220;must be committed to the principles of self-regulation and freedom for the press.&#8221; </blockquote>
  <?php paragraphLink('D',2,3,8); ?>The Inquiry was told candidates are also tested on this particular issue during the application process. For example, Lord Grade was asked at interview whether or not he supported statutory regulation, and Sir Christopher Meyer suggested that he regarded his tenure as PCC Chair as a success as he warded off the threat of statutory regulation.</p>
  <?php paragraphLink('D',2,3,9); ?>The Public Members and Press Members of the PCC are appointed differently. According to the Articles of Association, Public Members and Press Members are appointed by the Appointments Commission (Article 6.3). This Commission also has absolute discretion to appoint Public and Press Members upon whatever terms and for whatever period it sees fit. Similarly, it has the power to revoke or to vary any appointment of a Public or Press member. Article 6.3 makes clear that no Public Member shall be engaged in, or otherwise connected with or interested, in the business of publishing newspapers, periodicals or magazines (other than through his appointment as a Commissioner).</p>
  <?php paragraphLink('D',2,3,10); ?>In practice, however, the Appointments Commission has been abolished and responsibility for the appointment of Public Members has been taken on by the Nominations Committee. This reform was introduced following the Governance Review in 2009 but, at this point, has not yet been formalised as an amendment to the Articles of Association.</p>
  <?php paragraphLink('D',2,3,11); ?>The Nominations Committee is chaired by the PCC Chair and has two other members drawn from Public Members of the Commission. At present, Ian Nichol and Professor Ian Walden sit on the Nominations Committee along with the Chair. Vacancies for Public Members are advertised publicly. The Nominations Committee considers applications and then makes nominations for the whole of the Commission to vote upon. As part of the process of considering applications, the Nominations Committee consults with the Chair of PressBoF. The Nominations Committee is also responsible for appointing the Independent Reviewer and the Review Committee.</p>
  <?php paragraphLink('D',2,3,12); ?>Press (or Editorial) Member appointments are made by the trade bodies through PressBoF.<?php footnoteRef('D',2,12); ?></p>
  <h3>Functions of the PCC</h3>
 <?php paragraphLink('D',2,3,13); ?>The then Director of the PCC, Stephen Abell, provided detailed evidence to the Inquiry about the function and operation of the PCC. He briefly summarised the purpose of the Commission as: 
 <ol type="a">
 
 <li>to investigate complaints, primarily from concerned individuals, that relate to the terms of the Editors&#8217; Code of Practice;</li>
 <li>to deal with pre-publication concerns of individuals and advocate on their behalf with news organisations, with a view to preventing the publication of non-compliant material; and</li>
 <li>to prevent harassment by journalists.</li>
 
 </ol>
 </p>
  <?php paragraphLink('D',2,3,14); ?>In addition to this, the PCC also seeks pro-actively to contact individuals who might need the assistance of the Commission in their dealings with the press; provides guidance to the industry on a range of ethical issues (such as reporting on mental health issues); and works with titles to help raise standards across the industry.</p>
  <h4>Investigating complaints that relate to the terms of the Editors&#8217; Code of Practice<br/>The complaints process &#8211; assessment</h4>
 <?php paragraphLink('D',2,3,15); ?>One of the core functions of the PCC is the investigation of complaints relating to the terms of the Editors&#8217; Code of Practice. Investigations are handled by the complaints officers in the PCC secretariat.<?php footnoteRef('D',2,13); ?> Each new complaint is assessed by a complaints officer or the Head of Complaints; at this stage, any complaint which falls outside the remit of the PCC or the Code of Practice is sifted out.<?php footnoteRef('D',2,14); ?> It may be the case that the PCC has to ask for further details before a decision can be taken about whether or not the complaint falls within its competence.<?php footnoteRef('D',2,15); ?></p>
  <h4>When the PCC does not investigate</h4>
 <?php paragraphLink('D',2,3,16); ?>The PCC does not investigate cases where no breach of the Code is raised in the complaint. Examples of this might include where the complaint was about a broadcaster, or where the complaint raised questions of taste and decency.<?php footnoteRef('D',2,16); ?> The PCC might also decide that, if sufficient remedial action had been taken by a newspaper, no further action was necessary.</p>
  <?php paragraphLink('D',2,3,17); ?>When a complaint does not fall within the remit of the PCC, it will try to redirect the complainant to the relevant alternative regulator.<?php footnoteRef('D',2,17); ?> Where the complaint does fall within the competence of the PCC, but there is no prima facie case to answer, the matter may be put before the Commission directly without investigation.<?php footnoteRef('D',2,18); ?></p>
  <h4>Investigation</h4>
 <?php paragraphLink('D',2,3,18); ?>If a complaint does raise a prima facie breach of the PCC Code, it is assigned for investigation to a Complaints Officer. Complaints Officers at the PCC play a dual role of both investigator and conciliator.<?php footnoteRef('D',2,19); ?> Where a complaint is accepted for investigation, the PCC first writes to the editor of the relevant publication. That editor is sent a copy of the complaint and is asked to respond within seven days. There then follows three way correspondence, with the PCC Complaints Officer acting as the conduit between the complainant (or his/her representative) and the publication complained about.</p>
  <?php paragraphLink('D',2,3,19); ?>The PCC has a protocol for disclosure.<?php footnoteRef('D',2,20); ?> This document does not place either party under any obligation to provide key documents to the other party or to the PCC itself. The protocol provides that any material submitted by a publication to the PCC in the course of a complaint will be seen by the complainant. It also provides that the PCC will&#8216;consider on request providing to the complainant copies of our correspondence &#8211; conducted during an investigation &#8211; with editors &#8217;. The PCC has no power to subpoena documents, having argued in the past that a power of subpoena would contribute to delay in the system.<?php footnoteRef('D',2,21); ?> There is no obligation on a complainant or a publication to disclose to the other party or to the PCC documents which might undermine a party&#8217;s own case or strengthen that of the other party.</p>
  <?php paragraphLink('D',2,3,20); ?>While the PCC does have the power to hold oral hearings, that power has never been exercised. According to the PCC&#8217;s response to the 2010 Independent Governance Review, oral hearings would be undesirable because they might undermine two key virtues of the PCC system, namely that the system is free and fair.<?php footnoteRef('D',2,22); ?></p>
  <?php paragraphLink('D',2,3,21); ?>On some occasions, the PCC has found that, after the conclusion of investigations, it has insufficient information to reconcile the positions of the parties and, as a consequence, has declined to come to any conclusion as to the merits of the complaint. There are other instances of PCC decisions in which the PCC has not upheld a complaint on the basis that there was not enough evidence for it to be sustained; on its face, however, it seems that if key documents were disclosed, the matter might have been resolved.</p>
  <h4>Action to prevent publication of material that does not comply with the PCC Code</h4>
 <?php paragraphLink('D',2,3,22); ?>On occasion, the PCC coordinates with publications and complainants who are at the centre of a specific news story.<?php footnoteRef('D',2,23); ?> Where the police are involved, the PCC might seek to approach the subject or probable subject of stories through the police (such as contact with Cumbria police following the shootings by Derrick Bird);<?php footnoteRef('D',2,24); ?> or through other representatives such as solicitors (as in the case of Christopher Jefferies).<?php footnoteRef('D',2,25); ?> The PCC can send a private advisory note to editors, making it clear that an individual does not want to speak to the media.</p>
  <h4>Preventing harassment by journalists</h4>
 <?php paragraphLink('D',2,3,23); ?>Harassment by journalists is covered by Clause 4 of the PCC Code. Where an individual asks a publication to desist from questioning, telephoning, pursuing or photographing him, the Code makes clear that publications should not persist in their pursuit of the individual.<?php footnoteRef('D',2,26); ?> The PCC has developed a system whereby it can communicate the request of a complainant to an individual newspaper or to the whole print and broadcast industry. Since 2003, the PCC has operated a 24-hour helpline,<?php footnoteRef('D',2,27); ?> the number for which is advertised on the PCC website. The system, referred to by some as a desist order, has been widely praised by both members of the public and those who have benefited from the system. However, it is notable that this has been used only rarely, and only in circumstances in which individuals have been placed under sustained, intense and intrusive media speculation.</p>
  <h4>Limitations on the PCC&#8217;s role</h4>
 <?php paragraphLink('D',2,3,24); ?>The Articles of Association also make express a number of explicit limitations on the PCC&#8217;s competence to consider complaints. These are: 
 <ol type="a">
 
 <li>
 the PCC can only consider complaints made by the person affected or by a person authorised by him to make a complaint (Article 53.3(a));</li>
 <li>
 the PCC cannot consider a complaint where the matter complained of is the subject of proceedings in a court of law or tribunal in the United Kingdom (Article 53.3(b)); and</li>
 <li>
 where the person affected has a remedy by way of proceedings in a court of law in the United Kingdom, the PCC may consider the complaint if in the particular circumstances of the case it appears to the Commission that it is appropriate for the Commission to consider a complaint about it. The PCC only deals with complaints relating to an article in a newspaper, magazine or periodical, or on the website of a newspaper, magazine or periodical.</li>
 </ol>
 </p>
  <h4>Powers and sanctions</h4>
 <?php paragraphLink('D',2,3,25); ?>The PCC has only limited powers available to it. For instance, as already observed, the PCC has no power to subpoena documents. The PCC also has a range of sanctions available<?php footnoteRef('D',2,28); ?> which, in brief, are: 
<ol type="a">
 <li>negotiation of an agreed remedy;</li>
 <li>publication of a critical adjudication;</li> 
<li>a letter of admonishment from the PCC Chairman to an editor;</li>
 <li>follow-up by the PCC to establish what steps have been taken to avoid a repeat of a breach and what steps have been taken against those responsible for breaches; and</li> 
<li>referral of an editor to his publisher.</li> 
</ol>
</p>
  <?php paragraphLink('D',2,3,26); ?>Although criticised by a number of witnesses (including Dr Martin Moore and Professor Greenslade) as inadequate, Baroness Buscombe told the Inquiry that the current sanctions regime available to the PCC had been broadly effective.<?php footnoteRef('D',2,29); ?> Indeed, in its response to the Culture, Media and Sport Select Committee report, the PCC said &#8220;at present, the Commission believes that its powers are effective and can point to a culture in which its sanctions have real impact&#8221;.<?php footnoteRef('D',2,30); ?> The PCC has also pointed to the growing number of settled complaints as testament to the efficacy of the current sanctions regime.</p>
  <?php paragraphLink('D',2,3,27); ?>Both Baroness Buscombe and Sir Christopher Meyer told the Inquiry that the possibility of an adverse adjudication on an editor of a newspaper was a real and effective sanction. Sir Christopher said that editors would go to considerable lengths to avoid an adverse adjudication and that this was to the benefit of the complainant.<?php footnoteRef('D',2,31); ?> Baroness Buscombe went further, observing that editors reacted with fury to the announcement of an adverse PCC adjudication and that the effect of such an adjudication on an editor was considerable.<?php footnoteRef('D',2,32); ?> In so doing, Baroness Buscombe has implied that the deterrent and punitive effect of a PCC adjudication was real. However, elsewhere in her evidence, she appeared to concede that the deterrent impact of an adverse adjudication from the PCC was not as effective as might have been suggested. She accepted that the anger she had experienced from editors when providing notice of a forthcoming adjudication was at the fact of personal criticism rather than its content and impact.<?php footnoteRef('D',2,33); ?></p>
  <?php paragraphLink('D',2,3,28); ?>Baroness Buscombe also explained that both the Daily Mirror and the Financial Times had threatened to leave the PCC as a consequence of an adverse adjudication. She accepted the suggestion of the Inquiry that this reflected that the balance of power within the self- regulatory system for the press may be wrong.<?php footnoteRef('D',2,34); ?> However, she was emphatic that, although an issue for the system of self-regulation through the PCC, adverse and indeed disdainful reactions from editors to PCC adjudications were rare and limited to a small minority.<?php footnoteRef('D',2,35); ?></p>
  <?php paragraphLink('D',2,3,29); ?>In a further reflection on this point, Baroness Buscombe acknowledged that the current state of affairs impacted directly on levels of trust in the PCC and that, as a consequence, there was very real difficulty in persuading both policy makers and members of the public that an adverse adjudication was, in fact, an effective sanction.<?php footnoteRef('D',2,36); ?> It is important to note in this context that the PCC has no power to enforce its adjudications or rulings if they are ignored by an editor or publisher. The lack of power in this respect has been the subject of some criticism and had already been identified as an issue to be reviewed by the PCC Reform Committee by February 2012.<?php footnoteRef('D',2,37); ?></p>
  <?php paragraphLink('D',2,3,30); ?>A further analysis of the punitive and deterrent impact of adjudications as a sanction is undertaken later in the Report.<?php footnoteRef('D',2,38); ?></p>
  <h4>Options for appeal or review</h4>
 <?php paragraphLink('D',2,3,31); ?>There is no avenue within the self-regulation system through which complainants can appeal against the substance of a PCC decision. The Inquiry has been told that this was the source of some frustration to complainants, and indeed, had dissuaded some from taking complaints to the PCC in the first instance. On occasion, parties who have been informed of the substance of the outcome of adjudications in their cases have asked the PCC to reconsider its decision.<?php footnoteRef('D',2,39); ?> However, when this happens, the PCC has only reviewed the process of the handling of the complaint and not the substance of the material decisions made.</p>
  <h4>Charter commissioner and independent reviewer</h4>
 <?php paragraphLink('D',2,3,32); ?>The position of Charter Commissioner was introduced in 2003, together with a Charter Compliance Panel, as part of the policy of &#8216;permanent evolution&#8217; initiated by Sir Christopher Meyer. The function of the Charter Commissioner is defined under Articles 55 and 56 of Articles of Association as to:<?php footnoteRef('D',2,40); ?></p>
<blockquote>&#8220;consider complaints (other than complaints relating to the substance of an adjudication) from persons who have received a decision from the Commission and who are dissatisfied with the way in which the Commission has handled their matter.&#8221; </blockquote>
  <?php paragraphLink('D',2,3,33); ?>The first Charter Commissioner was Sir Brian Cubbon, who served until 2009. He was replaced by Sir Michael Wilcocks (who became the first Independent Reviewer). The Independent Reviewer is now Professor Robert Pinker CBE: he served as a Public Member of the PCC between 1991 and 2004 and was Acting Chair in 2002-2003 and in 2011. The role of the Charter Commissioner was characterised in the 2003 PCC Annual Report as being to &#8216;operate a sort of internal system of judicial review&#8217;. The Charter Commissioner is assisted in his work by the Charter Compliance Panel. Article 55.1 sets out the role of the Charter Compliance Panel as:<?php footnoteRef('D',2,41); ?></p>
<blockquote>&#8220;to examine the handling of complaints by the Commission pursuant to Article 53.&#8221; </blockquote>
  <?php paragraphLink('D',2,3,34); ?>In practice, the Charter Commissioner and the Charter Compliance Panel provide an avenue through which a complainant might refer his or her complaint if he or she believes that there had been some procedural defect in the way that the complaint had initially been handled. However, the Charter Commissioner had no remit to look at the substance of a complaint. This role has, since the independent governance review, been included unaltered in the position of Independent Reviewer.</p>
  <h4>Pro-active work by the PCC</h4>
 <?php paragraphLink('D',2,3,35); ?>The PCC produces Guidance Notes to assist the industry with particular issues where there is an apparent need.<?php footnoteRef('D',2,42); ?> Such guidance has been produced on a range of subjects including: the reporting of suicide (developed together with the Samaritans); the reporting of people accused of crimes; payments to parents for material about their children and the reporting of court cases involving sex offences.</p>
  <?php paragraphLink('D',2,3,36); ?>The PCC also publishes Annual Reviews. Among other information, these contain statistics about the number and types of complaints received. In addition, the PCC has in the past organised public events such as talks and Question & Answer sessions.</p>
  <?php sectionAnchor('D',2,4); ?>PressBof</h2>
 <?php paragraphLink('D',2,4,1); ?>PressBoF, is responsible for the organisation and collection of the levy which funds the PCC from the newspapers and periodicals participating in it. PressBoF is a company limited by guarantee and was incorporated shortly before the inauguration of the PCC. The membership of the Board of PressBoF is set out under Article 5 of the Articles of Association.<?php footnoteRef('D',2,43); ?> Currently, three members of the PressBoF Board are drawn from the Newspaper Association; three members from the Newspaper Society; two from the Periodical Publishers&#8217; Association and two from the Scottish Daily Newspaper Society.<?php footnoteRef('D',2,44); ?> The Board members are appointed by their trade association and in turn appoint the Chair, currently Lord Black of Brentwood (who, between 1996 and 2003 was the Director of the PCC).</p>
  <?php paragraphLink('D',2,4,2); ?>The structure of PressBoF is based loosely on the funding body for the Advertising Standards Authority.<?php footnoteRef('D',2,45); ?> However, whilst the funding structure underpinning that organisation has been made public, that is not the case with the PCC or PressBoF. As a consequence, there is little public understanding of how the PCC budget is financed. This has been the subject of both criticism and speculation. In addition to the oganisation of funding for the PCC, PressBoF also exercised full control over the appointment of the PCC Chair, as well as playing a prominent role in the appointment of new members to the Commission until changes were introduced as part of the 2010 Internal Governance Review.<?php footnoteRef('D',2,46); ?></p>
  <?php paragraphLink('D',2,4,3); ?>The Inquiry has heard detailed evidence from Lord Black, who has been Chair since September 2009, which has helped to explain the role of PressBoF as to the function of the PCC. He told the Inquiry that PressBoF not only funded the PCC through the collection and disbursement of the levy, it also had a fundamental role in relation to the exercise of its functions, as all decisions relating to the role and remit of the PCC must first be ratified by PressBoF. Lord Black explained that this was to ensure that no substantive changes were made to the role of the PCC without consultation with the industry.<?php footnoteRef('D',2,47); ?> In part, this was enforced through an undertaking made by Commissioners, on their appointment to the PCC, not to agree any changes to the articles of association without the express permission of PressBoF. This was one of two such undertakings made by Commissioners to the PCC, the second being to contribute &#163;1 to the winding up costs of the PCC should this ever prove necessary.<?php footnoteRef('D',2,48); ?></p>
  <?php paragraphLink('D',2,4,4); ?>Lord Black also explained the generality of the PCC funding arrangements. Payments by national newspapers accounted for 54% of the levy, regional newspapers paid 39% of the levy and magazines paid the remaining 7%.<?php footnoteRef('D',2,49); ?> Lord Black explained that, each year, PressBoF asked the national press through the National Newspaper Association to pay a specified amount towards the levy.<?php footnoteRef('D',2,50); ?> The contribution from each member of the NPA was decided by a formula derived from the amount of news print consumed by each member and the number of publications owned by each member.<?php footnoteRef('D',2,51); ?></p>
  <?php paragraphLink('D',2,4,5); ?>This calculation was made through the NPA as some of the information needed to deduce the level of contributions to the levy was commercially sensitive.<?php footnoteRef('D',2,52); ?> Although the membership of the NPA was in the public domain, the details of who paid for what were not public<?php footnoteRef('D',2,53); ?> or, indeed, shared with PressBoF, as members of the Board or PressBoF staff may have links with the individual publishing houses.<?php footnoteRef('D',2,54); ?> The monies collected through the levy were collected and passed on to PressBoF twice each year.<?php footnoteRef('D',2,55); ?></p>
  <h3>Role of PressBoF in PCC appointments</h3>
 <?php paragraphLink('D',2,4,6); ?>PressBoF also plays an important role in the appointment of personnel to the PCC,<?php footnoteRef('D',2,56); ?> including to the position of Chair. Lord Black made the point that the appointment process had not been static but had changed, becoming increasingly transparent,<?php footnoteRef('D',2,57); ?> over time: he noted that the appointment of the first Chairman of the PCC, Lord Wakeham in 1991, was done effectively by a tap on the shoulder, with no outside scrutiny or independent influence.<?php footnoteRef('D',2,58); ?></p>
  <?php paragraphLink('D',2,4,7); ?>By comparison, Lord Black explained that the appointment of Sir Christopher Meyer in 2003 involved the use of specialist recruitment consultants. The process for the more recent appointment of Baroness Buscombe was more transparent, and was built around the public advertisement of the post in the national press.<?php footnoteRef('D',2,59); ?> Further changes had since been made as a consequence of the independent review of the PCC governance processes; these were intended to make the appointment process more open and independent of the industry.<?php footnoteRef('D',2,60); ?> However, it is important to note that, although lay members of the PCC were involved in the appointment of Lord Hunt in 2011, they owned no formal role in the process.</p>
  <?php paragraphLink('D',2,4,8); ?>The appointment of Lord Hunt incorporated these changes for the first time. Following the resignation of Baroness Buscombe, the position of PCC Chair was advertised in the national press in August 2011. A firm of recruitment consultants, Korn, Ferry, Whitehead, Mann, were appointed to manage the process for the first time and an independent assessor was also appointed to oversee the process. The independent assessor provided an audit note of the complete application process.</p>
  <?php paragraphLink('D',2,4,9); ?>Applications were made not to PressBoF but direct to the recruitment consultants. They drew up an initial long-list which was discussed with both the independent assessor and the PressBoF Board. Those discussions resulted in the production of a shorter list and prospective candidates were interviewed by the consultants in the first instance. At that point, a final shortlist of some 12 candidates was drawn up by PressBoF and formal interviews took place during September 2011. A subcommittee of five members was involved in the interview process. That committee made a final recommendation to the PressBoF Board.</p>
  <?php paragraphLink('D',2,4,10); ?>The involvement of lay members was indirect. In the first instance, they were provided with an opportunity to put names forward for the post.<?php footnoteRef('D',2,61); ?> Later, members were offered a meeting with Lord Hunt at which they were provided with an opportunity to give their views on the type of Chair they thought appropriate to the position.<?php footnoteRef('D',2,62); ?> In his evidence to the Inquiry, Lord Black said that he spoke with all lay members of the Commission, with one exception.<?php footnoteRef('D',2,63); ?> Further, the Deputy Chair of the Commission, Ian Nichol, was appointed to liaise between the independent assessor and the recruitment consultants to monitor the process.<?php footnoteRef('D',2,64); ?></p>
  <?php paragraphLink('D',2,4,11); ?>Lord Black rejected the notion, put to him by Robert Jay QC, that, in practice, the position of PCC Chair was a de facto political one, on the basis that the post did not deal with political matters. Lord Black also noted that Lord MacGregor of Durris, the first Chairman of the PCC, was a Liberal Democrat Peer.<?php footnoteRef('D',2,65); ?> He also emphasised that the most recent recruitment process had been open to applicants from all political parties.<?php footnoteRef('D',2,66); ?> Lord Black told the Inquiry that the politics of Lord Hunt, the fourth Conservative Party peer to have held the post of PCC Chair, had played no role in his appointment.<?php footnoteRef('D',2,67); ?></p>
  <h3>The Editors&#8217; Code Committee</h3>
 <?php paragraphLink('D',2,4,12); ?>The Code Committee is responsible for the wording of the Editors&#8217; Code of Practice. The Code Committee has also been responsible for producing the Editors&#8217; Codebook, which brings together the Code and the PCC case law. The Code Committee is made up of editors appointed by the relevant trade bodies of the newspaper and magazine industry.</p>
  <?php paragraphLink('D',2,4,13); ?>The current Chair of the Code Committee is Paul Dacre, the editor-in-chief of Associated Newspapers. The PCC is represented through its Chair or Director at every meeting of the Code Committee and the PCC Commissioners must ratify any changes to the Code before they become valid.<?php footnoteRef('D',2,68); ?></p>
  <?php paragraphLink('D',2,4,14); ?>Lord Black has said that representation of serving editors on the Committee of the Editors&#8217; Code of Practice is a basic requirement for the success of the system of self-regulation. In his view, serving editors brought necessary expertise and industry knowledge to the system and, in particular, an awareness of the dilemmas faced by staff in newsrooms.<?php footnoteRef('D',2,69); ?> He suggested that majority industry representation was normal for systems of self-regulation, and was certainly the case with regard to systems of press self-regulation globally.<?php footnoteRef('D',2,70); ?> However, Lord Black did concede that public or independent representation on the Code Committee or a successor body would need to be considered going forward, particularly as this would be central to any effort in rebuilding public trust and confidence.<?php footnoteRef('D',2,71); ?></p>
  <?php paragraphLink('D',2,4,15); ?>Having said that, Lord Black categorically rejected the notion that that the Code Committee was not suitably independent of either PressBoF or the industry more widely. He told the Inquiry that, whilst PressBoF provided funding to the PCC, and although PressBoF, through the Code Committee, determined the Code, the independence of the complaints process by the PCC was sacrosanct.<?php footnoteRef('D',2,72); ?> He noted that his formal engagement with the Commission was rare, limited to one meeting each a year, the purpose of which was to update the Commission on the state of the industry. In his view, there was no capacity to exercise control over the function of the PCC.<?php footnoteRef('D',2,73); ?></p>
  <?php paragraphLink('D',2,4,16); ?>Importantly, Lord Black clarified that the Editors&#8217; Code of Practice Committee was a part of PressBoF and not the PCC. It was not, therefore, subject to the same level of lay scrutiny and influence as the PCC. Indeed, the only lay representation on the Editors&#8217; Code of Practice Committee was through the Chair and Director of the PCC, who were entitled to attend in an ex-officio capacity.<?php footnoteRef('D',2,74); ?> As neither were entitled to participate in discussions or in any decision- making capacity, it is clear that the influence of lay members on the Committee was limited.<?php footnoteRef('D',2,75); ?></p>
  <?php paragraphLink('D',2,4,17); ?>Witnesses from the PCC pointed to the merit in allowing serving editors to sit on decision- making boards like the Code Committee, particularly in the light of the current knowledge and experience they brought of a fast moving industry. Similarly, a number of editors told the Inquiry that such input to the Code was crucial if the Code was to have sufficient credibility with the industry. The same point was also made by Lord Hunt, who stated that it was important that any rules for the press, particularly around standards, were written by professionals with an appropriate level of knowledge and experience.<?php footnoteRef('D',2,76); ?></p>
  <?php paragraphLink('D',2,4,18); ?>However, there was some recognition that this knowledge could be brought to bear by former editors or, indeed, other industry experts. Lord Grade accepted that the codes developed by the Communications regulator Ofcom did not suffer because input came from former rather than serving journalists.<?php footnoteRef('D',2,77); ?> He also acknowledged that credibility with the industry could also be achieved through other means, such as consultation on the content of a code with serving industry editors, rather than their direct input through representation on the Code Committee.<?php footnoteRef('D',2,78); ?></p>
  <?php paragraphLink('D',2,4,19); ?>On one occasion at least, the Code Committee had been required to play a role as arbiter of the meaning of a given provision of the PCC Code where the PCC found that there was ambiguity.<?php footnoteRef('D',2,79); ?> On 22 September 2010, Baroness Buscombe wrote to Ian Beales (Secretary to the Code Committee) asking for clarification of Clause 15 of the PCC Code (payments to witnesses).<?php footnoteRef('D',2,80); ?> This was in the context of the Mail on Sunday having made payments to Baroness Scotland&#8217;s housekeeper. On that occasion, the Editors&#8217; Code Committee took legal advice from Mr Jonathan Caplan QC, and that advice was relayed to the PCC by Ian Beales.<?php footnoteRef('D',2,81); ?></p>
  <h3>The Editors&#8217; Code of Practice</h3>
 <?php paragraphLink('D',2,4,20); ?>The Editors&#8217; Code of Practice is the cornerstone of the system of self-regulation for the press,<?php footnoteRef('D',2,82); ?> and it is the responsibility of the PCC to ensure that the Code is properly enforced. The PCC&#8217;s website states that all members of the press have a duty to maintain the highest professional standards.<?php footnoteRef('D',2,83); ?> It makes clear that these standards are set out in the Code of Practice, and that the Code acts as a benchmark for those ethical standards. According to the PCC, the Code protects both the rights of the individual and the public&#8217;s right to know.</p>
  <?php paragraphLink('D',2,4,21); ?>Although there was later comment about ways in which the Code could be improved, witnesses to the Inquiry have, in the main, spoken favourably about its content. It has been praised by witnesses for being both readily understandable and usable. Even those witnesses who have been otherwise critical of the PCC, have spoken in favourable terms about the Code: for example, Alan Rusbridger, the editor of the Guardian, has described the Code as &#8220;good&#8221;.</p>
  <?php paragraphLink('D',2,4,22); ?>The PCC makes clear just how the Code should be interpreted by editors: the PCC website states that the Code should be &#8220;honoured not only to the letter but in the full spirit&#8221;.<?php footnoteRef('D',2,84); ?> Issues around interpretation are elaborated further on the website, including the unambiguous statement that the Code should not be interpreted &#8220;so narrowly as to compromise its commitment to respect the rights of the individual, nor so broadly that it constitutes an unnecessary interference with freedom of expression or prevents publication in the public interest .&#8221;<?php footnoteRef('D',2,85); ?></p>
  <?php paragraphLink('D',2,4,23); ?>Lastly, the PCC makes clear that &#8220;it is the responsibility of editors and publishers to apply the Code to editorial material in both printed and online versions of publications&#8221;. They should take care to ensure it is observed rigorously by all editorial staff and external contributors, including non-journalists, in printed and online versions of publications.</p>
  <h3>Amendments to the Code</h3>
 <?php paragraphLink('D',2,4,24); ?>The Editors&#8217; Code of Practice has developed through a process of iteration over the last two decades, responding to challenges and concern at the behaviour and actions of the press.<?php footnoteRef('D',2,86); ?> The Code has now been amended on at least 30 occasions, most notably following the death of Diana, Princess of Wales, in 1997.</p>
  <?php paragraphLink('D',2,4,25); ?>The most substantial of the amendments made to the Code of Practice have related to privacy and, in particular, the privacy of minors. Specifically, new wording was introduced to clause 3 in relation to privacy. This was largely drawn from the European Convention on Human Rights which, at the time the amendments to the Code of Practice were made, was about to be incorporated into UK law.<?php footnoteRef('D',2,87); ?> Significantly, these amendments also altered the definition of a &#8216;private place&#8217;, to include both public and private places &#8216;where there is a reasonable expectation of privacy&#8217;. Changes were also made to Clause 1 on accuracy to cover photographic manipulation.<?php footnoteRef('D',2,88); ?></p>
  <?php paragraphLink('D',2,4,26); ?>Further amendments to the Code sought to address concerns around the alleged role and actions of the paparazzi in the death of Princess Diana and the manner in which some photographs were sought. To address these concerns, provisions on harassment were expanded and revised to include a ban in the use of information or pictures obtained through &#8216;persistent pursuit&#8217;. This new Clause 4<?php footnoteRef('D',2,89); ?> also made explicit the responsibility of the editor not to publish material that had been obtained in breach of this clause, regardless of whether the material had been obtained by the newspaper&#8217;s staff or by journalists or other staff employed on a freelance basis.<?php footnoteRef('D',2,90); ?></p>
  <?php paragraphLink('D',2,4,27); ?>A new clause 6 was also introduced, making explicit provision for the protection of the rights of children to privacy while they were at school (previously, this clause had referred only to children under the age of 16). The revised clause 6 also forbade payments to minors or the parents or guardians of children for information involving the welfare of a child (unless demonstrably in the child&#8217;s interest), and introduced a requirement for a justification for the publication of information about the private life of a child other than the fame, notoriety or position of his or her parents or guardian.<?php footnoteRef('D',2,91); ?></p>
  <?php paragraphLink('D',2,4,28); ?>The final changes saw the phrase &#8216;should not&#8217; replaced by &#8216;must not&#8217; throughout the Code, and the amendment of the section on the public interest to ensure that, in cases involving children, an editor must demonstrate an exceptional public interest to over-ride the normally paramount interests of the child.<?php footnoteRef('D',2,92); ?></p>
  <?php paragraphLink('D',2,4,29); ?>Despite these attempts to keep the Code updated, the Inquiry has heard some criticism about the opaqueness of the drafting process, as well as the limited opportunity afforded to members of the public to influence the process of amendment. The Media Standards Trust, for example, said:<?php footnoteRef('D',2,93); ?></p>
<blockquote>&#8220;It [the Code of Practice] has grown up outside of public scrutiny, framed by those responsible for putting it into practice.&#8221; </blockquote>
  <?php paragraphLink('D',2,4,30); ?>This criticism has, however, been rejected by representatives of the PCC. Lord Black indicated that there were a number of means through which the public could contribute to the amendment of the code.<?php footnoteRef('D',2,94); ?> He specifically pointed to the annual review of the Code, which is undertaken by the Code Committee, during which suggestions for amendments were invited from Committee members, interested parties and the public.<?php footnoteRef('D',2,95); ?></p>
  <?php paragraphLink('D',2,4,31); ?>In practice, the Inquiry heard that the opinions and views offered by members of the public or from individuals outside of the newspaper industry were rarely heard. Lord Black acknowledged, in response to questions about the influence of lay voices and views on the Committee, that, as the Committee was &#8220;an Editors&#8217; Code Committee&#8221;, the voice of the press was &#8220;bound to be predominant&#8221;.<?php footnoteRef('D',2,96); ?> However, he also suggested that this potential bias was mitigated by the breadth of freely voiced opinion across the Code Committee.<?php footnoteRef('D',2,97); ?></p>
  <?php paragraphLink('D',2,4,32); ?>Lord Black was asked about criticisms that the Committee was slow to respond or adapt to criticism, that it had put the system of self-regulation ahead of the needs of individuals, particularly those who had been subject to abuse and mistreatment by the press, and had not looked critically or objectively at the efficacy of the system.<?php footnoteRef('D',2,98); ?> He denied that any of these were sustainable criticisms, and suggested instead that the sustained level of funding by the industry for an independent system of self-regulation had brought about a number or real successes, including significant improvements to the behaviour of journalists and the press.<?php footnoteRef('D',2,99); ?></p>
  <?php paragraphLink('D',2,4,33); ?>In particular, Lord Black noted improvements in behaviour related to harassment and the treatment of children and hospital patients.<?php footnoteRef('D',2,100); ?> He also suggested that a key, but hidden, success of the changes that stemmed from the Code of Practice was the increased tendency of editors to receive and deal with complaints themselves, particularly around accuracy, without referral to the PCC.<?php footnoteRef('D',2,101); ?></p>
  <?php paragraphLink('D',2,4,34); ?>Lord Black was particularly keen to make clear to the Inquiry that one of the primary functions of PressBoF, as a body that represented the industry, was forcefully to promote press freedom.<?php footnoteRef('D',2,102); ?> However, he rejected the notion that this had the potential to affect the overall balance of the Editors&#8217; Code of Practice by the Code Committee, by giving greater weight to the issue of press freedom, noting that there was only one member of PressBoF who sat on the Code Committee. He did, however, concede that the 13 members of the Code Committee (editors in their own right) would have clear and deeply held views of their own on press freedom.<?php footnoteRef('D',2,103); ?></p>
  <?php sectionAnchor('D',2,5); ?>Benefits of self-regulation</h2>
 <?php paragraphLink('D',2,5,1); ?>Witnesses from the PCC were clear about the benefits of a system of self-regulation for the press. They suggested that any form of statutory regulation for the press in the UK would also undermine the efficacy of the ex-ante interventions currently undertaken by the PCC, particularly work intended to stop the publication of particularly damaging or defamatory articles.<?php footnoteRef('D',2,104); ?> If this function were passed to a statutory body open to political capture then the potential for abuse of that function would have worrying and significant implications for freedom of expression.<?php footnoteRef('D',2,105); ?></p>
  <?php paragraphLink('D',2,5,2); ?>To illustrate his point, Lord Grade provided the example of complaints to the BBC about Jonathan Ross and Russell Brand in October 2008. The BBC Trust was able to issue an apology and a correction within ten days, whereas Ofcom took almost three months to investigate the same complaint and reach broadly similar conclusions. Lord Grade also suggested that, given the nature of complaints directed to the PCC, speed of resolution is of primary importance to the complainant.</p>
  <?php paragraphLink('D',2,5,3); ?>Lord Hunt said that he firmly believed in the value of self-regulation above formal statutory regulation, which he suggested was open to political interference.<?php footnoteRef('D',2,106); ?> By contrast, he suggested that independent, voluntary, self regulation of the press, for the press and in the public interest was preferable and the optimal of the available approaches. Ideally, such a system of self regulation should be universal but he did not expand on his thinking as to how bodies outside that system might be induced to join.</p>
  <?php paragraphLink('D',2,5,4); ?>Like other witnesses to the Inquiry, Lord Hunt has argued that it is the press who are in best position to correct the perceived failings with the current system of self-regulation and develop a solution that is more appropriate for dealing with the issues described to the Inquiry. Lord Hunt also suggested it is only by the press working together that a system of regulation such as that outlined by Sir David Calcutt in his second report can be achieved.<?php footnoteRef('D',2,107); ?></p>
  <?php paragraphLink('D',2,5,5); ?>A similar line of argument was advanced by Baroness Buscombe, who told the Inquiry that the speed and flexibility of the current system are advantageous when compared with attempts to find resolution through the courts.<?php footnoteRef('D',2,108); ?> She noted the harm that could be done to individuals as a consequence of drawn out court processes.<?php footnoteRef('D',2,109); ?></p>
  <?php paragraphLink('D',2,5,6); ?>In her evidence to the Inquiry, Baroness Buscombe suggested that the collaborative structure of the PCC was a strength.<?php footnoteRef('D',2,110); ?> She suggested that had the system of self-regulation been closer to a formal regulatory process, with potentially a system of fines for breaches, the efficacy of the PCC in dealing with complaints and pre-publication issues would have been compromised. She has argued that such a change would have made the system more adversarial and would have necessitated the involvement of lawyers in decision making, leading to drawn out processes which would have resulted in a lesser service to the public.<?php footnoteRef('D',2,111); ?></p>
  <?php paragraphLink('D',2,5,7); ?>Lord Hunt also suggested to the Inquiry that a regulatory regime backed in statute would not be sufficiently flexible as an independent self-regulatory system. In particular he worried that a regime backed in statute would not be able to respond to new challenges as they emerged, as such a system would require changes to the law and would be beholden to the Parliamentary timetable.<?php footnoteRef('D',2,112); ?> By contrast, Lord Hunt argued, an independent regulator could make changes in a more timely fashion. Although Lord Hunt conceded that it was perfectly possible to base the new system on legislation that was not proscriptive, he suggested that his experiences as a Parliamentarian led him to believe that legislation could rarely account adequately for future circumstances.<?php footnoteRef('D',2,113); ?></p>
  <?php sectionAnchor('D',2,6); ?>Anti-harassment policy</h2>
 <?php paragraphLink('D',2,6,1); ?>The PCC operates an anti-harassment hotline for the general public through which an individual might communicate a desire for press attention to cease to newspapers. Such a request may result in the Commission issuing a desist order to newspapers after which press attention in the person in question should cease.</p>
  <?php paragraphLink('D',2,6,2); ?>In his evidence to the Inquiry, Stephen Abell said that the PCC anti-harassment service was one of the cornerstones of the &#8220;fast moving&#8221; part of the system of self-regulation for the press; something, that by implication may not be possible or practicable under a different system.<?php footnoteRef('D',2,114); ?> The service was regarded by the PCC as an important complement to Clause 4 (harassment) of the Editors&#8217; Code of Practice. This states that journalists</p>
<blockquote>&#8220;must not persist in questioning, telephoning, pursuing or photographing individuals once asked to desist; nor remain on their property when asked to leave and must not follow them. If requested, they must identify themselves and whom they represent.&#8221;</blockquote>
  <?php paragraphLink('D',2,6,3); ?>The anti-harassment service is intended, therefore, to provide members of the public and other individuals affected by the actions and behaviour of journalists with the means of making express the terms of the Clause 4 of the Editors&#8217; Code of Practice.</p>
  <?php paragraphLink('D',2,6,4); ?>Although the PCC has no formal responsibility for broadcast journalists, as these are not covered by the terms of the Editors&#8217; Code, the PCC has, as a rule, forwarded desist notices to broadcasters, who have then taken appropriate action to ensure that their journalists abide by the will of the desist notice. Mr Abell&#8217;s written evidence to the Inquiry noted that:<?php footnoteRef('D',2,115); ?>
<blockquote>&#8220;This helps to reduce the problem of &#8220;media scrums&#8221; </blockquote>that involve journalists from all forms of media.&#8221; </p>
  <?php paragraphLink('D',2,6,5); ?>The anti-harassment service is accessed through the 24-hour helpline operated by the PCC. The PCC website provides comprehensive details of the service and the circumstances under which it might be used. The PCC has made clear that the initial telephone conversation with the affected party or, in some cases, their representatives is usually handled by a senior member of Commission staff. The PCC will also request an email setting out the concern or allegation from the individual in question. This email then becomes in effect the desist notice, which the PCC will then forward to a list of senior editorial and legal representatives. I note that Mr Abell has written that: </p>
  <blockquote>&#8220;Almost invariably, it is followed and the attention ceases.&#8221;<?php footnoteRef('D',2,116); ?></blockquote>
  <?php paragraphLink('D',2,6,6); ?>In his written evidence, Mr Abell suggested that the service could be used &#8220;prophylactically&#8221;. He provided the example of a grieving family who might contact the PCC ahead of an inquest or funeral, to make their wishes known. He noted that in such circumstance &#8220;the PCC will act to disseminate their position immediately.&#8221; I note that in this regard, the PCC has produced specific guidance both for bereaved individuals and also for journalists in relation to grief and intrusion into grief. This guidance encourages the bereaved to use the anti-harassment service. This guidance has been disseminated to all UK police forces and coroners&#8217; courts.<?php footnoteRef('D',2,117); ?></p>
  <?php paragraphLink('D',2,6,7); ?>The PCC has said in evidence that the anti-harassment service also had an application for individuals in the public eye. It was explained that a desist order acted as a check on the publication of paparazzi photographs obtained through harassment. Mr Abell stated:<?php footnoteRef('D',2,118); ?></p>
<blockquote>&#8220;The starting premise is that as soon as an editor publishes a photograph, he or she is taking responsibility for the conduct of the person providing it.&#8221; </blockquote>
  <?php paragraphLink('D',2,6,8); ?>He noted further that:<?php footnoteRef('D',2,119); ?></p>
<blockquote>&#8220;This places the onus on the editor to take care over the publication of photographs of the affected individual. This in turn means that non-compliant photographs are not bought by newspapers or magazines, and the market for them dwindles. This in turn affects the behaviour of the paparazzi in regard to the individual.&#8221; </blockquote>
  <?php paragraphLink('D',2,6,9); ?>The PCC suggested that the use of the anti-harassment service was the most effective means currently available of influencing paparazzi. Mr Abell&#8217;s written evidence explained that, as a class, the paparazzi were not regulated through any formal mechanism. Therefore, restricting the market for paparazzi photographs that may have been taken in breach of the code, or in contravention of a desist notice, helped to enforce standards of behaviour.<?php footnoteRef('D',2,120); ?></p>
  <h4><a href="#tableD2-1" id="tableD2-1">Table D2.1</a> Total Number of Desist notices</h4>
  <table>
  <tr>
 <th width="30%">Month</th> <th width="70%">Number of Desist and Private Advisory Notices*</th> </tr>  <tr>
 <td>Jan 2010</td> <td>8</td> </tr>  <tr>
 <td>Feb 2010</td> <td>4</td> </tr>  <tr>
 <td>Mar 2010</td> <td>11</td> </tr>  <tr>
 <td>Apr 2010</td> <td>5</td> </tr>  <tr>
 <td>May 2010</td> <td>4</td> </tr>  <tr>
 <td>Jun 2010</td> <td>1</td> </tr>  <tr>
 <td>Jul 2010</td> <td>2</td> </tr>  <tr>
 <td>Aug 2010</td> <td>3</td> </tr>  <tr>
 <td>Sep 2010</td> <td>8</td> </tr>  <tr>
 <td>Oct 2010</td> <td>7</td> </tr>  <tr>
 <td>Nov 2010</td> <td>4</td> </tr>  <tr>
 <td>Dec 2010</td> <td>2</td> </tr>  <tr>
 <td>Jan 2011</td> <td>10</td> </tr>  <tr>
 <td>Feb 2011</td> <td>9</td> </tr>  <tr>
 <td>Mar 2011</td> <td>13</td> </tr>  <tr>
 <td>Apr 2011</td> <td>12</td> </tr>  <tr>
 <td>May 2011</td> <td>12</td> </tr>  <tr>
 <td>Jun 2011</td> <td>11</td> </tr>  <tr>
 <td>Jul 2011</td> <td>16</td> </tr>  <tr>
 <td>Aug 2011</td> <td>10</td> </tr>  <tr>
 <td>Sep 2011</td> <td>7</td> </tr>  <tr>
 <td>Oct 2011</td> <td>5</td> </tr>  <tr>
 <td>Nov 2011</td> <td>11</td> </tr>  <tr>
 <td>Dec 2011</td> <td>14</td> </tr>  <tr>
 <td>Jan 2012</td> <td>13</td> </tr>  <tr>
 <td>Feb 2012</td> <td>12</td> </tr>  <tr>
 <td>Mar 2012</td> <td>11</td> </tr>  <tr>
 <td>Apr 2012</td> <td>17</td> </tr>  <tr>
 <td>May 2012</td> <td>7</td> </tr>  <tr>
 <td>Jun 2012</td> <td>6 (up to 27th June 2012)</td> </tr>  <tr>
 <td><strong>Total</strong></td> <td><strong>255</strong></td> </tr> </table> * The PCC makes no distinction between a &#8220;desist notice&#8221; and a &#8220;private advisory notice&#8221;. A desist notice is an  internal PCC term for a notice in relation to Clause 4 of the Editors&#8217; Code of Practice (harassment).</p>
  <?php paragraphLink('D',2,6,10); ?>At the time of writing, the PCC had issued 255 desist notices since January 2010 (as set out in Table D2.1). I note that, whilst there is no significant variance in the recorded monthly figures, the trend is towards the more frequent issue of these notices.</p>
  <?php paragraphLink('D',2,6,11); ?>I have heard little evidence that has been critical of the anti-harassment service operated by the PCC and it would be appropriate, therefore, to restrict myself to some general comments only. I note, first, that the service appears to be well regarded. The PCC has provided me with evidence of the efficacy of this service in helping those in often extraordinary circumstances to benefit either from a desist notice or in helping affected parties manage press and other media interest.</p>
  <?php paragraphLink('D',2,6,12); ?>This additional evidence was submitted in response to comments made in evidence by Gillian Shearer, the Communications Director for the Cumbrian Police Force, in relation to shootings in Whitehaven in Cumbria in July 2010. Ms Shearer described what she regarded as the aggressiveness of the press, the impact on the families concerned and the failure by the press to adhere to the police notice requesting that the media respect the families&#8217; wishes for privacy. She also criticised what she suggested was the failure of the PCC to respond meaningfully both to events but also the wishes of those individuals affected.<?php footnoteRef('D',2,121); ?></p>
  <?php paragraphLink('D',2,6,13); ?>In the evidence he has provided to the Inquiry, Michael McManus, the Transitional Director of the PCC, has sought to correct this perception of the actions of the PCC; he provided the Inquiry with a detailed description of the PCC&#8217;s activities in response to events in Whitehaven. It is to be borne in mind that although the events Mr McManus has described were extraordinary, they illustrate well the services the PCC is able to offer those individuals who become the subject of intense press attention. Mr McManus has written that:<?php footnoteRef('D',2,122); ?></p>
<blockquote>&#8220;On the day of the shootings, a member of PCC staff spoke briefly to Cumbria Police and followed up immediately with an email providing our contact details and explaining how we could help deal with concerns about media scrums and prepublication issues. A similar email was also sent to local hospitals.&#8221; </blockquote>
  <?php paragraphLink('D',2,6,14); ?>Mr McManus noted that during this difficult period members of PCC staff were in regular contact with police communicators. In addition, the PCC issued a private advisory notice on behalf of one individual who had become the subject of unwanted media attention and handled a number of formal complaints about published material. I note that the then Director of the PCC, Mr Abell, travelled on 9 July 2010 to Cumbria to meet with police communicators, local clergy and the editor of the <em>Whitehaven News</em>. The <em>Whitehaven News</em> subsequently published a letter from Mr Abell setting out the PCC&#8217;s services, and encouraging people to make contact with the PCC if they wished to do so.</p>
  <?php paragraphLink('D',2,6,15); ?>It is also clear that the PCC undertook a great deal of work in relation to events in Whitehaven. Mr McManus notes that:<?php footnoteRef('D',2,123); ?>
<blockquote>&#8220;The PCC stayed in touch with the police after the shootings, and also initiated contact with the local Coroner&#8221;.</blockquote> It is right to record that the PCC provided some assistance to Professor John Ashton, chair of the West Cumbria Shootings Recovery Group, in drafting a letter to the media requesting restraint ahead of the formal start of Inquest hearings in 2011. The PCC also worked with the police and Coroner to identify those individuals who had decided not to speak to the media; the Commission circulated a desist request on their behalf, requesting that they not be contacted.</p>
  <?php paragraphLink('D',2,6,16); ?>It is clear that the work of the PCC was wide-ranging. In May 2011, the PCC organised a public meeting in Carlisle to enable local communities to speak to its representatives. The panel also included the then editor of the News and Star (Carlisle), Neil Hodgkinson. Mr McManus has also told the Inquiry that following these events, the PCC has amended the guidance it offers to families in dealing with the media following a death.</p>
  <?php paragraphLink('D',2,6,17); ?>This is not to say that there are still not concerns with the anti-harassment service that should not be elaborated. Although the PCC website provides clear advice on the services available to members of the public with regard to harassment by journalist and photographers, it also sets a number of steps that the affected parties should follow before contacting the PCC. In certain circumstances, these steps might prove to be unduly difficult or, indeed, impossible to fulfil. They depend both on the goodwill and cooperation of the journalists and press photographers involved, as well as on the substantive efforts of the affected party who, feasibly, might not be in a position to comply with the suggested steps.<?php footnoteRef('D',2,124); ?> The PCC website states:<?php footnoteRef('D',2,125); ?></p>
<blockquote>&#8220;There are a number of practical steps that you can take to avoid unwanted or repeated approaches: 
<ol>
<li>Get the name of the journalist and the newspaper or news agency for which they work. Tell them politely that you do not wish to speak to them and that they should not contact you again. Say that you understand that under the Code of Practice journalists must not persist in contacting you having been asked to desist. It will help if you tell them that you are saying the same to every journalist. This applies however a journalist is approaching you &#8211; whether it is at home, in a public place or over the telephone. You should then be left alone. If you are not, see point 5, below.</li>
<li>If you are at home and too distressed to answer your door, pin a short note to it to say that you do not wish to speak to journalists and do not want to be disturbed.</li>
<li>Similarly, if you are being telephoned repeatedly and do not wish to speak to journalists, alter your answerphone message to say that only personal callers should leave a message as you are not speaking to the media.</li>
<li>Some people &#8211; particularly at times of grief or shock &#8211; find it helpful to ask a friend or neighbour who is not as closely associated with the story to deal with press enquiries. They can then answer your phone and door and either pass on a prepared statement (reflecting what is said in point 1) or turn down requests for interviews.</li>
<li>If these measures fail and you feel that you are still being harassed, contact the PCC immediately.&#8221;</li>
</ol>
</blockquote>
  <?php paragraphLink('D',2,6,18); ?>However, whilst the PCC guidance with regard to harassment is in most respects clear, there are significant caveats and exemptions to desist notices. In those cases where it has been impossible for the individuals concerned to establish the names of the journalists or newspapers in question, the PCC makes no claim to be able to take action. Even then, however, the website still encourages members of the public in such circumstances; it states thereafter that the PCC:<?php footnoteRef('D',2,126); ?>
<blockquote>&#8220;may then be able to communicate your concerns across the industry as a whole via a general &#8220;desist&#8221; message, which should alleviate the problem.&#8221; </blockquote>In so doing, the website makes no claim to the certainty of success of any action on the part of the PCC in this regard.</p>
  <?php paragraphLink('D',2,6,19); ?>Lastly, it is also important to underline that the website states that, in those cases in which there is a perceived public interest, there is no obligation on the part of the press to heed a desist notice. The website does not, however, elucidate what any public interest might be, and does not provide the public and more specifically the users of the service with any degree of certainty or clarity on this important issue. Perhaps of more importance, it leaves those individuals and their families who may already be in some distress open to continued and unwarranted press attention.<?php footnoteRef('D',2,127); ?></p>
  <?php sectionAnchor('D',2,7); ?>Complaints</h2>
 <?php paragraphLink('D',2,7,1); ?>I will now look how complaints are dealt with by the PCC, considering in turn the different aspects of that system: who might make a complaint; the circumstances in which an individual might complain; the limitations on the ability of a complainant to make a complaint; the informal resolution of complaints; and complaints deemed inadmissible.</p>
  <?php paragraphLink('D',2,7,2); ?>Before doing so, there is value is in setting into context the complaints handling process operated by the Commission. First, it is worth noting that the level of complaints received by the PCC is neither disproportionate nor excessive; the number received by the Irish Press Ombudsman is broadly similar, when adjusted for population, as is the number received by Ofcom, in relation to content. The number of complaints rejected by the PCC is also comparable to the numbers rejected by Ofcom. The majority of complaints to other regulators, however, are rejected because the complainant has not followed due process and has used the regulator in question, rather than the regulated company, as the starting point for the complaint. In such cases, the complaint is referred back to the company in question. However, this option is not available to the PCC as very few UK newspapers have formal complaints processes beyond the discretion of the editor.</p>
  <?php paragraphLink('D',2,7,3); ?>It is also important that the Inquiry provides a context to any discussion of the complaint- handling process with the detail of the volume of complaints considered by the PCC. The figures for 2010, reported by the PCC in 2011, are the most recent full figures available, and are broadly similar to those received up to 2010. In that year, the PCC received a little over 7,000 complaints. Of these 1,687 resulted in a ruling<?php footnoteRef('D',2,128); ?> and 44 in adjudications. Only two publications had more than one upheld adjudication against them.<?php footnoteRef('D',2,129); ?></p>
  <?php paragraphLink('D',2,7,4); ?>It is without doubt that the handling of complaints was the main and dominant part of the PCC&#8217;s business, taking up most of the day to day function of the Secretariat. After salaries, administration and property costs, complaints handling accounted for the greatest part of the remaining budget. Exact figures have not been provided to the Inquiry, but it has been suggested by witnesses that the PCC budget was only just sufficient for its purposes and only just stretched to cover these costs, with no remainder for any other actual or proposed function. This raises serious questions about the ability of the model proposed by Lord Black to provide for an investigatory arm within the funding envelope suggested.</p>
  <?php paragraphLink('D',2,7,5); ?>Evidence presented to the Inquiry by the PCC, and taken from the routine surveying of complainants, suggests that the level of satisfaction among complainants with the conduct of complaints handling by the PCC is genuinely high.<?php footnoteRef('D',2,130); ?> Lord Hunt said in evidence that that the satisfaction rate among complainants to the PCC was very high. He suggested that 80% of complainants were satisfied at the outcome of their complaint. However, this figure has been called into question by other evidence submitted to the Inquiry. It has been suggested that such a figure can only be reached if all complaints are understood to have been resolved in a manner satisfactory to the complainant.</p>
  <?php paragraphLink('D',2,7,6); ?>Certainly, witnesses to the Inquiry have recognised that the secretariat and, in particular, the complaints handling staff at the PCC make considerable effort to be courteous and helpful. The MediaWise Trust, an independent press watchdog that monitors the behaviour of the press, has noted that in the surveys of complainants that they have undertaken, respondents score the staff highly against these criteria.<?php footnoteRef('D',2,131); ?> Complainants also appreciate the speed with which PCC staff deal with issues raised by complainants in the course of the complaints.<?php footnoteRef('D',2,132); ?></p>
  <?php paragraphLink('D',2,7,7); ?>PCC witnesses to the Inquiry have certainly drawn attention to the apparent satisfaction at the speed of the complaint-handling process and the value placed on this by complainants. Sir Christopher Meyer gave evidence that, in most cases, resolutions were reached within a month of the complaint first being lodged.<?php footnoteRef('D',2,133); ?> Given that most editors dislike the personal criticism inherent in any upheld adjudication, it is unsurprising that they will work hard to reach a resolution to the satisfaction of the complainant.</p>
  <?php paragraphLink('D',2,7,8); ?>The PCC website makes clear that the Commission will deal with complaints as expeditiously as it is able. The website points to an average turnaround for the resolution of complaints of 34.8 days.<?php footnoteRef('D',2,134); ?> However, in evidence presented to the Inquiry, the Media Standards Trust has suggested that this figure is misleading as it takes account of complaints which do not fall into the jurisdiction of the PCC and are therefore rejected. The Media Standards Trust notes that, although such complaints are passed on to the relevant body or organisation, they are regarded by the PCC as &#8216;resolved&#8217;. The Media Standards Trust suggests that the inclusion of such cases therefore serves to distort both rates of satisfaction, as well as the record of the time taken to resolve a complaint. The Media Standards Trust deduced from available PCC data that the actual figure of turnaround was an average of 106 working days, three times greater than the PCC figure.<?php footnoteRef('D',2,135); ?> That said, there are limits to the analysis of any of the PCC data, as the Commission publishes information which omits the date on which a complaint is received.</p>
  <h4>Who can complain</h4>
 <?php paragraphLink('D',2,7,9); ?>The website states that the PCC is an independent body, which has been set up to examine complaints about the editorial content of UK newspapers and magazines (and their websites).<?php footnoteRef('D',2,136); ?> It makes clear that the PCC exists to help complainants and that its services are free. The PCC website explains that the Commission will deal with all editorially-controlled material in UK newspapers and magazines (and their websites). Examples are provided:<?php footnoteRef('D',2,137); ?>  </p>
 
 <ul>
  <li>Articles and pictures;</li>
  <li>Words and pictures (including video) on newspaper and magazine websites;</li>
  <li>Audio material on newspaper and magazine websites;</li>
  <li>Readers&#8217; letters; and,</li>
  <li>Edited or moderated reader comments on newspaper and magazine websites.</li>
 </ul> 
 
  <?php paragraphLink('D',2,7,10); ?>The website also explains that the PCC will also consider complaints brought in relation to the behaviour of journalists. Again, examples are provided. These are:<?php footnoteRef('D',2,138); ?> 
<ul> 
 <li>Persistent pursuit of individuals</li>
  <li>Refusing requests to stop taking photos or asking questions</li>
  <li>Using hidden cameras to obtain material</li>
  <li>Failing to be sensitive when dealing with cases involving grief and shock</li>
  <li>Failing to obtain the proper consent before speaking to children or people in hospital.</li>
 </ul> 
  <p>The website further explains that Complaints have to be judged against the terms of Editors&#8217; Code of Practice.</p>
  <?php paragraphLink('D',2,7,11); ?>Most importantly, the website makes clear that the PCC will only &#8220;normally accept complaints only from those who are directly affected by the matters about which they are complaining.&#8221;<?php footnoteRef('D',2,139); ?> It explains that individuals who meet that criterion are able to make complaints to the PCC and may raise complaints through the Commission against any newspaper, magazine or publication which subscribed to PressBoF.<?php footnoteRef('D',2,140); ?> The website also explains the limited circumstances in which third parties are able to make complaints. Such complaints will be considered by the Commission only in those circumstances where the third party has signed authorisation to act on behalf of the individual concerned.<?php footnoteRef('D',2,141); ?></p>
  <?php paragraphLink('D',2,7,12); ?>Lord Hunt has said that there is &#8220;misunderstanding&#8221; around the PCC&#8217;s policy on complaints from third parties: they have always been able to bring complaints in relation to accuracy. However, it is clear from Chapter 1 above that, as a matter of history, it has proved difficult to bring third party complaints. Further, the evidence received from the PCC in this regard might be said to contradict this account. Thus, Mr Abell explained that it was not the policy of the PCC to take account of complaints from third parties.<?php footnoteRef('D',2,142); ?> This evidence chimes with that received from a number of groups who drew attention to the difficulties they have encountered in the face of this policy.</p>
  <?php paragraphLink('D',2,7,13); ?>However, the policy of the PCC has not been entirely inflexible, in particular in the fairly limited number of cases where a single article has given rise to a very large number of complaints. In some instances, complaints received from third parties may cause the PCC to contact the subject named in the article in question, or someone directly affected by that article, to consider whether they would take forward a complaint.<?php footnoteRef('D',2,143); ?></p>
  <?php paragraphLink('D',2,7,14); ?>In this regard the case of Stephen Gately is instructive. An article published by the Mail on Sunday about the singer&#8217;s death, written by columnist Jan Moir in 2009, prompted a record number of complaints from members of the public to the PCC.<?php footnoteRef('D',2,144); ?> In response, the PCC contacted Mr Gately&#8217;s partner and asked if he would consider submitting a complaint.<?php footnoteRef('D',2,145); ?> In the event, the PCC did not uphold the complaint, although it considered that the article had come close to breaching the Editors&#8217; Code of Practice.</p>
  <h3>Time limits and delay</h3>
 <?php paragraphLink('D',2,7,15); ?>The PCC website clearly sets out a timetable for members of the public seeking to bring a complaint against a newspaper.<?php footnoteRef('D',2,146); ?> Thus, in most circumstances, the PCC will not accept complaints made more than two months after the date of publication (or over two months after the end of direct correspondence between a given complainant and an editor, provided that correspondence was entered into straight away).<?php footnoteRef('D',2,147); ?> The same section of the website also explains that complainants can formally submit a complaint to the PCC if the newspaper in question has failed to respond to the complaint within one week of the receipt of that complaint, but goes on to say that if the article in question remains available on the publication&#8217;s website, this time limitation does not usually apply. Beyond the strict timeframe set down by the PCC for the initial submission of the complaint, however, the times for each subsequent element of the complaints-handling process are not specified and no guidance is provided as to the likely duration of that process. Rather it suggests only that the steps involved in reaching the stage of an adjudication are less formal and are likely to be determined on a case by case basis.<?php footnoteRef('D',2,148); ?></p>
  <?php paragraphLink('D',2,7,16); ?>There are a range of resolutions that may be offered by titles. However, the PCC has no powers to stipulate the form of resolution that might be offered by the newspaper in question. Resolution can take the form of published apologies, the correction of the content in question in a future edition, the removal of the offending article from the title&#8217;s archives or online editions, or private letters of apology. In a limited number of circumstances, resolution might also include ex-gratia payments or donations to charities or other organisations.</p>
  <?php paragraphLink('D',2,7,17); ?>Some witnesses to the Inquiry have complained about what they regarded as an unnecessary slow process that was prone to delay. Some have said that lengthy periods between correspondence and delay were not uncommon. According to an analysis undertaken by the Inquiry of complaints to the PCC between January 2009 and May 2012, declared to have been resolved during that period, the time taken to resolve a case can vary significantly. In the fastest example, the resolution of a complaint took one month; in the slowest case the process appeared to have lasted for three years.<?php footnoteRef('D',2,149); ?> The value of an apology or other resolution after such a period of delay is questionable.</p>
  <?php paragraphLink('D',2,7,18); ?>Will Moy of Full Fact stated that whilst some complaints resulted in a prompt response from the newspaper in question, sometimes within a day of two, in other cases the process of reply was much slower, taking as many as 21 days.<?php footnoteRef('D',2,150); ?> In a limited number of circumstances no reply had been received from the newspaper.<?php footnoteRef('D',2,151); ?> In its evidence, Full Fact provided details of a number of complaints, including one about an article published in the Evening Standard, where that newspaper did not respond until two months after the initial submission to the PCC.<?php footnoteRef('D',2,152); ?> Similar experiences have been documented in the evidence provided by ENGAGE.<?php footnoteRef('D',2,153); ?></p>
  <?php paragraphLink('D',2,7,19); ?>The majority of complaints submitted to the PCC and ruled admissible are settled through a process of informal mediation between the complainant and the title in question. Only a very small number of complaints are not resolved in this manner, and those which fall into this category go forward for adjudication by the PCC. Complainants have a period of one month to appeal in writing to the Independent Reviewer should they wish to contest the PCC&#8217;s decision (although, as already identified, the Independent Reviewer will only look at the way that the PCC handled the complaint and not its merits).<?php footnoteRef('D',2,154); ?> The PCC website provides details of a total of 5,241 complaints that have been the subject of PCC rulings since 1996.<?php footnoteRef('D',2,155); ?> It lists 257 such complaints in 2012, (as set out in Table D2.2) of which 96.1% were informally resolved, 1.6% were upheld at adjudication and similar a proportion were not upheld.<?php footnoteRef('D',2,156); ?> In 0.8% of cases the PCC found that the newspaper question had taken sufficient remedial action to declare the complaint resolved. </p>
  <h4><a href="#tableD2-2" id="tableD2-2">Table D2.2</a>: Complaints to the pCC: 2009-2012</h4>
  <table>
  <tr>
 <th rowspan="2">Year</th> <th rowspan="2">Total Number of Complaints</th> <th rowspan="2">Resolved</th> <th colspan="3">Adjudicated Complaints</th> </tr>  <tr>
 <th>Upheld</th> <th>Against</th> <th>Sufficient remedy offered</th> </tr>  <tr>
 <th>&nbsp;</th> <th>No.</th> <th>%</th> <th>%</th> <th>%</th> <th>%</th> </tr>  <tr>
 <td>2012</td> <td>257</td> <td>96.1</td> <td>1.6</td> <td>1.6</td> <td>0.8</td> </tr>  <tr>
 <td>2011</td> <td>588</td> <td>93.5</td> <td>3.2</td> <td>1.4</td> <td>1.9</td> </tr>  <tr>
 <td>2010</td> <td>499</td> <td>91.4</td> <td>4.0</td> <td>4.0</td> <td>0.6</td> </tr>  <tr>
 <td>2009</td> <td>400</td> <td>86.5</td> <td>7.0</td> <td>5.0</td> <td>1.5</td> </tr>  <tr>
 <td class="sum">Total</td> <td class="sum">1744</td> <td class="sum">91.7</td> <td class="sum">4.1</td> <td class="sum">3.0</td> <td class="sum">1.3</td> </tr> </table> </p>
  <?php paragraphLink('D',2,7,20); ?>Data for 2011, 2010 and 2009 suggests a similarly high proportion of complaints were resolved through informal mediation processes (93.4%, 91.5% and 86.5% respectively), with only a correspondingly small percentage of case taken forward to formal adjudication. These figures show a trend towards the informal resolution of an ever larger number of cases, although this is from an already high base. Unfortunately, these figures do not relate to figures published in relation to complaints in the PCC Annual Reviews for 2009, 2010, and 2011.<?php footnoteRef('D',2,157); ?> Those Reviews refer to complaints received in a given year, and break down the details into somewhat different categories.</p>
  <?php paragraphLink('D',2,7,21); ?>It has been suggested by the PCC that the very large number of cases resolved informally, and through no process of adjudication by the PCC or the sustained intervention of the PCC through mediation, represented a &#8216;substantial and hidden success of self-regulation&#8217; .<?php footnoteRef('D',2,158); ?> Others have claimed that the odds are heavily stacked against the complainant, and that the PCC does not always appear to be neutral. But Mr Abell suggested that the position of the complaints handler was one of neutrality:<?php footnoteRef('D',2,159); ?></p>
<blockquote>&#8220;So I don&#8217;t think it&#8217;s a neutral act by complaints people. I think their job is to grip the issues and to try and bring them to a conclusion, and that will invariably be by assisting the complainant.&#8221; </blockquote>
  <?php paragraphLink('D',2,7,22); ?>In particular, Mr Abell suggested that there was no validity in the assertion that the PCC&#8217;s preferred outcome of a mediated resolution was in the better interest of editors and newspapers rather than the complainant.<?php footnoteRef('D',2,160); ?> Sir Christopher Meyer also rejected the characterisation of the complaints-handling process as attritional, in which intense pressures were placed on the complainant to resolve issues through mediation rather than pursuing a decision through the PCC and that the effort in reaching that resolution wass made disproportionately by the complainant.<?php footnoteRef('D',2,161); ?></p>
  </div>

