<?php 
require_once('../../common.php');
levesonHeader('D',1); 
levesonNav('../../');
levesonBread('D',1);
require_once('content.php');
levesonFooterNav('D',1); 
require_once('footnotes.php');
LevesonCommonFooter();
?>