<?php 
require_once('../../common.php');
levesonHeader('E',2); 
levesonNav('../../');
levesonBread('E',2);
require_once('content.php');
levesonFooterNav('E',2); 
require_once('footnotes.php');
LevesonCommonFooter();
?>