<div class="content" id="contentPartEChapter2">
<h1 id="top">CHAPTER 5<br/>A NEW APPROACH TO THE ALLEGATIONS</h1>
 <?php sectionAnchor('E',5,1); ?>Police Inquiries: Operations Weeting, Elveden and tuleta</h2>
 <h3>Introduction</h3>
 <?php paragraphLink('E',5,1,1); ?>Operation Weeting commenced on 26 January 2011. Its immediate spur was the provision to the Metropolitan Police Service (MPS) by News International (NI) of what the MPS has characterised as significant new information relating to allegations of phone hacking at the News of the World (NoTW) in 2005-2006.<?php footnoteRef('E',5,1); ?> Its remit was initially to investigate these allegations, but evidence relating to other dates and print titles is now being considered. The operation falls under the aegis of the Specialist Crime Directorate (SCD) of the MPS, and at all material times until 31 October 2012 has been headed by DAC Sue Akers, head of organised crime and criminal networks with the SCD, who has received universal praise for her work. DAC Akers also headed Operations Elveden and Tuleta.</p>
  <?php paragraphLink('E',5,1,2); ?>Operation Elveden began on 20 June 2011 following the MPS being handed by NI a number of documents containing evidence relating to alleged inappropriate payments to a small number of police officers by journalists at the NoTW in exchange for confidential information.<?php footnoteRef('E',5,2); ?> Since its early stages however, the ambit of Operation Elveden has widened significantly: additional print titles are now being investigated, as well as a range of public officials.<?php footnoteRef('E',5,3); ?></p>
  <?php paragraphLink('E',5,1,3); ?>Operation Tuleta commenced as a scoping exercise in June 2011 to consider the possibility of investigating allegations of computer hacking at the NoTW falling outside the remit of Operations Elveden and Tuleta.<?php footnoteRef('E',5,4); ?> In due course it became a fully-fledged investigation, and again its scope has broadened considerably.</p>
  <?php paragraphLink('E',5,1,4); ?>DAC Akers attended the Inquiry on 6 and 27 February, and 23 July 2012, to provide updates as to the current status of these three operations. On each occasion she helpfully provided a witness statement which she elaborated in oral evidence.<?php footnoteRef('E',5,5); ?> On 31 October 2012 DAC Akers filed a fourth witness statement which brings the position as up to date as it can be.<?php footnoteRef('E',5,6); ?> She was not asked to give oral evidence in line with that statement. This section of the Report is heavily based on her evidence, as well as other material which is in the public domain.</p>
  <h4>Operation Weeting</h4>
 <?php paragraphLink('E',5,1,5); ?>As at 6 February 2012 there were 90 officers including support staff dedicated to Operation Weeting; of these, approximately 35 worked full time in relation to notifying and supporting the victims.<?php footnoteRef('E',5,7); ?> As DAC Akers has explained in evidence, in its initial phases Operation Weeting focused on seeking to notify the victims and on analysing the numerous pages of the Mulcaire notebooks,<?php footnoteRef('E',5,8); ?> which had been seized as part of Operation Caryatid on 8 August 2006.<?php footnoteRef('E',5,9); ?> Subsequently, however, Operation Weeting acquired possession of substantial quantities of email data from a variety of sources.<?php footnoteRef('E',5,10); ?> In due course, the MPS was provided with the content of NI&#8217;s main server from 2005, containing a vast number of permanently deleted emails.<?php footnoteRef('E',5,11); ?> Officers working on Operation Weeting have been able to complete the reconstruction of these deleted emails recovered from storage devices obtained from NI, restoring three hundred million emails. DAC Akers has informed the Inquiry that:<?php footnoteRef('E',5,12); ?></p>
<blockquote>&#8220;&#8230;we&#8217;ve rebuilt &#8211; experts have rebuilt material that we thought had been lost, and that was completed towards the end of November last year. So we&#8217;re now going through that material.&#8221; </blockquote>
  <?php paragraphLink('E',5,1,6); ?>The first arrest carried out under Operation Weeting was in April 2011, and the last (to date) at the end of August 2012. So far, 25 people<?php footnoteRef('E',5,13); ?> have been arrested in connection with phone hacking, ten of whom are non-journalists. 17 individuals have been arrested for conspiring to intercept communications and/or in relation to the substantive offence. Of these, seven former NoTW employees have been charged with an overarching, general offence of conspiracy to intercept communications, and an additional former employee has also been charged with a number of date-specific substantive offences. A provisional court date has been fixed for 9 September 2013. Of the 17 arrested, six individuals have been released from police bail with no further action taken; the remaining three individuals remain on police bail for conspiracy offences.<?php footnoteRef('E',5,14); ?></p>
  <?php paragraphLink('E',5,1,7); ?>It is clear that Operation Weeting has expended a considerable amount of police manpower and resource. It is also clear that its work has not finished.</p>
  <?php paragraphLink('E',5,1,8); ?>Eight individuals have been arrested for perverting the course of justice: this operation has been named Operation Sacha. Seven of these have been charged with conspiring to commit that offence, and have been sent to the Crown Court for trial. A hearing for the defendants&#8217; applications to dismiss is scheduled for 12 and 13 December 2012.<?php footnoteRef('E',5,15); ?></p>
  <h3>Operation Elveden</h3>
 <?php paragraphLink('E',5,1,9); ?>In February 2012 there were 40 police officers and staff working on Operation Elveden and the MPS was in the process of increasing this to 61.<?php footnoteRef('E',5,16); ?> The investigation has entailed going through large quantities of NI business records and emails, seeking evidence relevant to suspicious payments. As of 26 October 2012 a total of 52 individuals had been arrested by officers working on Operation Elveden; of these, 25 are current and former journalists (including journalists from The Sun; the Daily Mirror and its sister paper, the Sunday Mirror; and the Daily Star Sunday).<?php footnoteRef('E',5,17); ?> The arrests made thus far under Operation Elveden are for offences under the Prevention of Corruption Act 1906, misconduct in a public office and conspiracy to commit these offences, aiding and abetting misconduct in a public office, money laundering contrary to s328 of the Proceeds of Crime Act 2002, and bribery contrary to s1 of the Bribery Act 2010;<?php footnoteRef('E',5,18); ?> the gravamen of the allegations being that they offered money to public officials in exchange for stories. As at 26 October 2012 files had been submitted to the CPS to advise on appropriate charges for three public officials and four current and former journalists.<?php footnoteRef('E',5,19); ?></p>
  <?php paragraphLink('E',5,1,10); ?>In an important piece of evidence, DAC Akers pointed out that offences<?php footnoteRef('E',5,20); ?> of this nature are suspected to have been committed in at least three separate newspaper titles right up to early 2012.<?php footnoteRef('E',5,21); ?> DAC Akers expects further arrests to be made in due course.<?php footnoteRef('E',5,22); ?></p>
  <h4>Operation Tuleta</h4>
 <?php paragraphLink('E',5,1,11); ?>Operation Tuleta began with an investigation into the circumstances surrounding the hacking into computers of Ian Hurst by or at the instigation of NoTW journalists in 2006.<?php footnoteRef('E',5,23); ?> As at October 2012, Operation Tuleta was undertaking an assessment of 142 separate allegations of data intrusion, including allegations of phone hacking, computer hacking, and improper access to banking, medical and other personal records.<?php footnoteRef('E',5,24); ?> This has entailed interrogating between 8-12 terabytes of data across 70 different storage devices; a vast undertaking.<?php footnoteRef('E',5,25); ?></p>
  <?php paragraphLink('E',5,1,12); ?>In April 2012, officers working on Operation Tuleta discovered inconsistencies with regard to the origin of material they had received from the Management Standards Committee (MSC).<?php footnoteRef('E',5,26); ?> Some of the information provided by the MSC had been traced to material which appears to have been obtained from two stolen mobile phone devices. DAC Akers has said that:<?php footnoteRef('E',5,27); ?></p>
<blockquote>&#8220;&#8230;it seems that on occasions we&#8217;ve found that material has been downloaded from and is in possession of News International titles which appear to have come from stolen mobile telephones. It appears from some of the documentation, and that&#8217;s dated around late 2010, that one of the mobile phones has been examined with a view to breaking its code, its security code, so that the contents can be downloaded by experts.&#8221; </blockquote>
  <?php paragraphLink('E',5,1,13); ?>Officers working on Operation Tuleta are anticipating the identification of the individuals responsible for the download of the content of these stolen devices, and are also seeking to establish whether the downloading of stolen data may have been a common practice at the other NI titles. DAC Akers has told the Inquiry that it is her firm intention to request further documentation from the MSC in respect of this discovery, with the purpose of establishing:<?php footnoteRef('E',5,28); ?></p>
<blockquote>&#8220;&#8230;whether in fact these are just isolated incidents or just the tip of an iceberg.&#8221; </blockquote>
  <?php paragraphLink('E',5,1,14); ?>As at 31 October 2012, 17 arrests had been made under the Computer Misuse Act 1990, and/or in respect of offences of handling stolen goods, by officers working on Operation Tuleta.<?php footnoteRef('E',5,29); ?> This figure includes a former Times journalist who, on 29 August 2012, was arrested by Operation Tuleta officers on suspicion of offences under the Computer Misuse Act 1990 and conspiracy to pervert to course of justice.<?php footnoteRef('E',5,30); ?> All these individuals are on police bail pending completion of the arrest phase and CPS advice on charging.<?php footnoteRef('E',5,31); ?></p>
  <?php paragraphLink('E',5,1,15); ?>As with Operations Weeting and Elveden, it is clear that there is considerable potential for further arrests of journalists, and not merely those previously employed by the NoTW.</p>
  <?php sectionAnchor('E',5,2); ?>The Management and Standards Committee</h2>
 <?php paragraphLink('E',5,2,1); ?>Between 2007 and 2011, the approach to the containment of the issue of what had happened at the NoTW gradually unravelled. Payments to Clive Goodman and Glenn Mulcaire might have ensured their silence but a number of the victims were prepared to invest in legal proceedings both to learn precisely what had happened and to obtain redress. Very substantial further payments in settlement did not stem the tide and, although most of the press was entirely silent on the subject, the effect of the July 2009 story in the Guardian (quite apart from the approach of the police) was to generate enquiry in Parliament, press coverage in the New York Times and the fact (and yet further risk) of an exponential rise in litigation.</p>
  <?php paragraphLink('E',5,2,2); ?>In the circumstances that have been described, the MPS grasped the nettle and re-opened the investigation; from the perspective of NI, containment was no longer an option because the reputational risk to News Corporation (News Corp) (let alone NI) required a complete change of direction. That came in the form of the Management and Standards Committee (MSC) and in July 2011, the board of News Corp appointed the distinguished UK commercial lawyer, Lord Grabiner QC, to the role of Chairman.</p>
  <?php paragraphLink('E',5,2,3); ?>Lord Grabiner&#8217;s appointment was made, at least in part, to help ensure the effective exchange of information between NI and the MPS, particularly with regard to the inquiry into alleged police payments at the NoTW, as part of Operation Elveden.<?php footnoteRef('E',5,32); ?> Lord Grabiner reports to Gerson Zweifach, Senior Executive Vice President and Group General Counsel of News Corp, who was himself appointed to that role in June 2012, taking over that previously held by Joel Klein, formerly Assistant Attorney General of the United States.<?php footnoteRef('E',5,33); ?> Gerson Zweifach in turn reports to the independent directors on the News Corp Board through Professor Viet Dinh, an independent Director and Chairman of News Corp&#8217;s Nominating and Corporate Governance Committee, and also a former Assistant Attorney General.<?php footnoteRef('E',5,34); ?></p>
  <?php paragraphLink('E',5,2,4); ?>In July 2011, two further NI executives (Will Lewis, formally editor-in-chief of the Telegraph Media Group and previously group General Manager at NI, and Simon Greenberg, previously Head of Corporate Affairs) resigned from their positions with NI in order to take up posts with the MSC. They have been appointed as full time MSC executive members. News Corp&#8217;s General Counsel for Europe and Asia, Jeff Palker, was appointed to the MSC as a part-time legal executive.<?php footnoteRef('E',5,35); ?></p>
  <?php paragraphLink('E',5,2,5); ?>The independence of the MSC from both NI and News Corp is one of its defining characteristics. This independence is ensured by requiring the MSC to operate its own governance structure, separate to that of News Corp. The MSC is housed and operates from a secure unit on NI&#8217;s Wapping site in London, located at a physical distance from the main NI building.<?php footnoteRef('E',5,36); ?> This independence, both in physical and figurative forms, is critical to the MSC&#8217;s ability independently to investigate the allegations of wrongdoing at the NoTW, as well as at NI.</p>
  <h4>Terms of reference and remit</h4>
 <?php paragraphLink('E',5,2,6); ?>The MSC was established by News Corp with a role and remit to investigate allegations of criminality relating to phone hacking at the NoTW and other NI titles. Specifically, the MSC has been set up to investigate a number of matters including: allegations of phone hacking at the NoTW; allegations of illegal payments made by NI employees to public officials, including police officers; and all other related issues with regard to NI (including this Inquiry).<?php footnoteRef('E',5,37); ?> The Committee has therefore played a role of fundamental importance to the ongoing criminal and other investigations into the allegations of wrongdoing at NI. The reason for this new approach is clear. Quite apart from issues concerned with reputation, the United States&#8217; Foreign Corrupt Practices Act makes it illegal for any US company to pay bribes to overseas officials and News Corp (the corporate parent of News International) is incorporated in the USA. In the light of what had emerged in the UK, it is not surprising that while NI (and, to a lesser extent, News Corp) is subject to investigation in the UK, government and regulators in the USA have also been concerned to look at what had been happening. Rupert Murdoch told the Inquiry that News Corp (through the MSC) was therefore cooperating fully with the US Department of Justice.<?php footnoteRef('E',5,38); ?></p>
  <?php paragraphLink('E',5,2,7); ?>The UK investigations into allegations of phone hacking and payments to public officials are being led by the MPS. Operation Elveden, investigating the allegations of police corruption, has been operating under the supervision of the Independent Police Complaints Commission (IPCC).<?php footnoteRef('E',5,39); ?> The MPS investigations have focused on the UK subsidiary, NI, and although the MSC is cooperating with enforcement agencies in both the USA and the UK, the investigatory remit of the MSC is restricted to only NI titles and matters in the UK.<?php footnoteRef('E',5,40); ?> The MSC has been authorised by the News Corp board to investigate practices through a process of internal review at the NI titles, namely The Sun, The Times and The Sunday Times. It has also assisted in relation to the evidence gathering related to the NoTW.</p>
  <?php paragraphLink('E',5,2,8); ?>As well as the Committee&#8217;s investigatory functions, the MSC is also responsible for recommending and overseeing the implementation of new policies and systems at NI titles. According to representatives of the MSC, the purpose of this role is to ensure that the highest standards of editorial practices are upheld in future at NI. This includes ensuring business at the newspaper titles, The Sun, The Times and The Sunday Times, are underpinned by robust systems of governance and compliance, as well as a legal structure.<?php footnoteRef('E',5,41); ?> The Inquiry has not heard any evidence in relation to such recommendations made by the MSC.</p>
  <?php paragraphLink('E',5,2,9); ?>In addition, the MSC has also been given the authority to negotiate and settle any civil litigation in relation to phone hacking. As such it oversees the News International Compensation Scheme for victims in relation to voicemail hacking by the NoTW and it is right that full mention should be made of this willingness by NI to provide informal redress. The Scheme was announced by NI on 8 April 2011, following a public apology from the newspaper, their publishing company News Group Newspapers (NGN) as well as NI itself, for the actions of journalists involved in phone hacking at the NoTW.<?php footnoteRef('E',5,42); ?> The Scheme was launched on 4 November 2011, with the solicitors, Olswang, being appointed to handle all victim-driven civil litigation in relation to voicemail hacking at the NoTW, along with administrative responsibilities in relation to the Scheme.<?php footnoteRef('E',5,43); ?> Sir Charles Gray (formerly a High Court Judge and a very experienced media lawyer) was appointed as the adjudicator of the Scheme. As such, he has provided an independent assessment of any applications received for compensation claims made against NGN by those whose voicemails had allegedly been intercepted.<?php footnoteRef('E',5,44); ?></p>
  <?php paragraphLink('E',5,2,10); ?>According to NI, the purpose of the Scheme is to offer an accessible and streamlined process for the victims of voicemail hacking, in order that they might obtain remedial action without the complexities that can be involved in the court process. The Scheme has also promised an uplift of 10% in respect of potential payments, based on what victims might expect if they successfully settled in the courts. The Scheme has advised potential victims of alleged voicemail hacking to contact the police team in Operation Weeting before applying to join the Scheme, so that the police can identify whether they have been revealed to have been a victim as part of the investigation, thereby justifying a claim. NGN is responsible for reimbursing the costs incurred by the MPS in providing those who apply with appropriate disclosure; it also meets the legal advisory costs of any alleged victims joining the Scheme.<?php footnoteRef('E',5,45); ?></p>
  <h3>Cooperation with the police</h3>
 <?php paragraphLink('E',5,2,11); ?>The autonomy of the MSC has been the cornerstone of the collaboration between the MSC and all those working on the ongoing investigations into the allegations of wrongdoing at NI.<?php footnoteRef('E',5,46); ?> In addition to the three overarching investigations being undertaken by the MPS, namely Operations Weeting, Elveden (under the supervision of the IPCC) and Tuleta, along with the subsidiary operations that are derived from those, there are the ongoing civil proceedings relating to phone hacking and data hacking and the Parliamentary hearings of the Culture, Media and Sport Select Committee.<?php footnoteRef('E',5,47); ?> In this regard, in its 11 th Report of Session 2010-12, that Committee commented on the cooperation of the MSC at the time of the Parliamentary investigation, praising:<?php footnoteRef('E',5,48); ?></p>
<blockquote>&#8220;&#8230;the willingness of the newly-established Management and Standards Committee to provide the Committee with unsolicited copies of recently unearthed e-mail exchanges that are of relevance to the events under investigation&#8221;.</blockquote>
  <?php paragraphLink('E',5,2,12); ?>Deputy Assistant Commissioner Sue Akers has sought to explain to the Inquiry the nature and reality of the relationship between the MPS and the MSC. In particular, DAC Akers has praised the levels of assistance and cooperation demonstrated by the MSC, as well as its cooperation in providing information which has been requested by officers conducting the three MPS investigations. As an example of the cooperative approach of the MSC toward the MPS investigations, this has included the voluntary disclosure of potential evidence to Operation Elveden, gathered as part of the MSC&#8217;s internal review of The Sun.<?php footnoteRef('E',5,49); ?> It is also perhaps illustrative of the MSC&#8217;s approach to the matters of investigation, that the Committee initiated internal reviews of The Sun, The Times and The Sunday Times without specific requests from the MPS.</p>
  <?php paragraphLink('E',5,2,13); ?>To a certain extent, the MPS has been dependent on the cooperation of the MSC in relation to the disclosure of information; although cooperation is exactly what the police would expect from any corporate body where evidence of criminality has been revealed. As DAC Akers explained to the Inquiry, however, because of the terms of the Police and Criminal Evidence Act 1984 (PACE) (as to which the Deputy Commissioner of the MPS has made submissions to the Inquiry), the MPS has not been in a position to force compliance. She stated that:<?php footnoteRef('E',5,50); ?></p>
<blockquote>&#8220;&#8230;the legal advice that we&#8217;ve had has told us that whilst you have the co-operation of News International, as it is in this case, we must proceed by the way of protocol, and that&#8217;s what we&#8217;re doing. So it&#8217;s voluntary disclosure as opposed to applying for a production order through PACE&#8221;.</blockquote>
  <?php paragraphLink('E',5,2,14); ?>To date, pursuant to requests and otherwise, the MSC has disclosed large amounts of documentation to Operation Elveden. Evidence obtained through the analysis of some of this documentation has already led to a number of arrests of journalists, as well as other staff at The Sun, on 28 January 2012 and 11 February 2012.<?php footnoteRef('E',5,51); ?> These (and other) arrests since November 2011 have been highly publicised. Indeed, some of this coverage has led to complaints from current journalists at The Sun, particularly concerning the circumstances and scale of the arrests. By way of example, following the arrests on 11 February 2012, the associate editor of The Sun, Trevor Kavanagh, claimed that a disproportionately large number of police officers had been involved in the dawn arrests of journalists at their homes and in The Sun offices, representing a witch hunt and an attack on press freedom.<?php footnoteRef('E',5,52); ?></p>
  <?php paragraphLink('E',5,2,15); ?>In response, Ms Akers explained that the fact that the arrests were carried out without warning was in line with protocols for such investigations, with the primary goal being to secure evidence and prevent suspects from conferring or disposing of evidential material.<?php footnoteRef('E',5,53); ?> She also suggested that arrests had been carried out in a manner intended to minimise business disruption to the newspaper, noting that searches of The Sun offices were conducted on a Saturday, outside of business hours. She went on to state that:<?php footnoteRef('E',5,54); ?>
<blockquote>&#8220;The purpose of police action to date has been proactively to investigate the alleged criminality which has been identified. The aim has never been to threaten the existence of The Sun. To this end there has been liaison with the MSC to take account of business risk to The Sun newspaper hence searches being made at The Sun offices on a Saturday when the office would be empty&#8221;.</blockquote> DAC Akers has acknowledged that this approach to the conduct of searches has since been changed, following the launch of The Sun on Sunday.</p>
  <?php paragraphLink('E',5,2,16); ?>DAC Akers has also told the Inquiry that there was a time when the attitude of the MSC to the MPS changed somewhat. Following the arrests of 28 January 2012 and 11 February 2012, DAC Akers said that the approach of the MSC to the disclosure of evidence was different:<?php footnoteRef('E',5,55); ?></p>
<blockquote>&#8220;We were being asked perhaps to justify our requests to a degree that we perhaps formerly hadn&#8217;t been, and the material that we were requesting was slower in being forthcoming&#8221;.</blockquote>
  <?php paragraphLink('E',5,2,17); ?>This change of behaviour occurred at a time of increased publicity for both the MPS and the MSC, against a backdrop of threats of legal action against the MSC and also when changes were made to the senior personnel at the MSC,<?php footnoteRef('E',5,56); ?> which might themselves have contributed to the different relationship between the MSC and the MPS. In this regard, she observed:<?php footnoteRef('E',5,57); ?></p>
<blockquote>&#8220;&#8230;those two arrest days, there was considerable adverse publicity of both the MPS, the police and the MSC, including threats of legal action against the MSC.&#8221; </blockquote>
  <?php paragraphLink('E',5,2,18); ?>More specifically, DAC Akers has referred to a period in May 2012 when, for a number of weeks, the MSC temporarily halted the voluntary disclosure of material to the MPS.<?php footnoteRef('E',5,58); ?> She reported to the Inquiry her understanding that the MSC had been considering their position in relation to the MPS operations during this hiatus<?php footnoteRef('E',5,59); ?> and went on:<?php footnoteRef('E',5,60); ?></p>
<blockquote>&#8220;At the beginning, when we began the enquiries, all contact was through the lawyers; then these were other lawyers, Burton Copeland. Then Mr Lewis and Mr Greenberg were introduced to help facilitate the co-operation, which they did. And in mid- May this year, following a development in our investigation, it caused the MSC to reconsider their position and they decided that they would prefer the meetings to be on a more formal basis with lawyers only&#8221;.</blockquote>
  <?php paragraphLink('E',5,2,19); ?>DAC Akers stressed the importance of full cooperation by the MSC to police operations, and commented that any change in the approach of the voluntary disclosure of evidence would: &#8220;&#8230; adversely affect initial decisions that we&#8217;d made and arrests that were made as well&#8221;.<?php footnoteRef('E',5,61); ?> The disclosure of documentation by the MSC resumed in mid-June, following discussion between the MPS with Lord Grabiner and the legal team representing the MSC.<?php footnoteRef('E',5,62); ?> Such consequences would undeniably have affected the extent to which NI could have argued that it had adopted a new approach to compliance with the criminal law.</p>
  <?php paragraphLink('E',5,2,20); ?>At that same meeting, a new framework was agreed in relation to communication. This has involved a changed format to meetings between the MSC and MPS teams, and, notably, the insistence on legal representation by the MSC while liaising with officers from the MPS operations.<?php footnoteRef('E',5,63); ?> Further, a number of executive members of the MSC, including Will Lewis and Simon Greenberg, have been stood down from attending regular briefings between the two parties.<?php footnoteRef('E',5,64); ?> Despite the change in process, DAC Akers was keen to make clear in evidence to the Inquiry that the professional approach of the MSC towards the MPS has been maintained and that the change &#8220;&#8230;hasn&#8217;t affected the co-operation, which is still very good&#8221;.<?php footnoteRef('E',5,65); ?></p>
  <?php paragraphLink('E',5,2,21); ?>Since DAC Akers gave evidence in July, it is clear that some tensions have become apparent about the way in which the relationship between the MSC and the MPS has developed. I cannot resolve this issue and, for good reason, I am satisfied that it is not appropriate to elaborate or even to set out the respective positions. In the circumstances, I leave the matter there.</p>
  <h4>The approach of the MSC to disclosure</h4>
 <?php paragraphLink('E',5,2,22); ?>Material provided by the MSC is for the MPS to assess, evaluate and follow up as appropriate. The MSC has made clear that it has a duty to protect journalistic sources used by the NI titles and it is careful to ensure that these are not compromised through disclosure.<?php footnoteRef('E',5,66); ?> Where disclosed material might enable the identification of confidential but legitimate sources of information, the MSC has provided such documentation in redacted form. All such material has been categorised in order to determine whether and what redactions should apply.</p>
  <?php paragraphLink('E',5,2,23); ?>To this end, DAC Akers has explained the detail of the process of receiving documents relating to the allegations of alleged payments to public officials. In such circumstances, documents which, in the first instance, have been redacted to remove confidential material, are provided to officers working on Operation Elveden. However, if, following this disclosure, the assessment of the evidence by the MPS provides a proper justification for identifying the source, the MSC will provide the information, this time in an unredacted form.<?php footnoteRef('E',5,67); ?></p>
  <?php paragraphLink('E',5,2,24); ?>In response to questions from Mr Jay, DAC Akers has sought to provide a sense of the scale and scope of the material disclosed by the MSC. She noted that this material related to allegations of data intrusion, including phone hacking, computer hacking and the illegal accessing of other personal data. Separately, it also contains material relevant to Operation Tuleta, which is now investigating over 100 separate allegations of data intrusion. The documentation provided has been sourced from previous inquiries, as well as the review of 70 electronic storage devices which were seized during both Operations Weeting and Elveden.<?php footnoteRef('E',5,68); ?> Ms Akers has said that the evidence gathered amounted to between eight and twelve terabytes of data.<?php footnoteRef('E',5,69); ?></p>
  <?php paragraphLink('E',5,2,25); ?>Material of real significance has also been disclosed by the MSC to officers working on Operation Elveden, which appears to indicate that not only were routine payments made to public officials by some journalists working at the NoTW but that similar payments had also been made by the employees of The Sun. These payments are alleged to have occurred on multiple occasions and included large payments in figures of thousands of pounds. In her oral evidence, DAC Akers said that:<?php footnoteRef('E',5,70); ?></p>
<blockquote>&#8220;There also appears to have been a culture at the Sun of illegal payments, and systems have been created to facilitate those payments, whilst hiding the identity of the officials receiving the money. The emails indicate that payments to sources were openly referred to within the Sun, in which case the source is not named, but rather the category &#8220;public official&#8221; is identified, rather than the name&#8221;. </blockquote>
  <?php paragraphLink('E',5,2,26); ?>The consequence of this disclosure by the MSC has led the police to the investigation of those to whom payments were made. This has revealed evidence to suggest that the practice of payments to public officials, including police officers, may have taken place at other titles outside the NI titles.<?php footnoteRef('E',5,71); ?> In her evidence to the Inquiry in July 2012, Ms Akers said that the MPS had identified potential payments to individuals related to prison officials, made by staff at both Trinity Mirror Group (TMG) and the Express News Group (the Express). The MPS now believes that a number of stories published in the Daily Mirror, the Sunday Mirror, the Daily Star and the Star on Sunday, were obtained through such payments.<?php footnoteRef('E',5,72); ?> As a consequence of this disclosure, an employee of TMG and an employee of the Express were arrested by officers working on Operation Elveden. This has led the police to seek the assistance of both those groups, requesting evidential material relating to these arrests.<?php footnoteRef('E',5,73); ?></p>
  <?php paragraphLink('E',5,2,27); ?>Although not relevant to the MSC, it is appropriate here to note that TMG and the Express have taken different approaches to the requests for information requests from the MPS. Specifically, TMG has asked the MPS to obtain a production pursuant to PACE which it is said will not be opposed; the Express has stated that the company would be prepared voluntarily to share documents through an agreed system, similar to that operated by the MSC; at the time of Ms Akers&#8217; evidence, no such protocol had been put in place.<?php footnoteRef('E',5,74); ?></p>
  <h4>A critical view of the MSC</h4>
 <?php paragraphLink('E',5,2,28); ?>Although the MSC operates independently of NI and News Corp, its independence has not gone unchallenged by some witnesses to the Inquiry. Brian Paddick, a former Deputy Assistant Commissioner of the MPS, has raised doubts over the ability of the MSC to conduct an impartial and transparent investigation. The fact that News Corp was responsible for the establishment of the MSC has led Mr Paddick to believe that the MSC was potentially susceptible to the influence of News Corp executives and staff, and that this alleged influence may have an impact on both its investigations and cooperation with the MPS.<?php footnoteRef('E',5,75); ?></p>
  <?php paragraphLink('E',5,2,29); ?>Mr Paddick also explained his lack of faith in the credibility in the system of disclosure. He expressed concerns that the MSC might withhold potential evidence from the MPS, particularly as the disclosure of material is voluntary, noting that reliance has been placed on cooperation rather than a production order sought pursuant to the legislative powers set out in PACE.<?php footnoteRef('E',5,76); ?> Commenting specifically on the disclosure of evidence by the MSC in relation to the internal review of the practices at The Sun, Mr Paddick said that:<?php footnoteRef('E',5,77); ?></p>
<blockquote>&#8220;The difficulty is &#8211; and as she (Sue Akers) is saying, for example, all the issues that we&#8217;ve had around the Sun newspaper she never asked for. It&#8217;s been volunteered by this committee. What information are they not volunteering that Sue Akers is not aware of?&#8221; </blockquote>
<p>He also suggested that the MSC had an advantage in so far that it was potentially able to withhold material from the MPS investigations, by claiming journalistic privilege:<?php footnoteRef('E',5,78); ?></p>
<blockquote>&#8220;...whilst it&#8217;s maybe ... it is independent of News International, it&#8217;s not independent of the parent company, as it were&#8230; &#8230;requests are put in to this committee by the police. If that committee decides that actually, as far as they&#8217;re concerned, there&#8217;s no criminal implications, that it is subject to journalistic privilege, then that committee does not reveal the information that the police are asking for.&#8221; </blockquote>
  <?php paragraphLink('E',5,2,30); ?>Mr Paddick has also criticised the lead role of the MPS in the investigations of allegations of corrupt payments made to police officers, as well as public officials. He expressed reservations at the putative neutrality of the MPS, explaining that he feared that public perceptions risked becoming skewed by the fact that the investigation into the alleged corruption of MPS officers was being conducted by the very police force under investigation. Although Mr Paddick made specific acknowledgement of the integrity of both DAC Akers and the Commissioner of the MPS, Mr Paddick has made clear that he remained concerned that the MPS could not objectively investigate alleged corruption within their own force. He has suggested that an external police force, one which was not implicated in the current investigations, should have been appointed independently to investigate the alleged wrongdoing which has taken place. He told the Inquiry that:<?php footnoteRef('E',5,79); ?></p>
<blockquote>&#8220;&#8230;some people may not be convinced by the current arrangements and it may be better if it was an outside force who were investigating, purely from a public perception point of view. But I am not in any way casting doubt on either Sue Akers&#8217; integrity, nor the head of the MSC&#8230;&#8221; </blockquote>
  <?php paragraphLink('E',5,2,31); ?>The suggestion was also raised during Mr Paddick&#8217;s oral evidence that it would be difficult to find an independent force with senior officers who did not have previous experience at the MPS, but Mr Paddick maintained that this could be achieved, and that it would be better in terms of public perception if the MPS were unaffiliated with the investigation. He said:<?php footnoteRef('E',5,80); ?></p>
<blockquote>&#8220;&#8230;it is possible to find ACPO officers who have no previous history with the Metropolitan Police who could lead up this investigation. Whether they would be better at it, I don&#8217;t know, but in terms of public perception, I&#8217;m saying that it might be better.&#8221; </blockquote>
  <?php paragraphLink('E',5,2,32); ?>Mr Paddick has also voiced concerns at the risk of collusive behaviour between the MPS and NI. Specifically, he was concerned at what could happen should the MPS investigations, or the MSC reviews of the NI titles, uncover evidence which placed either party in an unfavourable position in the public eye. He explained his concerns using a hypothetical example:<?php footnoteRef('E',5,81); ?></p>
<blockquote>&#8220;&#8230;perhaps somebody very senior in the Metropolitan Police is seen to be having received inappropriate payments from somebody very senior in News International, how it might be in the interests of Rupert Murdoch or News Corp and in the interests of the Metropolitan Police for that not to be made public.&#8221; </blockquote>
  <?php paragraphLink('E',5,2,33); ?>Mr Paddick suggested that it may be possible for the MPS and NI to work together to disguise or hide incriminating evidence in order to protect the reputation of either organisation. In his response to questions from Counsel to the MPS, Neil Garnham QC, Mr Paddick remained of the view that he had &#8220;&#8230;difficulty in having complete confidence&#8221; in the MPS investigations for the reasons he has elucidated.<?php footnoteRef('E',5,82); ?> Although Mr Garnham was at pains to address a number of external factors which would prevent such collusion, including oversight of Operation Elveden by the IPCC, Mr Paddick insisted that the investigation:<?php footnoteRef('E',5,83); ?>
<blockquote>&#8220;&#8230;should be led by a senior office from another force who has had no previous service with the Metropolitan Police.&#8221; </blockquote>He also expressed his concerns about the independence of the IPCC but did not elaborate further.</p>
  <?php paragraphLink('E',5,2,34); ?>DAC Akers has also addressed the concerns raised by Mr Paddick, by emphasising the fundamental importance of the professional and productive relationship the MPS has built with the MSC. She stressed that the independence of the MSC from NI and the structure it operates within:<?php footnoteRef('E',5,84); ?></p>
<blockquote>&#8220;&#8230;goes a long way to allay some criticisms that have been made about how it&#8217;s perceived that it can&#8217;t be necessarily an independent inquiry. The fact that we are dealing with the MSC directly and not News International I think should make any contention that it isn&#8217;t independent without foundation.&#8221; </blockquote>
  <?php paragraphLink('E',5,2,35); ?>As testament to the important contribution that the MSC has made to the investigation, DAC Akers noted that, as at the date of her fourth witness statement, namely 31 October 2012, the disclosure of material to Operation Elveden had led to the arrest of 25 journalists out of a total of 52 arrests; this was in addition to 25 arrests made as part of Operation Weeting and 17 arrests as part of Operation Tuleta.<?php footnoteRef('E',5,85); ?></p>
  <?php paragraphLink('E',5,2,36); ?>In forming a view about these matters, I am primarily reliant on the evidence provided by DAC Akers (about whom nobody has spoken other than in terms of the highest praise) although I also have professional experience of Lord Grabiner and knowledge of his high standing as an independent barrister in England and Wales. Furthermore, I am able to draw inferences from the nature and extent of what has happened as events have unfolded. On the other hand, there has been no evidence to support the concerns raised by Mr Paddick, either as to the independence of the MSC or to the impartiality and integrity of the MPS officers responsible for the conduct of its investigation into alleged police corruption and other crime.</p>
  <?php paragraphLink('E',5,2,37); ?>The purpose of the MSC has been to re-establish (or establish) a reputation in NI as a company that takes its obligations to the law very seriously and is determined to root out criminality wherever it has existed and whomever it has involved, albeit recognising that some difficult decisions might have to be made in relation to journalistic privilege. In the light of events, neither News Corp nor NI can do less if the purpose is to be achieved. It is obviously important that News Corp, NI and the MSC continue in the resolve that has now been shown.</p>
  <?php paragraphLink('E',5,2,38); ?>I ought to make it clear that I am not at all critical of Mr Paddick for raising these concerns which I have no doubt are legitimate and ventilated in good faith, based on the history of this investigation and seared by his own experience both of NI and the MPS. For my part, however, I am fully satisfied as to the way in which the police are now conducting this investigation (to which considerable resources have been devoted doubtless because of the reputational damage that the MPS has suffered) and as to the integrity of the officers involved.</p>
  <?php paragraphLink('E',5,2,39); ?>Equally, albeit without resolving the present differences between the MPS and the MSC, I have seen no evidence to undermine the view expressed by DAC Akers as to the independence of the MSC and its effectiveness as an independent arbiter in accordance with its remit. I am satisfied that sufficient safeguards (by way of protocols and otherwise) have been put in place to dispel legitimate concerns along the lines that he has raised.</p>
  <h4>Findings and progress of the MSC</h4>
 <?php paragraphLink('E',5,2,40); ?>On 1 May 2012, the MSC announced the completion of its internal reviews of the three NI titles, that is to say The Times, The Sunday Times and The Sun.<?php footnoteRef('E',5,86); ?> Rupert Murdoch, in an address to NI staff, has been quoted in relation to the findings of the reviews of The Times and The Sunday Times, saying there was:<?php footnoteRef('E',5,87); ?>
<blockquote>&#8220;&#8230;no evidence of illegal conduct other than a single incident reported months ago&#8221;.</blockquote> This single incident is thought to refer to the activities of the former Times journalist in relation to gaining unlawful access to one or more personal emails.</p>
  <?php paragraphLink('E',5,2,41); ?>No further details have been announced in relation to findings of the internal review of The Sun. Neither has the MSC released further documentation to the MPS following the completion of its review of The Sun. DAC Akers put the matter in this way:<?php footnoteRef('E',5,88); ?>
<blockquote>&#8220;&#8230;the MSC would say the result of the review was the material that they had disclosed to us, but we haven&#8217;t received or -- I understand there is no formal report as a result of their review.&#8221; </blockquote>Neither has the Inquiry heard any evidence in relation to the findings of the reviews conducted by the MSC. In the light of the quantity of evidence that has emerged from these titles and the evidence of DAC Akers, no further information has been sought.</p>
  <?php paragraphLink('E',5,2,42); ?>In the meantime, the MSC has also begun to implement governance reforms in the newspaper titles at NI. These reforms include improving policies relating to anti-bribery, whistleblowing and payments. These changes have been implemented through the office of Gerson Zweifach and appropriate information relating to them has been disseminated to employees and staff at NI.<?php footnoteRef('E',5,89); ?> The Inquiry has not heard any evidence relating to these specific reforms by the MSC, although Thomas Mockridge, Chief Executive Officer of NI, informed the Inquiry in October 2011 that:<?php footnoteRef('E',5,90); ?></p>
<blockquote>&#8220;&#8230;it is appropriate that compliance within NI be strengthened immediately. I have therefore not waited for the output of the reviews... I have implemented, or am in the process of implementing, new policies&#8230; Current policies, practices and systems may be adjusted later in line with the findings of the reviews.&#8221; </blockquote>
  <?php paragraphLink('E',5,2,43); ?>Finally, it is worth noting the costs of the MSC to NI have been borne by the UK subsidiary rather than by News Corp. From the Group Report and Financial Statement, as at 8 May 2012, excluding any costs relating to the News International Compensation Scheme or ongoing civil litigation, the MSC has cost NI &#163;53.2 million. These costs have been accrued primarily in legal and professional fees since July 2011.<?php footnoteRef('E',5,91); ?> It is likely that, by the time of publication, these costs will have increased further.</p>
  </div>

