<div class="content" id="contentPartEChapter2">
<h1 id="top">CHAPTER 1<br/>THE LEGAL FRAMEWORK</h1>
<?php sectionAnchor('E',1,1); ?>
 <?php paragraphLink('E',1,1,1); ?>An Inquiry into the culture, practices and ethics of the press might not be thought to engage or require detailed consideration of the law but, as many witnesses have correctly identified, the starting point from which any assessment of the way in which the press goes about its business must be the general framework of the law. In that regard, there have been criticisms that the press is already far too over-regulated with particular reference to the complications of the ever-changing criminal and regulatory law, itself requiring training for journalists, as well as the equally ever-developing civil law. In this second category falls not only the jurisprudence in this country (in respect of which particular criticism has been made of the law of defamation) but also the effect of the Human Rights Act 1998, which gave further effect in domestic law to the rights and freedoms guaranteed under the European Convention on Human Rights and Fundamental Freedoms 1950 (Cmd. 8969) (ECHR). That has led to litigation involving the press that has not infrequently been taken through the UK courts and has then been the subject of further argument before the European Court of Human Rights.</p>
  <?php paragraphLink('E',1,1,2); ?>The purpose of this Inquiry is not to analyse the law in any depth but, in order to provide a wider picture to anyone interested in the issues affecting the press, it is necessary to provide some background in relation to the criminal law, the civil law and the regulatory framework provided by the Data Protection Act 1998. Where the law touches upon specific issues which fall within the Terms of Reference, a degree of analysis will follow in the text. Otherwise, a general outline has been provided in Appendices to the Report. Nobody should rely on the Appendices as a complete review of the nuances of the law: there are text books for that purpose. It is intended only to identify the broad landscape.</p>
  <?php paragraphLink('E',1,1,3); ?>The criminal law can touch upon the work of journalists in many ways and inevitably prescribes the ways in which it is acceptable for stories to be obtained. A brief summary of aspects of the criminal law most likely to be engaged in the pursuit of journalism is at Appendix 4 but it is neither complete in detail nor is it comprehensive. By way of example, aspects of the behaviour of Neville Thurlbeck as he pursued a follow up to his scoop relating to Max Mosley were described by Mr Justice Eady in the ensuing civil litigation as containing &#8220;a clear threat to the women involved that unless they cooperated &#8230; (albeit in exchange for some money)&#8221; making the point that it was &#8220;elementary that blackmail can be committed by the threat to do something which would not, in itself, be unlawful.&#8221;<?php footnoteRef('E',1,1); ?> Blackmail is not, however, a crime that is covered in this Appendix. There is no doubt room for other potential offences to be engaged in the unprincipled pursuit of a story.</p>
  <?php paragraphLink('E',1,1,4); ?>In addition to the substantive criminal law, it is also necessary to consider aspects of criminal procedure which recognise the important place that journalism plays in our society and accords to journalists special protection in relation to journalistic material. The restrictions and limitations on the powers of the police to search for or seize such material add to the privileges that society gives to those involved in this work: they are summarised in Appendix 4.</p>
  <?php paragraphLink('E',1,1,5); ?>The same is so for the civil law. Developments have undeniably broadened the focus in defamation beyond meaning, justification and fair comment. In addition, new concerns surround the concept of privacy. This has developed with the increasing recognition of the significance of Article 8 of the ECHR which, subject to exceptions, provides for everyone the right to respect for his private and family life, his home and his correspondence. Running parallel to Article 8, however, is Article 10 which, similarly subject to exceptions, provides that everyone has the right to freedom of expression, including the freedom to hold opinions and to receive and impart information and ideas without interference by public authority and regardless of frontiers. A brief summary of the most important aspects of the civil law insofar as it affects journalism or journalists is set out at Appendix 4. Again, it is not intended to be exhaustive.</p>
  <?php paragraphLink('E',1,1,6); ?>A separate analysis has been completed in relation to the law of data protection (see Appendix 4). That is because it has criminal, civil and regulatory aspects and stands outside the areas of law so far outlined with the Information Commissioner being accorded, by statute, powers and responsibilities which go beyond the power to prosecute, or to commence civil proceedings. Given that the Terms of Reference specifically cover &#8220;the extent to which the current policy and regulatory framework has failed including in relation to data protection&#8221; the remit of the Information Commissioner will require detailed analysis beyond the brief synopsis of the legislative framework.<?php footnoteRef('E',1,2); ?></p>
  <?php paragraphLink('E',1,1,7); ?>Against the background of this framework, this Part of the Report will focus chronologically on the criminal investigations that have been undertaken both in relation to data protection and interception of mobile telephones, the outcome of those investigations and the reaction not only at the time but as further material entered the public domain. In particular, the milestones that led to this Inquiry include: 
  <ol type="a">
<li>the publicity accorded to the investigations by the Information Commissioner through reports to Parliament and discussions with the PCC; </li>
<li>the outcome of each of the criminal prosecutions and, in particular in relation to Operation Caryatid, the police strategy adopted thereafter; </li>
<li>the reaction of the press (and, in particular, the News of the World) to the prosecutions along with the response of the PCC; </li>
<li>the impact of civil litigation; </li>
<li>the investigations undertaken by the Guardian and, subsequently, the New York Times along with the reactions of the police and Parliament to each of the articles; </li>
<li>the further civil litigation and the proceedings for judicial review of the strategy adopted by the police following the successful prosecutions of Clive Goodman and Glenn Mulcaire; </li>
<li>the re-opening of the criminal investigation and the reactions thereafter of News International, the PCC and Parliament.</li>
</ol>
</p>
  <?php paragraphLink('E',1,1,8); ?>The purpose of this Part of the Report is to provide what is a vital narrative to the background against which the criticisms of the culture, practices and ethics of the press (or part of the press) can be considered. It starts with the police operations that led to Operation Motorman, which was an investigation that fell to the Information Commissioner. The narrative then passes to Operation Caryatid, the police investigation of interception of voicemail messages (phone hacking) and its consequences, which continue to be felt today.</p>
  </div>

