<?php 
require_once('../../common.php');
levesonHeader('B',2); 
levesonNav('../../');
levesonBread('B',2);
require_once('content.php');
levesonFooterNav('B',2); 
require_once('footnotes.php');
LevesonCommonFooter();
?>