<?php 
require_once('../../common.php');
levesonHeader('C',4); 
levesonNav('../../');
levesonBread('C',4);
require_once('content.php');
levesonFooterNav('C',4); 
require_once('footnotes.php');
LevesonCommonFooter();
?>