<div class="content" id="contentPartAChapter3">
<h1 id="top">CHAPTER 3<br/>FURTHER ISSUES OF LAW</h1>
 <?php sectionAnchor('A',3,1); ?>Rule 13 of the Inquiry Rules 2006: the approach</h2>
 <?php paragraphLink('A',3,1,1); ?>Prior to the publication of any Report which includes explicit or significant criticism of any person, the Inquiry Rules 2006 mandate that such a person must be warned of that criticism and given a reasonable opportunity to respond. I set out the background and the legal framework in a ruling on the Application of Rule 13<?php footnoteRef('A',3,1); ?> which I can do no better than repeat:</p>
 <blockquote>
 <ol start="8">
  <li>One of the touchstones of the inquisitorial process prescribed by the 2005 [Inquiries] Act is the requirement of fairness to all. Whereas s. 17(1) of the Act provides that the procedure and conduct of the Inquiry shall be such as I direct, that provision is subject to s. 17(3) in these terms: &#8220;In making any decision as to the procedure or conduct of an inquiry, the chairman must act with fairness and with regard to the need to avoid any unnecessary cost (whether to public funds or to witnesses or others).&#8221;</li>
  <li>No higher manifestation of that duty is apparent than that which deals with the requirement that those who may be criticised in any report have the opportunity afforded to them to deal with the basis of that criticism. The origin is to be found in the Royal Commission on Tribunals of Inquiry (Cmnd 3121, 1966) (&#8220;the Salmon Report&#8221;) which proposed, among other recommendations, that before a person was called as a witness, he should be informed of any allegations which are made against him and the substance of the evidence in support of them: thus were born Salmon letters although over-rigid adherence has been recognised as &#8216;unhelpful&#8217;: see the observations of Sir Richard Scott VC (in (1995) 111 LQR 596) to the effect that every inquiry must adapt its procedures to meet its own circumstances.</li>
  
  <li>The next manifestation of this requirement (described as &#8216;fair play in action&#8217; by Sachs LJ in Re Pergamon Press Ltd [1971] Ch 388 at 405) dealt with comment on proposed criticism. Mr Robert Maxwell&#8217;s attempt to obtain sight of proposed draft conclusions was rejected in the Court of Appeal when Lawton LJ put the matter in this way: see Maxwell v Department of Trade and Industry [1974] QB 523 at page 541B- D: &#8220;Those who conduct inquiries have to base their decisions, findings, conclusions or opinions ... on the evidence. In my judgment they are no more bound to tell a witness likely to be criticised in their report what they have in mind to say about him than has a judge sitting alone who has to decide which of two conflicting witnesses is telling the truth. The judge must ensure that the witness whose credibility is suspected has a fair opportunity of correcting or contradicting the substance of what other witnesses have said or are expected to say which is in conflict with his testimony. Inspectors should do the same but I can see no reason why they should do any more.&#8221;</li>
  
  <li>Notwithstanding these judicial observations, the broad process was adopted by Lord Bingham in the BCCI Inquiry, by Sir Richard Scott in the Inquiry into Matrix Churchill and also by Sir John Chilcott in the Iraq Inquiry. This lack of clarity is itself unhelpful and potentially productive either of very substantial delay or satellite litigation (in each case with attendant cost) or both.</li>
  
  <li>The 2005 Act (pursuant to which this Inquiry is being conducted) adopts a different and, in my judgment, self-contained approach to ensure fairness. First, s. 21 of the Act provides that I may by notice require any person to provide evidence in the form of a written statement along with documents. Such notices have identified, in comprehensive terms, the issues with which the statement has been required to deal; where appropriate, it has identified relevant documents or other public statements which should be addressed. It cannot, of course, deal with evidence not then seen by the Inquiry but where issues of significance have arisen before the witness arrives, forewarning has been given and, if necessary, witnesses allowed time to deal with a matter for which they were not prepared. Where the issue has arisen only after the witness has given evidence, again if it is significant, second statements have been requested and obtained; more than one witness has been required to return to give further evidence.</li>
  
  <li>The second (and most extensive) protection is provided by Rules 13-15 of the Inquiry Rules 2006 (&#8216;the 2006 Rules&#8217;) which concern what are described as Warning Letters. Thus, Rule 13 provides: 
 <ol>
  <li>The Chairman may send a warning letter to any person: 
  <ol type="a">
  <li>he considers maybe, or who has been, subject to criticism in the inquiry proceedings; or</li>
 <li>about whom criticism may be inferred from evidence that has been given during the inquiry proceedings; or</li>
 <li>who may be subject to criticism in the report, or any interim report.</li>
  </ol>
</li>
 <li>The recipient of a warning letter may disclose it to his recognised legal representative. 
 </li>
 <li>
 The inquiry panel must not include any explicit or significant criticism of a person in the report, or in any interim report, unless 
 <ol tyoe="a">
 <li>the chairman has sent that person a warning letter; and</li>
 <li>the person has been given a reasonable opportunity to respond to the warning letter.</li>
 </ol>
 </li>
  </ol>
 </li>
  </ol> 
  </blockquote> 
  <?php paragraphLink('A',3,1,2); ?>In my ruling, I explained the ways in which I have sought to ensure that the Inquiry was conducted fairly and with full regard to the position of all who might be affected. In relation to Rule 13, therefore, I concluded that a warning addressed to a section of the press consisting of the national titles (even if a number of those have not been the subject of criticism or complaint) allowed each to make submissions as to the conclusions that I should draw as to the culture, practices and ethics of the press generally (as opposed to the specific conduct of individual titles although it has been made clear titles have been free to comment on stories which are identifiably referable to them). I went on to conclude not only that generic criticisms should be evidence based, but that the justification for my concerns should be &#8220;visible and capable of being understood both by those affected and by the public&#8221;.<?php footnoteRef('A',3,2); ?></p>
  <?php paragraphLink('A',3,1,3); ?>I appreciate (as was argued by Mr Desmond Browne QC for Trinity Mirror plc) that this could allow anyone following the references through to the transcript to identify the titles and, perhaps, the relevant journalists; in reality, however, that would be possible whether or not I identified the references and, on the basis that I have not made specific findings in most individual cases, this approach does not offend the general principle that I am not focussing on the detail of &#8216;who did what to whom&#8217;. It is equally consistent with the principle that my intention not to prejudice criminal proceedings means that I have not identified those alleged to have been involved in mobile phone interception; therefore, in fairness, although there are exceptions when I have considered that the narrative compels specificity, generally speaking, I have exercised similar restraint in respect of those, not being investigated, who may be responsible for similar or other illegal or unethical practices.</p>
  <?php paragraphLink('A',3,1,4); ?>Conscious that any approach to Rule 13 was likely to be contentious, I arranged for the matter to be argued in principle and ruled on the approach generally. This ruling fell within to s38(1) (b) of the Inquiries Act 2005 and had any Core Participant wished to challenge it by way of judicial review, that course was open within 14 days. There was no such challenge and, insofar as generic criticism is concerned, I have followed it.</p>
  <?php paragraphLink('A',3,1,5); ?>I have, however, issued Rule 13 warnings to individuals (and others concerned with the relationship between the press and the public) in those circumstances where I thought fairness warranted it and, in particular, when I was concerned that any conclusion that I might reach in relation to a specific incident could be said to contain an express or implied criticism of them. The touchstone has been to provide an opportunity to make representations about identifiable concerns that I was proposing to express.</p>
  <?php paragraphLink('A',3,1,6); ?>Having said that, it is important that I emphasise that this Report should not be read as addressing the individual conduct of members of the press in their dealings with the public and no implied criticism should be read into the fact that references to particular complaints are inevitably to particular stories written by identifiable journalists (albeit not named in the text of the Report). I cannot repeat too often that this part of the Inquiry is not concerned with individual conduct but with the culture, practices and ethics of the press (or a section of the press) as a whole. Who would be to blame for a particular egregious story? Would it be a proprietor or editor who ordained a particular approach or a particular agenda? Would it be the journalist who felt driven to do what had been bidden irrespective of personal qualms? Would it be the sub-editor who wrote a headline that misrepresented what should be derived from correctly identified facts or modified the words of caution that the journalist had carefully included? How could I decide between these cumulative or alternative possibilities? In the circumstances, I have only been able to take the story at face value along with the reaction of the subject of the story and my view of the law (for example in relation to privacy) and the Editors&#8217; Code of Practice.</p>
  <?php paragraphLink('A',3,1,7); ?>The result of this analysis is that, in relation to most of the complaints made by those who have been subject to press intrusion I have not issued Rule 13 letters. This is because I do not intend either expressly or by implication to make explicit or significant criticism of the relevant journalists (rather than, generically, of the press). If I had done otherwise, hundreds of journalists (if not more), most of whom have neither been asked nor volunteered to give evidence to the Inquiry or even to make a statement, would have had to receive a warning. Having said that, if, in any particular case or in relation to any particular example that I wish to highlight, I have been in doubt, I have issued a warning and provided an opportunity for representations to be made. In reaching my conclusions, I have taken full account of the representations that I have received in response to all these warnings including those issued generically to the press.</p>
  <?php paragraphLink('A',3,1,8); ?>In relation to Module Two and the police, different considerations apply on the basis that there being no ongoing criminal investigation into the conduct of the MPS (although there are inquiries into other aspects of police conduct in relation to the press).<?php footnoteRef('A',3,3); ?> On the other hand, I received detailed submissions from Counsel for the MPS both generally and specifically as to the interaction of Parts 1 and 2 of the Inquiry. In the circumstances, I separately ruled in relation to the application of Rule 13 both to the MPS and to individual police officers.<?php footnoteRef('A',3,4); ?> Again, I have followed it and issued Rule 13 letters both general and specific in nature, taking full account of the representations that I have received.</p>
  <?php paragraphLink('A',3,1,9); ?>Module Three raised different issues for a number of reasons. First, there is no criminal investigation that could affect my approach and, in addition, it does not appear that there will be any other consideration of the general issues which I have to address in the Terms of Reference; that might be thought to be a basis for encouraging me to range further and wider than in relation to the other modules. On the other hand, the Terms of Reference are specific to the culture, practices and ethics of the press &#8216;including contacts and the relationships between national newspapers and politicians, and the conduct of each&#8217;. It is argued that the Inquiry should investigate the nature of friendships between individual members of the press and individual politicians but, save to the extent that these bite or may bite upon the way in which a journalist (or politician) attend to his or her professional duties, it does not appear to me that it is necessary or appropriate for me to enquire. Throughout the hearing of Module Three, I emphasised that politicians were entitled to be friendly with whosoever they wished; absent some impact on the public interest, it is no part of the work of the Inquiry to challenge that right.</p>
  <?php paragraphLink('A',3,1,10); ?>Second, each of the major UK political parties has recognised, in general terms, that the relationship between politicians and the press has become too close: indeed, that was the conclusion expressed by the Prime Minister and his three predecessors when they gave evidence. For me to express that conclusion, however, undeniably constitutes an &#8216;explicit or significant criticism&#8217; in respect of which I must issue a Rule 13 letter. Such a criticism, however, is not intended to be personal but generic. It recognises that how close is too close is itself a very difficult and nuanced issue, given that it is critically important, in a democratic society, that politicians engage with the press and seek to explain their policies to the public through the press.</p>
  <?php paragraphLink('A',3,1,11); ?>The third concern has been the extent to which the work of the Inquiry has involved contemporary political issues with the risk of entering into a party political debate which is no part of its function: this particularly relates to the attempted acquisition News Corp of the publicly owned shares in BSkyB Ltd. I made it clear that I would not opine on the Ministerial Code or seek to prevent Parliament from investigating whatever aspect of the bid it wished to investigate;<?php footnoteRef('A',3,5); ?> however, I recognise that it constitutes the most recent and most well documented inter-reaction between a very powerful media organisation and politicians (although the interaction in relation to the legislative proposals now contained in s77-78 of the Criminal Justice and Immigration Act 2008 which has not yet been implemented are also important). I have, therefore, attempted to analyse these issues from a general, cultural perspective: the process has inevitably involved a consideration of individual decisions and, on the basis that, even if not explicit, implied significant criticism may be inferred, I have issued appropriate warnings accordingly.</p>
  <?php paragraphLink('A',3,1,12); ?>I can deal with Module Four quite shortly. In this Report, each of the ideas put before the Inquiry has been subject to rigorous analysis and none more so than the proposals advanced by Lord Black of Brentwood (on behalf of the Press Board of Finance) and advocated by, among others, Lord Hunt of Wirral, the Chairman of the Press Complaints Commission. It is right that they should be, not least because, from the outset of the Inquiry and throughout, I encouraged the press to put forward their own ideas for press regulation, bearing in mind not only the values which it held to be important but also the interests of the public as demonstrated not only by the demand for this Inquiry but also by the evidence which has been given to it.</p>
  <?php paragraphLink('A',3,1,13); ?>I appreciate that Lord Black has had to deal with a wide spread of press interest; I have no doubt that different constituents have put forward different priorities and different ideas and that, furthermore, Lord Black has done his best to bring everyone to a common consensus which I expect is also consistent with his own ideas. Any concern or criticism that I have of the final formulation, however, is not a criticism of him or, indeed, any other person whether individual or corporate: neither should it be seen as such. In those circumstances, I have not felt it appropriate or necessary to give advance warning of my concerns but have simply set them out in the body of the Report.</p>
  <?php sectionAnchor('A',3,2); ?>Rule 13 of the Inquiry Rules 2006: the practice</h2>
 <?php paragraphLink('A',3,2,1); ?>The reason for the existence of Rule 13 of the Inquiry Rules is clear from this analysis. Flowing from that, however, are two further consequences. The first is the fact that a notice is only necessary to address potential criticism: it is not intended to present a balanced picture of any sort. Nobody needs to be warned of the risk that their conduct might be applauded. The point was clear from the body of the letter which explained: <blockquote>&#8220;By definition, this letter is focussed on the aspects of the culture, practices and ethics of the press which may attract criticism and it is not the function of this letter to refer to the evidence of good culture, practice and ethics which the Inquiry has received.&#8221;</blockquote>  </p>
  <?php paragraphLink('A',3,2,2); ?>The second consequence flows from the first. A possible criticism should not be interpreted as one that will inevitably be made. As a result, the letter also made it clear that both it and any response were subject to &#8220;a legal duty of confidence&#8221; owed in the public interest under Rule 14(1)(b) of the Inquiry Rules 2006.<?php footnoteRef('A',3,6); ?> This requirement (expressly mandated in the Rules) is specifically designed to discourage public discussion or debate about criticisms which have not yet been made and which could well, in the end, be less serious. It was and is, therefore, a demonstrable attempt to be fair and to provide an opportunity to those who might be affected to make submissions about possible criticism at a time when, as I made clear, I was continuing to reflect on the narrative and conclusions which I would reach and before I had done so.</p>
  <?php paragraphLink('A',3,2,3); ?>Thus, although it has been portrayed as such, the letter is not intended to be a secret: it is only confidential until the Report is signed or published,<?php footnoteRef('A',3,7); ?> after which time anyone is free to discuss the letters, criticise their content and analyse the extent to which my views might have changed. My concluded view, as expressed in the Report, will then be available.</p>
  <?php paragraphLink('A',3,2,4); ?>It is therefore not in the least surprising that the letters are &#8220;one-sided,&#8221; that the positive should not be subject to a similar letter, or that I would be concerned if the contents were being openly discussed in the press.<?php footnoteRef('A',3,8); ?> All are, of course, entitled to express whatever view they wish about the summary of press practice that can be culled from the evidence but it is worth repeating (not for the first, or the last, time) that the criticisms that I have suggested were not directed at the entirety of the press: most journalists, most if not all the time, do not behave in the way that, on my assessment of the evidence, a small but not insignificant number have behaved, thereby generating criticism of the culture that permitted this to happen, the practices involved and the ethics of those who have behaved in that way. As in every other walk of life, regulation is required for the small minority.</p>
  <?php paragraphLink('A',3,2,5); ?>A number of recipients of Rule 13 letters have questioned the fairness of the process on various grounds, and I should record that I have considered these objections and submissions with great care, always in the context of my ultimate obligation under section 17 of the Inquiries Act to act fairly. I am completely satisfied that all recipients who have chosen to submit substantive responses have understood the issues in respect of which I have sought further assistance, and have addressed them in appropriate detail. In the few instances where it appeared that recipients might have misunderstood the point that I wished them to have the opportunity to address, I have provided further explanation and given them that opportunity. In the result, many of my provisional conclusions have been revised or reformulated to reflect the Rule 13 process and the representations that I have received.</p>
  <?php sectionAnchor('A',3,3); ?>The nature and standard of proof</h2>
 <?php paragraphLink('A',3,3,1); ?>The starting point for any consideration of the nature of what must be proved and the standard of proof is, from the outset, to recognise that the Inquiry has been set up specifically because &#8220;particular events have caused ... public concern&#8221;.<?php footnoteRef('A',3,9); ?> To some extent, it is sufficient simply to refer back to the Terms of Reference of Part 1 of the Inquiry but, summarising at least the most important of these events, it would be appropriate to include as topics about which I have been required to inquire: 
 <ol type="a">
 <li>the disclosure of the interception of Milly Dowler&#8217;s mobile phone messages and the deletion of such messages;</li>
 <li>the fact that it was common ground that the News of the World had engaged in interception of mobile phone messages (revealed in civil litigation and otherwise) contrary to the continued assertion that Clive Goodman was one &#8220;rogue reporter&#8221;;</li>
 <li>other complaints of illegal or unethical methods by which journalists obtained stories (not the least significant being activity in breach of Data Protection legislation leading to a concern about the policy, operation and effectiveness of the regulatory regime for data protection);</li>
 <li>the harassment and pressure placed both on members of the public caught up in stories attracting enormous press coverage and those in the public eye whether because of their celebrity or otherwise;</li>
 <li>the failure of the Press Complaints Commission to address the activities of the News of the World (save only to exonerate them and criticise The Guardian for its reporting); to provide adequate regulatory oversight in relation to the press; to provide adequate redress for those complaining of press misconduct save in limited circumstances; and to ensure that its remit embraced the press as a whole;</li>
 <li>the nature of the relationship between the press and the police and, in particular, the extent to which failure of the police properly to investigate the extent of interception of mobile phone messages was a consequence of that relationship;</li>
 <li>the way in which politicians engaged with the press and, in particular, the extent to which the commercial interests of the press influenced the development or implementation of policy, along with the failure to address prior concerns over many years relating to media misconduct; and</li>
 <li>the impact of the plurality of the media and cross media ownership on the public interest.</li>
 </ol>
  </p>
  <?php paragraphLink('A',3,3,2); ?>More important than the topics about which I am required to inquire are the subjects about which I am required to make recommendations. It is sufficient to repeat the Terms of Reference which are expressed in this way: 
  <blockquote>&#8220;To make recommendations: 
  <ol type="a">
  <li>for a new more effective policy and regulatory regime which supports the integrity and freedom of the press, the plurality of the media, and its independence, including from Government, while encouraging the highest ethical and professional standards;</li>
  <li>for how future concerns about press behaviour, media policy, regulation and cross-media ownership should be dealt with by all the relevant authorities, including Parliament, Government, the prosecuting authorities and the police;</li>
  <li>the future conduct of relations between politicians and the press; and</li>
  <li>the future conduct of relations between the police and the press.&#8221;</li>
  </ol>
  </blockquote>  </p>
  <?php paragraphLink('A',3,3,3); ?>These issues are to be contrasted with those set out in Part 2 of the Terms of Reference, which are specifically directed to a far more fact focussed investigation of the conduct of News International and other newspaper organisations (&#8220;the extent of unlawful or improper conduct&#8221;, &#8220;the extent of corporate governance and management failures&#8221;), along with the police (&#8220;the extent to which the police received corrupt payments or other inducements, or were otherwise complicit in such misconduct or in suppressing its proper investigation&#8221;) and politicians (&#8220;the role, if any, of politicians, public servants and others in relation to any failure to investigate wrongdoing at News International&#8221;). In Part 2, there is a requirement &#8220;to consider the implications&#8221; of what is then found to have happened. In other words, Part 1 of this Inquiry is a qualitative exercise of sufficient breadth to determine the appropriate recommendations to make for the future. Part 2 is a quantitative exercise: how extensive have been the identified failures in News International, other press organisations, the police, the political class, public servants or others? On that basis, the implications (and any additional recommendations fall to be addressed. Part 2 requires a far greater and more detailed factual investigation than has Part 1: this is not surprising given that the Terms of Reference were split into two because of the ongoing police investigation and the lack of clarity as to where it might lead).</p>
  <?php paragraphLink('A',3,3,4); ?>Against that background it is necessary to consider the overriding obligation as to the procedure or conduct of the Inquiry, which requires me &#8220;to act with fairness and with regard to the need to avoid any unnecessary cost&#8221;.<?php footnoteRef('A',3,10); ?> Further, although the Inquiry may &#8220;not rule on and has no power to determine, any person&#8217;s civil or criminal liability&#8221;, it is not inhibited in the discharge of its function &#8220;by any likelihood of liability being inferred from the facts that it determines or recommendations that it makes&#8221;.<?php footnoteRef('A',3,11); ?> Subject to this framework, the obligation is set out in s24(1) of the Inquiries Act 2005 in these terms: <blockquote>&#8220;The Chairman of an inquiry must deliver a report to the Minister setting out &#8211; 
  <ol type="a">
  	<li>the facts determined by the inquiry panel;</li>
  	<li>the recommendations of the panel ... The report may also contain anything else that the panel considers to be relevant to the terms of reference (including any recommendations the panel sees fit to make despite not being required to do so by the terms of reference)&#8221;</li>
  </ol>	
  	
  	</blockquote>.</p>
  <?php paragraphLink('A',3,3,5); ?>The facts as determined, however, are those which are necessary in order to provide the context for the recommendations. Focussing on the relationship between the press and the public, therefore, the submission that a single or occasional instance of misconduct will not itself justify any adverse finding about the culture, practices or ethics of the press is to proceed on the mistaken basis of thinking quantitatively rather than qualitatively. In relation to the future of regulation, the question whether a new regime is appropriate must be asked by reference to how the present regulatory regime has dealt with such issues as have arisen and whether it retains public confidence. If problems with or concerns about the culture, practices and ethics of the press are &#8211; represented by a single or occasional example &#8211; it may not be appropriate or necessary to recommend any change. Nobody, however, has submitted that this is the case. It is not challenged that there is legitimate public concern about the regulatory regime which it is no longer suggested is fit for purpose; the issue is the extent of that problem and the benefits and detriments of possible solutions.</p>
  <?php paragraphLink('A',3,3,6); ?>Neither does it matter that any problem is limited to one or a small number of titles. A regulatory regime must deal with all titles and be in a position appropriately to deal with even a single recalcitrant paper; it is irrelevant if one or more title never attracts its adverse attention. To that extent, the approach of at least one newspaper group to the Inquiry, restricting itself to demonstrating how illegal or unethical activity cannot be placed at its door, has wholly missed the point. I have no intention of either applauding one paper for its culture, practices and ethics or (with the exception of the NoTW) of condemning another. The reason for the exception is so that the public do not ascribe to other titles the many criticisms that have been articulated about that one. What I sought from all Core Participants (but have not always received) was an analysis of the extent to which, as a matter of generality, there was a problem with the culture, practices and ethics of the press or a section of the press, so that it would be possible to consider a new and sufficiently robust policy and regulatory regime which supports the integrity and freedom of the press but also reflects the legitimate rights of others.</p>
  <?php paragraphLink('A',3,3,7); ?>In argument, it has been submitted that it is appropriate for the Inquiry to express its findings at a high level of generality. The point is made in this way. It does not matter whether, for example, phone hacking occurred only at one title or was more widespread since it is an established problem of conduct by at least part of the press which will inform the recommendations made. Similarly, the problem of intrusion on grief identified by certain witnesses is a problem of conduct by at least part of the press and it matters not for the purpose of making recommendations whether it occurred only at one title, at several titles, or at all titles. From this perspective the Inquiry can find that there are &#8216;concerns&#8217; about alleged press misconduct without determining whether the particular type of misconduct occurred on one occasion or one hundred, at one title or many. This puts the qualitative versus the quantitative argument at its highest.</p>
  <?php paragraphLink('A',3,3,8); ?>To a point, the argument is well made and correct. I have already concluded, however, that a single or occasional instance of misconduct may not be sufficient to justify an adverse finding about culture, practices and ethics on the basis that it is of no real significance. Neither am I prepared to proceed on the basis that the argument of &#8216;one rogue reporter&#8217; can be replaced, by the remainder of the press, with an argument of &#8216;one rogue newspaper title&#8217;: if that is what I consider the position to be, I shall so conclude. That does not require me to decide how extensive was the practice or knowledge of phone hacking (although keeping quiet about a known abuse of the law by another title itself says something about culture, practices and ethics, on the basis that who otherwise will hold the press to account) but, in any event, illegality and unethical behaviour comes in many different forms and it is the overall picture that is critical.</p>
  <?php paragraphLink('A',3,3,9); ?>That is not to say that I will not deal with individual cases because worked examples can exemplify the problems that exist even in titles that are not the subject of repeated complaint and these may add to the overall picture. As a consequence, it is important to underline that it is not an inevitable inference that the culture, practices and ethics of the title affected is driven by the problem that I am exemplifying. Each generality along with each example is intended to provide or add to the narrative of facts against which to judge the regulatory regime and consider what should now take its place.</p>
  <?php paragraphLink('A',3,3,10); ?>Against that background, a consideration of the standard of proof becomes much more straightforward. I accept that the public interest requires that the findings of the Inquiry are expressed in such a way that can readily be understood to be a judgment on what has occurred and why any recommendations have been made and, furthermore, that the appropriate standard is that applicable in all but criminal cases, namely the balance of probability. To put it more colloquially, before reaching a conclusion, for example, that an event has happened, I must conclude that its occurrence is more likely than not. I further recognise both from an analysis of Re H (Minors) (Sexual Abuse: Standard of Proof)<?php footnoteRef('A',3,12); ?> and the subsequent decisions of R(N) v Mental Health Review Tribunal (Northern Region)<?php footnoteRef('A',3,13); ?> and Re D<?php footnoteRef('A',3,14); ?> that the application of the balance of probabilities is flexible in its application in that the more serious the allegation, the more careful the analysis of the facts will have to be not least because of the reduced likelihood of it being true.<?php footnoteRef('A',3,15); ?></p>
  <?php paragraphLink('A',3,3,11); ?>In my ruling in relation to the application of Rule 13 of the Inquiry Rules 2006, I raised the question whether it was sufficient that I consider whether the evidence reveals such a concern about particular conduct that regulatory arrangements should be put in place to deal with that type of behaviour should it arise.<?php footnoteRef('A',3,16); ?> I there had regard to the Baha Mousa Inquiry conducted by The Rt Hon Sir William Gage who, referring to s24(1) of the Inquiries Act 2005 (to the effect that the report could contain &#8220;anything else the panel considers relevant to the terms of reference&#8221;), concluded that it was open to him to express suspicion that an allegation is true. He recognised that such a comment would not be a finding of fact and that the power so to conclude &#8220;should be exercised sparingly&#8221;.<?php footnoteRef('A',3,17); ?></p>
  <?php paragraphLink('A',3,3,12); ?>I accept that unresolved suspicions, on their own, do not provide a sufficient basis for conclusions, in particular as to the success or otherwise of the present regulatory regime but the words &#8216;on their own&#8217; are important. By way of example, I can conclude without difficulty that mobile phone interception was far more extensive at the NoTW than was initially admitted and I can also be satisfied that knowledge of the technique was far more widespread than the confines of the NoTW but, until the Guardian article in 2009, it was not addressed by the press or the PCC.</p>
  <?php paragraphLink('A',3,3,13); ?>That alone is likely to be sufficient to justify a new approach to regulation but it seems to me that I can (and should) be able to go much further. A considerable body of evidence has been adduced which gives rise to reasonable grounds for believing that knowledge of the practice was linked to its use, albeit there is not the hard evidence (such as comes from the Mulcaire material) of names, telephone numbers and the like. It seems to me that it could be possible to conclude, inferentially, on the balance of probability, that others were involved in the practice; it might be fairer, however, (and sufficient to add to the weight of any conclusion about the need for a new approach to regulation) simply to conclude that there are strong reasonable grounds for believing that it did. I recognise, however, the need for real caution before proceeding along these lines.</p>
  <?php paragraphLink('A',3,3,14); ?>Mr Jonathan Caplan QC for Associated Newspapers Ltd argues that any general statement that there are grounds to suspect senior executives within a section of the national press of knowledge, concealment or acquiescence in voicemail interception raised very serious reputational issues for those senior personnel reasonably considered by the public to be within that section of the press (that is to say the tabloid or popular press). It is argued that such conclusions should not be reached unless the evidence discloses objectively reasonable grounds to suspect those executives which it cannot because there has been no proper investigation of the issue.</p>
  <?php paragraphLink('A',3,3,15); ?>I have not singled out &#8216;senior executives&#8217; for special mention but it is important to make the point that this should not and does not mean that, in appropriate cases, individual titles (and individual executives or journalists) will not be identified or identifiable. The effect of the argument that to do so offends my general approach is that I would not be able to reach any conclusion because to criticise any individual title or group is to criticise the editor. This is no more than a repetition of the argument that I rejected in the ruling on Rule 13 concerning the implied criticism of those involved<?php footnoteRef('A',3,18); ?> which was not thereafter challenged. I am certainly prepared to accept, however, that I should not criticise any individual by name unless satisfied on the balance of probability that such criticism is justified.</p>
  <?php paragraphLink('A',3,3,16); ?>Similar, but not identical, reasoning applies to my approach to the relations between the press and the police (Module Two) and the press and politicians (Module Three) and I will express my conclusions about the nature and impact of those relationships on the balance of probability. In both of these cases, there is no complication of pending criminal investigation which could limit my ability to focus on individual conduct.</p>
  <?php paragraphLink('A',3,3,17); ?>In connection both with the police and with politicians, the material before the Inquiry is sufficient to reach conclusions on the important questions without having to consider issues of reasonable suspicion but the complication in these relationships arises in connection with the additional question of perception. Thus, by way of example, it has been suggested that &#8216;deals&#8217; were struck between the press and politicians to the mutual advantage of both. That allegation has been strenuously denied both by the press and by politicians. Quite apart from that, however, there is the very different issue of whether, even assuming there was no such &#8216;deal&#8217;, the behaviour of both gave rise to legitimate perception in the public that the relationship was being conducted in a way that was not in the public interest. On that basis, it may be entirely wrong to suggest or conclude that there was impropriety of any sort but still correct to decide that the way in which the relationship is handled from the perspective both of the press and politicians requires adjustment so that each can perform their duty but in a way that does not give rise an adverse perception. A similar problem arises in connection with the relationships between the press and the police (in particular in relation to the refusal to re-open investigations into mobile phone interception).</p>
 </div>

