<?php 
require_once('../../common.php');
levesonHeader('A',3); 
levesonNav('../../');
levesonBread('A',3);
require_once('content.php');
levesonFooterNav('A',3); 
require_once('footnotes.php');
LevesonCommonFooter();
?>