<?php 
require_once('../../common.php');
levesonHeader('I',8); 
levesonNav('../../');
levesonBread('I',8);
require_once('content.php');
levesonFooterNav('I',8); 
require_once('footnotes.php');
LevesonCommonFooter();
?>