<?php 
require_once('../../common.php');
levesonHeader('H',7); 
levesonNav('../../');
levesonBread('H',7);
require_once('content.php');
levesonFooterNav('H',7); 
require_once('footnotes.php');
LevesonCommonFooter();
?>