<!-- Footnotes-->
<div id="footnotes"> <?php footNote('F',7,1); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',7,2); ?> <?php internalChapterLink('../../','F',2); ?></p>
 <?php footNote('F',7,3); ?> p34, lines 16-25, James Hipwell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-21-December-20111.pdf">Transcript-of-Morning-Hearing-21-December-20111.pdf</a></p>
 <?php footNote('F',7,4); ?> pp9-10, paras 43-44, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Piers-Morgan.pdf">Witness-Statement-of-Piers-Morgan.pdf</a></p>
 <?php footNote('F',7,5); ?> p4, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Richard-Peppiatt.pdf">Witness-Statement-of-Richard-Peppiatt.pdf</a></p>
 <?php footNote('F',7,6); ?> p5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Michelle-Stanistreet.pdf">Witness-Statement-of-Michelle-Stanistreet.pdf</a></p>
 <?php footNote('F',7,7); ?> p6, para 22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Richard-Desmond.pdf">Witness-Statement-of-Richard-Desmond.pdf</a></p>
 <?php footNote('F',7,8); ?> p60, lines 4-14, Dawn Neesom,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a>; pp6-7, paras 17-19, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dawn-Neesom.pdf">Witness-Statement-of-Dawn-Neesom.pdf</a>; p13, para 58, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Justin-Walford.pdf">Witness-Statement-of-Justin-Walford.pdf</a>; pp4-5, paras 12-14, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Peter-Wright.pdf">Witness-Statement-of-Peter-Wright.pdf</a> </p>
 <?php footNote('F',7,9); ?> p115, lines 9-13, Hugh Whittow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,10); ?> pp117-118, lines 12-2, <em>ibid</em></p>
 <?php footNote('F',7,11); ?> p14 lines 3-21, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a>; p115, lines 14-25, Hugh Whittow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a>;</p>
 <?php footNote('F',7,12); ?> p9, lines 3-18, Hugh Whittow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,13); ?> p119, lines 5-17, Hugh Whittow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a>; pp12-13, lines 15 &#8211;18, John Witherow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-17-January-2012.pdf">Transcript-of-Afternoon-Hearing-17-January-2012.pdf</a>; p10, para 42, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dominic-Mohan.pdf">Witness-Statement-of-Dominic-Mohan.pdf</a></p>
 <?php footNote('F',7,14); ?> p15, lines 18-20, p23, lines 10-15, Hugh Whittow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,15); ?> p1, para 3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Alastair-Brett.pdf">Witness-Statement-of-Alastair-Brett.pdf</a> ; p1, para 1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Jonathan-Chapman.pdf">Witness-Statement-of-Jonathan-Chapman.pdf</a> ; p1, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Justin-Walford.pdf">Witness-Statement-of-Justin-Walford.pdf</a></p>
 <?php footNote('F',7,16); ?> p1, para 1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Jonathan-Chapman.pdf">Witness-Statement-of-Jonathan-Chapman.pdf</a>; p2, para 4, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Tom-Crone.pdf">Witness-Statement-of-Tom-Crone.pdf</a></p>
 <?php footNote('F',7,17); ?> p14, line 20, John Witherow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-17-January-2012.pdf">Transcript-of-Afternoon-Hearing-17-January-2012.pdf</a>; p9, para 33, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-John-Witherow.pdf">Witness-Statement-of-John-Witherow.pdf</a></p>
 <?php footNote('F',7,18); ?> p13, lines 8-18, John Witherow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-17-January-2012.pdf">Transcript-of-Afternoon-Hearing-17-January-2012.pdf</a></p>
 <?php footNote('F',7,19); ?> p19, para 66, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Richard-Wallace.pdf">Witness-Statement-of-Richard-Wallace.pdf</a></p>
 <?php footNote('F',7,20); ?> p51, lines 1-15, Thomas Mockridge,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-17-January-2012.pdf">Transcript-of-Morning-Hearing-17-January-2012.pdf</a>; p7, para 19, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dawn-Neesom.pdf">Witness-Statement-of-Dawn-Neesom.pdf</a>; p10, para 42, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dominic-Mohan.pdf">Witness-Statement-of-Dominic-Mohan.pdf</a>; p6, para 43, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Colin-Myler1.pdf">Witness-Statement-of-Colin-Myler1.pdf</a>; p9, para 33 <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-John-Witherow.pdf">Witness-Statement-of-John-Witherow.pdf</a> </p>
 <?php footNote('F',7,21); ?> p50, lines 10-25, Thomas Mockridge,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-17-January-2012.pdf">Transcript-of-Morning-Hearing-17-January-2012.pdf</a>; p119, lines 5-17, Hugh Whittow; p9, lines 3-18, Nicole Patterson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a>; pp12-13, lines 15-end, John Witherow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-17-January-2012.pdf">Transcript-of-Afternoon-Hearing-17-January-2012.pdf</a>; p5, para 25, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Justin-Walford.pdf">Witness-Statement-of-Justin-Walford.pdf</a>; p13, para 49, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Richard-Wallace.pdf">Witness-Statement-of-Richard-Wallace.pdf</a>; p9, para 33, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-John-Witherow.pdf">Witness-Statement-of-John-Witherow.pdf</a> </p>
 <?php footNote('F',7,22); ?> p3, para 11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-John-Witherow.pdf">Witness-Statement-of-John-Witherow.pdf</a></p>
 <?php footNote('F',7,23); ?> pp84-85, lines 8-20, Peter Wright, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-11-January-2012.pdf">Transcript-of-Morning-Hearing-11-January-2012.pdf</a>; p11, para 35, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Paul-Dacre.pdf">Witness-Statement-of-Paul-Dacre.pdf</a>; p6, para 17, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dawn-Neesom.pdf">Witness-Statement-of-Dawn-Neesom.pdf</a>; pp1-2, paras 5 &#8211; 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-James-Welsh.pdf">Witness-Statement-of-James-Welsh.pdf</a>; p4, para 13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Peter-Wright.pdf">Witness-Statement-of-Peter-Wright.pdf</a></p>
 <?php footNote('F',7,24); ?> pp34-35, lines 14-15, Paul Ashford, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,25); ?> pp68-71, lines 13-21, Susan Panuccio, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-17-January-2012.pdf">Transcript-of-Morning-Hearing-17-January-2012.pdf</a>; p3, para 5.1.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Susan-Panuccio.pdf">Witness-Statement-of-Susan-Panuccio.pdf</a>; p7, para 22.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Simon-Toms.pdf">Witness-Statement-of-Simon-Toms.pdf</a></p>
 <?php footNote('F',7,26); ?> p2, para 5.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Susan-Panuccio.pdf">Witness-Statement-of-Susan-Panuccio.pdf</a></p>
 <?php footNote('F',7,27); ?> p3, para 11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Richard-Desmond.pdf">Witness-Statement-of-Richard-Desmond.pdf</a> The Daily Mail introduced new procedures in late 2011 as part of a review of payments to third parties inlight of the new Bribery Act; however, Paul Dacre did not accept that problems existed under the previous system: p3,para 7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Paul-Dacre.pdf">Witness-Statement-of-Paul-Dacre.pdf</a></p>
 <?php footNote('F',7,28); ?> pp34-35, lines 14-15, Paul Ashford, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,29); ?> pp47-49, lines 1-7,Richard Wallace,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a>; p7, para 27, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dominic-Mohan.pdf">Witness-Statement-of-Dominic-Mohan.pdf</a>; p5, para 11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dawn-Neesom.pdf">Witness-Statement-of-Dawn-Neesom.pdf</a>; p3, paras 12-13 and p6, para 22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-John-Witherow.pdf">Witness-Statement-of-John-Witherow.pdf</a> </p>
 <?php footNote('F',7,30); ?> pp112-113, lines 22-15, Tina Weaver, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a>; pp107-108, lines 9-19, Hugh Whittow, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a>;</p>
 <?php footNote('F',7,31); ?> p5, paras 33-34, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Nick-Fagge.pdf">Witness-Statement-of-Nick-Fagge.pdf</a></p>
 <?php footNote('F',7,32); ?> p9, para 42,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Piers-Morgan.pdf">Witness-Statement-of-Piers-Morgan.pdf</a>; p5, para 21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dominic-Mohan.pdf">Witness-Statement-of-Dominic-Mohan.pdf</a>; p3, paras 12-13, p6, para 22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-John-Witherow.pdf">Witness-Statement-of-John-Witherow.pdf</a>; p3, paras 6-7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-James-Harding.pdf">Witness-Statement-of-James-Harding.pdf</a>; p11, para 35, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Paul-Dacre.pdf">Witness-Statement-of-Paul-Dacre.pdf</a> </p>
 <?php footNote('F',7,33); ?> p11, para 35,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Paul-Dacre.pdf">Witness-Statement-of-Paul-Dacre.pdf</a>; p3, para 7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-James-Harding.pdf">Witness-Statement-of-James-Harding.pdf</a>; p9, para 7.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Thomas-Mockridge.pdf">Witness-Statement-of-Thomas-Mockridge.pdf</a> p5, para 21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dominic-Mohan.pdf">Witness-Statement-of-Dominic-Mohan.pdf</a>; p5, paras 34-35, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Colin-Myler1.pdf">Witness-Statement-of-Colin-Myler1.pdf</a>; pp48-49, lines 21-8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a>; p3, para 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dawn-Neesom.pdf">Witness-Statement-of-Dawn-Neesom.pdf</a>; p9, para 42, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Piers-Morgan.pdf">Witness-Statement-of-Piers-Morgan.pdf</a>; </p>
 <?php footNote('F',7,34); ?> p13, para 49, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Richard-Wallace.pdf">Witness-Statement-of-Richard-Wallace.pdf</a></p>
 <?php footNote('F',7,35); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Richard-Peppiatt.pdf">Witness-Statement-of-Richard-Peppiatt.pdf</a></p>
 <?php footNote('F',7,36); ?> p37, lines 1-22, Dawn Neesom, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,37); ?> p3, paras 16-19, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Colin-Myler1.pdf">Witness-Statement-of-Colin-Myler1.pdf</a></p>
 <?php footNote('F',7,38); ?> p54, lines 4-12, Richard Wallace, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a>; pp55-56, lines 22-1, Lloyd Embley, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-16-January-20121.pdf">Transcript-of-Afternoon-Hearing-16-January-20121.pdf</a></p>
 <?php footNote('F',7,39); ?> p7, para 29, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Dominic-Mohan.pdf">Witness-Statement-of-Dominic-Mohan.pdf</a></p>
 <?php footNote('F',7,40); ?> p46, lines 17-25, Dominic Mohan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-9-January-2012.pdf">Transcript-of-Afternoon-Hearing-9-January-2012.pdf</a></p>
 <?php footNote('F',7,41); ?> p62, lines 1-18, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,42); ?> p73, lines 4-6, Richard Wallace, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a></p>
 <?php footNote('F',7,43); ?> p73, lines 10-19, Richard Wallace, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a></p>
 <?php footNote('F',7,44); ?> p63, lines 1-10, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a>; p6, para 22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Richard-Desmond.pdf">Witness-Statement-of-Richard-Desmond.pdf</a>; pp27-28, lines 1-3, Richard Peppiatt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,45); ?> pp32-33, lines 15-14, Paul Silva, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-11-January-2012.pdf">Transcript-of-Morning-Hearing-11-January-2012.pdf</a>; p73, lines 9-20, Peter Wright, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-11-January-2012.pdf">Transcript-of-Morning-Hearing-11-January-2012.pdf</a>;</p>
 <?php footNote('F',7,46); ?> pp1-2, paras 1-2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Jonathan-Chapman.pdf">Witness-Statement-of-Jonathan-Chapman.pdf</a></p>
 <?php footNote('F',7,47); ?> pp66-69, lines 16-7, Tom Crone, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Afternoon-Hearing-13-December-20111.pdf">Transcript-of-Afternoon-Hearing-13-December-20111.pdf</a>; p85, lines 2-25, Jonathan Chapman, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-14-December-2011.pdf">Transcript-of-Morning-Hearing-14-December-2011.pdf</a></p>
 <?php footNote('F',7,48); ?> p3, para 3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Jonathan-Chapman.pdf">Witness-Statement-of-Jonathan-Chapman.pdf</a></p>
 <?php footNote('F',7,49); ?> p23, lines 10-15, p25, lines 18-22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Jonathan-Chapman.pdf">Witness-Statement-of-Jonathan-Chapman.pdf</a></p>
 <?php footNote('F',7,50); ?> p28, lines 4-22, Richard Peppiatt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-29-November-2011.pdf">Transcript-of-Morning-Hearing-29-November-2011.pdf</a></p>
 <?php footNote('F',7,51); ?> pp77-78, lines 21-11, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,52); ?> p8, para 10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Second-Witness-Statement-of-Peter-Hill.pdf">Second-Witness-Statement-of-Peter-Hill.pdf</a></p>
 <?php footNote('F',7,53); ?> pp75-76, lines 23-3, Paul Dacre, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-6-February-20121.pdf">Transcript-of-Afternoon-Hearing-6-February-20121.pdf</a></p>
 <?php footNote('F',7,54); ?> p76, lines 4-16, Paul Dacre, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-6-February-20121.pdf">Transcript-of-Afternoon-Hearing-6-February-20121.pdf</a></p>
 <?php footNote('F',7,55); ?> p81, lines 9-13, Paul Dacre, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-6-February-20121.pdf">Transcript-of-Afternoon-Hearing-6-February-20121.pdf</a>; pp85-86, lines 22-6, Dawn Neesom, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',7,56); ?> p81, lines 14-22, Paul Dacre, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-6-February-20121.pdf">Transcript-of-Afternoon-Hearing-6-February-20121.pdf</a>; p9, para 30, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Peter-Hill.pdf">Witness-Statement-of-Peter-Hill.pdf</a>; p39, lines 16-23, Paul McMullan <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-29-November-2011.pdf">Transcript-of-Afternoon-Hearing-29-November-2011.pdf</a></p>
 <?php footNote('F',7,57); ?> p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-Gordon-Brown-MP.pdf">Witness-Statement-of-Gordon-Brown-MP.pdf</a></p>
 <?php footNote('F',7,58); ?> p6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Witness-Statement-of-Professor-Baroness-ONeil.pdf">Witness-Statement-of-Professor-Baroness-ONeil.pdf</a></p>
 <?php footNote('F',7,59); ?> pp46-47, lines 1-8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-9-February-20121.pdf">Transcript-of-Afternoon-Hearing-9-February-20121.pdf</a></p>
 <?php footNote('F',7,60); ?> <?php internalChapterLink('../../','F',5); ?></p>
 <?php footNote('F',7,61); ?> p21, lines 7-9, Lord Black, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-1-February-2012.pdf">Transcript-of-Morning-Hearing-1-February-2012.pdf</a></p>
 </div>
