<?php 
require_once('../../common.php');
levesonHeader('X',6);
levesonNav('../../');
levesonBread('X',6);
require_once('content.php');
levesonFooterNav('X',6); 
require_once('footnotes.php');
LevesonCommonFooter();
?>