<?php 
require_once('../../common.php');
levesonHeader('F',3); 
levesonNav('../../');
levesonBread('F',3);
require_once('content.php');
levesonFooterNav('F',3); 
require_once('footnotes.php');
LevesonCommonFooter();
?>