<!-- Footnotes-->
<div id="footnotes"> <?php footNote('G',2,1); ?> p4, para 10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Condon.pdf">Witness-Statement-of-Lord-Condon.pdf</a></p>
 <?php footNote('G',2,2); ?> p5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Dr-Rob-Mawby.pdf">Witness-Statement-of-Dr-Rob-Mawby.pdf</a></p>
 <?php footNote('G',2,3); ?> pp12-13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,4); ?> p4, para 10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Condon.pdf">Witness-Statement-of-Lord-Condon.pdf</a></p>
 <?php footNote('G',2,5); ?> p14, lines 8-9, Lord Condon, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-6-March-20122.pdf">Transcript-of-Morning-Hearing-6-March-20122.pdf</a></p>
 <?php footNote('G',2,6); ?> pp4-5, paras 11-13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Condon.pdf">Witness-Statement-of-Lord-Condon.pdf</a></p>
 <?php footNote('G',2,7); ?> p4, para 12, <em>ibid</em></p>
 <?php footNote('G',2,8); ?> pp25-26, lines 12-3, Lord Condon, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-6-March-20122.pdf">Transcript-of-Morning-Hearing-6-March-20122.pdf</a></p>
 <?php footNote('G',2,9); ?> pp26-27, lines 24-3, Lord Condon, <em>ibid</em></p>
 <?php footNote('G',2,10); ?> p2, para 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sandra-Laville.pdf">Witness-Statement-of-Sandra-Laville.pdf</a></p>
 <?php footNote('G',2,11); ?> p23, lines 10-11, Lord Condon, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-6-March-20122.pdf">Transcript-of-Morning-Hearing-6-March-20122.pdf</a></p>
 <?php footNote('G',2,12); ?> p31, lines 21-23, Lord Condon, <em>ibid</em></p>
 <?php footNote('G',2,13); ?> http://www.archive.official-documents.co.uk/document/cm42/4262/4262.htm</p>
 <?php footNote('G',2,14); ?> pp4-5, para 14, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Stevens.pdf">Witness-Statement-of-Lord-Stevens.pdf</a></p>
 <?php footNote('G',2,15); ?> pp55-56, lines 22-15, Lord Stevens, http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-6-March-2012.txt</p>
 <?php footNote('G',2,16); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/MPS-9-Special-Notice-19-00.pdf">MPS-9-Special-Notice-19-00.pdf</a></p>
 <?php footNote('G',2,17); ?> p12, para 34, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Stevens.pdf">Witness-Statement-of-Lord-Stevens.pdf</a></p>
 <?php footNote('G',2,18); ?> p10, para 30, <em>ibid</em></p>
 <?php footNote('G',2,19); ?> p11, para 33, <em>ibid</em></p>
 <?php footNote('G',2,20); ?> p3, para 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Jacqueline-Hames.pdf">Witness-Statement-of-Jacqueline-Hames.pdf</a></p>
 <?php footNote('G',2,21); ?> p2, para 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sandra-Laville.pdf">Witness-Statement-of-Sandra-Laville.pdf</a></p>
 <?php footNote('G',2,22); ?> p2, para 23, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Michael-Sullivan.pdf">Witness-Statement-of-Michael-Sullivan.pdf</a></p>
 <?php footNote('G',2,23); ?> p7, para 18, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Blair.pdf">Witness-Statement-of-Lord-Blair.pdf</a></p>
 <?php footNote('G',2,24); ?> p14, lines 21-22, Lord Blair, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-7-March-2012.pdf">Transcript-of-Morning-Hearing-7-March-2012.pdf</a>; p9, para 21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Blair.pdf">Witness-Statement-of-Lord-Blair.pdf</a></p>
 <?php footNote('G',2,25); ?> pp5-6, para 14, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Blair.pdf">Witness-Statement-of-Lord-Blair.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Annex-to-Lord-Blair-Statement.pdf">Annex-to-Lord-Blair-Statement.pdf</a></p>
 <?php footNote('G',2,26); ?> pp3, 76, lines 9-21, 7-13, Lord Blair, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-7-March-2012.pdf">Transcript-of-Morning-Hearing-7-March-2012.pdf</a></p>
 <?php footNote('G',2,27); ?> p42, lines 2-7, Michael Sullivan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-15-March-2012.pdf">Transcript-of-Morning-Hearing-15-March-2012.pdf</a></p>
 <?php footNote('G',2,28); ?> p19, lines 6-10, CC Lynne Owens, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-6-March-2012.pdf">Transcript-of-Afternoon-Hearing-6-March-2012.pdf</a></p>
 <?php footNote('G',2,29); ?> p27, line 2, Stephen Wright, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-15-March-20121.pdf">Transcript-of-Afternoon-Hearing-15-March-20121.pdf</a></p>
 <?php footNote('G',2,30); ?> pp7-8, lines 12-5, Sir Paul Stephenson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-5-March-2012.pdf">Transcript-of-Morning-Hearing-5-March-2012.pdf</a>; p6, para 15, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Paul-Stephenson2.pdf">Witness-Statement-of-Sir-Paul-Stephenson2.pdf</a></p>
 <?php footNote('G',2,31); ?> p13, lines 2-22, Sir Paul Stephenson <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-5-March-2012.pdf">Transcript-of-Morning-Hearing-5-March-2012.pdf</a>; pp6-7, para 17, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Paul-Stephenson2.pdf">Witness-Statement-of-Sir-Paul-Stephenson2.pdf</a></p>
 <?php footNote('G',2,32); ?> p49, lines 10-12, Dick Fedorcio, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-13-March-2012.pdf">Transcript-of-Morning-Hearing-13-March-2012.pdf</a></p>
 <?php footNote('G',2,33); ?> p8, lines 11-17, Sir Paul Stephenson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-5-March-2012.pdf">Transcript-of-Morning-Hearing-5-March-2012.pdf</a></p>
 <?php footNote('G',2,34); ?> p9, para 25, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Paul-Stephenson2.pdf">Witness-Statement-of-Sir-Paul-Stephenson2.pdf</a></p>
 <?php footNote('G',2,35); ?> p6, para 16, <em>ibid</em></p>
 <?php footNote('G',2,36); ?> p10, lines 10-24, Sir Paul Stephenson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-5-March-2012.pdf">Transcript-of-Morning-Hearing-5-March-2012.pdf</a>; p8, para 23, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Paul-Stephenson2.pdf">Witness-Statement-of-Sir-Paul-Stephenson2.pdf</a></p>
 <?php footNote('G',2,37); ?> pp17-18, lines 8-8, Sir Paul Stephenson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-5-March-2012.pdf">Transcript-of-Morning-Hearing-5-March-2012.pdf</a>; p9, para 26, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Paul-Stephenson2.pdf">Witness-Statement-of-Sir-Paul-Stephenson2.pdf</a></p>
 <?php footNote('G',2,38); ?> p25, lines 10-16, Kit Malthouse, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-29-March-2012.pdf">Transcript-of-Morning-Hearing-29-March-2012.pdf</a></p>
 <?php footNote('G',2,39); ?> pp53-54, para 130, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Paul-Stephenson2.pdf">Witness-Statement-of-Sir-Paul-Stephenson2.pdf</a></p>
 <?php footNote('G',2,40); ?> p2, lines 12-25, Commissioner Hogan-Howe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-20-March-2012.pdf">Transcript-of-Morning-Hearing-20-March-2012.pdf</a>; p3, para 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Commissioner-Bernard-Hogan-Howe1.pdf">Witness-Statement-of-Commissioner-Bernard-Hogan-Howe1.pdf</a></p>
 <?php footNote('G',2,41); ?> p4, lines 3-13, Commissioner Hogan-Howe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-20-March-2012.pdf">Transcript-of-Morning-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,42); ?> p14, lines 7-24, Lord Condon, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-6-March-20122.pdf">Transcript-of-Morning-Hearing-6-March-20122.pdf</a></p>
 <?php footNote('G',2,43); ?> p3, para 9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Lord-Blair.pdf">Witness-Statement-of-Lord-Blair.pdf</a></p>
 <?php footNote('G',2,44); ?> p57, lines 7-8, CC Chris Sims, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,45); ?> p9, para 38, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-John-Twomey.pdf">Witness-Statement-of-John-Twomey.pdf</a></p>
 <?php footNote('G',2,46); ?> For example: p11, para 24, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Mark-Hughes-The-Telegraph-taken-as-read.pdf">Witness-Statement-of-Mark-Hughes-The-Telegraph-taken-as-read.pdf</a>; p8, para 23, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Thomas-Pettifor.pdf">Witness-Statement-of-Thomas-Pettifor.pdf</a></p>
 <?php footNote('G',2,47); ?> p19, lines 1-14, Timothy Gordon, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,48); ?> p90, lines 1-9, Deputy Commissioner Craig Mackey, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-26-March-2012.pdf">Transcript-of-Afternoon-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,49); ?> pp36-37, lines 21-6, Anne Campbell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-26-March-2012.pdf">Transcript-of-Morning-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,50); ?> pp17-18, paras 20.1-20.2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Andrew-Trotter1.pdf">Witness-Statement-of-Chief-Constable-Andrew-Trotter1.pdf</a></p>
 <?php footNote('G',2,51); ?> p5, para 5.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Hugh-Orde.pdf">Witness-Statement-of-Sir-Hugh-Orde.pdf</a></p>
 <?php footNote('G',2,52); ?> pp86-87, lines 21-1, Sir Hugh Orde, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-hearing-28-March-2012.pdf">Transcript-of-Morning-hearing-28-March-2012.pdf</a></p>
 <?php footNote('G',2,53); ?> p50, lines 1-13, Anne Campbell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-26-March-2012.pdf">Transcript-of-Morning-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,54); ?> pp34-35, lines 21-8, Liz Young, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-28-March-2012.pdf">Transcript-of-Afternoon-Hearing-28-March-2012.pdf</a>; p16, para 29, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Liz-Young.pdf">Witness-Statement-of-Liz-Young.pdf</a></p>
 <?php footNote('G',2,55); ?> pp64-65, lines 18-11, Gillian Shearer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-26-March-2012.pdf">Transcript-of-Afternoon-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,56); ?> <?php internalChapterLink('../../','G',3); ?></p>
 <?php footNote('G',2,57); ?> p78, lines 9-11, Gillian Shearer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-26-March-2012.pdf">Transcript-of-Afternoon-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,58); ?> p26, lines 8-22, Amanda Hirst, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-27-March-2012.pdf">Transcript-of-Afternoon-Hearing-27-March-2012.pdf</a></p>
 <?php footNote('G',2,59); ?> For example, pp27-28, lines 8-3, Nick Davies, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-28-February-2012.pdf">Transcript-of-Afternoon-Hearing-28-February-2012.pdf</a>; p3, para d, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Second-Witness-Statement-of-Nick-Davies.pdf">Second-Witness-Statement-of-Nick-Davies.pdf</a>; p12, para 45, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Scott-Hesketh-taken-as-read.pdf">Witness-Statement-of-Scott-Hesketh-taken-as-read.pdf</a></p>
 <?php footNote('G',2,60); ?> p54, lines 20-24, CC Chris Sims, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a>; p1, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Chris-Sims.pdf">Witness-Statement-of-Chief-Constable-Chris-Sims.pdf</a></p>
 <?php footNote('G',2,61); ?> p53, lines 13-22, Chief Insp Sally Seeley, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,62); ?> p7, para 25, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Chris-Sims.pdf">Witness-Statement-of-Chief-Constable-Chris-Sims.pdf</a></p>
 <?php footNote('G',2,63); ?> pp76-77, lines 22-17, CC Chris Sims, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a>; p8, para 31, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Chris-Sims.pdf">Witness-Statement-of-Chief-Constable-Chris-Sims.pdf</a></p>
 <?php footNote('G',2,64); ?> pp25-26, lines 15-18, CC Peter Vaughan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-21-March-2012.pdf">Transcript-of-Afternoon-Hearing-21-March-2012.pdf</a></p>
 <?php footNote('G',2,65); ?> p42, lines 4-11, CC Stephen House, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a>; p3, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Stephen-House1.pdf">Witness-Statement-of-Chief-Constable-Stephen-House1.pdf</a></p>
 <?php footNote('G',2,66); ?> p43, lines 2-15, CC Stephen House, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a>; p4, para 3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Stephen-House1.pdf">Witness-Statement-of-Chief-Constable-Stephen-House1.pdf</a></p>
 <?php footNote('G',2,67); ?> pp44-45, lines 11-1, CC Stephen House, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a></p>
 <?php footNote('G',2,68); ?> p59, lines 1-12, CC Stephen House, <em>ibid</em></p>
 <?php footNote('G',2,69); ?> p74, lines 7-23, CC Stephen House, <em>ibid</em></p>
 <?php footNote('G',2,70); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Simon-Ash.pdf">Witness-Statement-of-Chief-Constable-Simon-Ash.pdf</a></p>
 <?php footNote('G',2,71); ?> p4, <em>ibid</em></p>
 <?php footNote('G',2,72); ?> Although the MPS refer to this system by its former name, Solcara</p>
 <?php footNote('G',2,73); ?> p11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Simon-Ash.pdf">Witness-Statement-of-Chief-Constable-Simon-Ash.pdf</a></p>
 <?php footNote('G',2,74); ?> p21, lines 20-23, CC Simon Ash, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-26-March-2012.pdf">Transcript-of-Morning-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,75); ?> p93, lines 14-25, Terry Hunt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-26-March-2012.pdf">Transcript-of-Morning-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,76); ?> p79, lines 5-25, Colin Adwent, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-26-March-2012.pdf">Transcript-of-Morning-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,77); ?> pp57-58, lines 21-11, Gillian Shearer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-26-March-2012.pdf">Transcript-of-Afternoon-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,78); ?> pp6-13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Assistant-Chief-Constable-Jerry-Kirkby.pdf">Witness-Statement-of-Assistant-Chief-Constable-Jerry-Kirkby.pdf</a></p>
 <?php footNote('G',2,79); ?> pp24-25, lines 19-3, ACC Jerry Kirkby, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-27-March-2012.pdf">Transcript-of-Morning-Hearing-27-March-2012.pdf</a></p>
 <?php footNote('G',2,80); ?> p25, lines 7-12, ACC Jerry Kirkby, <em>ibid</em></p>
 <?php footNote('G',2,81); ?> p26, lines 8-15, ACC Jerry Kirkby, <em>ibid</em></p>
 <?php footNote('G',2,82); ?> pp47-48, lines 23-7, CC Colin Port, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-27-March-2012.pdf">Transcript-of-Morning-Hearing-27-March-2012.pdf</a></p>
 <?php footNote('G',2,83); ?> p55, lines 5-22, CC Colin Port, <em>ibid</em></p>
 <?php footNote('G',2,84); ?> pp41-42, lines 21-7, CC Jon Stoddart, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-27-March-2012.pdf">Transcript-of-Afternoon-Hearing-27-March-2012.pdf</a></p>
 <?php footNote('G',2,85); ?> p46, lines 15-16, Barbara Brewis, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-27-March-2012.pdf">Transcript-of-Afternoon-Hearing-27-March-2012.pdf</a></p>
 <?php footNote('G',2,86); ?> p47, lines 21-24, Liz Young, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-28-March-2012.pdf">Transcript-of-Afternoon-Hearing-28-March-2012.pdf</a></p>
 <?php footNote('G',2,87); ?> p68, lines 18-25, Dick Fedorcio, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-13-March-2012.pdf">Transcript-of-Afternoon-Hearing-13-March-2012.pdf</a></p>
 <?php footNote('G',2,88); ?> p26, lines 11-22, Oliver Cattermole, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-28-March-2012.pdf">Transcript-of-Afternoon-Hearing-28-March-2012.pdf</a></p>
 <?php footNote('G',2,89); ?> p40, lines 14-25, CC Andy Trotter, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-hearing-28-March-2012.pdf">Transcript-of-Morning-hearing-28-March-2012.pdf</a></p>
 <?php footNote('G',2,90); ?> p41, lines 7-21, CC Andy Trotter, <em>ibid</em></p>
 <?php footNote('G',2,91); ?> pp57-58, lines 14-6, CC Jon Stoddart, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-27-March-2012.pdf">Transcript-of-Afternoon-Hearing-27-March-2012.pdf</a></p>
 <?php footNote('G',2,92); ?> p84, lines 2-21, Dr Rob Mawby, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/lev030412am. pdf;p10, http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Dr-Rob-Mawby.pdf">lev030412am. pdf;p10, http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Dr-Rob-Mawby.pdf</a>;</p>
 <?php footNote('G',2,93); ?> p85, Iines 11-17, Dr Rob Mawby, <em>ibid</em> ; p10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Dr-Rob-Mawby.pdf">Witness-Statement-of-Dr-Rob-Mawby.pdf</a></p>
 <?php footNote('G',2,94); ?> p2, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Amanda-Hirst.pdf">Witness-Statement-of-Amanda-Hirst.pdf</a></p>
 <?php footNote('G',2,95); ?> p11, para 12.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Andrew-Trotter1.pdf">Witness-Statement-of-Chief-Constable-Andrew-Trotter1.pdf</a></p>
 <?php footNote('G',2,96); ?> p11, para 20.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Derek-Barnett.pdf">Witness-Statement-of-Derek-Barnett.pdf</a></p>
 <?php footNote('G',2,97); ?> p13, para 29, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Second-Witness-Statement-of-Anne-Campbell.pdf">Second-Witness-Statement-of-Anne-Campbell.pdf</a></p>
 <?php footNote('G',2,98); ?> p7, para 10.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sir-Hugh-Orde.pdf">Witness-Statement-of-Sir-Hugh-Orde.pdf</a></p>
 <?php footNote('G',2,99); ?> p11, para 12.2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Andrew-Trotter1.pdf">Witness-Statement-of-Chief-Constable-Andrew-Trotter1.pdf</a></p>
 <?php footNote('G',2,100); ?> p5, para 5.2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Joanne-Bird.pdf">Witness-Statement-of-Joanne-Bird.pdf</a></p>
 <?php footNote('G',2,101); ?> p6, para 13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Amanda-Hirst.pdf">Witness-Statement-of-Amanda-Hirst.pdf</a></p>
 <?php footNote('G',2,102); ?> p10, para 21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Adrian-Faber.pdf">Witness-Statement-of-Adrian-Faber.pdf</a></p>
 <?php footNote('G',2,103); ?> p15, para 38, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sandra-Laville.pdf">Witness-Statement-of-Sandra-Laville.pdf</a></p>
 <?php footNote('G',2,104); ?> p10, para 46, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jonathan-Ungoed-Thomas.pdf">Witness-Statement-of-Jonathan-Ungoed-Thomas.pdf</a></p>
 <?php footNote('G',2,105); ?> p12, para 44, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeremy-Lawton.pdf">Witness-Statement-of-Jeremy-Lawton.pdf</a></p>
 <?php footNote('G',2,106); ?> p10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Chris-Sims.pdf">Witness-Statement-of-Chief-Constable-Chris-Sims.pdf</a></p>
 <?php footNote('G',2,107); ?> p6, para 13.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Gillian-Shearer.pdf">Witness-Statement-of-Gillian-Shearer.pdf</a></p>
 <?php footNote('G',2,108); ?> p2, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Adrian-Faber.pdf">Witness-Statement-of-Adrian-Faber.pdf</a></p>
 <?php footNote('G',2,109); ?> p24, lines 6-12, Adrian Faber, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,110); ?> p14, para 33, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Sandra-Laville.pdf">Witness-Statement-of-Sandra-Laville.pdf</a></p>
 <?php footNote('G',2,111); ?> p19, para 40, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Matthew-Baggott.pdf">Witness-Statement-of-Chief-Constable-Matthew-Baggott.pdf</a></p>
 <?php footNote('G',2,112); ?> pp27-28, lines 8-3, Nick Davies, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-28-February-2012.pdf">Transcript-of-Afternoon-Hearing-28-February-2012.pdf</a></p>
 <?php footNote('G',2,113); ?> p3, para f, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Second-Witness-Statement-of-Nick-Davies.pdf">Second-Witness-Statement-of-Nick-Davies.pdf</a></p>
 <?php footNote('G',2,114); ?> p11, para 43, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeremy-Lawton.pdf">Witness-Statement-of-Jeremy-Lawton.pdf</a></p>
 <?php footNote('G',2,115); ?> p2, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Adrian-Faber.pdf">Witness-Statement-of-Adrian-Faber.pdf</a></p>
 <?php footNote('G',2,116); ?> pp22-23, lines 8-12, Commissioner Hogan-Howe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-20-March-2012.pdf">Transcript-of-Morning-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,117); ?> p26, para 89, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Constable-Peter-Vaughan.pdf">Witness-Statement-of-Chief-Constable-Peter-Vaughan.pdf</a></p>
 <?php footNote('G',2,118); ?> See for example: p4, para 10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-James-Murray.pdf">Witness-Statement-of-James-Murray.pdf</a>; and p73, lines 8-14, Paul Peachey, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-14-March-2012.pdf">Transcript-of-Morning-Hearing-14-March-2012.pdf</a></p>
 <?php footNote('G',2,119); ?> p6, para 12, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Barbara-Brewis.pdf">Witness-Statement-of-Barbara-Brewis.pdf</a></p>
 <?php footNote('G',2,120); ?> pp16-17, para 44, <em>ibid</em></p>
 <?php footNote('G',2,121); ?> p73, lines 7-12, Barbara Brewis, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-27-March-2012.pdf">Transcript-of-Afternoon-Hearing-27-March-2012.pdf</a></p>
 <?php footNote('G',2,122); ?> p88, lines 6-10, Jon Ungoed-Thomas, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-14-March-2012.pdf">Transcript-of-Morning-Hearing-14-March-2012.pdf</a></p>
 <?php footNote('G',2,123); ?> p6, paras 6.1-6.2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/10/Submission-from-ACPO-Interim-Guidance-for-relationships-with-the-Media.pdf">Submission-from-ACPO-Interim-Guidance-for-relationships-with-the-Media.pdf</a></p>
 <?php footNote('G',2,124); ?> p1, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,125); ?> p1, para 3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Dick-Fedorcio.pdf">Witness-Statement-of-Dick-Fedorcio.pdf</a></p>
 <?php footNote('G',2,126); ?> p2, para 3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Inspector-Sally-Seeley.pdf">Witness-Statement-of-Chief-Inspector-Sally-Seeley.pdf</a>; p86, line 16, Robert Shorthouse, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a>; p3, lines 23,Catherine Llewellyn, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-21-March-2012.pdf">Transcript-of-Afternoon-Hearing-21-March-2012.pdf</a></p>
 <?php footNote('G',2,127); ?> p4, para 13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Dick-Fedorcio.pdf">Witness-Statement-of-Dick-Fedorcio.pdf</a></p>
 <?php footNote('G',2,128); ?> p5, para 15, <em>ibid</em></p>
 <?php footNote('G',2,129); ?> p3, para 7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,130); ?> <em>ibid</em></p>
 <?php footNote('G',2,131); ?> p3, para 8, <em>ibid</em></p>
 <?php footNote('G',2,132); ?> p4, MPS Notice 26/2006 Media Relations Standing Operating Police, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/MPS-12-Notices-26-2006.pdf">MPS-12-Notices-26-2006.pdf</a></p>
 <?php footNote('G',2,133); ?> p5, para 16, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Dick-Fedorcio.pdf">Witness-Statement-of-Dick-Fedorcio.pdf</a></p>
 <?php footNote('G',2,134); ?> p5, para 13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,135); ?> see for example p74, lines 15-20, Lord Stevens, http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-6-March-2012.txt</p>
 <?php footNote('G',2,136); ?> pp73-74, lines 20-1, Commissioner Hogan-Howe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-20-March-2012.pdf">Transcript-of-Morning-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,137); ?> p74, lines 9-11, Commissioner Hogan-Howe, <em>ibid</em></p>
 <?php footNote('G',2,138); ?> pp74-75, lines 17-3, Commissioner Hogan-Howe, <em>ibid</em></p>
 <?php footNote('G',2,139); ?> pp5-6, para 18, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Dick-Fedorcio.pdf">Witness-Statement-of-Dick-Fedorcio.pdf</a></p>
 <?php footNote('G',2,140); ?> p6, lines 14-20, Bob Quick, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-7-March-2012.pdf">Transcript-of-Afternoon-Hearing-7-March-2012.pdf</a></p>
 <?php footNote('G',2,141); ?> p6, para 16, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,142); ?> p6, para 19, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Dick-Fedorcio.pdf">Witness-Statement-of-Dick-Fedorcio.pdf</a>; p9, Special Notice 24/98 MPS Master Bundle Policies/Procedures, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/MPS-8-Special-Notice-24-98.pdf">MPS-8-Special-Notice-24-98.pdf</a></p>
 <?php footNote('G',2,143); ?> For example, p9, para 30, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Anne-Campbell.pdf">Witness-Statement-of-Anne-Campbell.pdf</a></p>
 <?php footNote('G',2,144); ?> Filkin, E,<em> The Ethical Issues Arising From The Relationship Between Police And Media &#8211; Advice to the</em>  Commissioner of Police of the Metropolis and his Management Board (January 2012), p46, http://www.levesoninquiry.org.uk/wp- </p>
 <?php footNote('G',2,145); ?> pp13-14, lines 10-1, Kit Malthouse, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-29-March-2012.pdf">Transcript-of-Morning-Hearing-29-March-2012.pdf</a></p>
 <?php footNote('G',2,146); ?> pp55-57, 69-70, lines 9-14, lines 23-23, Michael Sullivan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-15-March-2012.pdf">Transcript-of-Morning-Hearing-15-March-2012.pdf</a>; p13, para 65, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Michael-Sullivan.pdf">Witness-Statement-of-Michael-Sullivan.pdf</a></p>
 <?php footNote('G',2,147); ?> p14, para 34, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,148); ?> p24, lines 9-10, Sean O&#8217;Neill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a></p>
 <?php footNote('G',2,149); ?> p24, lines 11-19, Sean O&#8217;Neill, <em>ibid</em></p>
 <?php footNote('G',2,150); ?> p26, para 66, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,151); ?> p4, lines 14-19, Sean O&#8217;Neill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a></p>
 <?php footNote('G',2,152); ?> p22, lines 15-23, Sean O&#8217;Neill, <em>ibid</em> ; for example, pp81-82, lines 20-1, Justin Penrose, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-20-March-2012.pdf">Transcript-of-Morning-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,153); ?> pp4-5, lines 7-21, Timothy Gordon, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,154); ?> p42, lines 4-11, CC Andy Trotter, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-hearing-28-March-2012.pdf">Transcript-of-Morning-hearing-28-March-2012.pdf</a></p>
 <?php footNote('G',2,155); ?> pp45-46, lines 11-3, Ed Stearns, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/lev030412am.pdf">lev030412am.pdf</a> ; p8, para 21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,156); ?> For example, p107, lines 16-20, Thomas Pettifor, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-20-March-2012.pdf">Transcript-of-Morning-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,157); ?> p47, lines 10-22, Commissioner Hogan-Howe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-20-March-2012.pdf">Transcript-of-Morning-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,158); ?> p9, lines 2-18, Commissioner Hogan-Howe, <em>ibid</em></p>
 <?php footNote('G',2,159); ?> p8, para 22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,160); ?> p23, para 59, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-AC-Cressida-Dick.pdf">Witness-Statement-of-AC-Cressida-Dick.pdf</a></p>
 <?php footNote('G',2,161); ?> The Inquiry understands the position in West Midlands Police has changed, however, this does not change theanalysis.</p>
 <?php footNote('G',2,162); ?> p53, lines 4-9, Chief Insp Sally Seeley, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,163); ?> p8, para 14, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Chief-Inspector-Sally-Seeley.pdf">Witness-Statement-of-Chief-Inspector-Sally-Seeley.pdf</a></p>
 <?php footNote('G',2,164); ?> p54, lines 6-9, Chief Insp Sally Seeley, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-20-March-2012.pdf">Transcript-of-Afternoon-Hearing-20-March-2012.pdf</a></p>
 <?php footNote('G',2,165); ?> p54, lines 6-15, Chief Insp Sally Seeley, <em>ibid</em></p>
 <?php footNote('G',2,166); ?> p76, lines 15-22, CC Stephen House, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a></p>
 <?php footNote('G',2,167); ?> p82, lines 11-22, CC Stephen House, <em>ibid</em></p>
 <?php footNote('G',2,168); ?> p87, lines 10-12, Rob Shorthouse, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-21-March-2012.pdf">Transcript-of-Morning-Hearing-21-March-2012.pdf</a></p>
 <?php footNote('G',2,169); ?> pp51-52, lines 13-7, Lord Blair, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-7-March-2012.pdf">Transcript-of-Morning-Hearing-7-March-2012.pdf</a></p>
 <?php footNote('G',2,170); ?> p53, lines 1-13, Lord Blair, <em>ibid</em></p>
 <?php footNote('G',2,171); ?> p6, lines 9-21, Jeff Edwards, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-14-March-2012.pdf</p>
 <?php footNote('G',2,172); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,173); ?> p2, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-John-Twomey.pdf">Witness-Statement-of-John-Twomey.pdf</a></p>
 <?php footNote('G',2,174); ?> p4, lines 21-25, Jeff Edwards, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-14-March-2012.pdf</p>
 <?php footNote('G',2,175); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,176); ?> pp4-5, lines 21-10, Jeff Edwards, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-14-March-2012.pdf</p>
 <?php footNote('G',2,177); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,178); ?> p3, <em>ibid</em></p>
 <?php footNote('G',2,179); ?> p30, lines 13-19, Michael Sullivan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-15-March-2012.pdf">Transcript-of-Morning-Hearing-15-March-2012.pdf</a></p>
 <?php footNote('G',2,180); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,181); ?> pp67-68, lines 20-2, Colin Adwent, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-26-March-2012.pdf">Transcript-of-Morning-Hearing-26-March-2012.pdf</a></p>
 <?php footNote('G',2,182); ?> p23, para 58, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,183); ?> pp23-24, para 59, <em>ibid</em></p>
 <?php footNote('G',2,184); ?> p6, para 22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-John-Twomey.pdf">Witness-Statement-of-John-Twomey.pdf</a></p>
 <?php footNote('G',2,185); ?> p31, lines 10-13, John Twomey, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-19-March-20121.pdf">Transcript-of-Morning-Hearing-19-March-20121.pdf</a>; p6, para 21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-John-Twomey.pdf">Witness-Statement-of-John-Twomey.pdf</a></p>
 <?php footNote('G',2,186); ?> p24, para 60, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,187); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,188); ?> p4, <em>ibid</em></p>
 <?php footNote('G',2,189); ?> pp8-9, lines 19-20, Jeff Edwards, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-14-March-2012.pdf; p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,190); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,191); ?> p4, lines 9-21, Jeff Edwards, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-14-March-2012.pdf</p>
 <?php footNote('G',2,192); ?> pp4-5, lines 21-2, Jeff Edwards, <em>ibid</em></p>
 <?php footNote('G',2,193); ?> pp6-7, lines 22-6, Jeff Edwards, <em>ibid</em></p>
 <?php footNote('G',2,194); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,195); ?> p60, lines 8-11, Paul Peachey, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-14-March-2012.pdf">Transcript-of-Morning-Hearing-14-March-2012.pdf</a></p>
 <?php footNote('G',2,196); ?> p60, lines 15-18, Paul Peachey, <em>ibid</em></p>
 <?php footNote('G',2,197); ?> pp30-31, lines 22-13, Michael Sullivan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-15-March-2012.pdf">Transcript-of-Morning-Hearing-15-March-2012.pdf</a>; p12, para 53, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Dick-Fedorcio.pdf">Witness-Statement-of-Dick-Fedorcio.pdf</a></p>
 <?php footNote('G',2,198); ?> pp29-30, lines 19-4, Michael Sullivan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-15-March-2012.pdf">Transcript-of-Morning-Hearing-15-March-2012.pdf</a></p>
 <?php footNote('G',2,199); ?> p3, para 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Justin-Penrose.pdf">Witness-Statement-of-Justin-Penrose.pdf</a></p>
 <?php footNote('G',2,200); ?> p22, para 56, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,201); ?> p84, lines 2-18, Stephen Wright, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-15-March-2012.pdf">Transcript-of-Morning-Hearing-15-March-2012.pdf</a></p>
 <?php footNote('G',2,202); ?> pp22-23, para 56, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Ed-Stearns.pdf">Witness-Statement-of-Ed-Stearns.pdf</a></p>
 <?php footNote('G',2,203); ?> pp90-91, lines 14-5, Jacqueline Hames, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-28-February-2012.pdf">Transcript-of-Morning-Hearing-28-February-2012.pdf</a></p>
 <?php footNote('G',2,204); ?> p19, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Jacqueline-Hames.pdf">Witness-Statement-of-Jacqueline-Hames.pdf</a></p>
 <?php footNote('G',2,205); ?> p15, lines 9-19, Jeff Edwards, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Afternoon-Hearing-14-March-2012.pdf</p>
 <?php footNote('G',2,206); ?> p13, lines 1-5, Jeff Edwards, <em>ibid</em></p>
 <?php footNote('G',2,207); ?> p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Witness-Statement-of-Jeff-Edwards.pdf">Witness-Statement-of-Jeff-Edwards.pdf</a></p>
 <?php footNote('G',2,208); ?> pp73-74, lines 9-6, Stephen Wright, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-15-March-2012.pdf">Transcript-of-Morning-Hearing-15-March-2012.pdf</a></p>
 <?php footNote('G',2,209); ?> p80, lines 7-17, Jonathan Ungoed-Thomas, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-14-March-2012.pdf">Transcript-of-Morning-Hearing-14-March-2012.pdf</a></p>
 <?php footNote('G',2,210); ?> p57, lines 7-11, Ed Stearns, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/lev030412am.pdf">lev030412am.pdf</a></p>
 <?php footNote('G',2,211); ?> p23, lines 1-5, Lucy Panton, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/lev030412am.pdf">lev030412am.pdf</a></p>
 <?php footNote('G',2,212); ?> p81, lines 14-24, Jonathan Ungoed-Thomas, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-14-March-2012.pdf">Transcript-of-Morning-Hearing-14-March-2012.pdf</a></p>
 <?php footNote('G',2,213); ?> p22, lines 7-23, Lord Condon, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/03/Transcript-of-Morning-Hearing-6-March-20122.pdf">Transcript-of-Morning-Hearing-6-March-20122.pdf</a></p>
 </div>
