<?php 
require_once('../../common.php');
levesonHeader('G',2); 
levesonNav('../../');
levesonBread('G',2);
require_once('content.php');
levesonFooterNav('G',2); 
require_once('footnotes.php');
LevesonCommonFooter();
?>