<div class="content" id="contentPartBChapter3">
<h1 id="top">CHAPTER 3<br/>COMPETING PUBLIC INTERESTS</h1>
  <?php sectionAnchor('B',3,1); ?>Context</h2>
 <?php paragraphLink('B',3,1,1); ?>The public interest in a free press is fundamental. But it cannot be viewed in isolation. As has been demonstrated, it is, itself, an aspect of wider public interests such as the public interest in democracy, for example, in public life and in the rule of law. There are other public interests also of which press freedom is not a major aspect, and with which it may sometimes be in tension. This section considers some of them, in order to put the public interest in a free press in its fuller context, and to reflect on how competing aspects of the public interest are resolved and reconciled.</p>
  <?php paragraphLink('B',3,1,2); ?>The &#8216;public interest&#8217; is therefore not a monolithic concept. Nor is it the particular property of the press or any other organisation or sector. It will often be a matter of balancing a number of outcomes which would be for the common good, but which cannot all be achieved simultaneously. In a democracy, this is principally a role for Government that is, for example, used to grappling with a balance between the public interests in public spending and in low taxes, in liberty and in security, in high accountability and low bureaucracy.</p>
  <?php paragraphLink('B',3,1,3); ?>That is by no means to portray any aspects of the public interest as mutually exclusive or zero- sum. On the contrary, the fact that many aspects of public, and indeed private, life may benefit the public makes the task of the decision-maker a much more subtle and skilful one than that. There are critical decisions to be taken about how to balance, weigh and reconcile many things that are in themselves good but not all of which may be simultaneously achievable. So it is a complex task for those charged with it, and one for which accountabilities are rightly demanded. A wider perspective than that of the press is therefore inevitable:<?php footnoteRef('B',3,1); ?></p>
<blockquote>&#8220;There are more components of the public interest than those that are served by a free press, so that the press may need to control its activity to respect those wider factors. &#8230; Sometimes it seems that the press&#8217;s confidence that its activities are serving the public interest makes it insensitive to the complexity of that notion.&#8221; </blockquote>
  <?php paragraphLink('B',3,1,4); ?>Most proponents of free speech, for example, accept that its exercise must be restricted in order to protect the rights and interests of others. There is an important public interest in free speech, and there is also an important public interest in the civil liberties of individuals. These may sometimes need to be reconciled. Certain acts of speech, such as speech inciting violence or race hate, are so connected with producing specific conduct as to be relatively unprotected. Even Milton, in a passage from the Areopagitica overshadowed by his rhetoric in defence of a free press, acknowledged necessary limits to free speech (although not necessarily limits which we would now condone): </p>
  <blockquote>&#8220;I mean not tolerated popery, and open superstition, which as it extirpates all religious and civil supremacies, so itself should be extirpate &#8230; that also which is impious or evil absolutely against faith or manners that no law can possibly permit that intends not to unlaw itself&#8221;.</blockquote>
  <?php paragraphLink('B',3,1,5); ?>Some of those who place the strongest emphasis on press freedom take their lead from the principally American brand of &#8216;free speech absolutism&#8217;. Free speech absolutists take the injunction of the First Amendment to the United States Constitutions at face value: that Congress shall make no law abridging the freedom of speech. Within this tradition, the United States Supreme Court has developed some of the most extensive protections of free speech in the democratic world, including the protection of religious and racist hate speech as a species of &#8216;political speech&#8217;.<?php footnoteRef('B',3,2); ?></p>
  <?php paragraphLink('B',3,1,6); ?>However, even in a culture committed to maximum protection to free speech, the absolutist position has proved impossible to sustain. In practice, the United States Supreme Court imposes extensive restrictions on freedom of speech by identifying categories of speech which are deemed not to fall within the scope of the First Amendment. These categories include for example advocacy of imminent illegal conduct, official secrets, defamation and fraudulent misrepresentation. The Supreme Court has also denied that certain categories of sexually explicit material amount to protected speech and has been prepared to sanction far more extensive restrictions of obscene material than exist in the UK.<?php footnoteRef('B',3,3); ?></p>
  <?php paragraphLink('B',3,1,7); ?>Article 10(2) of the ECHR itself permits &#8220;formalities, conditions or restrictions&#8221; on freedom of expression so long as they are prescribed by law and necessary in a democratic society. Thus, to the extent that press freedom is protected as an aspect of the protection of freedom of expression under Article 10, certain restrictions will be necessary and justifiable in the overall public interest.</p>
  <?php paragraphLink('B',3,1,8); ?>The Inquiry invited thoughts on the place of press freedom within a wider concept of the public interest by asking the following question, both of some of the expert witnesses and more generally of the public at large via the Inquiry website:<?php footnoteRef('B',3,4); ?> 
  <blockquote>
  In order to maximise the overall public interest, with what other aspects of the public interest would freedom of expression, or freedom of the press, have to be balanced or limited? The Inquiry is particularly interested in the following, but there may be others: 
	<ol type="a">
		<li>the interest of the public as a whole in good political governance, for example in areas such as:
			<ul>
				<li>national security, public order and economic wellbeing,</li>
				<li>the rule of law, the proper independence and accountability of law enforcement agencies, and access to justice, and</li>
				<li>the democratic accountability of government for the formation and implementation of policy;</li>
			</ul>
		</li>
		<li>the public interest in individual self-determination and the protection and enforcement of private interests, for example 
			<ul>	
				<li>privacy, including (but not necessarily limited to) the rights to privacy specified in general in Article 8 of the European Convention on Human Rights and in European and national legislation on the protection of personal data,</li>
				<li>confidentiality, the protection of reputation, and intellectual and other property rights, and</li>
				<li>individual freedom of expression and rights to receive and impart information where those interests and rights are not identical to the interests and rights of the press.</li>
			</ul>				
		</li>
	</ol>
</blockquote>
What follows picks up some of the strands of thought in the responses the Inquiry received to these questions, and which seemed to be particularly pertinent. 
  </p>
  <?php sectionAnchor('B',3,2); ?>Freedom of expression</h2>
 <?php paragraphLink('B',3,2,1); ?>As noted above, the rights of individuals to freedom of expression have different origins from the public interest in the free speech of the press. Thus, freedom of expression or speech has value for individuals because of its ability to contribute to individual self-expression and self-realisation.<?php footnoteRef('B',3,5); ?></p>
<blockquote>&#8220;Freedom of individual expression is important for the development and maintenance of social identity, and for forming relationships and associations, for developing projects (that may be counter to prevailing opinion or orthodoxy).&#8221;</blockquote>
  <?php paragraphLink('B',3,2,2); ?>There is a distinct public interest in individual freedom of self-expression. Liberal democracies are composed of individuals free to express and develop themselves. It was put to the Inquiry in this way:<?php footnoteRef('B',3,6); ?></p>
<blockquote>&#8220;Freedom of thought and expression are also in the public interest because they constitute the public as a society of equals who respect one another: a society in which each member can participate and bring their own views to the public sphere. This is a good independent of the instrumental benefits it brings.&#8221;</blockquote>
  <?php paragraphLink('B',3,2,3); ?>The public interest in individual freedom of expression is a distinct and different aspect of the public interest to press freedom. Here is one way in which the difference was explained:<?php footnoteRef('B',3,7); ?></p>
<blockquote>&#8220;The press has, as it were, no &#8217;self&#8217; to fulfil, so an argument from self-fulfilment or self-development will not be directly relevant to questions of press freedom. More importantly, however, demands for press freedom are not (or not centrally) demands for free expression, but rather for the communication of information, and even if we think that individuals need to be able to express their views in order to develop fully as human beings, it does not follow that extensive freedom should be extended to those (eg the press) whose primary concern is with communication of information. To put the point starkly, those who aim to communicate must aspire to standards which are inapplicable for those who aim only to express their own views.&#8221; </blockquote>
  <?php paragraphLink('B',3,2,4); ?>The democratic rationale for freedom of expression in relation to individuals is also different from the democratic interest in a free press. It encompasses the individual&#8217;s right to receive information, impart his or her own views and participate in democracy on an informed basis. Democracy benefits from a free press where the press, taken as a whole (a sum of partisan parts), communicate a plurality of views and provide a platform for public debate.</p>
  <?php paragraphLink('B',3,2,5); ?>In this context, mass communication by the press has the capacity both to enhance and inhibit individual freedom of expression. It is therefore necessary to bear in mind the important point made to the Inquiry that some limitations to freedom of expression under the law are necessary in order to protect free speech from being inhibited by the free speech of others. This is a significant issue when there is an imbalance of power between the competing voices. A free debate cannot happen if some participants simply drown out others and prevent them from speaking. As the New ealand Law Commission pointed out in its submission to the Inquiry:<?php footnoteRef('B',3,8); ?></p>
<blockquote>&#8220;[C]ensorship is not the only enemy of free speech. Those who exercise their free speech to intimidate, bully, denigrate and harass others on the internet lessen the credibility of free speech arguments. Even though the web provides those who are harmed by free speech the opportunity to exercise their right of reply, not all have the courage or the standing to exercise it. In effect, those who exercise their free speech rights to cause harm may inhibit others from participating freely in this vital new public domain&#8221;.</blockquote>
  <?php paragraphLink('B',3,2,6); ?>Such restrictions may be necessary to protect the freedom of expression of one individual or group of individuals from the speech of another individual or group of individuals. For example, speech which inhibits personal self-expression, be it artistic, religious or sexual, or which intimidates others into silence, inhibits freedom of expression of others. This is why society does not protect racial or religious hate speech in law.<?php footnoteRef('B',3,9); ?> Nor is there protection in law for speech which is threatening, intimidating or harassing.<?php footnoteRef('B',3,10); ?></p>
  <?php paragraphLink('B',3,2,7); ?>When one individual&#8217;s right to freedom of expression is inconsistent with the similar rights of another, a difficult balancing exercise must be carried out in law. It may also be necessary to balance the public interest in the free speech of the press against the public interest in the freedom of expression of individuals. Race hate would be no more protected in the pages of a newspaper than it would anywhere else. This is, of course, a straightforward example. Political philosophers and ethicists would say that more complex issues arise where individual freedom of expression is put under pressure by the free speech of others in ways which are not objectionable in law but which nonetheless might be objectionable on other grounds.</p>
  <?php paragraphLink('B',3,2,8); ?>There are, for example, those cases in which the free speech of one party is experienced in a very intimate way as a threat to the core self-expression and identity of another. That is the context, for instance, in which debates about the portrayal of women and some minorities in the press is conducted.<?php footnoteRef('B',3,11); ?> There is a public interest in the free expression of views (and images) which some, perhaps many, find objectionable. There is also a public interest in the liberty of individuals to live free from publicly promulgated stereotyping which limits their own expression and development of themselves. This is not in any sense a point about censorship or law. It is a very simple and self-contained point about competing public interests in free expression.</p>
  <?php sectionAnchor('B',3,3); ?>Personal autonomy and civil liberties</h2>
 <?php paragraphLink('B',3,3,1); ?>To this extent, the public interest in individual freedom of expression is an aspect of a broader public interest in the autonomy, integrity and dignity of individuals. More generally, personal autonomy and human dignity require that individuals enjoy a protected personal sphere over which they exercise a measure of autonomous control. This is a dimension to the public interest which has a very ancient history in the UK and a special place in public imagination. It underlies the iconic status of habeas corpus as an early guarantee of personal liberty, and it underlies the special importance of freedom from interference in home life: &#8216;an Englishman&#8217;s home is his castle&#8217;.</p>
  <?php paragraphLink('B',3,3,2); ?>Personal autonomy means that individuals must have a sphere in which they can exercise individual choices without interference from others (including the state). This important personal sphere has been described in Western liberal philosophy in terms of the public interest in personal privacy. As David Feldman has stated:<?php footnoteRef('B',3,12); ?></p>
<blockquote>&#8220;The combination of the idea of a right to be respected as a moral agent with the idea of social spheres of decision-making within which people or groups are entitled to regard themselves as free from outside coercion are, I suggest, of the essence off the notion of privacy as a civil liberty.&#8221; </blockquote>
  <?php paragraphLink('B',3,3,3); ?>It is evident and well evidenced that the public interest in free speech and free self- expression does, on occasion, come into tension with the public interest in individual privacy and autonomy. Both are protected in law. Article 10 of the ECHR (freedom of expression) is held in a dynamic balance with Article 8 (home and private life). This dynamic balance has been developed in the English law of the protection of privacy. Lord Hoffmann observed in Campbell v MGN Ltd that the protection of privacy was essential to &#8220;the protection of human autonomy and dignity &#8211; the right to control the dissemination of information about one&#8217;s private life and the right to the esteem and respect of other people&#8221;. In the same case, Lord Nicholls agreed that &#8220;[a] proper degree of privacy is essential for the wellbeing and development of an individual&#8221;.</p>
  <?php paragraphLink('B',3,3,4); ?>Thus the existence of a private sphere is vital for human development. It is the space in which individuals are able to experiment with preferences and build personal relationships beyond public scrutiny and judgment. Violations of the private sphere prevent individuals from obtaining these benefits. The private sphere is also critical to personal autonomy as a space over which an individual exercises control. To invade someone&#8217;s privacy disregards that individual&#8217;s choices as to when and by whom he or she will be seen and what personal information he or she will divulge.</p>
  <?php paragraphLink('B',3,3,5); ?>That element of choice and control of the personal sphere, although a fundamental public good, is also capable of being exercised contrary to the public interest. So, for example, where an individual seeks to draw a veil of privacy over his or her criminal conduct, then the public interest in privacy will come into conflict with the public interest in law enforcement. But even there, the balanced result will be a partial and not a complete invasion of privacy, and one which is carefully prescribed by law; even in prison there are basic guarantees of human dignity.</p>
  <?php paragraphLink('B',3,3,6); ?>Where the public interest in free expression, in holding power to account, and in the pursuit of wrongdoing are all aligned on the one hand, and conflict with the public interest in an individual&#8217;s privacy on the other, it is clear that the balance will be able to come down in favour of the former. But again, it is important to keep in mind that the public interest in privacy, although compromised, never completely goes away. Violation of the private sphere must always be proportionate to any larger public interest being served. The element of control over one&#8217;s personal life is never all-or-nothing, but a matter of an infinite number of degrees and decisions.</p>
  <?php paragraphLink('B',3,3,7); ?>Where an individual has chosen to put a matter within the private sphere into the public domain, then he or she will have ceded a measure of control over it.<?php footnoteRef('B',3,13); ?> Making choices of that nature is of the essence of personal autonomy. They do not necessarily imply that other choices will be made, much less that the freedom to make other choices is also being ceded. Everyone is entitled to some private space and always provided that there is no countervailing public interest in exposure of that private space (because, for example, it exposes crime or serious impropriety)<?php footnoteRef('B',3,14); ?> there is a public interest in preserving it.</p>
  <?php paragraphLink('B',3,3,8); ?>This important point was made in a number of ways to the Inquiry.<?php footnoteRef('B',3,15); ?></p>
<blockquote>&#8220;An actor who is successful may be well known because his films are viewed by many. He may indeed wish and hope that many continue to view the results of his (and others&#8217;) craft. It does not follow from this that he has a pathological compulsion to display himself, or to have every aspect of his life observed and documented. Nor does it follow that he has made some kind of tacit contractual agreement, where he has waived his privacy rights in exchange for fame.... &#8220;Those who do wish to enter a quasi-contractual agreement where they exchange the protection of privacy for an increase in their fame should not be prohibited from doing so, but it does not follow from this that everyone that the public might have an interest in &#8230; should have their private lives placed at risk of intrusive and invasive acts.&#8221;<?php footnoteRef('B',3,16); ?></blockquote>
  <?php paragraphLink('B',3,3,9); ?>To treat an individual merely as something to be talked about, reported or looked at against his or her wishes is contrary to the public interest in individual autonomy, and to the ethical imperative to treat individuals as an &#8220;end&#8221; and not simply as a &#8220;means&#8221;.</p>
  <?php paragraphLink('B',3,3,10); ?>It is right to acknowledge however that the nature of the public interest in privacy and our understanding of the implications of choices made by individuals about their privacy are matters which lie at the heart of a number of fast-moving contemporary social changes, about which a clear and stable consensus may not yet have been reached. The explosion in use of social media, particularly by the young, has not yet been matched by a settled understanding of the implications of the choices that people make in placing private material online; many do so unwisely or naively with disproportionate exposure to exploitation of such material and the compromising of their privacy.</p>
  <?php paragraphLink('B',3,3,11); ?>At the same time, the nature of commercial &#8216;celebrity culture&#8217; continues to be pondered even as it evolves with great rapidity; again, there is as yet no settled understanding or consensus about this. A celebrity obviously gives up his or her right to privacy if he or she sells an intimate photograph to a newspaper. How far this goes is another question. The right is clearly ceded as regards the transaction in question, but does that give the newspaper or even the press in general, a blank cheque for all purposes or for all time? Put in those terms, the answer, in my view, is clearly not. But around the margins there may be issues of fact and degree.</p>
  <?php paragraphLink('B',3,3,12); ?>In any event, while the precise limits of the public interest in this area may be being developed and contested, the underlying basics must not be lost sight of. As Professor Megone put it:<?php footnoteRef('B',3,17); ?></p>
<blockquote>&#8220;Journalists and editors need to recognise that both personal privacy and the importance of confidentiality can in part be understood in terms of an agent&#8217;s ownership of his own information, and the importance of that to the control of his own life. These are matters a free society seeks to protect as part of the public interest &#8211; and the press need to be clear that they may well need respecting even when such respect adversely affects journalistic activity&#8221; </blockquote>
  <?php paragraphLink('B',3,3,13); ?>The protection of the &#8220;reputation and rights of others&#8221; is expressly identified by Article 10(2) of the ECHR as a necessary public interest basis for limiting the expression of others. The right to freedom of expression must therefore be accommodated with other fundamental liberties. Thus, when confronted with conflicting claims under two protected ECHR rights, the courts must undertake a difficult balancing exercise to determine which will prevail. This is the reason why there is no protection for speech (written or oral) which unjustifiably damages a person&#8217;s reputation or which interferes with a person&#8217;s &#8220;reasonable expectation of privacy&#8221;.<?php footnoteRef('B',3,18); ?></p>
  <?php sectionAnchor('B',3,4); ?>Other public goods</h2>
 <?php paragraphLink('B',3,4,1); ?>The relationship between freedom of the press and the public interest in justice is similarly a matter of balance. On the one hand, freedom of expression is integral to the principle of open justice, which encompasses the entitlement of the media to impart and the public to receive information in relation to the process of justice. Therefore, any restriction on the ability of the press to report proceedings openly must be expressly limited.<?php footnoteRef('B',3,19); ?> On the other hand, reporting restrictions may be necessary if the right of an individual to a fair trial would be prejudiced by publication of information about the proceedings: this is no more than the protect the integrity of the justice system and a person&#8217;s right to a fair trial.</p>
  <?php paragraphLink('B',3,4,2); ?>Even more fundamental are the limits on freedom of expression necessary to protect a democratic society in which freedom of expression is able to flourish. Thus, first listed in the restrictions on freedom of expression permitted by Article 10(2) are those &#8220;necessary in a democratic society, in the interests of national security, territorial integrity or public safety, for the prevention of disorder or crime&#8221;. These are straightforward concepts which speak for themselves. 
  </div>

