<?php 
require_once('../../common.php');
levesonHeader('B',3); 
levesonNav('../../');
levesonBread('B',3);
require_once('content.php');
levesonFooterNav('B',3); 
require_once('footnotes.php');
LevesonCommonFooter();
?>