<?php 
require_once('../../common.php');
levesonHeader('I',1); 
levesonNav('../../');
levesonBread('I',1);
require_once('content.php');
levesonFooterNav('I',1); 
require_once('footnotes.php');
LevesonCommonFooter();
?>