<?php 
require_once('../../common.php');
levesonHeader('H',6); 
levesonNav('../../');
levesonBread('H',6);
require_once('content.php');
levesonFooterNav('H',6); 
require_once('footnotes.php');
LevesonCommonFooter();
?>