<div class="content" id="contentPartKChapter2">
<h1 id="top">CHAPTER 5<br/>INTERNATIONAL COMPARATORS</h1>
 <?php sectionAnchor('K',5,1); ?>The press Council of Ireland and the press ombudsman</h2>
 <h3>History and background</h3>
 <?php paragraphLink('K',5,1,1); ?>The Irish Press Council and Ombudsman system was set up in 2007 as a direct response to the threat of legislation from the Irish Government. The Chair of the Press Council, Daith&#237; O&#8217;Ceallaigh, described the agreement eventually reached between the Government and the industry as:<?php footnoteRef('K',5,1); ?></p>
<blockquote>&#8220;a win-win solution&#8230;.[where] at least some of the changes in defamation law sought by the industry would be incorporated in a new Act and, in return, the industry would sponsor an independent Press Council and Press Ombudsman along lines broadly acceptable to government.&#8221; </blockquote>
  <?php paragraphLink('K',5,1,2); ?>In the mid 1990s the Irish Government set up a Commission on the newspaper industry; in 1996, that body recommended the establishment of a Press Ombudsman, but no action was taken.<?php footnoteRef('K',5,2); ?> Then in 2002, the Minister for Justice, Michael McDowell, set up an expert advisory group which reported in 2003 with a recommendation for a statutory system of regulation for the press.<?php footnoteRef('K',5,3); ?> The industry set up a steering committee to consider its response; this committee included representatives of all the major newspaper groups in Ireland, including some of those based in the UK, namely News International and Trinity Mirror.<?php footnoteRef('K',5,4); ?> This group ultimately developed a model for the Press Council, which was to be independent of Government and, in its operations, independent of the industry; this was the model that was adopted for the new Council and Ombudsman in the summer of 2007.</p>
  <?php paragraphLink('K',5,1,3); ?>ProfessorJohn Horgan, the Irish Press Ombudsman, explained to the Inquiry his understanding that the Press Council had been established with the quid pro quo that that Government would withdraw its proposals for the statutory regulation of the press.<?php footnoteRef('K',5,5); ?> At the same time, the Government agreed to use the legislative opportunity provided by the Defamation Bill in 2009 to offer some statutory underpinning for the new Council.<?php footnoteRef('K',5,6); ?></p>
  <?php paragraphLink('K',5,1,4); ?>Professor Horgan made it clear that the industry considered there to be a very real threat that the Government would legislate for press regulation in the absence of an adequate self- regulatory solution:<?php footnoteRef('K',5,7); ?>
<blockquote>&#8220;LORD JUSTICE LEVESON: But behind it all, do I gather from what you were saying somewhat earlier, was the threat of statutory regulation? <br/>
A. Absolutely.<br/>
 LORD JUSTICE LEVESON: So in other words, it behoved the press interests to come up with a solution that was less than the club that was being held over them? <br/>
A. That is absolutely the case. And in fact my membership, or our membership of the Alliance of Independent Press Councils of Europe indicates that in quite a few countries this threat has been the engine which has generated or promoted the successful establishment of press councils of the same kind in many European countries. So even though before this threat was made, there had been moves towards the establishment of something like this, the 1996 report of the commission, which wasn't under such a threat, recommended the establishment of an ombudsman. As I said, it was the real and present danger of that that created the situation in which we found ourselves.&#8221; </blockquote></p>
  <h3>Legal recognition</h3>
 <?php paragraphLink('K',5,1,5); ?>In practice the Defamation Act 2009 set out some fairly detailed requirements for the structure, coverage and operation of a Press Council before it could be recognised under the legislation; this meant that, whilst the detail of both the code of practice and the complaints mechanism were left to the industry to set, the broad framework was dictated by the legislation if the industry wanted to take advantage of the protection offered by the Act. Professor Horgan told the Inquiry:</p>
 <blockquote> &#8220;without the benefit of knowledge of what went on behind closed doors in the four years leading up to the creation of the Press Council, it might be thought that this legislation represents a framework imposed by the state on the private sector. Whereas in fact &#8211; and Professor Thomas Mitchell has briefed me extensively on this &#8211; by and large the provisions relating to the Press Council that found their place in the Defamation Act were those proposed by the Press Council itself to the government.&#8221; </blockquote>
 <p>There is scope within the Act for the industry collectively to decide not to create a Press Council, and for any individual journal to decide not to participate. However, the Press Council of Ireland, as currently constituted, was established before the Act came into force and all significant publishers of newspapers in Ireland are members of the Council.<?php footnoteRef('K',5,8); ?></p>
  <h4>Benefits</h4>
 <?php paragraphLink('K',5,1,6); ?>The Act provides a defence of &#8216;fair and reasonable publication&#8217; to a defamation action.<?php footnoteRef('K',5,9); ?> In the case of a statement published in a periodical by a person who at the time of publication was a member of the Press Council, a court in considering whether publication was fair and reasonable may take into account the extent to which the person adhered to the code of standards of the Press Council and abided by determinations of both the Press Ombudsman and the Press Council.<?php footnoteRef('K',5,10); ?> There was, as yet, no case law on this.<?php footnoteRef('K',5,11); ?> Professor Horgan clarified that this did not mean that the defence was only available to those who had signed up to the system. The defence was also available, in theory, to other publications if they could satisfy the court that they operated to standards and procedures in no way inferior to those of the Council. Similarly, this had not been tested in court and Professor Horgan said:<?php footnoteRef('K',5,12); ?></p>
<blockquote>&#8220;My honest view it that it would be quite difficult for publications that are not members of the Council to satisfy a court that they operate to such standards.&#8221; </blockquote>
  <?php paragraphLink('K',5,1,7); ?>In order to enact these benefits, the Act makes provision for the Minister, by order, to recognise a body as &#8220;the Press Council&#8221; for the purposes of the Act. The requirements for recognition are specific and detailed and it is worth setting them out here to show the extent to which the Defamation Act establishes the objectives and the structural independence of the Press Council, the approach to dealing with complaints and the overarching coverage of the code of standards.</p>
  <?php paragraphLink('K',5,1,8); ?>Only one Press Council may be recognised at any one time. Before the Press Council can be recognised the Minister must satisfy himself that it meets the specifications set out in Schedule 2 to the Act. He can revoke the recognition at any time he considers that the Press Council fails to meet the specifications in the Schedule.<?php footnoteRef('K',5,13); ?> So far this power has been used once, in April 2010, to recognise the Press Council of Ireland as &#8216;the Press Council&#8217;.</p>
  <?php paragraphLink('K',5,1,9); ?>Schedule 2 of the Act requires that the Press Council should have the principle objectives of:<?php footnoteRef('K',5,14); ?> <blockquote> <ol style="list-style-type:lower-alpha;"> <li>ensuring the protection of freedom of expression of the press,</li>
 <li>protecting the public interest by ensuring ethical, accurate and truthful reporting by the press,</li>
 <li>maintaining certain minimum ethical and professional standards among the press,</li>
 <li>ensuring that the privacy and dignity of the individual is protected.</li>
 </ol> </blockquote> Interestingly, Professor Horgan told the Inquiry that the primary purpose of the Press Council was:<?php footnoteRef('K',5,15); ?>
<blockquote>&#8220;to maintain the rights of the press to freedom of expression, to maintain the independence of the press from the State and State control or regulation and to decide on appeals against decisions or the Press Ombudsman on complaints.&#8221; </blockquote>with the primary role of the Press Ombudsman being:<?php footnoteRef('K',5,16); ?>
<blockquote>&#8220;to receive and adjudicate on complaints, to raise public awareness of the work of his Office and of the Council, and to encourage and promote the highest ethical standards of journalism in Ireland.&#8221; </blockquote>Meanwhile, the website of the Press Council says that the objectives of the Press Council are:<?php footnoteRef('K',5,17); ?> </p>
<blockquote> <ul>
 <li>&#8220;To provide the public with an independent forum for resolving complaints about the press.</li>
 <li>To resolve all complaints quickly, fairly and free of charge.</li>
 <li>To defend the freedom of the press and the freedom of the public to be informed.&#8221;</li>
 <ul>
 </blockquote> 
  <?php paragraphLink('K',5,1,10); ?>Specific provision is made in the Act about the structure of the Council, the number of members and how many of those members should independently represent the public interest, the interests of owners and publishers, and of journalists.<?php footnoteRef('K',5,18); ?> The Schedule makes requirements about the independence of the appointments procedures; it requires that the Minister should be satisfied by the independence of the appointments procedure but gives him no role in establishing or operating it.<?php footnoteRef('K',5,19); ?></p>
  <?php paragraphLink('K',5,1,11); ?>Professor Horgan told the Inquiry that it was clear to the industry when they were formulating their proposals for the Council that:<?php footnoteRef('K',5,20); ?></p>
<blockquote>&#8220;one critical aspect of what the industry proposed to establish, without which no possible measure of Government acceptance or approval would have been available, was independence.&#8221; </blockquote>
  <?php paragraphLink('K',5,1,12); ?>It is a requirement of the Act that the Press Council should be funded by subscribing journals and should receive no funding from other sources.<?php footnoteRef('K',5,21); ?></p>
  <?php paragraphLink('K',5,1,13); ?>The Act requires that the Press Council should appoint a body (the Press Ombudsman) to resolve complaints about the conduct of its members. The Press Ombudsman is to have the power to require publication of its own decisions, corrections, retractions and &#8220;such other action as the Ombudsman may, in the circumstances, deem appropriate&#8221;. Decisions of the Ombudsman are to be appealable to the Press Council itself, which is to have similar powers in respect of requiring publication of decisions.<?php footnoteRef('K',5,22); ?></p>
  <?php paragraphLink('K',5,1,14); ?>The Press Council must have adopted a code of practice with which all members are required to comply; this includes:<?php footnoteRef('K',5,23); ?></p>
<blockquote>
<ol type="a">
<li>&#8220;ethical standards and practices, </li>
<li>rules and standards intended to ensure the accuracy of reporting where a person&#8217;s reputation is likely to be affected, and </li>
<li>rules and standards intended to ensure that intimidation and harassment of persons does not occur and that the privacy, integrity and dignity of the person is respected.&#8221; </li>
</ol>
</blockquote>
  <h3>The Press Council</h3>
 <?php paragraphLink('K',5,1,15); ?>The Council was created by the Press Industry Steering Committee, comprising the publishing trade associations and the NUJ, in accordance with the provisions set out in the Act.</p>
  <h4>Appointments</h4>
 <?php paragraphLink('K',5,1,16); ?>The Act requires the Press Council to comprise 13 members, of whom seven are independent members representing the public interest, five represent the interest of owners and publishers and one represents the interest of journalists.<?php footnoteRef('K',5,24); ?> The public interest members are appointed by an independent four-person Appointments Committee, on the basis of public advertisement and interview.<?php footnoteRef('K',5,25); ?> The Chair of the Council is appointed from within the public interest members, although in practice external applications have also been invited.<?php footnoteRef('K',5,26); ?> The industry and journalist members are nominated by the various organisations that took part in the steering committee and the Appointments Committee ratifies the nominations. Professor Horgan explained that there was not an automatic guarantee of appointment for those who were nominated, but he could not readily foresee a situation in which such nominations would not be ratified.<?php footnoteRef('K',5,27); ?></p>
  <?php paragraphLink('K',5,1,17); ?>The first Appointments Committee was appointed by the Press Industry Steering Committee. Subsequent appointments to the Committee are made by the Press Council. The appointments are for three years; that first Committee was subsequently re-appointed for a second three year term by the Council in July 2010.<?php footnoteRef('K',5,28); ?> As of August 2010, the Chair of the Council was also the Chair of the Appointments Committee.<?php footnoteRef('K',5,29); ?></p>
  <?php paragraphLink('K',5,1,18); ?>The five industry members of the Press Council are current senior editorial executives, although not usually editors. The only serving editor currently on the Council is the editor of a regional publication; he fills the slot effectively reserved for regional newspaper editors.<?php footnoteRef('K',5,30); ?> Professor Horgan suggested that the absence of serving editors has worked well for the Press Council, particularly because he thought that there was more change of personnel than might be expected if editors were to hold the seats. The appointments are for a three year term, and can be extended for a second term; however, some four and a half years into the Council&#8217;s existence, only one of the original industry representatives is still a member of the Council.<?php footnoteRef('K',5,31); ?></p>
  <?php paragraphLink('K',5,1,19); ?>Professor Horgan told the Inquiry that the public interest majority on the Council was essential to the public acceptance of the independence of the model.<?php footnoteRef('K',5,32); ?> He also regarded the presence of a journalist member on the Council alongside the industry members as essential.<?php footnoteRef('K',5,33); ?></p>
  <h4>Structures and Funding</h4>
 <?php paragraphLink('K',5,1,20); ?>In line with the requirements of the Defamation Act, the Press Council is wholly funded by the press industry. The finances of both the Press Council and the Press Ombudsman are provided by the Administrative Committee of the Press Council; the Committee is chaired by an independent member of the Council but otherwise consists of representatives of the different types of publications covered, together with the NUJ. Each title covered by the Council pays a levy based on circulation.<?php footnoteRef('K',5,34); ?></p>
  <?php paragraphLink('K',5,1,21); ?>Making a complaint is free to the complainant.<?php footnoteRef('K',5,35); ?></p>
  <h4>The Code</h4>
 <?php paragraphLink('K',5,1,22); ?>The code was originally drawn up in 2007 by the Steering Committee. There is now a Code Committee, which is chaired by an independent retired journalist and comprises nominees of the industry bodies. Serving editors have the right to be on the Committee but, for the most part, they are represented by deputies or senior executives. The Ombudsman sits on the committee in an ex-officio capacity.<?php footnoteRef('K',5,36); ?> Any changes to the Code are made in consultation with the Council. The Council can also suggest changes to the Code Committee. There have not, in fact, been any significant changes since the code was originally drafted.<?php footnoteRef('K',5,37); ?> It may be worth noting that the code would have been available to the Government to see when formulating the terms of the 2009 Defamation Act.</p>
  <h4>Coverage</h4>
 <?php paragraphLink('K',5,1,23); ?>All national newspapers, including all the UK papers that are published in Ireland, and over 90% of regional newspapers, are members of the Press Council. Around 60%, by number, of periodicals are members of the Council, but this would account for considerably more than 60% of circulation as the larger magazines are members.<?php footnoteRef('K',5,38); ?> Since the creation of the Council no members have left, or threatened to leave, the system.<?php footnoteRef('K',5,39); ?> Recently a news website has applied for membership and the Council is considering the appropriate criteria for membership of web media.<?php footnoteRef('K',5,40); ?></p>
  <h4>Public awareness and satisfaction</h4>
 <?php paragraphLink('K',5,1,24); ?>Professor Horgan told the Inquiry that public awareness of the Press Council and Ombudsman was limited. A public awareness campaign had been launched in an attempt to make the services provided by the Ombudsman more widely known.<?php footnoteRef('K',5,41); ?></p>
  <h4>Impact of statute on freedom of speech and the public interest</h4>
 <?php paragraphLink('K',5,1,25); ?>Professor Horgan did not think that the statutory recognition afforded to the Press Council by the Defamation Act constituted a limitation on the freedom of expression because the limitations in the Act were, by and large, those proposed and endorsed by the industry itself as a necessary balancing of the right to publish against the rights of individuals.<?php footnoteRef('K',5,42); ?> The belief of the Council in the importance of the freedom of the press is reasserted in the preamble to the Code.<?php footnoteRef('K',5,43); ?></p>
  <?php paragraphLink('K',5,1,26); ?>In this context it is worth noting that all UK titles that publish in Ireland are members of the Council; they do not appear to allow any principled objections to statutory underpinning of press self-regulation to get in the way of constructive and willing participation in this system.</p>
  <?php paragraphLink('K',5,1,27); ?>The public interest is not defined in the code, and it is left up to the Council and the Ombudsman to interpret it on a case by case basis. The code does set out a general principle:<?php footnoteRef('K',5,44); ?></p>
<blockquote>&#8220;that the public interest is invoked in relation to a matter capable of affecting the people at large so that they may legitimately be interested in receiving and the press legitimately interested in providing information about it.&#8221; </blockquote>
  <h3>The Press Ombudsman</h3>
 <?php paragraphLink('K',5,1,28); ?>The Press Ombudsman primarily receives and adjudicates on complaints. The Ombudsman is appointed by the Press Council and reports to the Council on a monthly basis in respect of administrative matters.<?php footnoteRef('K',5,45); ?> The Ombudsman is independent of the Council in the execution of his functions of investigation and adjudication, but his decisions can be appealed to the Council by either the complainant or the newspaper if they are dissatisfied.<?php footnoteRef('K',5,46); ?> Professor Horgan stressed that his contract guarantees his independence from the Council and that the Council had recently agreed to amend its articles of association to give him greater independence. In particular the Ombudsman now has discretion to make decisions on whether someone is a person directly affected, and to rule out vexatious and frivolous complaints.<?php footnoteRef('K',5,47); ?></p>
  <h4>Complaints</h4>
 <?php paragraphLink('K',5,1,29); ?>Complaints can only be made in respect of publications that are members of the Press Council of Ireland. A complaint can relate to any article that breaches the Code of Practice or to the behaviour of a journalist that breaches the Code.<?php footnoteRef('K',5,48); ?></p>
  <?php paragraphLink('K',5,1,30); ?>Complainants are expected to go in the first instance to the publisher concerned, and the Ombudsman will only consider complaints if the complainant has not received a satisfactory reply within two weeks.<?php footnoteRef('K',5,49); ?> Professor Horgan told the Inquiry that he had: </p>
  <blockquote>&#8220;got a very severe telling off, which I think in the circumstances was quite justified, from the editor of the newspaper concerned&#8230;..&#8221;
  </blockquote>
  <p> when he had, on one occasion taken a <!--typo-->complaint directly at the request of the complainant who had been too fearful to confront the newspaper itself.<?php footnoteRef('K',5,50); ?>
  <?php paragraphLink('K',5,1,31); ?>Complainants are free to take their cases to court in advance of, alongside or after a case is considered by the Ombudsman. The Ombudsman will not consider a case while it is before a court, but will suspend consideration of the complaint until legal proceedings have concluded.<?php footnoteRef('K',5,51); ?> Professor Horgan could only recall one example of a complainant having taken legal action in respect of a matter which had already been adjudicated by him.<?php footnoteRef('K',5,52); ?></p>
  <h4>Process</h4>
 <?php paragraphLink('K',5,1,32); ?>The Ombudsman will generally carry out conciliation and reach conclusions on the basis of documentation alone, although there is also provision for face-to-face mediation, which may be used more often in future.<?php footnoteRef('K',5,53); ?> All decisions, whether by the Press Ombudsman or, on appeal, by the Press Council, are published to the interested parties and on the Press Council/ Ombudsman website.<?php footnoteRef('K',5,54); ?> An annual report is published setting out the data and the approach taken to key issues.</p>
  <h4>Volume and results</h4>
 <?php paragraphLink('K',5,1,33); ?>In the four years of its operation the Irish Press Ombudsman has received on average between 340-350 complaints per year. This is roughly analogous, in proportion to population, to the number received by the PCC. There is, however, one striking difference between the outcomes from the Irish Ombudsman and those from the PCC. The Irish Press Ombudsman has reached a decision on nearly 12% of the complaints brought to it over its four year lifetime, which compares to substantially less then 1% of complaints to reach adjudication with the PCC.<?php footnoteRef('K',5,55); ?> In 2010 and 2011 around two thirds of the decisions of the Press Ombudsman have included a finding that the code was breached, with sufficient remedial action already having been taken by the publisher in up to half of those cases.<?php footnoteRef('K',5,56); ?> Comparatively few cases are conciliated, with only 19 (6% and 5.5% respectively) conciliated in each of 2010 and 2011.<?php footnoteRef('K',5,57); ?></p>
  <h4>Appeals</h4>
 <?php paragraphLink('K',5,1,34); ?>Either party to a complaint can appeal the decision of the Press Ombudsman to the Press Council. Professor Horgan told the Inquiry that there were a substantial number of appeals in the early years but that only very few appeals were upheld by the Press Council.<?php footnoteRef('K',5,58); ?> The figures provided to the Inquiry show that 53% of the decisions taken by the Press Ombudsman have been appealed to the Council over the four years. There was a substantial dip in the level of appeals in 2009, but otherwise the proportion of decisions appealed has been over 50% in every year of the Press Ombudsman&#8217;s operation. It is not obvious from the figures whether those appeals were by publishers or claimants and Professor Horgan told the Inquiry:<?php footnoteRef('K',5,59); ?>
<blockquote>&#8220;Initially quite a substantial number of my decisions would have been appealed, either by newspapers or by complainants, on the grounds that, well, it was free and, you know, why not have a second bite at the cherry?&#8221; </blockquote>Very few of these appeals are upheld, however, with only three appeals having been upheld in four years (although some 12 appeals are described as being still outstanding).<?php footnoteRef('K',5,60); ?></p>
  <h4>Standards</h4>
 <?php paragraphLink('K',5,1,35); ?>The Ombudsman deals with individual cases and has no remit to identify or respond to any systemic issues which might become apparent from cases that he considers. Professor Horgan told us this would be a matter for the Press Council, on the basis of its own assessment of the issues before the Ombudsman and the decisions being reached. However, the Press Council does not have the power to conduct own-initiative investigations, and has no specific remit to tackle serious or systemic problems. Some efforts have been made to address systemic issues by, for example, sponsoring seminars on relevant matters.<?php footnoteRef('K',5,61); ?></p>
  <h4>Sanctions</h4>
 <?php paragraphLink('K',5,1,36); ?>The only sanction available to the Press Ombudsman is the requirement for the newspaper or magazine to publish a decision upholding a complaint.<?php footnoteRef('K',5,62); ?> Professor Horgan told the Inquiry that all the major newspapers have been the subject of critical adverse findings in one form or another.<?php footnoteRef('K',5,63); ?> Decisions of the Press Ombudsman also frequently include a correction of inaccurate facts.<?php footnoteRef('K',5,64); ?> Detailed guidelines have been adopted by the Council in relation to the publication of a decision by the Press Ombudsman. In relation to prominence of publication these guidelines say:<?php footnoteRef('K',5,65); ?></p>
<blockquote>&#8220;(3) Those sections of decisions of the Press Ombudsman upholding a complaint should be published: (a) in full; (b) promptly; (c) on the same page as the original article, or further forward, subject to the exception at (6) below; (d) on the same day of the week as the original publication, (e) with similar prominence; (f) unedited; and (g) without editorial commentary by way of a headline or otherwise. In addition, each should carry, above the headline, a strap-line indicating that it is a decision of the Press Ombudsman. <br/>
[&#8230;.] <br/>
(6) Where a complaint has been upheld in relation to an article published on the front page of a publication, the decision should be published with due prominence on one of the first four editorial pages.&#8221; </blockquote>
  <h4>UK titles as members</h4>
 <?php paragraphLink('K',5,1,37); ?>Professor Horgan told the Inquiry that UK titles accounted for 30% of membership of the Council, but were responsible for around 22% of the complaints. These figures have to be viewed with caution, however, as they make no allowance for circulation figures or other differences between titles.<?php footnoteRef('K',5,66); ?> In respect of the types of complaint that were received about UK titles and Irish titles, Professor Horgan said:<?php footnoteRef('K',5,67); ?>
<blockquote>&#8220;There&#8217;s absolutely no discernable differentiation between the basis of the complaints against indigenous publications and those against UK-based publications.&#8221; </blockquote>Professor Horgan went on to say that he had no complaints at all about the cooperation of any of the publications with the Ombudsman.<?php footnoteRef('K',5,68); ?></p>
  <?php sectionAnchor('K',5,2); ?>Other models of press regulation: Europe and beyond</h2>
 <?php paragraphLink('K',5,2,1); ?>In this section I consider systems of press regulation operated in Europe and elsewhere; whether they are comparable to conditions in the UK and whether there are lessons that might be learnt and applied. It is important to start by noting that, while there may be similarities between systems of press regulation, no two systems are the same and there are important differences.</p>
  <?php paragraphLink('K',5,2,2); ?>While all of those countries in consideration here operate systems of self-regulation, they differ from the PCC in many ways. In some cases, notably Denmark, Sweden, Finland and Germany, there is some form of involvement by government, either through statute or because of financial support; in the case of France, the impact of legislation is very different to the model in the UK and has real impacts upon the functioning of the press in that country.</p>
  <?php paragraphLink('K',5,2,3); ?>Most of the comparative European countries operate a form of self-regulation through a Press Council, but also in some cases a Press Ombudsman (notably in Sweden). Unsurprisingly, the majority of the Press Councils operating in Europe and internationally, have been established solely with the printed press in mind. The development of new media, such as online publications and micro-blogging sites, have created opportunities for Press Councils to review existing frameworks, in order to consider options for incorporating new media platforms into their regulatory structure. This has included consideration of how to encourage membership, as well as how to meet the expectations for new media platforms and additional sources of funding for the system of regulation.<?php footnoteRef('K',5,69); ?> By way of example, Denmark operates a &#8216;polluter pays&#8217; policy for online members who have joined the Press Council. However, this is regarded as a temporary measure, as no official funding mechanism has yet been developed.<?php footnoteRef('K',5,70); ?> Online and the self-regulatory settlement with online publishers is considered as and where appropriate in this section.</p>
  <?php paragraphLink('K',5,2,4); ?>This section will also look at the composition of the Press Council Boards, as well as sources of funding for the industry; both are important variables. The German Press Council for example is co-funded by the German Government. This system has not led to statutory regulation; neither has it been suggested that the Government exerts a deleterious influence simply because of the public funding. In her extremely well informed evidence to the Inquiry, Lara Fielden, a Visiting Fellow at the Reuters Institute for the Study of Journalism, has suggested that, although many of the European Press Councils profess to focus on the embedding and maintenance of journalistic standards, in practice this role is limited and most Press Councils are reactive and complaints driven instead.<?php footnoteRef('K',5,71); ?></p>
  <?php paragraphLink('K',5,2,5); ?>I will first consider the Scandinavian countries and thereafter Germany, France and the Netherlands. I will then pass on briefly to review the situation in both the United States and China.</p>
  <h3>Denmark, Sweden and Finland</h3>
 <?php paragraphLink('K',5,2,6); ?>The press in the Scandinavian countries has been described as a collective press which has historically prided itself on the publication of information to high standards of accuracy, and within the boundaries set by a clear journalistic code. In each of the Scandinavian countries, the respective Press Council has powers to raise monetary contributions and, if an article is found to breach the code, to mandate the publication of the fact of a breach along with an apology. Furthermore, in Denmark, the Press Council additionally has the ability (rarely used) to fine or imprison an editor-in-chief who fails to comply with a publication of a Council adjudication.<?php footnoteRef('K',5,72); ?> As to the relevance of rights of individuals, the Swedish Code of Standards includes the clause that journalists should:<?php footnoteRef('K',5,73); ?>
<blockquote>&#8220;Refrain from publicity which could violate the privacy of individuals, unless the public interest obviously demands public scrutiny&#8221;.</blockquote> Ms Fielden explained that the tabloid press in the Scandinavian countries had become increasingly comfortable with reporting on the private lives of politicians and others.<?php footnoteRef('K',5,74); ?></p>
  <?php paragraphLink('K',5,2,7); ?>Significantly, there are no press laws in place, nor specific legislation relating to the regulation of the printed press, in Denmark, Sweden or Finland. However, contrary to assertions made in evidence and in public over the course of this Inquiry, there are elements of governmental involvement that can be found in the systems of press self-regulation operated in these Scandinavian countries. For example, and most notably, the Danish Press Council is established in statute, pursuant to the Danish Media Liability Act 1998, albeit that other elements of the system are self-regulatory particularly in terms of handling adjudications, the composition of the Press Council Board and the exercise of Council responsibilities. Under the terms of the Act, all publications which are in printed circulation more than twice a year, as well as holders of broadcast licences, are subject to regulation by the Danish Press Council. The Council also deals with complaints across all media platforms, including online media, provided (in the case of online publishers) that these organisations are registered with the Council.</p>
  <?php paragraphLink('K',5,2,8); ?>Ms Fielden has explained that registration in Scandinavia is the expectation and is not perceived as a form of licensing.<?php footnoteRef('K',5,75); ?> Indeed, it is compulsory for any publisher seeking to participate in the self-regulatory system in Denmark, Sweden and Finland. The procedure of registering an editor-in-chief responsible for the publication is representative of the Scandinavian approach to responsible and accurate journalism.</p>
  <h4>Denmark</h4>
 <?php paragraphLink('K',5,2,9); ?>Any journalist, or individual who imparts news in some way, whether through printed media or online, is protected under the Danish Press Council&#8217;s professional umbrella. The benefits of membership of the Council include access to privileges in law such as the protection of journalists&#8217; sources. This has been the incentive for many online publishers to join the Council on a voluntary basis.<?php footnoteRef('K',5,76); ?> They have the ability to differentiate themselves from other online media who are not regulated by the Council. Online publishers are expected to contribute to the industry funding of the Press Council if they are affiliates of existing members (such as the online presence of a broadcaster or a printed newspaper). However, purely online-only outlets are not expected to contribute. This is partly due to the non-existence of a funding mechanism and is compensated by the Danish Press Council operating the &#8216;polluter pays&#8217; policy, which is applied if an online member breaches the Code.<?php footnoteRef('K',5,77); ?></p>
  <?php paragraphLink('K',5,2,10); ?>It is noteworthy that, in similar fashion to the PCC, the Danish Press Council does not accept third party complaints and deals with only those individuals who have been directly affected by press misreporting.</p>
  <?php paragraphLink('K',5,2,11); ?>One of the primary roles of the Danish Press Council is the duty to enforce a right of reply (albeit limited to specific factual inaccuracy). This power is enacted in statute under the Danish Media Liability Act 1998, and is procedurally different to the remedy obtainable from the court,<?php footnoteRef('K',5,78); ?> and applies to both newspapers and broadcasters.<?php footnoteRef('K',5,79); ?> Save for this and for the penal consequences visited on the editor-in-chief for failure to publish adjudications by the Press Council, there are no other enforceable rights under the Act. Like the Press Councils in Sweden and Finland, the Danish Press Council does not have the power to award compensation or to impose financial penalties.</p>
  <?php paragraphLink('K',5,2,12); ?>Although the Danish Press Council is set up in statute, it is still at a fundamental level self- regulatory and is regarded as such by its members. The eight members of the Council are appointed for their industry expertise. Historically, a member of the Danish Supreme Court has always been appointed as the Chair of the Council and a lawyer has held the position of Vice-Chair. The remainder of the Council consists of industry members, who are either journalists or editorial management, or independent public members; each is equally represented with two positions on the panel.</p>
  <?php paragraphLink('K',5,2,13); ?>Although the system operated in Denmark has its benefits, it has come under parliamentary scrutiny, in particular for the placement of apologies and corrections.<?php footnoteRef('K',5,80); ?> According to Ms Fielden, publications are:<?php footnoteRef('K',5,81); ?>
<blockquote>&#8220;&#8230;still, even within this co-regulatory framework, burying publication of an adjudication on sort of page 54&#8221;.</blockquote> In her evidence she highlighted the different approach of publications towards &#8216;regulation&#8217; and noted the distinction between two media camps: those who are found in breach and are ordered to comply with adjudications by the Danish Press Council; and those who voluntarily choose to comply with regulation in order to benefit from the protections that membership of the Press Council offers.</p>
  <h4>Sweden</h4>
 <?php paragraphLink('K',5,2,14); ?>In Sweden, the press and press freedom are specifically protected by two of Sweden&#8217;s four constitutional laws. These function to protect the freedom of speech (Freedom of the Press Act 1991) and the freedom of the Swedish press (Freedom of the Press Act 1949). These freedoms apply to any individual who has registered for authorisation to publish and can include private individuals such as online bloggers. Both Acts guarantee a ban on censorship, the protection for anonymous sources and the right of public access to documents held by Swedish authorities.<?php footnoteRef('K',5,82); ?></p>
  <?php paragraphLink('K',5,2,15); ?>Press standards in Sweden are upheld through the Swedish Press Council. Membership is voluntary and not backed by legislation, unlike in Denmark. Newspapers and print publications are authorised to publish as members of either the Swedish Newspaper Publishers&#8217; Association, the Magazine Publishers&#8217; Association, the Swedish Union of Journalists, or the National Press Club. There are no restrictions on who can apply for a licence through the Swedish Press Council. These organisations collectively finance the system of self-regulation, and also set the Code of Ethics for the printed media (and broadcasting) in Sweden.</p>
  <?php paragraphLink('K',5,2,16); ?>In Sweden, the editor-in-chief of a print publication is legally responsible for all content published by that title and is answerable to the Press Council Board. There are a total of 18 members of the Press Council Board. In similar fashion to Denmark, the Chair and three Vice-Chairs are members of the Swedish Supreme Court. The remaining members are representatives from the four associations responsible for funding the Press Council, as well as three representatives of the general public who are without affiliation to the press. This composition of the Board is seen as a way of underpinning the independence of the system of self-regulation in a country that has historically esteemed the freedom of the press and sought to protect it in law.<?php footnoteRef('K',5,83); ?></p>
  <?php paragraphLink('K',5,2,17); ?>Sweden also operates a Press Ombudsman whose role is to investigate complaints, provide information and advice to the public and contribute to the development of press standards. Both the Press Council and the Ombudsman deal with the online versions of printed newspapers and magazines. The Press Ombudsman is the first point of contact for any complainant who has a personal interest in press misreporting or who has been directly affected by it. As such, third party complaints are not accepted by the Swedish Ombudsman. The Press Ombudsman does not act as a mediator but rather makes decisions on whether a complaint can be accepted and passed to the Council for adjudication. If the Press Ombudsman decides a complaint does not warrant formal criticism of the title in question, the complainant can appeal directly to the Press Council. There are also no restrictions to prevent a complainant from taking the grievance to court after it has been considered by the Press Ombudsman and the Press Council.</p>
  <?php paragraphLink('K',5,2,18); ?>The Press Ombudsman is appointed by a special committee which consists of the Chief Parliamentary Ombudsman, the Chair of the Swedish Bar Association and the Chair of the National Press Club. The length of time taken for an adjudication by the Press Council can be a further six or seven months after the Ombudsman has considered a submitted complaint (which can last itself three to four months). The remedy for such complaints is the right to reply or the publication of a correction.</p>
  <?php paragraphLink('K',5,2,19); ?>In contrast to the UK and Denmark, however, the Swedish Press Council operates a system whereby titles are expected to contribute towards costs after a breach of the code. Whereas only online operators in Denmark are ordered to pay a levy towards the funding of the Council if they are in breach of the code, in Sweden, anyone who breaches the code is required to pay a &#8216;penalty&#8217; towards the fund. It is estimated that this form of &#8216;polluter pays&#8217; policy contributes approximately 20% of the Press Council&#8217;s funding.<?php footnoteRef('K',5,84); ?></p>
  <h4>Finland</h4>
 <?php paragraphLink('K',5,2,20); ?>Finland&#8217;s printed press is regulated by The Council for Mass Media (CMM), established by publishers and journalists in 1968. It is the main body responsible for the self-regulation of Finland&#8217;s printed press and broadcasters. It is also the only self-regulatory system in the Scandinavian countries that encompasses all media platforms, including online journalism. Under Finnish Law, the freedom of speech is protected through the Exercise of Freedom of Expression in Mass Media Act 2003.<?php footnoteRef('K',5,85); ?> Through this Act, publications are obliged to provide a public right of reply as well as the duty to correct factual inaccuracies. In similar requirements to Sweden, each publication must nominate an editor who holds the responsibility for all the published content of that publication.</p>
  <?php paragraphLink('K',5,2,21); ?>The CMM is responsible for issuing Guidelines for Journalists, which establishes professional conduct guidelines across cross-media platforms. Membership to the CMM is voluntary, although it is perhaps noteworthy that journalists who have affiliated membership to the Council commit themselves to advancing and upholding the principles set out in the Guidelines for Journalists. Dr Riitta Ollila, a member of the CMM has argued that the Council:<?php footnoteRef('K',5,86); ?>
<blockquote>&#8220;&#8230;does not act as a mediator between editors and audience but as a master of the code making remarks on the press of their errors.&#8221; </blockquote>Although the CMM has no legal jurisdiction over the regulation of the press, its position overseeing journalistic standards is generally accepted. The CMM receives state funding from the Finnish Government equivalent to 30% of the Council&#8217;s budget.</p>
  <?php paragraphLink('K',5,2,22); ?>In contrast to Denmark, Sweden and indeed effective practice in the UK, the CMM is open to third party complainants. Complaints can be received from any member of public who considers that there has been a breach of good practice or violation of the Guidelines for Journalists. Any title or broadcaster found in breach of good practice is compelled by the CMM to publish a notice issued by the Council within a certain timeframe. Similarly to the PCC, the CMM will not rule on an issue or consider a complaint where legal action is being taken concurrently. The Council can only rule on complaints brought to the Council&#8217;s attention within three months of publication.</p>
  <?php paragraphLink('K',5,2,23); ?>The CMM is comprised of eight representatives of the industry and (including the Chair) four public members. Up until 2007, only a current or serving media professional could be appointed to Chair of the CMM. Changes have since been made which now allow a former editor to assume the post of Chair of the CMM. These adjustments might have been to improve the operation of the Council, given the rate at which respective Chairs of the CMM have resigned.<?php footnoteRef('K',5,87); ?></p>
  <?php paragraphLink('K',5,2,24); ?>The membership of Press Councils in Scandinavia has historically been high; it appears that this is largely due to the reputational benefits of membership and the accountability that is perceived to be afforded by membership of the relevant Council. This is also shown through the increasingly high rate of membership by online media outlets, and the online platforms of traditional media. In addition, it appears to be the case that, in the Scandinavian countries, there is a culture of commitment to (and indeed pride in) high journalistic standards. Therefore the question of membership, irrespective of the cost of that membership to an individual publication, is not an issue for consideration by media bodies in Scandinavia. As has been noted, the only exception is Denmark, where any publication that meets the criteria defined by the Media Liability Act, is subjected to compulsory regulation by the Danish Press Council.</p>
  <h3>Germany</h3>
 <?php paragraphLink('K',5,2,25); ?>It has been argued by some commentators that the German Press Council operates the purest form of press self-regulation in Europe. In Germany, the press are regulated only by the press and are only subject to restrictions within the German Basic Law ( Grundgesetz ). The Press Council was established in 1956 and consists of members from industry organisations and the press trade unions. The Council has 28 industry members and the Chairmanship of the Council rotates between the representatives of the different industry organisations. Press behaviour and standards are set out in the German Press Code, first developed by the Press Council in 1973, which provides guidelines under which journalists should operate. In 2009, the Press Council expanded their remit to include online newspapers. The Press Council relies on Government funding for its operations (although there is a stipulation that the funding should not exceed 49% of the Press Council&#8217;s total revenue).<?php footnoteRef('K',5,88); ?> Other than providing monetary support to the Council, the Government has no powers or influence over the day-to-day operations of the Council.</p>
  <?php paragraphLink('K',5,2,26); ?>Any member of the general public may make a complaint directly to the Council. Complainants do not have to waive their rights to initiate legal proceedings if they submit a complaint to the Press Council. If the Press Council Board supports a public complaint, then the newspaper in question is expected to publish the Press Council&#8217;s ruling. This public reprimand is a voluntary undertaking by the title in breach, rather than an order dictated by law or mandated as a condition of membership of the Council. Ms Fielden has noted that some 90% of German publishers have signed up to the voluntary undertaking, although one major publisher, the Bauer Media Group,<?php footnoteRef('K',5,89); ?> has not renewed its declaration.<?php footnoteRef('K',5,90); ?> Whilst the Press Council can request that these reprimands are published, as with the PCC, it cannot determine the prominence given to the publication of the decision.</p>
  <?php paragraphLink('K',5,2,27); ?>The authority of the German Press Council has not gone unchallenged, particularly in response to the publication of public reprimands. The newspaper Bild, the best-selling German tabloid, has questioned decisions made by the Press Council. By way of example, a published Press Council ruling on 29 November 2007 was printed by the paper in question not as an adjudication but, rather, as a criticism of that adjudication.<?php footnoteRef('K',5,91); ?> The problem of compliance is ongoing and has led to delays in the publication of apologies. This has led to the reputation of the German Press Council being discredited and has damaged the public perception of its general credibility as a self-regulating body.</p>
  <?php paragraphLink('K',5,2,28); ?>The approach of the German press is perhaps more aggressive than that in Scandinavia, although it may appear tame in comparison to standards in the UK. Its behaviour has been described best as a &#8220;balancing act&#8221;.<?php footnoteRef('K',5,92); ?> Significantly, there is a culture in the German press (notably absent from the UK press) of titles publicly holding each other to account. In this respect, Bildblog is an example of an online media watchdog, which was originally established to examine the coverage by the Bild newspaper.<?php footnoteRef('K',5,93); ?> Bild has also been criticised by its readers, notably for its coverage in 2010 of a number of deaths at a music festival in Duisburg.<?php footnoteRef('K',5,94); ?> The title was accused of exaggerating reports of the deaths and came under intense scrutiny from the public and industry members alike. The German Press Council received a large number of complaints from readers, via traditional methods such as letters to the editor, as well as micro-blogging through channels such as Twitter. It has been argued that this event, and the resultant response, has led journalists to reflect on their standards of reporting for the future.</p>
  <h3>France</h3>
 <?php paragraphLink('K',5,2,29); ?>The system of press regulation in France is different to the countries so far outlined. In place of a Press Council, the press in France are regulated by the existing body of French law. Trade unions and professional associations, such as the Syndicat National des Journalistes and the Association des Journalistes R&#233;publicains Francais, are responsible for maintaining standards of journalism across the printed press. As a consequence, the development of a code of standards applicable to the industry has been problematic. Instead, both the Unions and professional associations have encouraged the appointment of ombudsmen at some newspaper titles. The first appeared in 1994 at Le Monde, although this has not been popular across the majority of the printed press.</p>
  <?php paragraphLink('K',5,2,30); ?>The Direction du D&#233;partment des M&#233;dias et des Industries Culturelles,<?php footnoteRef('K',5,95); ?> is responsible for the development of Government policy in relation to the media and plurality. It is also responsible for providing financial support to parts of the media, most of which is directed towards the printed press.</p>
  <?php paragraphLink('K',5,2,31); ?>Efforts at creating a Press Council in France have been unsuccessful. The most recent attempt in 2006 led to the establishment of the Association de prefiguration d&#8217;un Conseil de press,<?php footnoteRef('K',5,96); ?> led by a group of French journalists, although it is unclear how far their efforts have led.<?php footnoteRef('K',5,97); ?> It is likely that this is a consequence of lack of industry support.</p>
  <?php paragraphLink('K',5,2,32); ?>The corollary to the informal systems of self-regulation in France is the application of civil and criminal law. Although the freedom of the press and the freedom of speech are both constitutional principles, uniquely in Europe, privacy laws, in particular Article 9 of the Civil Code,<?php footnoteRef('K',5,98); ?> are also applicable to the press. Intrusions into privacy, including the taking of photographs of individuals in a public place, are prohibited. Article 9 guarantees the protection of the citizen&#8217;s private life, from which the right to one&#8217;s image emanates. The Civil Code, however, is fluid in definition in relation to individuals who have a public profile and, in particular, those who hold public office. Under the constitutional guarantees of freedom of speech, French law allows for the publication of information on individuals in public office, as a consequence of their occupation or status. They are presumed to waive rights over the publication of their image, on condition that it is used to inform and not for commercial gain. In French civil law, an individual who feels that their image has been misused can request court action to prevent the attack (through detention, seizure of property, banning the publication, or public denunciation) or seek damages in compensation. In criminal law, invasion of one&#8217;s privacy is punishable by a prison term of up to 12 months and a fine of up to &#8364;45,000.</p>
  <?php paragraphLink('K',5,2,33); ?>Historically, the French press has been reluctant to publish stories on the private lives of individuals. Perhaps the most famous example of this phenomenon was the refusal of the French press to publish stories about the extramarital affairs of the former President, Fran&#231;ois Mitterrand. Suffice to say that nothing was printed about President Mitterrand&#8217;s second family, and it was only shortly before his death that the press revealed the facts. There has been a historical willingness to interpret privacy law broadly (and some may argue too broadly) and it has been argued that French privacy law is used to suppress information. However, increasingly French newspapers and, particularly, celebrity gossip magazines are challenging this traditional reluctance to publish content that may be regarded as private and such stories are increasingly the norm in France. The recent publication of the photographs of the Duchess of Cambridge may be part of this trend.<?php footnoteRef('K',5,99); ?></p>
  <h3>Netherlands</h3>
 <?php paragraphLink('K',5,2,34); ?>Freedom of speech is set out in Article 7 of the Constitution of the Netherlands. The Constitution also states that the Government has a duty to enable the media to freely exercise their profession without any form of undue influence or interference. This is realised through the Dutch Media Act 2008. Although the Act regulates only public broadcasters and cable operators in the Netherlands, it also ensures that newspapers and internet publications have rights to operate independently and free from Government interference.<?php footnoteRef('K',5,100); ?> <?php footnoteRef('K',5,101); ?></p>
  <?php paragraphLink('K',5,2,35); ?>The Netherlands has operated a system of self-regulation for the last 50 years. The Netherlands Union of Journalists founded the prototype of a Dutch Press Council in 1948; this functioned originally as a disciplinary body, before being reconstituted as the Raad van Tucht, the Netherlands Press Council (NPC), in 1960.<?php footnoteRef('K',5,102); ?> This Council describes journalism in the country as a completely free profession, where any individual can be considered a journalist and is not required to be professionally registered as such.</p>
  <?php paragraphLink('K',5,2,36); ?>The NPC does not accept third party complaints. Complaints are only accepted from those who have a direct interest and are affected by the issue and must also be related to a specific breach of the Code. It must concern the journalistic practice of either a professional journalist or someone who, on a regular basis and for remuneration, collaborates on the editorial content of a mass medium. The Council can only pass judgment and is unable to impose sanctions on titles in breach of appropriate journalistic practice. In the Netherlands, and much like the UK, a complainant&#8217;s route to seeking compensation is through civil litigation.</p>
  <?php paragraphLink('K',5,2,37); ?>The fundamental difference between the system of press self-regulation operated in the Netherlands through the NPC and the PCC lies in the prominence accorded to publication of adjudications against titles in breach of the Netherlands guidelines for journalism. The adjudication summaries published by the NPC name and shame journalists who have breached terms on accuracy, or have been found to have crossed the limits of what it is acceptable to publish. These adjudications are published in full on the Press Council&#8217;s website, as well as in the Dutch union of journalists&#8217; newspaper, which is widely read by people working in the industry. The decisions are also widely circulated through national news agencies and to other media organisations. This very public naming of titles in breach of the code is seen as a deterrent for poor journalistic behaviour.</p>
  <?php paragraphLink('K',5,2,38); ?>Although the NPC cannot force a title to publish a correction, the majority of the media will respect such a request from the Council and will comply. Some titles have decided not to publish the verdicts of complaints against them, such as De Telegraaf (the largest newspaper in the country) and NOVA, a current affairs programme on television, who announced that they would no longer cooperate with the NPC. Despite this, 80% of the NPC members have indicated that they would publish adjudications involving their titles.</p>
  <?php paragraphLink('K',5,2,39); ?>The Chair of the Dutch Press Council has historically been appointed from the Dutch Judiciary. The Chair is assisted by three Vice-Chairs, who are also drawn from the law. The remaining members of the Council comprise 13 industry members (including journalists) and 13 lay members.<?php footnoteRef('K',5,103); ?> In recent years, steps have been taken to improve the effectiveness of the Council, including an internal review of systems and functions. Changes have included the appointment of five &#8216;public members&#8217; drawn from the Dutch public at large.<?php footnoteRef('K',5,104); ?> In order to implement improvements, the NPC has applied for additional financial support from the Dutch Government and has pushed for the adoption of a similar funding mechanism to that used in Germany. The review of systems and functions conducted by the NPC also considered other self regulatory models, including the PCC.</p>
  <?php paragraphLink('K',5,2,40); ?>Before concluding this summary of the approach of other European countries, it is worth adding that, in her evidence, Ms Fielden observed that Press Councils in Europe are now making concerted efforts to prove to readers that they are concerned with maintaining standards. She gave the example of a judgment by the Swedish Press Council, which ordered the publication of a decision, which the newspaper title ran on the front page of its publication, as a way of setting the bar:<?php footnoteRef('K',5,105); ?></p>
<blockquote>&#8220;&#8230;a Swedish paper that had got something very wrong had been censured by the Press Council and ordered to publish the Press Council decision, off its own bat published it on the front page, and the reason it did that was to say, &#8216;This is our compact with you, the reader. We are different. We aspire to very high standards. When we get it wrong, we will tell you that we&#8217;ve got it wrong, very visibly so.&#8217;&#8221; </blockquote>
  <h3>The United States</h3>
 <?php paragraphLink('K',5,2,41); ?>In some countries there are no systems of press regulation. The prime and only statutory structure of the United States print newspaper industry is the First Amendment to the American Constitution, adopted in 1791.<?php footnoteRef('K',5,106); ?> The First Amendment to the Constitution reads:<?php footnoteRef('K',5,107); ?>
<blockquote>&#8220;Congress shall make no law respecting an establishment of religion, or prohibiting the free exercise thereof; or abridging the freedom of speech, or of the press; or the right of the people peaceably to assemble, and to petition the Government for a redress of grievances.&#8221; </blockquote>The First Amendment protects both the freedom of speech and the freedom of the press, although there remain certain statutory limitations relating to defamation and privacy,<?php footnoteRef('K',5,108); ?> as well as certain forms of state censorship, which exempt some areas of free speech from the protections of the First Amendment.<?php footnoteRef('K',5,109); ?></p>
  <?php paragraphLink('K',5,2,42); ?>By way of example, there are restrictions in both Federal and State law in relation to obscene images (which may be defined to cover material which would not be considered to offend obscenity laws in the UK); there is no equivalent to Page 3. Many US states seek to build on the existing Federal law and place restrictions on the possession, dissemination and sale of obscene material in public places, in particular those where minors may be present such as schools and libraries.</p>
  <?php paragraphLink('K',5,2,43); ?>The Federal Communications Commission (FCC) is responsible for the regulation of broadcasting across the fifty states and on an international scale.<?php footnoteRef('K',5,110); ?> The remit of the FCC does not, however, include the regulation of the print media.</p>
  <h3>China</h3>
 <?php paragraphLink('K',5,2,44); ?>Some witnesses have suggested that any introduction of statute in relation to press standards is tantamount to placing the press under state control. It may be of some benefit to turn very briefly to look at China and the regulation of print media in that country, if only to provide an example of the sort of statutory control of the press that gives rise to these concerns and identify the key features of that regulation to demonstrate how widely and dramatically it differs from the type of underpinning statute that has been proposed by witnesses to the Inquiry.</p>
  <?php paragraphLink('K',5,2,45); ?>Chinese publications are required under law to abide by a strict registration criteria as well as to undergo a process of continual government approval, exercised by the General Administration of Press and Publications (GAPP). Individual publications are held accountable to the government by official sponsors, defined as a &#8216;managing institution&#8217;, which must be an institution recognised by the Chinese Communist Party or the government.<?php footnoteRef('K',5,111); ?> The managing institution is responsible for the exercise of control over the publication and content published by it. Specifically, the managing institution should limit any negative coverage of the Chinese Government and the Chinese Communist Party. There are, by definition and in fact, no free or independent media outlets in China.</p>
  <?php paragraphLink('K',5,2,46); ?>The regulation of the Chinese media by the government is not limited only to the domestic market. Indeed, the Chinese Government seeks to control the content of Chinese language newspapers published abroad. The Epoch Times is a Chinese newspaper founded in 2000 operated from the UK; it provides an interesting perspective on the reach of Chinese press regulation.<?php footnoteRef('K',5,112); ?> Their submission to the Inquiry suggests that the influence of the Chinese Communist Party extends to the Chinese language print media in the UK and that this influence is exercised through the Chinese Embassy. They have said that the Embassy seeks to influence media outlets targeted at the Chinese community and has sought to discourage its circulation. The Director of the English edition, Sek Halu, has suggested that a number of retailers and supermarkets have refused to stock the Epoch Times because of its critical view of the CCP.<?php footnoteRef('K',5,113); ?></p>
  <?php sectionAnchor('K',5,3); ?>Reviews of press regulation: Australia and New Zealand</h2>
 <?php paragraphLink('K',5,3,1); ?>The development of new media and, in particular, the convergence of delivery platforms for content, has challenged existing models of press regulation, causing some regulators to review the extant regulatory frameworks to consider how best to respond to this changing environment and how new forms of content delivery might be incorporated into existing regulatory structures.</p>
  <?php paragraphLink('K',5,3,2); ?>In Australia, the structures and functions of the existing Australian Press Council have recently been considered as part of a wider review of press standards, in the context of the Independent Media Inquiry, otherwise known as the Finkelstein Inquiry. The Finkelstein Inquiry has fed into the wider Convergence Review, being conducted by the Australian Government, of regulation across media platforms in Australia and broader media policy. In New Zealand, the Law Commission has looked specifically at the privileges and benefits accorded to traditional media and have considered how these might be applied to new media.</p>
  <h3>Australian Independent Media Inquiry: the Finkelstein Report</h3>
 <?php paragraphLink('K',5,3,3); ?>The Independent Media Inquiry was established by the Australian Government on 14 September 2011. A former Justice of the Federal Court of Australia, Mr Ray Finkelstein QC, was appointed to conduct the Inquiry. The Independent Media Inquiry invited submissions from any person with an interest in the issue and held public hearings in Melbourne, Sydney and Perth during November and December 2011. In parallel to these hearings, the Chair of the Inquiry also invited selected individuals, organisations, trade associations and other interested parties to make formal submissions. Responses were received from a range of parties, including serving editors of Australia&#8217;s major media outlets, former editors with experience of the news media industry, the current Chair of the Australian Press Council (as well as former Chairs), and academics specialising in media and regulation.</p>
  <?php paragraphLink('K',5,3,4); ?>The timing of the Independent Media Inquiry has overlapped with the establishment of this Inquiry. Although the former was not set up in response to any allegations of wrongdoing at News Limited (the Australian subsidiary of News Corp), or to investigate any press misconduct, it was nevertheless indirectly provoked by the allegations of phone hacking and corrupt payments at News International that led to this Inquiry.<?php footnoteRef('K',5,114); ?></p>
  <?php paragraphLink('K',5,3,5); ?>The Terms of Reference for the Independent Media Inquiry focussed on the efficacy of existing codes of conduct governing media practice in Australia, particularly the likely impact on these of the growing convergence of print media and digital and online platforms. Mr Finkelstein was also required to investigate:<?php footnoteRef('K',5,115); ?></p>
<blockquote>&#8220;The impact of this technological change on the business model that has supported the investment by traditional media organisations in quality journalism and the production of news, and how such activities can be supported, and diversity enhanced, in the changed media environment; ways of substantially strengthening the independence and effectiveness of the Australian Press Council, including in relation to online publications, and with particular reference to the handling of complaints; and any related issues pertaining to the ability of the media to operate according to regulations and codes of practice, and in the public interest.&#8221; </blockquote>
  <?php paragraphLink('K',5,3,6); ?>The Independent Media Inquiry concluded its review and reported to the Australian Government on 28 February 2012. Mr Finkelstein recommended that the current Australian Press Council (APC) should be replaced by an independent body, the News Media Council (NMC).<?php footnoteRef('K',5,116); ?> The role of the NMC would be to ensure that Australian news media operated in a more accountable manner to those who were the subject of press reporting, as well as to the general public at large. To enable the NMC to exercise this function, Mr Finkelstein argued that the NMC should have strengthened remedial powers to deal with complaints about the press. These proposed powers would be significantly greater than those available to the existing APC. Mr Finkelstein also proposed that the NMC should have powers to enforce a right of reply, the withdrawal of an article from further circulation, and the publication of apologies and Council adjudications (including the ability to control the size and prominence of these publications). These remedial powers are, according to Mr Finkelstein, necessary to preserve the integrity of the press.</p>
  <?php paragraphLink('K',5,3,7); ?>The NMC would also be responsible for setting journalistic standards, in consultation with the industry, and to handle complaints across all media platforms (specifically print, online, radio and television). Mr Finkelstein proposed a greater level of funding from the Government for the body which would replace the current levy system. He argued that this would remove a current burden on the print industry but would also address the issue of the independence of the NMC from the industry.</p>
  <?php paragraphLink('K',5,3,8); ?>Perhaps more significantly, and indeed a change of greater significance, Mr Finkelstein also proposed that a legal requirement should be established to grant powers to the NMC to take legal action against any media outlet that refused to comply with the requirements set by the NMC. By way of example, if a publication refused to publish an adjudication issued by the NMC, the Council or the complainant would have the right to apply for a court order compelling compliance from the publication. Any failure by the publication to comply with the court order would be subject to existing legal processes. It is this particular aspect of Mr Finkelstein&#8217;s proposals that has been the subject of considerable and heated media criticism.</p>
  <?php paragraphLink('K',5,3,9); ?>In his concluding remarks, Mr Finkelstein drew comparisons between his review and this Inquiry. He acknowledged that, although the Independent Media Inquiry was not established in response to phone hacking in Australia, they shared the historical experience of a Press Council that had limited powers as a self-regulatory body and was unable to fully bring the press to account in the public eye. Mr Finkelstein has also speculated, in relation to this Inquiry, that:<?php footnoteRef('K',5,117); ?></p>
<blockquote>&#8220;Looking at the matter from afar, it would not be surprising if statutory regulation were top of the list.&#8221; </blockquote>
  <h4>Public and Industry Response to the Finkelstein Report</h4>
 <?php paragraphLink('K',5,3,10); ?>It would be an understatement to observe that Mr Finkelstein&#8217;s recommendations have not gone unchallenged by the Australian press. Rather, the Report has led to a wide-ranging and, at times, heated debate as to the nature of press freedom in Australia.<?php footnoteRef('K',5,118); ?> News Limited&#8217;s Chief Executive, Kim Williams, called the Independent Media Inquiry&#8217;s report &#8220;too draconian&#8221; and argued that there was little value in replacing the existing Australian Press Council (APC) with the NMC as proposed by Mr Finkelstein.<?php footnoteRef('K',5,119); ?> Mr Williams went further and, speaking at the Pacific Area Newspaper Publishers&#8217; Association forum in Sydney, suggested that the Independent Media Inquiry was established by the minority Australian Labor Party Government primarily to attack News Limited, as a direct response to the coverage the Government was receiving in his company&#8217;s newspapers.<?php footnoteRef('K',5,120); ?></p>
  <?php paragraphLink('K',5,3,11); ?>Bob Cronin, group editor-in-chief of West Australian Newspapers, also expressed his opposition to Mr Finkelstein&#8217;s proposals. He heavily criticised the element of increased oversight of the new Council, as well as the powers of a Government-appointed regulator to control what the media was able to publish. He argued that the proposals were:<?php footnoteRef('K',5,121); ?></p>
<blockquote>&#8220;&#8230;the most outrageous assault on our democracy in the history of the media.&#8221; </blockquote>
  <?php paragraphLink('K',5,3,12); ?>A different perspective was provided by the Chair of the current APC, Professor Julian Disney, who has continued to argue for the improvement of resources available to the APC to ensure that it was able to fulfil its complaints-handling responsibilities. He stated that:<?php footnoteRef('K',5,122); ?></p>
<blockquote>&#8220;&#8230;resources are hopelessly inadequate and they were even before our number of complaints doubled so it is really just to carry out the responsibilities that we are meant to have and that people expect us to do.&#8221; </blockquote>
  <?php paragraphLink('K',5,3,13); ?>In this respect, Professor Disney agreed with many of the central recommendations of Mr Finkelstein&#8217;s report which, he suggested, clearly identified the fundamental flaws in the current system of complaints handling through the APC. However, Professor Disney has strongly disagreed with the two particular elements of Mr Finkelstein&#8217;s proposals.<?php footnoteRef('K',5,123); ?> He also drew attention to the absence of any coverage by local newspapers of the APC&#8217;s opinions of Mr Finkelstein&#8217;s report.<?php footnoteRef('K',5,124); ?> He stated that no Sydney or Melbourne paper had reported the views of the APC, despite the body being the main focus of the report, or their response to the proposals. He argued that this was a striking example of the lack of balanced coverage that existed in the Australian press.</p>
  <?php paragraphLink('K',5,3,14); ?>Some commentators have chosen not to focus on the detail of the proposals but have instead considered how the recommendations might be applied in practice, particularly as that Mr Finkelstein concluded the NMC should not be established by statute. Echoing the views of a number of Australian commentators, the former financial journalist Jim Parker, who currently writes for the respected Australian media blog, The Failed Estate,125 argued that, without a statutory backdrop, the powers of the proposed NMC would be without effect.126 </p>
  <h3>Australian Convergence Review</h3>
 <?php paragraphLink('K',5,3,15); ?>The Convergence Review was established in early 2011 by the Australian Government to examine the current system of media regulation in the light of the challenges posed by the conversion of services and the proliferation of media platforms. Specifically, the Convergence Review sought to establish whether a single model could be applied across the media.</p>
  <?php paragraphLink('K',5,3,16); ?>This review was led by the Convergence Review Committee, chaired by Glen Boreham, former Managing Director of IBM Australia and New Zealand.<?php footnoteRef('K',5,127); ?> The Committee was also tasked with looking at how the recommendations of Mr Finkelstein&#8217;s Independent Media Inquiry might be incorporated into media regulation.<?php footnoteRef('K',5,128); ?> The Committee reported to the Minister for Broadband, Communications and the Digital Economy, Senator Stephen Conroy, on 30 March 2012.</p>
  <?php paragraphLink('K',5,3,17); ?>The Convergence Review Committee recommended that any media title, regardless of the platform on which their content was delivered, should be subjected to certain restrictions by a single regulator.<?php footnoteRef('K',5,129); ?> In this respect, the Committee proposed that the licensing of broadcasting services should cease, and the regulation of the media should be undertaken by a single statutory body which would replace the existing Australian Communications and Media Authority (ACMA). The new regulator would be responsible for any media enterprise, across all platforms, defined as &#8216;content service enterprises&#8217;; this means organisations that:<?php footnoteRef('K',5,130); ?></p>
<blockquote>&#8220;&#8230;have control over the professional content they deliver; have a large number of Australian users of that content; and have a high level of revenue derived from supply that professional content to Australians.&#8221; </blockquote>
  <?php paragraphLink('K',5,3,18); ?>In this regard, the Convergence Review recommended that thresholds should be defined in relation to the annual revenue of a concern, as well as the number of readers (or &#8216;hits&#8217;) any media title attracts within the Australian market.<?php footnoteRef('K',5,131); ?> By setting these thresholds, Australia&#8217;s 15 largest media companies would be subject to regulation by the new body. Ms Fielden noted in her evidence to the Inquiry that online operator, Google, would be exempt from this definition, despite the company&#8217;s reach within the Australian media market. This was due to the stipulation that saw Google&#8217;s revenue understood in terms of professionally produced material, rather than as a content service enterprise.<?php footnoteRef('K',5,132); ?></p>
  <?php paragraphLink('K',5,3,19); ?>The Committee&#8217;s proposals did not, however, take forward the recommendation of the Independent Media Inquiry to establish the new News Media Council. Rather, it proposed an industry-led body for maintaining news standards across all media and communications, in the stead of the Government-appointed regulator proposed by Mr Finkelstein. This was in addition to the recommendation for a statutory regulator to replace the ACMA.</p>
  <?php paragraphLink('K',5,3,20); ?>At the time of writing, the Australian Government was still considering the recommendations of both Committees. However, whatever the eventual Government response, it will no doubt alter the regulatory landscape of Australia in relation to the convergence of print, broadcast and online media.</p>
  <h4>Public and Industry Response to the Convergence Review</h4>
 <?php paragraphLink('K',5,3,21); ?>There has been a mixed response from the industry to the recommendations of the Convergence Review. Although these recommendations have not generated the same levels of controversy and debate as those put forward by Mr Finkelstein, a number of commentators saw the proposals as part of a continued, and in some cases deliberate, erosion of the freedom of the press.<?php footnoteRef('K',5,133); ?> In her evidence, Ms Fielden drew the attention of the Inquiry to the response of some parts of the Australian press, which have argued that the Convergence Review was purposefully established in order to regulate the fifteen companies which would fall under the definition of &#8216;content service enterprises&#8217;, and has been otherwise unconcerned with other areas of media regulation that ought to have been considered more fully by the review. Ms Fielden disputed the validity of this assessment of the Convergence Review.<?php footnoteRef('K',5,134); ?></p>
  <?php paragraphLink('K',5,3,22); ?>Ms Fielden also told the Inquiry of the recent changes implemented to improve the function and practice of the Australian Press Council (APC), introduced in response both to the Convergence Review and the allegations of wrongdoing, in particular the allegations of phone hacking that led to the establishment of this Inquiry. She said that the Council had actively responded to the calls for reform of press regulation, and had proactively sought to consult the Australian public in order to determine how best to hold the press to account. This had led the APC consciously to shift its focus of activity to the maintenance and improvement of press standards, ensuring the fair balance of the Journalists&#8217; Code and the mediation of complaints. The APC had appointed an advisory board tasked with monitoring the coverage by news media of issues which were likely to give rise to a substantial number of complaints.<?php footnoteRef('K',5,135); ?></p>
  <h3>New Zealand Law Commission Review</h3>
 <?php paragraphLink('K',5,3,23); ?>The New Zealand Law Commission Review examined the legal and regulatory environment in which the media operated in New Zealand and, specifically, the privileges that existed for print media and whether these should be extended to their online equivalents. Such privileges included legal rights to the protection of sources and others relating to court proceedings. The Review tried to set a framework which defined who should benefit from these privileges and how. The Terms of Reference were to examine the following questions:<?php footnoteRef('K',5,136); ?></p>
<blockquote>&#8220;how to define &#8216;news media&#8217; for the purposes of the law; whether, and to what extent, the jurisdiction of the Broadcasting Standards Authority and/or the Press Council should be extended to cover currently unregulated news media and, if so, what legislative changes would be required to achieve this end, and; whether the existing criminal and civil remedies for wrongs such as defamation, harassment, breach of confidence and privacy are effective in the new media environment and, if not, whether alternative remedies may be available.&#8221; </blockquote>
  <?php paragraphLink('K',5,3,24); ?>The New Zealand Law Commission provided a list of preliminary proposals, published in December 2011, and has since invited submissions in relation to these proposals. The proposals included the suggestion for a statutory definition of &#8216;news media&#8217; (to include new media), specifically for the purposes of defining which publications should be entitled to the rights of the legal privileges and exemptions. The Review also proposed the establishment of a new independent regulator, responsible for all news media, regardless of the format or delivery platform. In relation to the existing civil remedies for victims of mistreatment by the press or other media, the Review proposed the creation of a Communications Tribunal, which would handle complaints in the context of the changing publishing environment.</p>
  <?php paragraphLink('K',5,3,25); ?>The Law Commission&#8217;s preliminary Report was published to encourage wider public debate, as well as to generate feedback on the scale and scope of initial solutions. By way of example, the Law Commission produced two options, for consideration by the public and stakeholders, as to whether membership of the new body should be enforced by statute or remain voluntary. The consultation period ran from December 2011 to March 2012.<?php footnoteRef('K',5,137); ?> The paper and accompanying proposals are currently being considered by the New Zealand Government which, similarly to the Australian Convergence Review, is due to report in Autumn 2012.<?php footnoteRef('K',5,138); ?></p>
  <h3>Concluding remarks</h3>
 <?php paragraphLink('K',5,3,26); ?>The alternative models of press regulation, as well as the other recent international reviews, have provided helpful examples of the different possible solutions for this Inquiry to consider. It is possible, however, to argue that there has been no compelling evidence to demonstrate that any of these models, or combinations of them, would function better than any others.</p>
  <?php paragraphLink('K',5,3,27); ?>It is clear, however, that all the structures considered in this Chapter are embedded in the social, cultural and historical functions of the media in each country, and are not necessarily ideal structures to apply to the UK. It is also worth noting how many countries are currently considering the impact of the evolution of digital platforms, as we have seen in Scandinavia and further afield in Australia and New Zealand. This development of online media content, as well as methods of delivery, has brought the regulation of print media into a whole new context. Although some of the practices revealed by the Inquiry may not be faced by other countries, the overarching questions being addressed are not unique; but neither is it possible to pretend that any other system, inquiry or review has successfully developed an ideal solution to the problems being faced.</p>
  </div>

