<!-- Footnotes-->
<div id="footnotes"> <?php footNote('K',7,1); ?> <?php internalChapterLink('../../','F',2); ?></p>
 <?php footNote('K',7,2); ?> journalists from News International, Trinity Mirror and Express Group: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Third-Witness-Statement-of-DAC-Sue-Akers.pdf">Third-Witness-Statement-of-DAC-Sue-Akers.pdf</a></p>
 <?php footNote('K',7,3); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('K',7,4); ?> <?php internalChapterLink('../../','J',4); ?></p>
 <?php footNote('K',7,5); ?> p13, para 1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Lord-Black-of-Brentwood1.pdf">Submission-by-Lord-Black-of-Brentwood1.pdf</a></p>
 <?php footNote('K',7,6); ?> <?php internalChapterLink('../../','K',2); ?></p>
 <?php footNote('K',7,7); ?> <?php internalChapterLink('../../','K',3); ?></p>
 <?php footNote('K',7,8); ?> <?php internalChapterLink('../../','K',4); ?></p>
 <?php footNote('K',7,9); ?> p60, lines 1-25 and p60 lines 1-2, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('K',7,10); ?> p81, lines 21-25, Nick Clegg, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-13-June-2012.pdf">Transcript-of-Morning-Hearing-13-June-2012.pdf</a></p>
 <?php footNote('K',7,11); ?> p4, para 1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-Ed-Miliband.pdf">Witness-Statement-of-Ed-Miliband.pdf</a></p>
 <?php footNote('K',7,12); ?> para 179, report of Joint Committee on Privacy and Injunctions http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf</p>
 <?php footNote('K',7,13); ?> p1, para 7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Joint-Submission-by-Core-Participant-Victims1.pdf">Joint-Submission-by-Core-Participant-Victims1.pdf</a></p>
 <?php footNote('K',7,14); ?> pp 1-2, lines 14-14, Lord Hunt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Morning-Hearing-10-July-2012.pdf">Transcript-of-Morning-Hearing-10-July-2012.pdf</a></p>
 <?php footNote('K',7,15); ?> p3, lines 11-15, Lord Hunt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Morning-Hearing-10-July-2012.pdf">Transcript-of-Morning-Hearing-10-July-2012.pdf</a></p>
 <?php footNote('K',7,16); ?> p11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Sir-Christopher-Meyer.pdf">Witness-Statement-of-Sir-Christopher-Meyer.pdf</a></p>
 <?php footNote('K',7,17); ?> p9, Speech by Lord Judge, Lord Chief Justice of England and Wales 19/10/2011 http://www.judiciary.gov.uk/Resources/JCO/Documents/Speeches/lcj-speech-annual-justice-lecture-2011.pdf</p>
 <?php footNote('K',7,18); ?> Paul Dacre, The future for self regulation? Seminar 12 October 2011, p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/RPC_DOCS1-12374597-v1-PAUL_DACRE_S_SEMINAR_SPEECH.pdf">RPC_DOCS1-12374597-v1-PAUL_DACRE_S_SEMINAR_SPEECH.pdf</a></p>
 <?php footNote('K',7,19); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Submission-by-Paul-Dacre1.pdf">Submission-by-Paul-Dacre1.pdf</a></p>
 <?php footNote('K',7,20); ?> p42, lines 4-8, Viscount Rothermere, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-10-May-2012.pdf">Transcript-of-Morning-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('K',7,21); ?> p44, lines 19-21, Evgeny Lebedev, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-23-April-2012.pdf">Transcript-of-Afternoon-Hearing-23-April-2012.pdf</a></p>
 <?php footNote('K',7,22); ?> p106, line 18, Aidan Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-23-April-2012.pdf">Transcript-of-Afternoon-Hearing-23-April-2012.pdf</a></p>
 <?php footNote('K',7,23); ?> p70, lines 1-3, James Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-24-April-2012.pdf">Transcript-of-Afternoon-Hearing-24-April-2012.pdf</a></p>
 <?php footNote('K',7,24); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/10/Submission-from-Kenneth-Clarke-MP.pdf">Submission-from-Kenneth-Clarke-MP.pdf</a></p>
 <?php footNote('K',7,25); ?> p2, <em>ibid</em></p>
 <?php footNote('K',7,26); ?> pp51-73, Michael Gove, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-29-May-2012.pdf">Transcript-of-Afternoon-Hearing-29-May-2012.pdf</a></p>
 <?php footNote('K',7,27); ?> p63, lines 13-20, David Cameron <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('K',7,28); ?> p81, lines 19-21, Nick Clegg, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-13-June-2012.pdf">Transcript-of-Morning-Hearing-13-June-2012.pdf</a></p>
 <?php footNote('K',7,29); ?> p82, lines 12-22, Nick Clegg, <em>ibid</em></p>
 <?php footNote('K',7,30); ?> p4, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Submission-by-Harriet-Harman-QC-MP-on-behalf-of-the-Labour-Party1.pdf">Submission-by-Harriet-Harman-QC-MP-on-behalf-of-the-Labour-Party1.pdf</a></p>
 <?php footNote('K',7,31); ?> para 187, report of Joint Committee on Privacy and Injunctions http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf. This may fall foul of what might be described as an entirely legitimate requirement ofthe press that any regulation must be independent of politicians (and the Government) whom the press are requiredto hold to account</p>
 <?php footNote('K',7,32); ?> para 188, report of Joint Committee on Privacy and Injunctions http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf</p>
 <?php footNote('K',7,33); ?> para 180, <em>ibid</em></p>
 <?php footNote('K',7,34); ?> p2, para 8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Joint-Submission-by-Core-Participant-Victims1.pdf">Joint-Submission-by-Core-Participant-Victims1.pdf</a></p>
 <?php footNote('K',7,35); ?> p11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Sir-Christopher-Meyer.pdf">Witness-Statement-of-Sir-Christopher-Meyer.pdf</a></p>
 <?php footNote('K',7,36); ?> p40, lines 5-9, Evgeny Lebedev, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-23-April-2012.pdf">Transcript-of-Afternoon-Hearing-23-April-2012.pdf</a></p>
 <?php footNote('K',7,37); ?> p107, lines 4-9, Aidan Barclay, <em>ibid</em></p>
 <?php footNote('K',7,38); ?> p107, lines 9-10, Aidan Barclay, <em>ibid</em></p>
 <?php footNote('K',7,39); ?> p69, lines 15-21, James Murdoch <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-24-April-2012.pdf">Transcript-of-Afternoon-Hearing-24-April-2012.pdf</a></p>
 <?php footNote('K',7,40); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/10/Submission-from-Kenneth-Clarke-MP.pdf">Submission-from-Kenneth-Clarke-MP.pdf</a></p>
 <?php footNote('K',7,41); ?> <?php internalChapterLink('../../','K',4); ?></p>
 <?php footNote('K',7,42); ?> <?php internalChapterLink('../../','D',1); ?></p>
 <?php footNote('K',7,43); ?> Carnegie Trust Voicing the Public Interest: Listening to the public on press regulation http://www.carnegieuktrust.org.uk/getattachment/8f98195f-4b95-4f0f-aa52-dd79cd3b5177/Voicing-the-Public-Interest.aspx?type=Finjan-Download&slot=000000F1&id=000008F0&location=0A64020EYouGov poll for Hacked Off: http://d25d2506sfb94s.cloudfront.net/cumulus_uploads/document/zbsbfp8gnb/Hacked%20Off%20results%20121005.pdf</p>
 <?php footNote('K',7,44); ?> I have been particularly interested in the informal advice of the relevant expert Assessors in framing and  draftingthe detail of the recommendations set out in this Chapter. All the relevant Assessors have clearly advised that thesystem I am recommending, organised by the industry to objective standards, delivers the independent regulationwhich is essential; it safeguards press freedoms, will not chill investigative journalism that is in the public interest, andcan command public confidence. It is their unanimous advice that it is in the interests of both the industry and theGovernment to accept and implement the recommendations to that end. For completeness, I have recorded one pointof detail, relating to how an industry body is recognised, on which Shami Chakrabarti gave me different advice: seepara 6.23 and footnote 56. As for the matters addressed in the next Chapter, two of the Assessors (Elinor Goodmanand George Jones) advised that it was not necessary for me to make a recommendation about what to do in the eventof the press not accepting the preferred option as they believe that independent self-regulation is the best solutionand that, if the industry considers it carefully, it too will agree. I also record that Shami Chakrabarti advised against thecontemplation of any element of compulsory backstop standards regulation of the press in the event of the inability orunwillingness of the press to implement the recommendations in this Chapter; she would prefer in that event to seea strengthening of the financial assistance available to those who feel their rights have been abused by the press inorder to help them defend those rights in court.</p>
 <?php footNote('K',7,45); ?> p21, para 28, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Lord-Black-of-Brentwood1.pdf">Submission-by-Lord-Black-of-Brentwood1.pdf</a></p>
 <?php footNote('K',7,46); ?> p89, lines 10-14, Professor Baroness O&#8217;Neil, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Afternoon-Hearing-16-July-2012.pdf">Transcript-of-Afternoon-Hearing-16-July-2012.pdf</a></p>
 <?php footNote('K',7,47); ?> This is equally apparent from an analysis of the evidence quoted at 3.1-3.13 above</p>
 <?php footNote('K',7,48); ?> These are the amounts suggested by Lord Black in his proposal, p12, paras 2.1-2,2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Lord-Black-of-Brentwood-Annex-C1.pdf">Lord-Black-of-Brentwood-Annex-C1.pdf</a>. There is some disagreement in the industryabout whether these limits are equitable and reasonable: in setting up the regulator, that would be an issue that would have to be addressed.</p>
 <?php footNote('K',7,49); ?> <?php internalChapterLink('../../','J',3); ?></p>
 <?php footNote('K',7,50); ?> <?php internalChapterLink('../../','K',4); ?></p>
 <?php footNote('K',7,51); ?> <?php internalChapterLink('../../','K',4); ?></p>
 <?php footNote('K',7,52); ?> <?php internalChapterLink('../../','H',6); ?></p>
 <?php footNote('K',7,53); ?> This approach to costs is discussed further in connection with the civil law: see <?php internalChapterLink('../../','J',3); ?></p>
 <?php footNote('K',7,54); ?> <?php internalChapterLink('../../','I',3); ?></p>
 <?php footNote('K',7,55); ?> s3 Communications Act 2003 http://www.legislation.gov.uk/ukpga/2003/21/section/3</p>
 <?php footNote('K',7,56); ?> Shami Chakrabarti has advised that she prefers this role to be fulfilled by the court but I do not see how the  court,of its own motion, could adopt an adjudicative role in relation to certification or subsequent review. Somebody wouldhave to be prepared to challenge either the extent to which the new body fulfilled the requirements of the legislationor the proposition that it should continue to do so. If that was Ofcom, and Ofcom raised no objection, there would benothing upon which the court could adjudicate. Thus, the decision would become whether Ofcom was satisfied. A verysimilar role would be available to the court if there was an appeal from an adverse decision of Ofcom (which couldallow a merits challenge rather than be limited to the more restrictive justification for intervention that is provided by judicial review.</p>
 <?php footNote('K',7,57); ?> This language is not prescriptive and neither do I intend to be prescriptive about the identity of the Secretary ofState given primacy in this area. The draft is taken from a submission to the Inquiry by the Media Regulation Round Table: see <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Media-Regulation-Round-Table.pdf">Submission-by-Media-Regulation-Round-Table.pdf</a> </p>
 <?php footNote('K',7,58); ?> See <?php internalChapterLink('../../','K',7); ?></p>
 <?php footNote('K',7,59); ?> See <?php internalChapterLink('../../','K',7); ?></p>
 </div>
