<!-- Footnotes-->
<div id="footnotes"> <?php footNote('J',3,1); ?> Appendix 4 and the Report of the Committee on Super-Injunctions chaired by Lord Neuberger MR: http://www.judiciary.gov.uk/Resources/JCO/Documents/Reports/super-injunction-report-20052011.pdf</p>
 <?php footNote('J',3,2); ?> s15(2) of the County Courts Act 1984. The High Court can transfer proceedings to the county court pursuant to s40(2)of the Act</p>
 <?php footNote('J',3,3); ?> A good example of this legal ingenuity provided one of the sparks that has generated this Inquiry. In an attempt tolearn whether she had been a victim of phone hacking, in July 2009, Sienna Miller issued proceedings against the MPSseeking disclosure of any material in its possession that provided evidence that she could use to deploy against NI:see <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Sienna-Miller.pdf">Witness-Statement-of-Sienna-Miller.pdf</a>. Herlawyers placed reliance on the decision in Norwich Pharmacal Co v. Customs and Excise Commissioners [1974] AC 133, obtained the order and the evidence. Many others have since followed suit.</p>
 <?php footNote('J',3,4); ?> http://webarchive.nationalarchives.gov.uk/+/http://www.justice.gov.uk/consultations/controlling-costs-in-defamation-proceedings.htm</p>
 <?php footNote('J',3,5); ?> http://www.parliament.uk/deposits/depositedpapers/2010/DEP2010-1241.pdf</p>
 <?php footNote('J',3,6); ?> Vol 1 is at http://www.judiciary.gov.uk/NR/rdonlyres/D2C93C92-1CA6-48FC-86BD-99DDF4796377/0/jacksonvol1low.pdf and vol 2 at http://www.judiciary.gov.uk/NR/rdonlyres/642936FA-292D-4432-8CF2-B2A44C7FC4FB/0/jacksonvol2low.pdf</p>
 <?php footNote('J',3,7); ?> Jackson LJ noted the &#8216;notional&#8217; ceiling on general damages awarded in defamation in the region of &#163;215,000 to&#163;250,000 (see Gur v. Avrupa Newspaper Ltd [2008] EWCA Civ 594; Tierney v News Group Newspapers Ltd [2006] EWHC  3275 para 10. In the final report he explained that the reason for this apparent limit is that &#8220;it is abhorrent if a claimant  with serious personal injuries is treated less generously by the courts than a defamation claimant who (although  distressed) remains fit and well&#8221; </p>
 <?php footNote('J',3,8); ?> [2005] UKHL 61 at para 31</p>
 <?php footNote('J',3,9); ?> In a speech to the Society of Editors in November 2008</p>
 <?php footNote('J',3,10); ?> <?php internalChapterLink('../../','F',7); ?></p>
 <?php footNote('J',3,11); ?> http://www.judiciary.gov.uk/NR/rdonlyres/8EB9F3F3-9C4A-4139-8A93-56F09672EB6A/0/jacksonfinalreport140110.pdf</p>
 <?php footNote('J',3,12); ?> This argument subsequently prevailed in the European Court of Human Rights following further litigation relating  toNaomi Campbell when the Court ruled that the recovery of success fees at the level sought by lawyers in privacy anddefamation cases represents a significant violation of freedom of expression. In that case, the figures were startling:Ms Campbell was awarded &#163;3,500 in damages after the House of Lords ruled her right to privacy had been breachedby a front-page story revealing her attendance at Narcotics Anonymous. Her legal costs came to more than &#163;1m,including &#163;288,468 base costs, &#163;279,981.35 in success fees and &#163;26,020 disbursements: see MGN v. United Kingdom  (Application 39401/04) </p>
 <?php footNote('J',3,13); ?> Chapter 32, para 3.4</p>
 <?php footNote('J',3,14); ?> <em> Rookes v Barnard</em> [1964] AC 1129</p>
 <?php footNote('J',3,15); ?> The reasons that Eady J gave were the absence of existing authority and concern about whether such a claim inrelation to the misuse of private information satisfied the twin tests of necessity and proportionality in Art. 10 of theECHR: see [2008] EWHC 1777, [2008] EMLR 20 at paras 172-197</p>
 <?php footNote('J',3,16); ?> The settlements that News International have agreed with a large number of those who have litigated in relation tophone hacking cannot be assumed to represent the sums that the court would have awarded</p>
 <?php footNote('J',3,17); ?> Numerous examples were provided by the evidence both of victims and solicitors acting in these cases: p10,lines 2-11, Sally Dowler, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-  Hearing-21-November-2011.pdf">Transcript-of-Morning-  Hearing-21-November-2011.pdf</a>; p39, line 15, Christopher Jefferies, http://www.levesoninquiry.org.uk/wp-content/  uploads/2011/11/Transcript-of-Morning-Hearing-28-November-2011.pdf; pp92-97, lines 21-5, Mark Lewis, http://  www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-23-November-20111.  pdf; p44, line 20, Gerry McCann, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-  Afternoon-Hearing-23-November-2011.pdf">Transcript-of-  Afternoon-Hearing-23-November-2011.pdf</a>; para 39: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/  Submission-on-behalf-of-Neil-Morrissey.pdf">  Submission-on-behalf-of-Neil-Morrissey.pdf</a>. In addition, when making submissions to Lord Justice Jackson, almost all  claimant firms placed great importance on the role of CFAs in offering non-wealthy claimants access to justice </p>
 <?php footNote('J',3,18); ?> http://www.publications.parliament.uk/pa/jt201012/jtselect/jtdefam/203/20302.htm</p>
 <?php footNote('J',3,19); ?> http://www.justice.gov.uk/downloads/publications/policy/moj/Government-response-draft-defamation-bill.pdf</p>
 <?php footNote('J',3,20); ?> [2012] EWCA Civ 1039; http://www.bailii.org/ew/cases/EWCA/Civ/2012/1039.html</p>
 <?php footNote('J',3,21); ?> [2012] EWCA Civ 1288; http://www.bailii.org/ew/cases/EWCA/Civ/2012/1288.html</p>
 <?php footNote('J',3,22); ?> <?php internalChapterLink('../../','K',7); ?>. As part of the response to encouragement by the Joint Committee to promote a voluntary, media-orientated forum for dispute resolution, the Government recognised that there could well be value in there being arange of arbitration options available, noting that methods of redress and the type of body required to secure effectiveregulation were issues which are central to this Inquiry: see para 68</p>
 <?php footNote('J',3,23); ?> Appendix 4</p>
 <?php footNote('J',3,24); ?> This is the same view as that formed by the Joint Committee on Privacy and Injunctions in its Report: see http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf (HL Paper 273; HC 1443), para 37</p>
 <?php footNote('J',3,25); ?> para 50, <em>ibid</em></p>
 <?php footNote('J',3,26); ?> [1997] QB 586</p>
 <?php footNote('J',3,27); ?> at 614E</p>
 <?php footNote('J',3,28); ?> [1991] 1 QB 153; see Lord Donaldson of Lymington MR at 178-9; Nourse LJ at 185-6; Russell LJ at 190: thereafter (perSir Thomas Bingham MR in John at page 608) &#8220;juries were reminded of the cost of buying a motor car, or a holiday, or a house&#8221; </p>
 <?php footNote('J',3,29); ?> Where the Court of Appeal had power to order a new trial on the ground that damages awarded by a jury wereexcessive or inadequate, this provision allowed the Court &#8220;to substitute for the sum awarded by the jury such sum asappears to the court to be proper&#8221;</p>
 <?php footNote('J',3,30); ?> For example,<em> Thompson v Commissioner of Police for the Metropolis</em> [1998] QB 513 which concerned falseimprisonment and malicious prosecution but applies equally to damages for defamation which were extensively discussed</p>
 <?php footNote('J',3,31); ?> [2008] EWHC 1777 QB; Eady J said (at para 214) that &#8220;the purpose of damages, therefore, must be to  addressthe specific public policy factors in play when there has been an &#8216;old fashioned breach of confidence&#8217; and/or anunauthorised revelation of personal information. It would seem that the law is concerned to protect such matters aspersonal dignity, autonomy and integrity&#8221;. He went on (at para 216): </p>
 <blockquote>&#8220;Thus it is reasonable to suppose that damagesfor such an infringement may include distress, hurt feelings and loss of dignity&#8221;.</blockquote>
 <?php footNote('J',3,32); ?> <em> Cooper & another v Turrell</em> [2011] EWHC 3269 see per Tughendhat J (at para. 102) who described damages formisuse of private information as being &#8220;to compensate for the damage, and injury to feelings and distress, caused by  the publication of information which may be either true or false(at para 102): http://www.bailii.org/ew/cases/EWHC/  QB/2011/3269.html </p>
 <?php footNote('J',3,33); ?> <em> Adenjii v London Borough of Newham</em> [Case 01TLQ 823], October 2001. This was an approved settlement (Garland J)in the High Court</p>
 <?php footNote('J',3,34); ?> <em> Campbell v MGN</em> [2004] UKHL 22</p>
 <?php footNote('J',3,35); ?> <em> Douglas v Hello!</em> [2003] EWHC 786 (Ch). The award of Lindsay J was upheld by the Court of Appeal</p>
 <?php footNote('J',3,36); ?> <em> McKennitt v Ash</em> [2005] EWHC 3003 QB</p>
 <?php footNote('J',3,37); ?> <?php internalChapterLink('../../','H',5); ?></p>
 <?php footNote('J',3,38); ?> Guidelines for the Assessment of General Damages (11 th edition) has recently been published by the Judicial College(previously the Judicial Studies Board)</p>
 <?php footNote('J',3,39); ?> s 6(3)(a)-(e) of the Civil Procedure Act 1997</p>
 <?php footNote('J',3,40); ?> As was the case in relation to the 10% increase proposed by Jackson LJ adopted in<em> Simmons v Castle</em> [2012] EWCACiv 1039</p>
 <?php footNote('J',3,41); ?> http://lawcommission.justice.gov.uk/docs/lc247_aggravated_exemplary_and_restitutionary_damages.pdf</p>
 <?php footNote('J',3,42); ?> <em> Rookes v. Barnard</em> [1964] AC 1129,<em> Cassell v Broome</em> [1972] AC 1027,<em> Kuddus v Chief Constable of Leicestershire Constabulary [2002]</em> 2 AC 122 and, in the Supreme Court, in R (Lumba) v Secretary of State for the Home Department  [2011] 2 WLR 67 1 </p>
 <?php footNote('J',3,43); ?> http://lawcommission.justice.gov.uk/docs/lc247_aggravated_exemplary_and_restitutionary_damages.pdf Part 4(page 53 et seq) analyses the law as at 1997 and although there may well have been some developments since then(although the caution of Eady J in Mosley is to be noted), a more detailed up to date analysis is not necessary for the  purposes of my recommendations </p>
 <?php footNote('J',3,44); ?> Such as those that surround the need to make a single award shared between multiple victims: see<em> R (Lumba) v Secretary of State for the Home Department [2011]</em> 2 WLR 671 per Lord Dyson at para. 167. Assessment is not without  difficulties where there is more than one tortfeasor: see Gatley on Libel and Slander, 10 th edn, para 9.25 </p>
 <?php footNote('J',3,45); ?> Para 134, http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf</p>
 <?php footNote('J',3,46); ?> Para 147, <em>ibid</em></p>
 <?php footNote('J',3,47); ?> <?php internalChapterLink('../../','K',6); ?></p>
 <?php footNote('J',3,48); ?> CPR 44.3(4)(a)</p>
 <?php footNote('J',3,49); ?> CPR 44.3(5)(a)</p>
 <?php footNote('J',3,50); ?> CPR 1.1(1). By 1.1(12), dealing with a case justly includes, so far as is practicable, (a) ensuring that the parties areon an equal footing ; (b) saving expense; (c) dealing with the case in ways which are proportionate to the amount ofmoney involved, to the importance of the case, to the complexity of the issues; and to the financial position of eachparty; (d) ensuring that it is dealt with expeditiously and fairly; and (e) allotting to it an appropriate share of the court&#8217;sresources while taking into account the need to allot resources to other cases</p>
 <?php footNote('J',3,51); ?> [2004] EWCA Civ 576; [2004] 1 WLR 3002; [2004] 4 All ER 920</p>
 <?php footNote('J',3,52); ?> <?php internalChapterLink('../../','K',6); ?>. The mechanism for achieving this objective could be amendment of CPR 44.3 and, in the discretionof the court, could be of relevance beyond a system of arbitration that is created by a new press regulator</p>
 </div>
