<div class="content" id="contentPartAChapter1">
<h1 id="top">CHAPTER 1<br/>THE ANNOUNCEMENT</h1>
 <?php sectionAnchor('A',1,1); ?>Introduction</h2>
 <?php paragraphLink('A',1,1,1); ?> On, 13 July 2011, the Prime Minister made a statement to the House of Commons in these terms:<?php footnoteRef('A',1,1); ?></p>
<blockquote>&#8220;In recent days, the whole country has been shocked by the revelations of the phone hacking scandal. What this country&#8212;and the House&#8212;has to confront is an episode that is, frankly, disgraceful: accusations of widespread lawbreaking by parts of our press: alleged corruption by some police officers; and, as we have just discussed, the failure of our political system over many, many years to tackle a problem that has been getting worse. We must at all times keep the real victims at the front and centre of this debate. Relatives of those who died at the hands of terrorism, war heroes and murder victims&#8212;people who have already suffered in a way that we can barely imagine&#8212;have been made to suffer all over again. </blockquote>
<blockquote>I believe that we all want the same thing: press, police and politicians who serve the public. Last night the Deputy Prime Minister and I met the Leader of the Opposition. I also met the Chairs of the Culture, Media and Sport Committee, the Home Affairs Committee and the Justice Committee to discuss the best way forward. Following these consultations, I want to set out today how we intend to proceed: first, on the public inquiry; secondly, on the issues surrounding News International&#8217;s proposed takeover of BSkyB; and thirdly, on ethics in the police service and its relationship with the press. </blockquote>
<blockquote>Before I do that, I will update the House on the current criminal investigation into phone hacking. I met Sir Paul Stephenson last night. He assured me that the investigation is fully resourced. It is one of the largest currently under way in the country, and is being carried out by a completely different team from the one that carried out the original investigation. It is being led by Deputy Assistant Commissioner Sue Akers, who I believe impressed the Home Affairs Committee yesterday. Her team is looking through 11,000 pages containing 3,870 names, and around 4,000 mobile and 5,000 landline phone numbers. The team has contacted 170 people so far, and will contact every single person named in those documents. The commissioner&#8217;s office informed me this morning that the team has so far made eight arrests and undertaken numerous interviews. </blockquote>
<blockquote>Let me now turn to the action that the Government are taking. Last week in the House I set out our intention to establish an independent public inquiry into phone hacking and other illegal practices in the British press. We have looked carefully at what the nature of the inquiry should be. We want it to be one that is as robust as possible&#8212; one that can get to the truth fastest and also get to work the quickest, and, vitally, one that commands the full confidence of the public. Clearly there are two pieces of work that have to be done. First, we need a full investigation into wrongdoing in the press and the police, including the failure of the first police investigation. Secondly, we need a review of regulation of the press. We would like to get on with both those elements as quickly as possible, while being mindful of the ongoing criminal investigations. So, after listening carefully, we have decided that the best way to proceed is with one inquiry, but in two parts. </blockquote>
<blockquote>I can tell the House that the inquiry will be led by one of the most senior judges in the country, Lord Justice Leveson. He will report to both the Home Secretary and the Secretary of State for Culture, Media and Sport. The inquiry will be established under the Inquiries Act 2005, which means that it will have the power to summon witnesses, including newspaper reporters, management, proprietors, policemen and politicians of all parties, to give evidence under oath and in public. &#8230; </blockquote>
<blockquote>Starting as soon as possible, Lord Justice Leveson, assisted by a panel of senior independent figures with relevant expertise in media, broadcasting, regulation and government will inquire into the culture, practices and ethics of the press; its relationship with the police; the failure of the current system of regulation; the contacts made, and discussions had, between national newspapers and politicians; why previous warnings about press misconduct were not heeded; and the issue of cross-media ownership. He will make recommendations for a new, more effective way of regulating the press&#8212;one that supports its freedom, plurality and independence from Government, but which also demands the highest ethical and professional standards. He will also make recommendations about the future conduct of relations between politicians and the press. That part of the inquiry we hope will report within 12 months. </blockquote>
<blockquote>The second part of the inquiry will examine the extent of unlawful or improper conduct at the News of the World and other newspapers, and the way in which management failures may have allowed it to happen. That part of the inquiry will also look into the original police investigation and the issue of corrupt payments to police officers, and will consider the implications for the relationships between newspapers and the police. Lord Justice Leveson has agreed to these draft terms of reference. I am placing them in the Library today, and we will send them to the devolved Administrations. No one should be in any doubt of our intention to get to the bottom of the truth and learn the lessons for the future.&#8221; </blockquote>
  <?php paragraphLink('A',1,1,2); ?>The Terms of Reference were then the subject of further discussion both with the devolved administrations of Scotland, Wales and Northern Ireland and other interested parties. The Prime Minister returned to the topic on 20 July 2011, when announcing the appointment of the Assessors. He said:<?php footnoteRef('A',1,2); ?></p>
<blockquote>&#8220;We have made some significant amendments to the remit of the inquiry. With allegations that the problem of the relationship between the press and the police goes wider than just the Met, we have agreed that other relevant forces will now be within the scope of the inquiry. We have agreed that the inquiry should consider not just the relationship between the press, police and politicians, but their individual conduct too. We have also made it clear that the inquiry should look not just at the press, but at other media organisations, including broadcasters and social media if there is any evidence that they have been involved in criminal activities.&#8221; </blockquote>
  <?php paragraphLink('A',1,1,3); ?>Thus, the Terms of Reference of the Inquiry, as finally drafted, are:</p>
  <blockquote>
  <strong>part 1</strong>
  <ol> 
  <li>To inquire into the culture, practices, and ethics of the press, including: 
  <ol type="a">
  <li>contacts and the relationships between national newspapers and politicians, and the conduct of each;</li>
  <li>contacts and the relationship between the press and the police, and the conduct of each;</li>
  <li>the extent to which the current policy and regulatory framework has failed including in relation to data protection; and</li>
  <li>the extent to which there was a failure to act on previous warnings about media misconduct.</li>
  </ol>
 </li>
  <li>To make recommendations: 
  <ol type="a">
  <li>or a new more effective policy and regulatory regime which supports the integrity and freedom of the press, the plurality of the media, and its independence, including from Government, while encouraging the highest ethical and professional standards; 
  <li>for how future concerns about press behaviour, media policy, regulation and cross-media ownership should be dealt with by all the relevant authorities, including Parliament, Government, the prosecuting authorities and the police; 
  <li>the future conduct of relations between politicians and the press; and</li>
  <li>the future conduct of relations between the police and the press. </li>
  </ol>
 </li>
  </ol>
  
  <strong>part 2</strong>
  <ol start="3">
 <li>To inquire into the extent of unlawful or improper conduct within News International, other newspaper organisations and, as appropriate, other organisations within the media, and by those responsible for holding personal data.</li>
 <li>To inquire into the way in which any relevant police force investigated allegations or evidence of unlawful conduct by persons within or connected with News International, the review by the Metropolitan Police of their initial investigation, and the conduct of the prosecuting authorities.</li>
 <li>To inquire into the extent to which the police received corrupt payments or other inducements, or were otherwise complicit in such misconduct or in suppressing its proper investigation, and how this was allowed to happen.</li> 
 <li>To inquire into the extent of corporate governance and management failures at News International and other newspaper organisations, and the role, if any, of politicians, public servants and others in relation to any failure to investigate wrongdoing at News International</li>
 <li>In the light of these inquiries, to consider the implications for the relationships between newspaper organisations and the police, prosecuting authorities, and relevant regulatory bodies &#8211; and to recommend what actions, if any, should be taken.</li>
 </ol>
 </blockquote> 
  <?php paragraphLink('A',1,1,4); ?>By letter dated 28 July 2011,<?php footnoteRef('A',1,3); ?> as responsible Ministers under the Inquiries Act 2005, the Rt Hon Jeremy Hunt MP (then the Secretary of State for Culture Media and Sports) and Baroness Browning (then a Minister of State at the Home Office) appointed me to Chair the Inquiry pursuant to s3(1)(a) of the Act. On the same date, their appointment having previously been announced by the Prime Minister, acting pursuant to s11(2)(a) of the Act, the Ministers appointed six Assessors with a wide range of professional experience to assist the Inquiry. These were Sir David Bell,<?php footnoteRef('A',1,4); ?> Shami Chakrabarti CBE,<?php footnoteRef('A',1,5); ?> Lord (David) Currie,<?php footnoteRef('A',1,6); ?> Elinor Goodman,<?php footnoteRef('A',1,7); ?> George Jones<?php footnoteRef('A',1,8); ?> and Sir Paul Scott-Lee.<?php footnoteRef('A',1,9); ?></p>
  <?php paragraphLink('A',1,1,5); ?>From the day of the announcement of my appointment, it was necessary to identify appropriate support. A Director General with a legal background and experience at the Home Office, the Ministry of Justice and the Office of the Deputy Prime Minister, Rowena Collins Rice was an ideal appointment as Secretary to the Inquiry. Kim Brudenell, a senior solicitor from the Treasury Solicitor&#8217;s office was appointed Solicitor to the Inquiry; Amanda Jeffery (from the Judicial Office) and Rachel Clark (from the Department of Culture, Media and Sport and previously the Department for Business, Innovation and Skills) were appointed as Heads of Administration and Research respectively. With an eye on prudent financial management, suitable civil servants from across Government were recruited to staff the Inquiry and ensure that it could proceed expeditiously and efficiently.</p>
  <?php paragraphLink('A',1,1,6); ?>I also set about appointing counsel. With the assistance of the Treasury Solicitor, I selected Robert Jay QC to be Counsel to the Inquiry; with my approval he nominated David Barr and Carine Patry Hoskins as junior Counsel, later adding Lucinda Boon for Module 2 (concerning the relationship between the press and the police). Counsel were assisted by junior members of the Bar in relation to the necessary research for both preparing the examination of witnesses and the subsequent collation of the evidence.</p>
  <?php paragraphLink('A',1,1,7); ?>At the very beginning of this Report, it is appropriate to record my enormous gratitude to the Assessors, to Counsel and to the entire Inquiry team (whose names are set out in Appendix A to this Report) for their unstinting commitment to the Inquiry and the prodigious effort that has been put into ensuring that it proceeded smoothly, to budget and, most important, was able appropriately to address the Terms of Reference within a time frame that aIlows early consideration to be given by the Government and Parliament to the way forward.</p>
  <?php sectionAnchor('A',1,2); ?>Role of the assessors</h2>
 <?php paragraphLink('A',1,2,1); ?>From the outset, challenges were mounted by a number of press interests to the way in which the Inquiry was set up and, in particular, to the experience, role and responsibility of the Assessors. Having obtained cross party support for their appointment, when identifying them by name,<?php footnoteRef('A',1,10); ?> the Prime Minister said of them &#8220;these people have been chosen not only for their expertise in the media, broadcasting, regulation and policing, but for their complete independence from the interested parties.&#8221; </p>
  <?php paragraphLink('A',1,2,2); ?>At the opening session of the Inquiry, I spoke of the Assessors having&#8220;a central role in the work&#8221; so that the report would be a &#8220;collaborative effort&#8221; and that if a particular recommendation was not unanimous, &#8220;I shall make the contrary view clear.&#8221; It was argued that this would make the Assessors into members of the panel pursuant to s4 of the Inquiries Act 2005 and that they lacked balance on the basis that their number included nobody with tabloid or mid- market newspaper experience.</p>
  <?php paragraphLink('A',1,2,3); ?>In a ruling of 17 October 2011,<?php footnoteRef('A',1,11); ?> I rejected the view that the Assessors were a hybrid between assessors within the meaning of s11 of the Inquiries Act 2005 and members of the determining panel (as set out in s4). I set out the role for assessors in para 3 of the Assessor Protocol in these terms:<?php footnoteRef('A',1,12); ?></p>
<blockquote>&#8220;An assessor will take such part in the proceedings of the Inquiry as the Chairman may request, and in particular the Chairman may at any time request an assessor to:
<ol type="a">
<li>Attend the whole or part of any hearing, seminar or briefing; and/or</li>
<li>Chair the whole or part of any seminar in an area of his or her expertise; and/ or</li> 
<li>Prepare a report for the Chairman on any matter relevant to the Inquiry within the area of expertise of the assessor; and/or</li>
<li>Provide to Counsel to the Inquiry suggested lines of questioning for witnesses, in respect of any matters within his or her expertise; and/or 
<li>Provide the Chairman with any other assistance, or advice, on any matter relevant to the Inquiry within the expertise of the assessor.&#8221;</li>
</ol>
</blockquote>
  <?php paragraphLink('A',1,2,4); ?>In the event that an Assessor prepared a report that I intended to take into account, paragraph 4 of the Protocol made it clear that it should be disclosed to the Core Participants (who could submit observations upon it) and thereafter published as part of the evidence. In the event, I have not asked any Assessor to prepare a report that I intend to take into account; there is no question of any providing me with &#8216;evidence&#8217; or other material which it is appropriate to share with Core Participants in order that they may make submissions about it. The extent to which the Assessors would take part in or impact upon my conclusions was also explained in my ruling which includes a description of their role and responsibilities in these terms:<?php footnoteRef('A',1,13); ?></p>
<blockquote>&#8220;30. The assessors also bring an understanding of the practical implications of potential ways forward &#8211; what may, or may not, work in the fields of their respective expertise. It is that to which I refer when I speak of being collaborative and &#8216;striving for unanimity&#8217;. There is absolutely no point in my suggesting a way forward (if different from the present system) that everyone decries as unworkable; if that were my provisional view, I would want to be told. The process I envisage would entail, amongst other things, seeking the assistance and advice of my assessors but, as I have also explained, I may also test out possible solutions in further seminars. Again, with fairness as my touchstone, if I believe that new material is generated, that material will be shared so that all can make submissions upon it.</blockquote><blockquote> 31. Ultimately, however, as I have made very clear, my conclusions shall be solely my conclusions. There is no question of publishing concurring views. In the spirit of openness and transparency, however, I shall identify the fact that one or more of the assessors disagrees with my conclusions and I shall explain the nature of the disagreement: in that way, those who read my report will be able to make up their own minds.&#8221; </blockquote>
  <?php paragraphLink('A',1,2,5); ?>The Assessors have been scrupulous to follow the approach set out in the Protocol and ruling. They have assisted in relation to avenues of investigation and lines of enquiry both generally and to specific witnesses. Although there has been repeated criticism of the Inquiry for not engaging an assessor with experience of tabloid or mid-market newspapers (along with suggestions that nobody working in a broadsheet newspaper would be able to understand the dynamics of tabloid or mid-market journalism), nobody has suggested in evidence that the approach to ethical issues should be different. In any event, far from ignoring the different interests to which tabloid and mid-market newspapers appeal, the Assessors with experience of journalism have been assiduous to keep me aware, both in advance and as I was hearing the evidence, of the arguments that have in fact been put forward in favour of the needs of this profitable sector of the market. In doing so, they have continuously emphasised the perspective that was trailed particularly by Trevor Kavanagh and Kelvin MacKenzie in the seminars and underlined by editors and journalists working for titles from these sectors when they gave evidence. They have kept at the front of my mind the ways in which those titles appeal to their very large readership and the vital importance of ensuring that it is taken into account in full measure &#8211; which I have done.</p>
  <?php paragraphLink('A',1,2,6); ?>The role of the Assessors was described by me in my ruling of 17 October 2011, when I said:<?php footnoteRef('A',1,14); ?></p>
<blockquote>&#8220;27. It is obviously desirable (as the Prime Minister and others have identified) that I obtain advice and assistance from those who have made their lives and careers in the various areas covered by the Inquiry, in particular in relation to dealings between the press and the public, the press and politicians and the propriety of press contact with the police. Not least, this is because I would be keen to understand any flaws or unintended consequences that might flow from suggestions that are advanced that my lack of experience would not otherwise identify. That is not to make the assessors advocates for any particular cause and that is not how I (or they) see their role.&#8221; </blockquote>
  <?php paragraphLink('A',1,2,7); ?>Neither has any of the Assessors sought to act as an advocate. It has recently been suggested in a number of press reports that, in the some way, I have been subject, on the part of my Assessors, to hidden lobbying, political partisanship or self-interested influence with specific agendas in mind. That is untrue. Having spent over 40 years seeking to persuade or influence, or listening to others trying to do the same, if it had been attempted or even crept in unconsciously, I would have detected it very quickly. I have found the assistance of my Assessors, in their areas of expertise and experience, invaluable. They will, however, not mind my saying here what I have assured them of many times as we have gone along: that my task in response has been to sift, weigh and test what they have said and make such use of it as seems to me right.</p>
  <?php paragraphLink('A',1,2,8); ?>It should be remembered that the Assessors were selected by the Prime Minister who, I repeat, described them as having been chosen &#8220;for their complete independence from the interested parties&#8221;. The Leader of the Opposition welcomed the Inquiry and &#8220;indeed the panel members chosen by the Prime Minister&#8221;. After they were nominated, I spoke to each at length and satisfied myself that the Prime Minister was right.</p>
  <?php paragraphLink('A',1,2,9); ?>Full declarations of possible conflict were made by each before the start of the Inquiry: along with their CVs, these have been published on the Inquiry website throughout. When challenging the position of the Assessors in the argument that led to the ruling to which I have referred, Jonathan Caplan QC for Associated Newspapers Ltd submitted that the three journalist Assessors were not representative of the industry but made it clear, in terms, that he recognised that there was no statutory requirement that an Assessor be impartial.<?php footnoteRef('A',1,15); ?> I underline that. It is an Assessor&#8217;s task to offer me the benefit of his or her personal perspective, expertise and experience. It is mine to take the impartial view.</p>
  <?php paragraphLink('A',1,2,10); ?>The duty of confidence which the Assessors owe by law in relation to the internal deliberations of the Inquiry is there to enable them to provide their expertise fully and frankly and to protect them from external pressures. In fact, nothing that the Assessors have said or done during the course of the Inquiry would allow anyone to suggest that they had gone any further than precisely to perform the role set out in my ruling. I make one further point about the Assessors. None has been concerned with or involved in any the decisions of fact, where I have had to make my mind up about what I considered had been established to the relevant standard. Those parts of the Report that depend only on a forensic analysis of issues of fact or issues outside their expertise (for example, <?php internalChapterLink('../../','I',6); ?> in relation to the bid for the shares of BSkyB plc), have not even been seen prior to publication of the Report.</p>
  <?php sectionAnchor('A',1,3); ?>Visits</h2>
 <?php paragraphLink('A',1,3,1); ?>In an effort, at least in part, to assuage concern that I had no experience or perception of the issues faced by the newspaper industry and the way in which newspapers operate, I have been very willing to receive evidence on the topic. Additionally, I offered to undertake private visits to any newspaper title that invited me. I was clear that one such newspaper should be regionally based and, prior to the commencement of the Inquiry, I visited the Southern Daily Echo in Southampton, the offices of Associated Newspapers Ltd (The Daily Mail and The Sunday Mail), Trinity Mirror plc (The Daily Mirror, The Sunday Mirror and The People) and News International Ltd (The Sun, The Times and The Sunday Times). I was treated with courtesy at each and shown not only the layout and operation but also aspects of the production of online editions.</p>
  <?php paragraphLink('A',1,3,2); ?>Towards the end of the hearings, I was invited to the offices of the Press Complaints Commission: having regard to the very extensive evidence that I had received both as to the operation of the Commission and the approach of its staff, I felt that to do so could give rise to misunderstanding and, furthermore, did not consider that it would add to my understanding of the issues. In the circumstances, I declined that invitation.</p>
  </div>

 