<?php 
require_once('../../common.php');
levesonHeader('A',1); 
levesonNav('../../');
levesonBread('A',1);
require_once('content.php');
levesonFooterNav('A',1); 
require_once('footnotes.php');
LevesonCommonFooter();
?>
