<div class="content" id="contentPartIChapter2">
<h1 id="top">CHAPTER 2<br/>THE CONSERVATIVE YEARS</h1>
 <?php sectionAnchor('I',2,1); ?>Prime Minister thatcher: 1979-1990</h2>
 <?php paragraphLink('I',2,1,1); ?>Margaret, now Baroness, Thatcher enjoyed sustained, substantial though not unqualified support from a range of national newspaper titles throughout her tenure as Prime Minister, yet she is reputed to have spent little time herself actually reading newspapers:<?php footnoteRef('I',2,1); ?>
<blockquote>&#8220;Margaret Thatcher never read a newspaper from one week to the next.&#8221; </blockquote>While titles with a consistent history of leaning to the left of centre were equally consistently critical, those sections of the press with a history of shifting political leanings were as supportive as traditionally Conservative newspapers. In that sense, at any rate, from Lord Mandelson&#8217;s perspective:<?php footnoteRef('I',2,2); ?></p>
<blockquote>&#8220;Mrs Thatcher was able to call on the virtually uncritical support of both publishers and editors.&#8221; </blockquote>
  <?php paragraphLink('I',2,1,2); ?>A particular feature of Baroness Thatcher&#8217;s era was the strong personal relationship which she enjoyed with a number of newspaper proprietors, characterised by mutual respect and shared political ideology. Rupert Murdoch described himself to be a &#8220;great admirer&#8221;<?php footnoteRef('I',2,3); ?> of Baroness Thatcher, agreeing that he was on the &#8220;same page politically&#8221;.<?php footnoteRef('I',2,4); ?></p>
  <?php paragraphLink('I',2,1,3); ?>The Inquiry heard a consistency of opinion on this matter. Mr Murdoch&#8217;s title, The Sun, was described to the Inquiry by Tony Blair as &#8220;a major part of supporting Mrs Thatcher&#8221;,<?php footnoteRef('I',2,5); ?> although Mr Murdoch himself put it more modestly.<?php footnoteRef('I',2,6); ?> David Mellor QC observed that: &#8220;[Rupert Murdoch&#8217;s] ...straightforward right wing populist opinions made him a soulmate for Mrs Thatcher&#8221;.<?php footnoteRef('I',2,7); ?> Sir John Major attributed Baroness Thatcher&#8217;s rapport with newspaper proprietors to her political outlook:<?php footnoteRef('I',2,8); ?>
<blockquote>&#8220;Margaret was probably the most right of centre leader the Conservative Party had had for quite a long time, and I think that appealed to the natural instincts of many proprietors and editors at the time, and I think support was accordingly offered.&#8221; </blockquote>Andrew Neil, the former editor of The Sunday Times, also described Baroness Thatcher and Mr Murdoch as &#8220;ideological soul mates&#8221;.<?php footnoteRef('I',2,9); ?> Sir John interestingly connected the bond between Baroness Thatcher and these proprietors with their common commitment to trade union reform, to shared views about business (and buccaneering businessmen)<?php footnoteRef('I',2,10); ?> and the European Union, and to popular admiration for Baroness Thatcher&#8217;s role in the Falklands War.</p>
  <?php paragraphLink('I',2,1,4); ?>Baroness Thatcher&#8217;s relationship with many proprietors did not manifest itself in frequent meetings with them or their editors. Mr Murdoch firmly denied the suggestion that he had consulted with her regularly on every important matter of policy.<?php footnoteRef('I',2,11); ?> Mr Neil saw Baroness Thatcher once in seven years.<?php footnoteRef('I',2,12); ?> Kelvin MacKenzie told the Inquiry that he probably saw Baroness Thatcher about twice a year but later confirmed that he did not doubt that she wanted his support.<?php footnoteRef('I',2,13); ?></p>
  <?php paragraphLink('I',2,1,5); ?>The relatively modest number of meetings does not necessarily indicate that a friendly proprietor did not have access to the Prime Minister. Mr Murdoch was readily received when he approached herwhilst hewas a bidder for Times Newspapers. The result was thathe visited Chequers for lunch where he briefed her on his bid and his vision for Times Newspapers. The acquisition of Times Newspapers is described in detail elsewhere.<?php footnoteRef('I',2,14); ?></p>
  <?php paragraphLink('I',2,1,6); ?>It is easy to understand why Baroness Thatcher enjoyed a good relationship with a number of proprietors but more difficult to attribute any specific benefit for either party to the relationship itself. Baroness Thatcher enjoyed a good deal of positive media coverage, although even generally supportive titles were sometimes critical (for example, Mr Murdoch preferred to support President Reagan over Baroness Thatcher when the United States invaded Grenada).<?php footnoteRef('I',2,15); ?> But the explanation for the positive coverage is readily attributable to editorial approval for her policies and disapproval of those of the Opposition. There was straightforward political alignment and an element of straightforward mutual personal rapport (not to say admiration).</p>
  <?php paragraphLink('I',2,1,7); ?>Importantly, it is clear from Mr Murdoch&#8217;s evidence, which is corroborated by contemporary notes, that he neither expressly asked for nor was expressly offered any favourable policy decisions by Baroness Thatcher.<?php footnoteRef('I',2,16); ?> He was indeed permitted to buy Times Newspapers without a reference to the Monopolies and Mergers Commission (MMC) but this does not appear to me to be directly attributable to personal influence. The Prime Minister was not in any event the decision maker.<?php footnoteRef('I',2,17); ?></p>
  <?php paragraphLink('I',2,1,8); ?>Mr Neil suggested that in late 1985, in the run up to the major industrial dispute at Wapping, Mr Murdoch went to&#8221;square Thatcher&#8221;,by which he meant seek an assurance that there would be sufficient policing of the dispute to enable him to continue to do business at Wapping.<?php footnoteRef('I',2,18); ?> That was indeed the result, but the Government&#8217;s stance during the Wapping dispute was in accordance with its approach to other industrial disputes (not least the miners&#8217; strike).</p>
  <?php paragraphLink('I',2,1,9); ?>An indication of the influence of Mr Murdoch towards the end of Baroness Thatcher&#8217;s tenure was provided by Mr Mellor in these terms:<?php footnoteRef('I',2,19); ?></p>
<blockquote>&#8220;By the time Murdoch came to establish Sky, a brave entrepreneurial investment that deserved to succeed, and a process I was happy to help along in the Broadcasting Act 1990, he was used to Ministers doing his bidding, rather than the other way around. He was personally charming to deal with, but he was one of the few people, apart from Heads of State, I, as a minister, had to visit at his premises rather than him having to schlepp over to the Home Office.&#8221; </blockquote>
  <?php paragraphLink('I',2,1,10); ?>There were nevertheless decisions on media policy taken by the Government which went against supportive proprietors. News International was not granted a domestic broadcasting licence and had to launch Sky, its satellite television service, using a foreign satellite.<?php footnoteRef('I',2,20); ?> On this, the Sunday Times, under Mr Neil, supported Lord Heseltine against Baroness Thatcher.<?php footnoteRef('I',2,21); ?></p>
  <?php paragraphLink('I',2,1,11); ?>More than one witness suggested that the prospect of honours played a part in Baroness Thatcher&#8217;s relationship with senior media figures. Alastair Campbell put it bluntly:<?php footnoteRef('I',2,22); ?></p>
<blockquote>&#8220;Margaret Thatcher had much more press support, partly for political and ideological reasons, in that most owners and editors are right wing and genuinely supported her, but also because she operated what today would be seen as a corrupt system of patronage using the honours system to reward supportive owners and editors&#8221;.</blockquote>
  <?php paragraphLink('I',2,1,12); ?>Lord Mandelson did not put it so high:<?php footnoteRef('I',2,23); ?></p>
<blockquote>&#8220;She cultivated and honoured and nurtured editors and journalists very successfully. The relationship was, I think, relatively calm during her period. It might not have seemed so calm to her on all occasions ...&#8221; </blockquote>
  <?php paragraphLink('I',2,1,13); ?>Lord Grade offered these thoughts on the question of patronage:<?php footnoteRef('I',2,24); ?></p>
<blockquote>&#8220;...we are happily past the days when the politicians of the day used to pack the boards of the regulators with their friends and supporters, such as my time as a controller of BBC One when in the days of then Mrs Thatcher&#8217;s government when the board of the BBC were packed with her friends. We&#8217;ve moved on from then, we have a Nolan process ...&#8221; </blockquote>
  <?php paragraphLink('I',2,1,14); ?>An issue of interest to the Inquiry was the question of the perception amongst politicians of the extent to which newspaper endorsement assists election prospects. Andrew Marr said:<?php footnoteRef('I',2,25); ?></p>
<blockquote>&#8220;There is always a hierarchy of media contacts. For a Conservative minister, contacts at The Daily Telegraph, Daily Mail, The Spectator and blogs like Conservative home are particularly valuable, and likely to be closer; Liberal Democrats will more likely turn to papers and blogs read by their activists, and Labour, ditto. <u>Throughout the Thatcher, Major and Blair governments, the Murdoch stable was always perceived by its rivals to have a privileged position.</u><br/>
&#8220;This was because of its spread and power as a publishing group, and Mr Murdoch&#8217;s readiness to use papers such as the Sun to intervene aggressively. But it made close social relationships, at Murdoch parties or Oxfordshire get-togethers, peculiarly disheartening for press rivals&#8221; (emphasis added)</blockquote> 
  <?php paragraphLink('I',2,1,15); ?>As notable as the active support of much of the press for Baroness Thatcher was its hostile attitude to the Opposition. Throughout Baroness Thatcher&#8217;s time in office, successive Leaders of the Opposition, first Michael Foot and then Neil Kinnock, were the subject of considerable adverse press coverage. Writing from the Labour Party&#8217;s perspective, Mr Campbell described the period as follows:<?php footnoteRef('I',2,26); ?>
<blockquote>&#8220;What we do know is that the press [Michael Foot and Neil Kinnock] received was hugely biased against them, and in favour of Mrs Thatcher and her Party. Michael Foot had long been derided by the right wing media for perceived political and personal shortcomings, the most famous being the alleged disrespect he showed in attending the 1981 Remembrance Sunday Service in what was mythologised as a &#8220;donkey jacket&#8221;.</blockquote> But that was but part of a long campaign during which in several papers Mr Foot could only be defined negatively. According to the book, Stick it up your Punter, the Sun and the Express told freelance photographers covering a Foot visit not to bother sending pictures of the Labour leader &#8220;unless falling over, shot or talking to Militants.&#8221; The Daily Mail, under a pre-knighted David English, led a front page with a disputed claim that Nissan would &#8220;scrap plans for a &#163;50m car plant&#8221; if Labour won the election. &#8220;35,000 jobs lost if Foot wins&#8221; screamed the headline. I cite this as a typical rather than exceptional example. Labour&#8217;s defeat in 1979, and a seeming shift to the left, ignited not so much political debate as focus on sinister Marxist forces, wrongly ensuring that at times in the public debate Labour&#8217;s political doctrine was indistinguishable from the Communists&#8217;. The Express earned top marks from Tory Central Office with a &#8220;Spot the Trots&#8221; feature of 70 &#8220;extremist&#8221; candidates, among them Neil Kinnock and Robin Cook&#8221;.</p>
  <?php paragraphLink('I',2,1,16); ?>Lord Mandelson put it this way:<?php footnoteRef('I',2,27); ?></p>
<blockquote>&#8220;I think what I meant by [horrible and bloody] is that, you know, there has been a longer standing trend in the press to mix reporting with comment, and it didn&#8217;t simply revolve around that period in the 1980s and the 1992 election. I think that what took this sort of merging of comment and reporting to a higher level was the more lethal cocktail, which I believe that the Labour Party was exposed to, and that was a sort of mixture of aggression and inaccuracy, and I think that the Labour Party generally and its leader, Mr Kinnock, in particular were the victims of that. &#8220;I think that the press took their gloves off, I think there was a sort of lack of scruple or restraint in the reporting of the Labour Party in those years. &#8220;Now I also quite honestly observe in my witness statement that, you know, a lot of the damage the Labour Party had done to itself in the early part of the 1980s. We weren&#8217;t exactly making it easy for people to report us positively or warmly given the vote-losing policies, the divisions, the entries into the Labour Party by the far left. &#8220;But by the end of the 1980s, by the time we got to the 1992 General Election, a great deal, I would say the bulk of that swamp had been emptied, and that the Labour Party had changed and I don&#8217;t think we were given the credit for those changes and I think Mr Kinnock in particular was on the receiving end of treatment by the media, notably but not only News International titles, that was not warranted and was not fair&#8221;.</blockquote>
  <?php paragraphLink('I',2,1,17); ?>Peter Oborne felt that there had been: &#8220;a poisonously unfair media towards Mr Kinnock at that time. He didn&#8217;t get a fair crack of the whip, and therefore if he tried to sell a policy, it tended to get misrepresented .&#8221;<?php footnoteRef('I',2,28); ?> Headlines from this era included: &#8220;Glenys the Menace&#8221; (Daily Mail) and &#8220;Kinnock &#8211; I back loonies&#8221; (The Sun).<?php footnoteRef('I',2,29); ?></p>
  <?php paragraphLink('I',2,1,18); ?>The relationship between the Labour Party and News International was particularly poor during this period for another reason: the dispute at Wapping. Labour sought to mark its disapproval of Mr Murdoch&#8217;s handling of the dispute by cutting off the supply of political news to his reporters. As Andrew Grice, formerly the political editor of the Sunday Times, put it:<?php footnoteRef('I',2,30); ?></p>
<blockquote>&#8220;There was a major industrial dispute at Wapping in 1986/7. During that period, officially at least, the Labour party was not even talking to the Murdoch papers and Murdoch paper journalists were banned from any briefings or press conferences the Labour party held. So the back cloth was not just difficult relations but no official relationships at all&#8221;.</blockquote>
  <?php paragraphLink('I',2,1,19); ?>Mr Campbell said that after the Wapping dispute the Labour Party wanted nothing to do with the Murdoch papers.<?php footnoteRef('I',2,31); ?></p>
  <?php paragraphLink('I',2,1,20); ?>A similarly confrontational line was also taken by the Labour Party with TV AM when it was involved in an industrial dispute. Adam Boulton explained to the Inquiry how he was unable to take cameras with him into the Labour Party conference:<?php footnoteRef('I',2,32); ?></p>
<blockquote>&#8220;...I report that in the context of having been through the TV AM dispute when, at the urging of the ACTT, the Labour Party had done precisely that. They had blacked, as it was then called, TV AM so we could not take our cameras, for example, into the Labour Party Conference of that year so that we &#8211; their spokesmen would not appear on our programmes. And of course, the immediate effect of that is that it means that your offering is weaker than the offering of your competitors, who have full access to all the political parties&#8221;.</blockquote>
  <?php sectionAnchor('I',2,2); ?>Prime Minister Major: 1990-1997</h2>
 <?php paragraphLink('I',2,2,1); ?>In November 1990 Sir John Major took up office with what he himself described as a quixotic approach to the national press.<?php footnoteRef('I',2,33); ?> He was keen to win their support and closely followed political coverage. But he did not seek a close relationship with proprietors and editors. Instead, he kept his distance, leaving contact primarily to others, especially his Press Secretary, a post held throughout his tenure by a civil servant.</p>
  <?php paragraphLink('I',2,2,2); ?>Sir John fared well, initially, so far as newspaper coverage was concerned. The 1992 election was marked by fiercely hostile coverage towards Sir John&#8217;s political rival Lord Kinnock. However, it was not long before sections of the press turned their hostility towards him. By the time of the 1997 election, The Sun and The News of the World had unequivocally transferred their support to New Labour.</p>
  <?php paragraphLink('I',2,2,3); ?>The Major years are undoubtedly important for the work of the Inquiry in relation to media policy because it fell to Sir John&#8217;s Government to consider and respond to the recommendations of Sir David Calcutt QC&#8217;s reports.<?php footnoteRef('I',2,34); ?> Many, including Sir John and Mr Cameron, now consider that the response of the time amounted to a missed opportunity.</p>
  <?php paragraphLink('I',2,2,4); ?>As Prime Minister, Sir John made a conscious choice not to seek a close relationship with any part of the media. He did not think it appropriate and, in any event, he did not share a closely- aligned political ideology or personal affinity with any of the media proprietors of the time. In his own words:<?php footnoteRef('I',2,35); ?></p>
<blockquote>&#8220;As Prime Minister, I did not inherit &#8211; or seek &#8211; a close relationship with any part of the media. I did not go out of my way to engage with the press. This was my own choice, made in part by natural instinct, and in part because the Black and Murdoch press were wedded to a more ideological type of Conservatism than my own. Nor did I engage closely with the Maxwell press or other centre or centrist left titles. This decision was, to an extent, quixotic, since the press are a daily route to the electorate. Nonetheless, a close engagement did not feel comfortable or proper to me and I left relationships with the media largely to the No 10 Press Office &#8211; then staffed exclusively by civil servants &#8211; and, where appropriate, the Party machine...I did not offer any peerages or knighthoods to any national newspaper proprietors or editors ...&#8221; </blockquote>
  <?php paragraphLink('I',2,2,5); ?>Sir John explained to the Inquiry his view that in terms of democratic accountability, the best relationship between the media and senior politicians is one of &#8216;constructive tension&#8217;. It should be neither too friendly nor too oppositional. In particular, if the relationship becomes too close it can become the context for exchanges of self-interest: leaks and stories in return for favourable coverage, as Sir John told the Inquiry had happened to an unnamed politician during the passage of the Maastricht Bill.<?php footnoteRef('I',2,36); ?></p>
  <?php paragraphLink('I',2,2,6); ?>In practice, Sir John did not often meet national newspaper proprietors. He met Mr Murdoch on three occasions (in 1992, 1993 and 1997 respectively), Lord (Conrad) Black on seven occasions and Lord Stevens twice (and attended four social events at his invitation). He did not meet Robert Maxwell at all, although Mr Maxwell did on occasion telephone No 10.<?php footnoteRef('I',2,37); ?> Strikingly, he not only turned down an invitation from Mr Murdoch in August 1993 to attend a &#8220;special celebration&#8221; to mark the launch of new Sky TV channels but also discouraged other Cabinet members from attending.<?php footnoteRef('I',2,38); ?> He met editors and political editors occasionally, typically in the presence of his Press Secretary, and usually for the purposes of explaining a particular policy.<?php footnoteRef('I',2,39); ?> He could recall hosting only one press lunch at Chequers, on 3 December 1995.<?php footnoteRef('I',2,40); ?> Unlike his immediate predecessor, he did not confer any peerages or honours on national newspaper proprietors and editors (although the position was different in relation to regional and magazine editors).<?php footnoteRef('I',2,41); ?></p>
  <?php paragraphLink('I',2,2,7); ?>The difference of approach was put into this context by Mr Campbell:<?php footnoteRef('I',2,42); ?></p>
<blockquote>&#8220;You see, I think a lot of this started under Margaret Thatcher, because I think that newspapers were given a sense of power. The numbers that received the peerages and the knighthoods and the sense that they were almost part of her team. I think it changed under John Major, and then I think when we were in power, I think that we &#8211; I think we maybe did give the media too much of a sense of their own place within the political firmament when we should have challenged it more&#8221;.</blockquote>
  <?php paragraphLink('I',2,2,8); ?>Lord O&#8217;Donnell (as he now is), a career civil servant, served as Sir John&#8217;s Press Secretary between 1990 and 1994 before being succeeded by another civil servant, Sir Christopher Meyer. Lord O&#8217;Donnell&#8217;s brief was to present Government policy on an even-handed basis to all members of the media. This approach marked a change from the higher profile approach of his predecessor, Sir Bernard Ingham, and was associated with the return of the Guardian and The Independent to the lobby. In Lord O&#8217;Donnell&#8217;s own words:<?php footnoteRef('I',2,43); ?></p>
<blockquote>&#8220;Well, I was told by the then cabinet secretary, Robin Butler, that what he wanted me to do in the role as press secretary was to lower the profile of the press secretary &#8211; as you mentioned, Mr Ingham, now Sir Bernard, had a higher public profile &#8211; and to establish very clearly the impartiality of the process. Its relationship with the media needed to change. At the time when I took over as Press Secretary, the lobby briefings had got to a stage where two newspapers, the Guardian and the Independent, had exited the lobby, and my job really was to try and get back to a situation where all newspapers could be represented there and felt able to attend, and indeed the Guardian and the Independent did come back in to the lobby. <br/>
&#8220;So it was trying to establish general principles of the Prime Minister&#8217;s press secretary being there clearly to present, in an impartial fashion, government policy, and to do that equally to all members of the media, both broadcast and newspapers.&#8221; </blockquote>
  <?php paragraphLink('I',2,2,9); ?>The distance which Sir John put between himself and the national press did not prevent his Government from paying close attention to the press or from seeking to get their message across to the press through briefings. Sir Christopher put it in these terms:<?php footnoteRef('I',2,44); ?></p>
<blockquote>&#8220;...Enormous attention was paid to editors of national newspapers &#8211; this extended, to a degree, to regional editors, but not much &#8211; and so a considerable effort went into courting them, bringing them around for privileged one-on-one briefings for example. This was in the early 1990s. I believe that that practice has now expanded phenomenally over the years.<br/>
&#8220;So what it came down to was an exaggerated belief in the influence of the front page headline and commentary columns within. There was an absolute belief that newspapers and their editors could win or lose elections depending on how they reported the stories. <br/>
&#8220;I personally believe that that influence is gigantically exaggerated. <br/>
&#8220;So the result was we did pay &#8211; we, in Downing Street, did pay a lot of attention, more than I thought was necessary, to trying to pull people on board. And of course the more you do that, the more demanding the editors and proprietors, in some cases, become. So I was always a bit sceptical about that.&#8221; </blockquote>
  <?php paragraphLink('I',2,2,10); ?>As Philip Webster, the editor of The Times website and a former political editor with the paper, observed in his evidence, Sir John built good relations with the press on his way to Downing Street.<?php footnoteRef('I',2,45); ?> Once in office, between 1990 and 1992, Sir John received press which he himself thought was appropriate, and regarded as neither especially supportive nor hostile.<?php footnoteRef('I',2,46); ?> That, of course, falls to be contrasted with the extremely negative political coverage that was accorded to the Leader of the Opposition during the same period.</p>
  <?php paragraphLink('I',2,2,11); ?>By 1993, the evidence clearly shows that Mr Murdoch&#8217;s British titles were writing some very hostile, and sometimes very personal, articles about Sir John. A selection of such articles was attached to a briefing note which Lord O&#8217;Donnell produced for the then Prime Minister on 18 August 1993.<?php footnoteRef('I',2,47); ?> Lord O&#8217;Donnell suggested in the note that Sir John took the opportunity of a forthcoming meeting with Mr Murdoch to communicate to him the matters quoted below. In the result Sir John did not consider it appropriate to do so, not least because of the implied threat, but the document nevertheless gives a flavour of the level of concern generated by the adverse press coverage:<?php footnoteRef('I',2,48); ?></p>
  <blockquote>&#8220;Your papers have made matters worse. They have ceased to make rational criticisms of policy. They are now simply anti everything and anti me in particular. (see attached cuttings.) This is bad for economic confidence and hence, bad for business. Longer term political repercussions difficult to assess. Conservative MPs now see no reason to be helpful to media. [Pressure growing over privacy rules, VAT on newspapers, cross-ownership. I am not keen to move on any of these areas but MPs from all parties becoming increasingly attracted to them.]&#8221;</blockquote>
  <?php paragraphLink('I',2,2,12); ?>Peter Riddell described the coverage of the Major Government as becoming &#8220;very hostile&#8221;.<?php footnoteRef('I',2,49); ?> Mr Webster said this:<?php footnoteRef('I',2,50); ?></p>
<blockquote>&#8220;Well, there were occasions I think where the treatment of certain leaders got a little bit &#8211; was over the top, I think. I recall newspaper treatment of Neil Kinnock, John Major, latterly of Gordon Brown, where it got too personal and in a sense I felt that was going a little bit too far. But I don&#8217;t regret the passing of the age of deference at all. I remember in the late 1960s, when I joined the Times, there was a much more deferential attitude of reporters towards politicians. I am rather glad that is all gone. <br/>
It&#8217;s just in some cases I think the treatment has been just a little bit too personal at times.&#8221; </blockquote>
  <?php paragraphLink('I',2,2,13); ?>There were probably many reasons for the change in coverage and the maintenance of its changed course. Antipathy to the Government&#8217;s policies and, in due course, the rise of New Labour were probably amongst them. But Sir John&#8217;s personal relationship, or rather lack of it, with influential media figures of the time was probably also a factor. Mr Murdoch said this:<?php footnoteRef('I',2,51); ?></p>
<blockquote>&#8220;Q. So the support the Sun gave to the Tory Party. not that it was the strongest support, because you, to put it bluntly, weren&#8217;t that appreciative of Sir John Major&#8221;<br/>
 &#8220;A. Or his government. Well, we were reading in all the papers of cabinet divisions&#8221;.</blockquote>
  <?php paragraphLink('I',2,2,14); ?>Kelvin MacKenzie, then editor of The Sun, said something similar:<?php footnoteRef('I',2,52); ?></p>
<blockquote>&#8220;Q. First of all, were your relations with or respect for Mr John Major as good as they were with Baroness Thatcher?<br/>
 A. No, they were &#8211; no, we didn&#8217;t have a &#8211; no, we did not have a particularly good relationship. He was no Thatcher, John Major.&#8221; </blockquote>
  <?php paragraphLink('I',2,2,15); ?>There was a conflict in the evidence of Mr MacKenzie and Sir John in relation to the content of a telephone conversation which both men recalled took place late on Black Wednesday.<?php footnoteRef('I',2,53); ?> Whatever the precise course of the conversation, however, it is noteworthy that the editor of The Sun was amongst those, including HM The Queen and senior ministers, to have been telephoned by the then Prime Minister.</p>
  <?php paragraphLink('I',2,2,16); ?>Sir John put it to the Inquiry that there had developed something of a culture of press hostility to his administration, and personal ridicule of him, which resulted in coverage which went beyond vigorous partisanship, and was not only unfair but inaccurate and misleading. He cited what he considered to be the mischaracterisation of his Back to Basics initiative as a moral crusade, certainly a depiction which had serious repercussions for his Government, and which was associated with (and was claimed as legitimising) highly intrusive coverage of the sexual behaviour of a number of Conservative politicians.<?php footnoteRef('I',2,54); ?></p>
  <?php paragraphLink('I',2,2,17); ?>He also pointed to the caricaturing of the Citizens&#8217; Charter:<?php footnoteRef('I',2,55); ?></p>
<blockquote>&#8220;Similarly, a policy to improve the culture of public services was launched under the title &#8220;Citizens&#8217; Charter&#8221;. This policy was aimed at improving public services, ensuring courtesy to the taxpayer who paid for them, and improving the esteem in which public servants and public services were held. <u>The press undermined this campaign from the outset, through a total misrepresentation of the facts behind it</u> &#8211; led by journalists who seemed to have no experience of public service and little care for it.&#8221; (emphasis added).</blockquote>
  <?php paragraphLink('I',2,2,18); ?>Sir John also pointed to a number of examples of unwarranted press intrusion into his private and family life. These included the following:
  <ol type="a">
<li>intrusion by a tabloid title into the family&#8217;s holiday home in Portugal to rearrange the furniture, take photographs and publish a story; Dame Norma Major telephoned the editor to seek an explanation but was told that she and her husband had &#8220;no right to any privacy&#8221;;<?php footnoteRef('I',2,56); ?> </li>
<li>an attempt to blag personal information about his son&#8217;s then girlfriend:<?php footnoteRef('I',2,57); ?><br/>
&#8220;on another occasion, my office received a telephone call purporting to be from the A&E Department of a hospital. The caller explained that my son&#8217;s then girlfriend had been involved in an accident and that emergency surgery was necessary. However, before this could be carried out, it was vital to know whether she was pregnant. Even though, on the face of it, this enquiry was clearly an urgent one, before giving any response my office made immediate contact with my son&#8217;s girlfriend, who was entirely well and in a meeting. For the record, she was not pregnant&#8221;; </li>
<li>speculative surveillance of his son:<?php footnoteRef('I',2,58); ?>
<br/> &#8220;In circa 1996/7, my son was followed repeatedly by an individual on a motorbike, with a long piece of equipment attached to his bike. My son became very alarmed, since this was at a time when Northern Ireland was a much larger security concern than it is today and &#8211; through his rear view mirror &#8211; he believed the equipment might be a rifle. My son followed the security procedures he&#8217;d been taught to follow, in order to &#8220;shake off&#8221; his pursuer, but to no avail. He therefore continued to drive, and requested assistance from the Cambridgeshire Armed Response Unit who flagged down the motorcycle and pulled it over. It turned out that the rider was a photographer for the News of the World, and the equipment was a telephoto lens. The motorcyclist had been instructed to follow my son &#8220;day and night&#8221;, in the hope of providing a story.&#8221;; and </li>
<li>picture manipulation:<?php footnoteRef('I',2,59); ?><br/>
&#8220;Following the General Election of 1997, I was on a private holiday. Following a picnic on the beach, I tossed an empty bottle to my wife, who was immediately beside me, tidying up. The following day, a series of photographs appeared in one of the British tabloids (from all of which my wife had been airbrushed), accusing me of tossing the bottle onto an empty beach, and thus being a &#8217;litter lout&#8217;.&#8221; </li>
</ol>
</p>
  <?php paragraphLink('I',2,2,19); ?>There was also this from Paul McMullan, the former News of the World journalist:<?php footnoteRef('I',2,60); ?></p>
<blockquote>&#8220;Yeah, I was sent to France &#8211; because I&#8217;d lived there and worked for an agency for a while &#8211; to try and track down the woman who took John Major&#8217;s virginity. This was a while ago. We found her but we couldn&#8217;t get a picture of her with her new boyfriend. So the idea was she traded in John Major, the Prime Minister, for this French wrinkly. I think the cleaner was in the house, so I blagged my way in and pinched it off the mantle piece and copied it. I remember at the time Rebekah Brooks said, &#8220;No, put it back, we&#8217;re not allowed to nick stuff!&#8221; And Piers said, &#8220;No, who cares? Well done. We&#8217;ll put it in the paper.&#8221; Which is what we did.&#8221; </blockquote>
  <?php paragraphLink('I',2,2,20); ?>Sir John nevertheless fairly also said this about his personal coverage:<?php footnoteRef('I',2,61); ?></p>
<blockquote>&#8220;Q. You refer to your disengagement in the first sentence of paragraph 7. Would it be fair to say, though, Sir John, that you were very sensitive about what was written about you by the press? <br/>
&#8220;A. It certainly would be, yes. I wouldn&#8217;t deny that at all in retrospect. It&#8217;s certainly true. I was much too sensitive from time to time about what the press wrote. God knows, in retrospect, why I was, but I was...I woke up each morning and I opened the morning papers and I learned what I thought that I didn&#8217;t think, what I said that I hadn&#8217;t said, what I was about to do that I wasn&#8217;t about to do.&#8221; &#8220;So there was a practical need to know what was going on but did I read them too much? Yes, I did. Was it hurtful sometimes? Yes, it was. Did I think, it was malicious? I think that&#8217;s for others to make a judgment about.&#8221; </blockquote>
  <?php paragraphLink('I',2,2,21); ?>There was a significant exchange between Mr Murdoch and Sir John shortly before the election. Sir John invited Mr Murdoch and his wife to dinner because he had been urged by party officials to &#8220;woo&#8221; newspaper proprietors. Sir John said this about the occasion:<?php footnoteRef('I',2,62); ?></p>
<blockquote>&#8220;...In the run-up to the 1997 election, in my third and last meeting with him on 2 February 1997, he made it clear that he disliked my European policies which he wished me to change. If not, his papers could not and would not support the Conservative Government. So far as I recall, he made no mention of editorial independence but referred to all his papers as &#8220;we&#8221;. Both Mr Murdoch and I kept our word. I made no change in policy, and Mr Murdoch&#8217;s titles did indeed oppose the Conservative Party...&#8221;</blockquote> 
  <?php paragraphLink('I',2,2,22); ?>As Sir John observed:<?php footnoteRef('I',2,63); ?></p>
<blockquote>&#8220;It is not very often someone sits in front of a prime minister and says to a prime minister: &#8220;I would like you to change your policy, and if you don&#8217;t change your policy, my organisation cannot support you&#8221;. People may often think that, they may often react &#8211;but it&#8217;s not often that point is directly put to a prime minister in that fashion, so it&#8217;s unlikely to have been something I would have forgotten.&#8221;</blockquote>
  <?php paragraphLink('I',2,2,23); ?>When Counsel to the Inquiry explored the nature of the opposition of Mr Murdoch&#8217;s papers to his Government at the 1997 election, Sir John said:<?php footnoteRef('I',2,64); ?></p>
<blockquote>&#8220;Q ...the Sunday Times continued to support the Conservative Party and the Times&#8217; position was more equivocal, supporting anybody who happened to be anti-Europe&#8221; <br/>
A &#8220;Well, may I please have a definition of &#8220;support&#8221;? If you mean, did they perhaps write an editorial saying, &#8220;On balance, the least of all evils is the Conservative and you had better vote for them&#8221;, I think the answer is probably that they did. If you mean: was there news coverage day in, day out, morning after morning, weekend after weekend, hostile, then I would have to say to you that I think it was. So I think I would have preferred to have less of the editorial support and more of the equitable news coverage&#8221;.</blockquote>
  <?php paragraphLink('I',2,2,24); ?>He did also acknowledge:<?php footnoteRef('I',2,65); ?></p>
<blockquote>&#8220;...After all, they had written about the Conservative Party between 1992 and 1997, how could they, in all credibility, have then said, &#8220;Despite all we have written over the past five years, we actually invite you to vote for these people we&#8217;ve been telling you are useless for five years&#8221;? I think that would have been quite a difficult editorial position to take&#8221;.</blockquote> 
  <?php paragraphLink('I',2,2,25); ?>More than one commentator has perceived a cyclical nature in the relationship between the press and Prime Ministers, starting well and finishing badly. Mr Riddell suggested:<?php footnoteRef('I',2,66); ?></p>
<blockquote>&#8220;Recent prime ministers &#8211; John Major, Tony Blair, Gordon Brown and David Cameron &#8211;have all sought close relations with the media, at various levels, from proprietors, through editors to political correspondents, during their rise to the top. But, when they have been in office for some time, the relationship has soured as media criticism has increased, and each PM has complained about the stridency, intrusiveness and unfairness of the media. Both the initial closeness and later disillusion have been detrimental to the public interest. It would have healthier to have a more distant, workmanlike, relationship throughout.&#8221; </blockquote>
  <?php paragraphLink('I',2,2,26); ?>Mr Webster agreed:<?php footnoteRef('I',2,67); ?></p>
<blockquote>&#8220;Q. You describe, rather like Mr Riddell, a circle whereby recent prime ministers and you name John Major and Tony Blair as initially having very good relations with the press but eventually becoming disillusioned; would you add Gordon Brown to that list? <br/>
&#8220;A. Yes, I would, yes. I think in all cases they began with good relations. John Major built good relations with the press on his way to Downing Street. But he became very quickly disillusioned with the press afterwards&#8221;.</blockquote> 
  <?php paragraphLink('I',2,2,27); ?>It would be perverse to suggest that Sir John&#8217;s relationship with the press was &#8216;too close&#8217; in the sense of too friendly, or such as to give rise to perceptions of mutual favour. It was, however, certainly personal. The lesson many subsequent politicians took from observation of the personal destructiveness of the press towards political leaders such as Mr Foot, Lord Kinnock and Sir John was a complex one. In part, it had to involve scrupulous reassessment of unpopular policy positions. That in itself contained its own complexities: was unpopularity with the press the same as unpopularity with the public? How far did the press themselves convince the public to dislike a policy, and was that fair or unfair? How should the personal dimension of a political leadership position be considered integral to the political? And, most of all, what could be done about any of it? For some at least, one of the lessons taken from these experiences was that previous relations between politicians and the press had been &#8216;not close enough&#8217;.</p>
  </div>

