<?php 
require_once('../../common.php');
levesonHeader('I',2); 
levesonNav('../../');
levesonBread('I',2);
require_once('content.php');
levesonFooterNav('I',2); 
require_once('footnotes.php');
LevesonCommonFooter();
?>