<div class="content" id="contentPartCChapter3">
<h1 id="top">CHAPTER 3<br/>ALTERNATIVE NEWS PROVIDERS</h1>
 <?php sectionAnchor('C',3,1); ?>Introduction</h2>
 <?php paragraphLink('C',3,1,1); ?>For centuries the printed press was the only medium that brought news to the people. The introduction of broadcasting in the 1920s brought a new voice, but one that had a very different relationship with the public than that of the newspapers with their readers. Technological changes in the last few decades have completely revolutionised the market in which newspapers are working, leading to the fragmentation not only in readership and advertising but also the introduction of news providers that are not currently a part of the self-regulatory, or indeed any other regulatory, regime.</p>
  <?php sectionAnchor('C',3,2); ?>Broadcasters</h2>
 <?php paragraphLink('C',3,2,1); ?>The main source of news in the UK is broadcasting, with 59% of news consumption coming from the three main broadcasters (as opposed to 29% from the six main national newspaper groups).<?php footnoteRef('C',3,1); ?> At the same time broadcasters reach a higher proportion of the public than any individual newspaper title, with 81% of those in the UK who consume news receiving some of their news from the BBC.<?php footnoteRef('C',3,2); ?></p>
  <?php paragraphLink('C',3,2,2); ?>96% of UK households have digital TV,<?php footnoteRef('C',3,3); ?> offering 50 TV channels without subscription<?php footnoteRef('C',3,4); ?> (and many more with subscription), including four free to view 24 hour news channels, with at least another six<?php footnoteRef('C',3,5); ?> 24 hour news channels in some subscription packages. With the significant exception of the BBC these broadcasters are either advertising or subscription funded. This means that broadcasters are competing with newspapers for sales, for audience time, and for advertising revenue. Broadcasters are regulated by Ofcom, operating under statutory powers, and are subject to the Ofcom&#8217;s Broadcasting Code.</p>
  <h3>The BBC</h3>
 <?php paragraphLink('C',3,2,3); ?>The BBC is a national public service broadcaster which is established by a Royal Charter<?php footnoteRef('C',3,6); ?> (this was last renewed in July 2006, and came into force on 1 January 2007)<?php footnoteRef('C',3,7); ?> and a Framework Agreement.<?php footnoteRef('C',3,8); ?> The Royal Charter sets out the objectives and purpose of the BBC.<?php footnoteRef('C',3,9); ?> There also exists a Framework Agreement between the BBC and the Secretary of State for Culture, Media and Sport, which sets out the provisions of the BBC&#8217;s funding and regulatory duties.<?php footnoteRef('C',3,10); ?></p>
  <?php paragraphLink('C',3,2,4); ?>The BBC Trust is the sovereign body, responsible for making overall strategic decisions for the BBC. It has full oversight of the BBC Executive Board.<?php footnoteRef('C',3,11); ?> Lord Patten, the current Chair of the BBC Trust, has made a clear distinction between the responsibilities of the Trust and the BBC Executive. As a sovereign body, the Executive is required to act in accordance with the governance set out by the Trust; equally, the Trust must not exercise the functions that are the responsibility of the Executive.<?php footnoteRef('C',3,12); ?></p>
  <?php paragraphLink('C',3,2,5); ?>A number of individual Boards report into the Executive Board, including the Editorial Standards Board. This is the main editorial forum for the discussion of editorial standards issues facing the BBC by senior editors, and where responses to such issues are formulated and discussed.<?php footnoteRef('C',3,13); ?> The function of the Editorial Standards Board is therefore to monitor and review the editorial compliance systems which are in place at the BBC, in tandem with the Complaints Management Board.<?php footnoteRef('C',3,14); ?></p>
  <?php paragraphLink('C',3,2,6); ?>The former Director General of the BBC, Mark Thompson, explained to the Inquiry that he also served as the Head of the BBC&#8217;s Executive Board. As Editor-in-Chief he was directly responsible for the entirely of the BBC&#8217;s editorial and creative output.<?php footnoteRef('C',3,15); ?> Mr Thompson described the BBC in the following terms:<?php footnoteRef('C',3,16); ?></p>
<blockquote>&#8220;&#8230;the character of public service broadcasting and the character of the BBC&#8217;s editorial mission is different in many respects from that of some newspapers. The kinds [sic] of stories we do are different. In matters of privacy, our focus, when there is a debate about intrusions of privacy, are, I think without exception, in a journalistic context, around investigations into matters which I think everyone would accept were of public interest. &#8230;we don&#8217;t do any investigations into people&#8217;s private lives for their own sake.&#8221; </blockquote>
  <?php paragraphLink('C',3,2,7); ?>The BBC meets its public purpose obligations, set out in the Royal Charter, through the distribution of information, education and entertainment. These are delivered on multiple platforms and include television, radio and online services.<?php footnoteRef('C',3,17); ?></p>
  <h4>Corporate Governance</h4>
 <?php paragraphLink('C',3,2,8); ?>The BBC&#8217;s Editorial Guidelines set out the overarching principles underpinning editorial management at the corporation as well as defining the appropriate structure for that management. These Guidelines, most recently revised in 2010 following a public consultation process, are &#8220;founded on the BBC&#8217;s stated editorial values&#8221;.<?php footnoteRef('C',3,18); ?> The Trust is responsible for commissioning these Guidelines from the Executive Board. In addition to the Guidelines, the BBC must also comply with sections of Ofcom&#8217;s statutory Broadcasting Code,<?php footnoteRef('C',3,19); ?> including the Code on fairness and privacy. This safeguards the treatment of individuals and organisations in programmes broadcasted by the BBC. Compliance with the BBC&#8217;s Editorial Guidelines is the responsibility of the individual editor and producer.<?php footnoteRef('C',3,20); ?> In addition to the Editorial Guidelines, there are separate Producers&#8217; Guidelines. Certain programmes, particularly those which rely on investigative journalism, also have to abide by relevant individual handbooks. The BBC has separate policies relating to complaints, data protection, and fraud management and ant-bribery.</p>
  <?php paragraphLink('C',3,2,9); ?>Different units at the BBC have responsibility for the general oversight of specific regulatory areas. For example, Fraud Management is overseen by the Investigations Unit under the overall supervision of the Chief Operating Officer and the Chief Financial Officer. Data Protection is overseen by the Information and Compliance Unit. With effect from 1 October 2007, the Controller, Fair Trading was appointed as BBC Compliance Officer. There is also a Central Compliance Unit (also established in 2007) which is responsible for monitoring, improving and reporting on the BBC&#8217;s compliance obligations. The Compliance Unit is &#8220;not responsible for delivering compliance but is responsible for ensuring that an appropriate framework is in place to minimise compliance failures.&#8221;<?php footnoteRef('C',3,21); ?> Editorial policy compliance and financial compliance fall outside the remit of the Compliance Unit&#8217;s functions.</p>
  <h4>Regulation of the BBC</h4>
 <?php paragraphLink('C',3,2,10); ?>The BBC is regulated by the BBC Trust. The Trust has a &#8216;supervisory role&#8217; which is generally restricted to the regulation of broadcast content after it has been transmitted.<?php footnoteRef('C',3,22); ?> Lord Patten told the Inquiry that:<?php footnoteRef('C',3,23); ?></p>
<blockquote>&#8220;I would never ever seek to interfere with one of [Mr Thompson&#8217;s] editorial decisions. I wouldn&#8217;t, for example, ever ask to see a BBC programme, at least not in conceivable circumstances, before it was broadcast, if the Director General had decided it was worth broadcasting&#8221;.</blockquote>
  <?php paragraphLink('C',3,2,11); ?>However, Lord Patten also told us that there were occasions where the Trust would consider the principles of the Editorial Guidelines prior to transmission.<?php footnoteRef('C',3,24); ?> The Trust exists to hold the Executive to account, ensuring that the BBC&#8217;s performance is in line with the public purpose set out in the Royal Charter. This includes: the BBC&#8217;s compliance with general law; regulatory requirements; as well as the policies set by the Trust, including editorial guidelines and other codes, strategies and other priorities. To this effect, the duty of the Trust is to ensure that the BBC functions in the interest of licence fee payers.<?php footnoteRef('C',3,25); ?></p>
  <?php paragraphLink('C',3,2,12); ?>Ofcom is responsible for the regulation of some aspects of the content produced by the BBC. This responsibility is defined in the Royal Charter and Framework Agreement, and the Communications Act 2003.<?php footnoteRef('C',3,26); ?> Therefore, the regulatory jurisdiction of the Trust and Ofcom overlap in respect of this content. Ofcom exercises a regulatory function in relation to the BBC&#8217;s commercial activities, notably where they impact on the wider media market. All BBC commercial services must comply with the Ofcom Statutory Code, and Article 29 of the Framework Agreement requires the BBC Trust and Ofcom to create a Joint Steering Group in respect of market impact assessments.<?php footnoteRef('C',3,27); ?> However, the BBC Trust assesses the market impact of &#8220;non-services&#8221; in-house (applying a Public Value Test). There is a clear delegation of function to Ofcom in relation to the assessment of the market impact of the BBC&#8217;s commercial activities. This is accompanied by an express recognition that Ofcom could play a greater role and offer assistance and expertise to the BBC, including in relation to areas which currently fall within the remit of the BBC Trust (such as non services).</p>
  <?php paragraphLink('C',3,2,13); ?>Ofcom also exercises a role of oversight in relation to the editorial content of BBC output, specifically in relation to privacy and fairness. Where Ofcom finds a breach of the privacy or fairness sections of its Code, it may require the BBC to broadcast a statement of its findings.<?php footnoteRef('C',3,28); ?> Further, should Ofcom find that the Code has been breached &#8220;seriously, deliberately, repeatedly, or recklessly&#8221;,<?php footnoteRef('C',3,29); ?> it can impose sanctions which range from a requirement to broadcast a correction or statement of finding to a fine of up to &#163;250,000.<?php footnoteRef('C',3,30); ?> Guidance on right to reply expressly refers to the requirement under the Ofcom Broadcasting Code to afford the person a timely opportunity to respond.<?php footnoteRef('C',3,31); ?></p>
  <?php paragraphLink('C',3,2,14); ?>The Inquiry has heard evidence of situations where editorial incidents have taken place, which have led the BBC Trust to commission independent investigations into apparent breaches of the Editorial Guidelines, and the decision to impose relevant sanctions.<?php footnoteRef('C',3,32); ?> The scandal around the misuse of premium rate phone lines by the BBC in 2007,<?php footnoteRef('C',3,33); ?> in which it was revealed that viewers had been invited to call premium rate numbers in order to enter competitions on programmes that had, in fact, been pre-recorded, is an example. The BBC Executive proposed an action plan and the BBC Trust commissioned an independent report by Ronald Neil. Mr Neil was appointed an independent editorial adviser to the Trust in order to review the Executive&#8217;s action plan. This resulted in the development of new training programmes, including the BBC Academy.<?php footnoteRef('C',3,34); ?> In the interim, audience phone-ins were suspended and a new Interactive Advice and Compliance Unit was created to look at audience interaction with the BBC.</p>
  <?php paragraphLink('C',3,2,15); ?>In October 2008, two radio presenters, Russell Brand and Jonathan Ross, made unacceptable phone calls to Andrew Sachs in the course of a radio programme aired in that month.<?php footnoteRef('C',3,35); ?> In December 2008, BBC Management announced an action plan to address the editorial failings which had led to the programme being broadcast.<?php footnoteRef('C',3,36); ?> The progress made under this action plan was then subject to an independent review carried out by Tony Stoller (former Chief Executive of the Radio Authority) and Tim Suter (former broadcasting partner and Board member at Ofcom) for the BBC Trust.<?php footnoteRef('C',3,37); ?> Both the BBC Executive and the BBC Trust reported on the findings of that independent review.</p>
  <?php paragraphLink('C',3,2,16); ?>Speaking to the importance to the BBC of addressing these failings in editorial conduct, Mr Thompson told the Inquiry about his role in informing the public of the necessary controls that have since been implemented, that:<?php footnoteRef('C',3,38); ?></p>
<blockquote>&#8220;&#8230;it&#8217;s fundamental to my duty in this role. I think my job is to &#8211; to &#8211; not just to sit on top of a management machine and try and optimise it for editorial compliance &#8211; that&#8217;s, you know, in a senses, part of what one has to do to try and get the right result &#8211; but also to take responsibility for what the BBC broadcast and also to take personal responsibility for occasions when we have fallen short of our high standards.&#8221; </blockquote>
  <?php paragraphLink('C',3,2,17); ?>The recent revelations of sexual abuse by Jimmy Savile, and decisions around the Newsnight investigation into the matter, have raised questions in some quarters as to the effectiveness of broadcasting regulation and the internal governance systems within the BBC. None of this is a matter for this Inquiry, and there are separate inquiries into the specific issues. I merely note that, without in any way prejudging any of those investigations, the original Newsnight investigations, the ITV documentary that ultimately revealed the allegations, and the subsequent Panorama programme that investigated the handling of the matter within the BBC, were produced within the constraints of broadcasting regulation, not by the print press. Any attempt, therefore, to suggest that broadcasting regulation has had any part in constraining reporting on the matter is simply not borne out by the facts.</p>
  <h4>Complaints system</h4>
 <?php paragraphLink('C',3,2,18); ?>The BBC is required to comply with the Royal Charter and the Framework Agreement. Complaints to the BBC therefore have an important role to play:<?php footnoteRef('C',3,39); ?></p>
<blockquote>&#8220;The BBC&#8217;s complaints handling framework (including appeals to the Trust) is intended to provide appropriate, proportionate and cost effective methods of securing that that BBC complies with its obligations and that remedies are provided which are proportionate and related to any alleged non-compliance.&#8221; </blockquote>
  <?php paragraphLink('C',3,2,19); ?>The Trust has the role of final arbiter in appropriate appeals, and has responsibility for setting the BBC&#8217;s complaint framework.<?php footnoteRef('C',3,40); ?> A Trust Protocol is established by the Trust, which oversees the procedures for specific areas of complaint, including editorial complaints.<?php footnoteRef('C',3,41); ?> This is to ensure a clear division of responsibilities between the Trust and the Executive. The Trust does not have a role in handling or adjudicating upon individual complaints in the first instance, unless the complaint is concerning the act or omission of the Trust itself.<?php footnoteRef('C',3,42); ?> In this regard, the responsibility as final arbiter is delegated to the Editorial Standards Committee.</p>
  <?php paragraphLink('C',3,2,20); ?>Any BBC viewer who is dissatisfied with any of the content broadcasted by the BBC may submit their complaint directly to the Corporation. Complaints that relate to fairness or privacy can also be made to Ofcom, in line with their regulatory jurisdiction over this form of content. Although the complainant can submit complaints relating to impartiality or accuracy issues to Ofcom,<?php footnoteRef('C',3,43); ?> it is unlikely that Ofcom would entertain these types of complaints. Lord Patten told the Inquiry that, in practice, Ofcom would inform the complainant that such a complaint could be dealt with by the BBC.<?php footnoteRef('C',3,44); ?> Equally, the Editorial Standards Committee is unlikely to consider a fairness and privacy or standards matter which overlaps with the regulatory responsibilities of Ofcom, until Ofcom has completed its own processes.<?php footnoteRef('C',3,45); ?></p>
  <?php paragraphLink('C',3,2,21); ?>Lord Patten explained the nature of the complaints system, whereby viewer complaints are dealt with at the first stage by the executive&#8217;s information department (possibly including the producers of the programme in question itself). Should no resolution result from this first stage of mediation, viewers can take complaints to a second stage process where they are handled by the complaints unit, governed by the Complaints Management Board (which reports directly to the BBC Direction Group).<?php footnoteRef('C',3,46); ?> The last stage is the process of appeal to the Trust, should the complaint be unresolved to the satisfaction of the viewer.<?php footnoteRef('C',3,47); ?></p>
  <?php paragraphLink('C',3,2,22); ?>There is a recognition that the complaints system requires improvement, particularly in order to speed up the process of reply. Lord Patten&#8217;s review of BBC Governance expressly acknowledged licence fee payers had expressed concerns that the current system was &#8220;too complicated and too slow&#8221;. He told the Inquiry that he has recommended the appointment of a &#8220;chief of editorial complaints, of corrections&#8221; ,<?php footnoteRef('C',3,48); ?> whose role would be to ensure that the system was improved and operated in a transparent manner. The Governance Report concluded that the BBC should publish a single page guide explaining where complainants should go to complain about BBC broadcast content or services. Lord Patten told the Inquiry that the BBC will work with Ofcom to ensure there is common language in the guide to explain in what circumstances complainants may complain to Ofcom. Other recommendations from the Governance Review include the streamlining of the appeals process and regular impartiality reviews. Concerns were also raised about the correction of mistakes made online on the BBC website.</p>
  <?php paragraphLink('C',3,2,23); ?>In 2007, the BBC Editorial Standards Committee recorded that 94% of complaints had been dealt with within ten working days. In this regard, Mr Thompson informed the Inquiry that:<?php footnoteRef('C',3,49); ?></p>
<blockquote>&#8220;The BBC receives well over a million contacts from the public every year, of which only a relatively small proportion are complaints, but that still adds up to something like 240,000 complaints a year, of which the overwhelming majority are responded to very quickly. We have a target of responding in ten days. I think we&#8217;re currently at 93,94 per cent of that target, and in, again, the overwhelming majority of cases, the complaint is satisfactorily dealt with at that stage.&#8221; </blockquote>
  <h3>ITN</h3>
 <?php paragraphLink('C',3,2,24); ?>ITN is a news provider responsible for the production of the news programme for the broadcast channel, ITV. ITN also produce Channel 4 News, through a contractual agreement between ITN and Channel 4.<?php footnoteRef('C',3,50); ?> The Chair of ITN, Maggie Carver, is responsible for the organisation, but delegates editorial matters to the Chief Executive Officer, John Hardie, who is responsible for the management of editors of both ITV News and Channel 4 News.<?php footnoteRef('C',3,51); ?> Ms Carver is responsible for ensuring that the corporate governance set out by the company is adhered to by staff. In part, this is done through the ITN&#8217;s Compliance Manual, the ITN Health and Safety Manual and the Ofcom Code.<?php footnoteRef('C',3,52); ?></p>
  <?php paragraphLink('C',3,2,25); ?>Compliance at ITN is the responsibility of the Head of Compliance, John Battle.<?php footnoteRef('C',3,53); ?> Mr Battle is author of the Compliance Manual, first published in July 2004. The Compliance Manual sets out &#8220;the industry regulations that affect news reporting, the main areas of laws affecting journalism such as libel, copyright, privacy and contempt of court and internal ITN standards and procedures.&#8221;<?php footnoteRef('C',3,54); ?> This manual is the centrepiece guidance issued to staff at ITN and forms the basis of ITN staff training.</p>
  <?php paragraphLink('C',3,2,26); ?>ITN recently reviewed its Compliance Manual in light of allegations of phone hacking, as well as allegations of payments to public officials by journalists and others working at the NoTW. Although Jim Gray, Editor of Channel 4 News, told the Inquiry that the review of the Compliance Manual was regular procedure, he explained that additionally &#8220;as part of the process triggered by this Inquiry, we have held an independent external Inquiry into ITN&#8217;s journalistic practices and some the [sic] findings of that will feature in the new Compliance Manual.&#8221;<?php footnoteRef('C',3,55); ?> Mr Battle also gave evidence to this effect, stating that:<?php footnoteRef('C',3,56); ?></p>
<blockquote>&#8220;It&#8217;s fair to say that as a grown-up and professional organisation, we&#8217;d have to have on board the Inquiry and what&#8217;s been discussed here and within the news. There have been some tightening up procedures, tilting, as you said this morning, sir, towards better regulation. I don&#8217;t think there&#8217;s been substantive changes as a result of this Inquiry but it also includes a lot of updates on other issues, such as Twittering in court or online posting, so it&#8217;s an update.&#8221;</blockquote>
  <h3>Channel 4 News</h3>
 <?php paragraphLink('C',3,2,27); ?>Mr Gray is responsible for the entirety of editorial content of Channel 4 News, and for upholding relevant policies to ensure that journalists and individual editors at Channel 4 News are required to comply with the ITN Compliance Manual.<?php footnoteRef('C',3,57); ?> Mr Gray reports directly to Mr Hardie, ITN&#8217;s Chief Executive Officer. Mr Gray told the Inquiry that Channel 4 News applied similar principles to the Omand principles,<?php footnoteRef('C',3,58); ?> which are &#8220;a whole series of tests about the proportionality of what is being proposed matches the level of gravity of what the story may be&#8221;.<?php footnoteRef('C',3,59); ?></p>
  <?php paragraphLink('C',3,2,28); ?>Mr Gray describes Channel 4 News as a public service news broadcaster with an editorial focus on news that is in the public interest. He has said that consideration is given as a matter course to issues of privacy, consent, and public interest; all of which are built into the ITN Compliance Manual.<?php footnoteRef('C',3,60); ?> He also told the Inquiry that there is a culture at Channel 4 News of behaving ethically and acceptance of journalists being held to account for their reporting. Mr Gray said in this regard that:<?php footnoteRef('C',3,61); ?></p>
<blockquote>&#8220;We don&#8217;t want to cause any problems, and we certainly don&#8217;t want so [sic] have any incoming attack on our reputation or integrity which would then go forward to possibly damage Channel 4&#8217;s repute, which we are contractually obliged to uphold and we must uphold and we want to.&#8221; </blockquote>
  <h4>Corporate governance at ITN and Channel 4 News</h4>
 <?php paragraphLink('C',3,2,29); ?>Mr Battle explained that although ITN is not a content broadcaster, the organisation is still obliged to operate in accordance with the Ofcom Broadcasting Code, as well as with the expectations and requirements of the individual broadcasters, ITV or Channel 4.</p>
  <?php paragraphLink('C',3,2,30); ?>There are three levels of compliance within Channel 4 News: the ITN system and core Compliance Manual; the Channel 4 independent producers&#8217; handbook; and contractual obligations between ITN and Channel 4 which require consultation and notice in certain circumstances. Mr Gray told the Inquiry that the compliance manual &#8220;adds layers of practice, best practice and how to go around carrying out such investigations&#8221;.<?php footnoteRef('C',3,62); ?> Separately, under the Ofcom Broadcasting Code, Channel 4 News is obliged to offer timely and appropriate rights of reply to the subject of a story.<?php footnoteRef('C',3,63); ?> Mr Gray also described how Channel 4 News would approach a story that might involve potential breach of privacy:<?php footnoteRef('C',3,64); ?></p>
<blockquote>&#8220;&#8230;if it was a serious allegation of wrongdoing or criminality, we would normally expect to contact the subject of the story in writing, putting forward the claims and the allegations and the evidence we had for what was going to be proposed to be contained in the report, and then give sufficient amount of time for the subject to respond. That can vary, That&#8217;s not set down but it could be a matter of days or it could be longer. In some cases, depending on the response from the subject, it can drag on. &#8230;That&#8217;s part of the way it is and if you have a real good story, you will navigate your way through that.&#8221; </blockquote>
  <?php paragraphLink('C',3,2,31); ?>Commenting on the role of Ofcom in relation to Channel 4, and Channel 4 News, Mr Gray told the Inquiry that the Ofcom Broadcasting Code helps to codify the principles and cultural standards that Channel 4 News seeks to uphold. He explained this thus:<?php footnoteRef('C',3,65); ?></p>
<blockquote>&#8220;&#8230;through the ITN guidelines, [we] turn [the Code] into practice, and that&#8217;s helpful as well, because for the team at ITN, that makes it our guidelines. It&#8217;s not an external imposition. This is our culture we&#8217;re expressing in the guidelines. It makes it more of a collaborative venture rather than: we&#8217;re only doing this because of &#8211; it&#8217;s a series of hurdles we have to overcome to get there. It can feel like that but it makes the journalism better at the end result.&#8221; </blockquote>
  <h4>Complaints system</h4>
 <?php paragraphLink('C',3,2,32); ?>In relation to complaints handling, Mr Battle told the Inquiry that ITN does not receive many complaints through Ofcom. He noted that, on average, ten complaints might be received in the course of a given year, and not all of these would be of a substantial nature.<?php footnoteRef('C',3,66); ?> Complaints in relation to Channel 4 News are handled by Mr Gray&#8217;s Deputy Editor at Channel 4 News, who consults closely with the production team. The complaints are assessed in relation to the report in question with the Head of Compliance, documented as appropriate in consultation with Channel 4. Mr Gray explained that only in serious cases would a complaint be referred to him.<?php footnoteRef('C',3,67); ?> However, should a complaint be submitted through Ofcom, then the complaint would be handled in accordance with the terms set down by the regulator. Mr Gray explained that Channel 4 News had received remarkably few complaints and, specifically, over the course of five years, &#8220;we haven&#8217;t actually had a finding against us from an Ofcom complaint except once&#8230; and that was a partial ruling against us on an investigation&#8221;.<?php footnoteRef('C',3,68); ?></p>
  <?php sectionAnchor('C',3,3); ?>The World Wide Web</h2>
 <?php paragraphLink('C',3,3,1); ?>The media landscape, particularly the provision of news, both globally and in the UK has been transformed by the invention and phenomenal development of the Internet. At its simplest the Internet is a system of interconnected computer networks which use a standardised address system to enable the identification of each of the electronic devices that make up the network. Now literally billions of machines are linked. This means that huge quantities of increasingly complex information can be stored and accessed at ever greater speeds. It also means that the services that media providers can offer through the Internet to consumers can be ever more sophisticated, personalised and immediate.</p>
  <?php paragraphLink('C',3,3,2); ?>In terms of access and reach, 74% of adults in the UK have access to broadband, with average actual speeds of 6.8Mbit/s.<?php footnoteRef('C',3,69); ?> 22% of all the time that adults spend engaging with media is spent on the internet, with this figure rising to 30% for those aged between 16 and 24.</p>
  <?php paragraphLink('C',3,3,3); ?>The Internet also enables citizens to access news generated by sources across the world.<?php footnoteRef('C',3,70); ?> All UK media organisations, whether newspapers, broadcasters or others now have an internet presence. Most of that content is available for free, although some, including some UK publishers, have begun to charge for online content. This free content can be accessed directly where the user knows what they are looking for, or can be found through search engines.</p>
  <?php paragraphLink('C',3,3,4); ?>In addition to the individual websites of the world&#8217;s news providers there are news aggregation services. Where a site is acting as an aggregator, it directs users to material created by others. These sites tend to rely on automatic selection through algorithms and usually involve no active editorial involvement by the aggregator. In some circumstances this will involve simply directing the user to the website of the news provider. In others, it involves essentially importing the news report from the original provider to the site of the aggregator. In the latter case this will mean that any associated advertising revenues will go to the aggregator rather than to the news provider. These sites are characterised by the fact that those operating the sites have little or no editorial input to the content of the material that they provide to users, take no responsibility for the accuracy of articles to which their users are directed, and have no role in the newsgathering process.</p>
  <?php paragraphLink('C',3,3,5); ?>Although some news sites are merely aggregators of news, linking to content hosted by other news websites, Google news is different. It is a function within Google that will search for material only through online news content.<?php footnoteRef('C',3,71); ?> However, the content itself is not generated by Google, nor does Google operate any editorial control over the searched content beyond the algorithms that facilitate the search.<?php footnoteRef('C',3,72); ?></p>
  <?php paragraphLink('C',3,3,6); ?>In addition to the presence that traditional providers have on the internet, recent years have also seen the growth of completely new approaches to news generation and provision. One example is the rise of blogs and other web-based news, current affairs and celebrity commentary. Blogs and other commentary come in a number of different forms, but are essentially a personal commentary. They can include examples of &#8216;citizen journalism&#8217; produced by individuals sharing their experience of, and views on, events that occur.</p>
  <h3>Regulation of the Internet</h3>
 <?php paragraphLink('C',3,3,7); ?>In evidence to the Inquiry, the Internet has been described as an unregulated space, in which businesses can avoid the regulation of a given jurisdiction by hosting the content they publish in a different legal jurisdiction. Witnesses to the Inquiry have said that this creates an imbalance with market consequences between what might be written by UK newspapers and what might be published by websites hosted abroad.<?php footnoteRef('C',3,73); ?> Witnesses have pointed to the publication of photos of, in particular, Prince Harry and the Duchess of Cambridge, which though different in terms of the surrounding circumstances, highlight issues around the existence of different jurisdictions and regulatory regimes as applied to the press and the Internet. The Sun has argued that the ready availability of photographs of Prince Harry on the Internet justified in part its decision to publish those same photographs.<?php footnoteRef('C',3,74); ?></p>
  <?php paragraphLink('C',3,3,8); ?>To some extent, this is an accurate if very cursory reflection of the regulatory picture with regard to the Internet. However, it is a simplification that ignores what is a more complex picture. Certainly, the very nature of the Internet does not lend itself to regulation. It is a global network made up of a very large number of interconnected, largely autonomous networks, operating from many different legal jurisdictions without any obvious central governing body. Indeed, in many ways this loose and lightly regulated structure has been encouraged by governments and by users as a source of both innovation and growth.</p>
  <?php paragraphLink('C',3,3,9); ?>This does not mean, however, that the Internet is without any governing principles. To ensure interoperability of the constituent networks, as well as consistent policy on addressing, addresses and standards are administered by the Internet Corporation for Assigned Names and Numbers (ICANN), based in California, at which the UK Government is represented.</p>
  <?php paragraphLink('C',3,3,10); ?>Access to Internet services is also regulated in the UK and Europe through telecommunications legislation as regulated by Ofcom. Internet services have predominantly been provided through the national copper wire telecoms network. The transmission of content wirelessly through the national radio spectrum network is regulated through the Wireless Telegraphy Act 2006 and has regulatory impacts for access to the Internet through wireless devices other than computers such as mobiles phones (especially smart phones like the iPhone), and other Internet enabled devices such as tablets (like the iPad and Kindles).</p>
  <?php paragraphLink('C',3,3,11); ?>In addition, just as the general law applies online as it does offline, some forms of online content are also regulated. Broadcast content, known as video on demand when it is made available online, through for example the BBC iPlayer service, or in the case of Channel 4, through 4oD, is regulated by the Audiovisual Media Services Regulations 2009 and the Audiovisual Media Services Regulations 2010, by the Authority for Television on Demand (ATVOD). The necessary powers for the regulation of these services are delegated to ATVOD by Ofcom through a formal designation. These ensure that protections similar to those applied to broadcast content are applied to that same or similar content when made available online.</p>
  <?php paragraphLink('C',3,3,12); ?>In addition to regulation of broadcast and equivalent content through ATVOD, UK Internet Service Providers have also taken a broadly self-regulatory approach to some of the content they host and have applied a limited number of standards to that content. In many circumstances, ISPs and others have cooperated with law enforcement and other agencies to remove illegal content or block access to it. The Internet Watch Foundation (IWF) is an example of this self- regulatory approach. The IWF works closely with ISPs to ensure that webpages, including those hosted outside of the UK, which provide access to potentially criminal content and, specifically, images of child abuse, are reported and removed or blocked at source.</p>
  <?php paragraphLink('C',3,3,13); ?>The current reliance on collaborative approaches and industry self-regulation does not mean that enforcement of UK law online is not possible. However, successful prosecution relies on considerable cooperation across a number of agencies, not least the ISPs and content providers, and is most effective where the alleged act is also clearly criminal in the host country.</p>
  <?php paragraphLink('C',3,3,14); ?>To this end, it is worth noting that Twitter and other social media have cooperated with UK law enforcement in cases of obvious criminality. During the rioting in the summer of 2011, both RIM Blackberry and Twitter worked closely with police and other enforcement agencies to identify those using social media and communications networks to perpetrate or help commit criminal acts. In 2011, Lancashire County Council also worked with Twitter to identify and bring prosecutions against individuals suspected of tax avoidance.</p>
  <?php paragraphLink('C',3,3,15); ?>This relative lack of internet specific regulation is unlikely to change. The Government made clear that it sees the Internet as a key driver of future economic growth and innovation, and has made public its commitment to an open but responsible Internet.<?php footnoteRef('C',3,75); ?> This should be understood as an internet in which all legal content is available and there is no blocking of sites or discriminatory practice (such as prioritising one very similar product over another), and where the industry works together with Government to deliver solutions to issues particularly in relation to: <ul>
 <li>e-Accessibility;</li>
 <li>harmful and inappropriate content; and</li>
 <li>copyright.</li>
 </ul>
 </p>
  <?php paragraphLink('C',3,3,16); ?>Where legislation has been brought forward in relation to the Internet,this has been in response to legislative changes decided at a European level, intended to protect the privacy of users. Changes to the law have extended the powers available to the Information Commissioner&#8217;s Office to ensure that it has appropriate tools to do its job effectively in a digital age.<?php footnoteRef('C',3,76); ?> These changes have extended the enforcement powers available to the ICO under the DPA into the Privacy and the Electronic Communications Regulations (PECR), and include powers to: <ul>
 <li>levy civil monetary penalties for PECR offences;</li>
 <li>compel Communication Providers to disclose the identity of third parties; and</li>
 <li>amend Assessment Notice powers which will enable the ICO to compel organisations to submit to an e-privacy audit.</li>
 </ul>
 </p>
  <?php paragraphLink('C',3,3,17); ?>The changes have been made in response to concerns at a number of high-profile data breaches, some as a consequence of criminal hacking, others by the apparent unwillingness of service providers to pay full heed of data protection legislation (as in the case of the unintentional interception of data from wifi-wireless and remote internet devices by Google in 2009).<?php footnoteRef('C',3,77); ?></p>
  <?php paragraphLink('C',3,3,18); ?>This has been alluded to in evidence given to the Inquiry. Google stated that privacy online was a matter of growing importance to the company. David John Collins, Vice President of Global Communications and Public affairs for Google, explained that the company&#8217;s attitude towards privacy online and related matters has changed considerably with time reflecting both the growth in the use of online services and the changing legal landscape with regard to the internet.<?php footnoteRef('C',3,78); ?> Mr Collins said:<?php footnoteRef('C',3,79); ?>
<blockquote>&#8220;Google has always taken privacy seriously from a very strict compliance position; it&#8217;s taken privacy seriously because ultimately the trust that we have with our users is incredibly important.&#8221; </blockquote>In this respect Google has worked hard to improve public awareness of privacy issues online, and in January 2012 launched the &#8220;good to know campaign&#8221; which actively sought to raise public awareness of privacy tools in relation to email, social network accounts and other online functions that might help users to protect their privacy online.<?php footnoteRef('C',3,80); ?></p>
  <?php sectionAnchor('C',3,4); ?>Blogs and other web-based commentary</h2>
 <?php paragraphLink('C',3,4,1); ?>The Inquiry heard evidence in regard to the operation of blogs, online news aggregators, publishers, social network sites and online hosts.</p>
  <?php paragraphLink('C',3,4,2); ?>There are a number of news blogs &#8211; the Huffington Post is an early, high profile example of one, which has developed over the years into something much more like an online newspaper &#8211; which specifically aim to bring a range of news stories and views on those stories to their readers. Other examples include the Guido Fawkes Blog, which focuses on &#8216;tittle-tattle, gossip and rumours&#8217; about Parliament;<?php footnoteRef('C',3,81); ?> the Jack of Kent Blog,<?php footnoteRef('C',3,82); ?> which describes itself as &#8216;liberal and critical&#8217;; and Popbitch, which is a celebrity newsletter and message-board. Camilla Wright, co-founder of Popbitch, told the Inquiry that her intention in founding Popbitch was to create a publication like Private Eye for the celebrity world that would:<?php footnoteRef('C',3,83); ?></p>
<blockquote>&#8220;... look at the hypocritical gap between how those in the public eye seek to be portrayed and how they really act.&#8221; </blockquote>
  <?php paragraphLink('C',3,4,3); ?>There is no single format for these types of sites and individual sites can evolve, and have evolved, a great deal over time. Whereas Popbitch is clear in its ambition to entertain and understands itself to &#8220;poke fun&#8221; and comment on the &#8220;lighter&#8221; side of celebrity culture, Guido Fawkes, though ostensibly and in many respects similar, is different in nature. Paul Staines, the founder of the Guido Fawkes website, stated that Guido Fawkes actively seeks to break stories and prides itself on doing so ahead of the main news providers.<?php footnoteRef('C',3,84); ?></p>
  <?php paragraphLink('C',3,4,4); ?>The type and size of audience attracted by such blogs varies hugely and depends unsurprisingly on the content they carry. For example, Mr Staines told the Inquiry that the Guido Fawkes site generally had between 50,000 and 100,000 readers daily. However, when very big stories are being broken this can rise to as many as 100,000 visitors per hour.<?php footnoteRef('C',3,85); ?> Mr Staines estimated that between 25% and 30% of his readers reached the site through search engines.<?php footnoteRef('C',3,86); ?> Popbitch, by contrast, has 350,000 subscribers, whilst Holy Moly, which also covers celebrity news and gossip, serves 6.5 million page impressions a month to 1.6 million people.<?php footnoteRef('C',3,87); ?></p>
  <?php paragraphLink('C',3,4,5); ?>In addition to the stand-alone blogs and sites described above, many established news providers also use blogs &#8211; for example the Guardian has been running a live blog on the Leveson Inquiry since the first of the Inquiry seminars &#8211; either for specific events or issues, or just by way of communicating with readers in a different manner. At the other end of the spectrum, many individuals run blogs on matters which are of interest to them, some of which will, from time to time, cover issues of news or current affairs and some which may well break stories if the people writing them are well placed to do so.</p>
  <?php paragraphLink('C',3,4,6); ?>These vastly different sites are all offered to the public in the same way; they all have the same theoretical reach to the entire internet-connected population at the touch of a button (particularly when facilitated by search engines). They are also, with the regulatory exceptions set out above, entirely unregulated, though subject to civil and criminal law in appropriate jurisdictions. However, it is noteworthy that although the blogs cited here are read by very large numbers of people, it should not detract from the fact that most blogs are read by very few people. Indeed, most blogs are rarely read as news or factual, but as opinion and must be considered as such.</p>
  <h3>Purpose and process</h3>
 <?php paragraphLink('C',3,4,7); ?>Ms Wright explained the nature and purpose of Popbitch as a gossip site. She said that she believed that the public had a right to know certain facts about certain celebrities, particularly given the ability of some to &#8220;shape and influence people&#8217;s lives.&#8221;<?php footnoteRef('C',3,88); ?> Ms Wright argued that it is only right that publishers should bring material to the attention of the public if it brings to light what she described as the &#8220;gap between people&#8217;s private life and public life .&#8221;<?php footnoteRef('C',3,89); ?> This she argues is not only very much in the public interest but is a reflection of everyday concerns that individuals may have, as well as the reality of celebrities and others putting potential personal or private information into the public domain through Facebook and other social media, that might sit uneasily or indeed at odds with their public persona.<?php footnoteRef('C',3,90); ?></p>
  <?php paragraphLink('C',3,4,8); ?>Ms Wright acknowledged that this may mean that the line between what is private and what might be made public is fluid and dependent on context:<?php footnoteRef('C',3,91); ?></p>
<blockquote>&#8220;We draw the line, I would say, we look at who is making themselves influential, and if so are they living up to it.&#8221; </blockquote>
  <?php paragraphLink('C',3,4,9); ?>Understandably perhaps, for a relatively small operation, the standards of proof deployed by Ms Wright are lower, and the processes different from those that might be found on a print newspaper. Ms Wright said in relation to the corroboration of stories:<?php footnoteRef('C',3,92); ?></p>
<blockquote>&#8220;If it is a contentious or controversial story, I would want to get someone else to back up what they&#8217;re saying and try and find if possible, some evidence to support what they&#8217;re both saying.&#8221; </blockquote>
  <?php paragraphLink('C',3,4,10); ?>Ms Wright also explained that whilst Popbitch may not have formal processes for establishing whether content might be in the public interest or a breach of privacy, the company does consult with and take advice from media lawyers, who have at times provided extracts from the Editors&#8217; Code of Conduct which they perceive might be useful for Popbitch to consider.<?php footnoteRef('C',3,93); ?></p>
  <?php paragraphLink('C',3,4,11); ?>Much as Popbitch understand itself to provide information to the public that it determines to be in the public interest, Guido Fawkes also prides itself on its ability to deliver stories it understands to be in the public interest, that might otherwise remain unknown. Mr Staines said:<?php footnoteRef('C',3,94); ?></p>
<blockquote>&#8220;I particularly don&#8217;t think people in public life, people who are, you know, paid for by the taxpayers, or subject to the voters, should expect the same degree of privacy as a private citizen who has no public life can expect. These people &#8211; their character speaks to what the voters need to know about them as politicians, so if they misbehave in their private life &#8211; it&#8217;s quite common that somebody who will lie to their wife will lie to the voters. That&#8217;s an old adage that has some truth to it.&#8221; </blockquote>
  <?php paragraphLink('C',3,4,12); ?>Indeed, Mr Staines stated in evidence that he would publish information that he assessed to be in public interest even if that information was the subject of a legally enforceable injunction. He referred in evidence to material made available by his blog which a court had ordered should be removed from the internet.<?php footnoteRef('C',3,95); ?> This is explored in more detail below.<?php footnoteRef('C',3,96); ?></p>
  <?php paragraphLink('C',3,4,13); ?>Mr Staines also gave evidence on the standards and editorial processes he deploys with regard to the content he publishes. He said that in many cases he is unable to corroborate stories through a second source:<?php footnoteRef('C',3,97); ?></p>
<blockquote>&#8220;Yeah, quite often there&#8217;s only one source in the room who can provide us with information, so we have no choice. We don&#8217;t rely on single sourcing from people we don&#8217;t know. There has to be some authority to that person or we have to have a level of trust built up over time. If someone came in fresh and was a single source we couldn&#8217;t verify in any way whatsoever, I&#8217;d be very reluctant to run with it.&#8221; </blockquote>
  <?php paragraphLink('C',3,4,14); ?>Mr Staines also made clear that accuracy was as important to the credibility of a blog site like Guido Fawkes as it was for a print newspaper. It is for this reason that the majority of material sourced by Mr Staines was either verifiable or from a trusted source. Only some 10% of material might be from an unknown source.<?php footnoteRef('C',3,98); ?></p>
  <?php paragraphLink('C',3,4,15); ?>Additionally, Mr Staines told the Inquiry that journalists occasionally provided him with material that an editor may have decided not to publish (that had been spiked), or that might not fit with the overall agenda of the publication in question.<?php footnoteRef('C',3,99); ?> As such Guido Fawkes provides a valuable vehicle for publication of such content. Guido Fawkes also receives material that journalists want to push further and establish whether the story in question has legs.<?php footnoteRef('C',3,100); ?></p>
  <?php paragraphLink('C',3,4,16); ?>Mr Staines also stated, in a parallel that he himself has drawn with the former editor of The Sun, Kelvin Mackenzie, that he would run stories that are single sourced if the story was of little consequence, or in keeping with the overall tone of the Guido Fawke s site, namely, that it was gossipy or humorous in nature.<?php footnoteRef('C',3,101); ?></p>
  <?php paragraphLink('C',3,4,17); ?>Much as the Guido Fawkes site is used as a proxy by some newspapers and a means of running stories that might lead to a newspaper being challenged, Ms Wright said that Popbitch is also occasionally used by journalists from print newspapers in this manner. However, Ms Wright made clear that is a practice that she generally seeks to avoid. She noted that such an approach has not happened for some time.<?php footnoteRef('C',3,102); ?> Ms Wright was also keen to emphasise that she would only publish such information if it were in the public interest. This, she said, has not yet happened.<?php footnoteRef('C',3,103); ?></p>
  <?php paragraphLink('C',3,4,18); ?>The Inquiry also heard evidence from the Carla Buzasi, Editor in Chief of the Huffington Post UK. In contrast to either Popbitch or Guido Fawkes, the Huffington Post UK is not a blog built around the knowledge and gossip of a given area, it is an online newspaper employing trained journalists and abiding by journalistic standards as set out in the Editors&#8217; Code of Practice, as well as participating in the system of self-regulation for the press through the PCC.<?php footnoteRef('C',3,104); ?> The Huffington Post UK also functions as a news aggregator and links to news content hosted on other websites, as well as hosting blogs for the discussion and dissemination of opinion.</p>
  <?php paragraphLink('C',3,4,19); ?>Ms Buzasi gave evidence on the importance of trust to the Huffington Post UK, and particularly to its reputation as a news source. This has informed editorial and management decisions made around training and editorial guidelines.<?php footnoteRef('C',3,105); ?> It is therefore expected that all stories are verifiable and are not single sourced. However, Ms Buzasi acknowledged that there may be a limited number of circumstances in which single sourcing was acceptable, but it was not the rule.<?php footnoteRef('C',3,106); ?> A similar emphasis on trust is placed on those news sites that the Huffington Post UK will link to.</p>
  <h3>Regulation of blogs</h3>
 <?php paragraphLink('C',3,4,20); ?>Blogs and other such websites are entirely unregulated. The Huffington Post UK is unique in having opted to subscribe to the PCC. It is the only solely online news provider to have elected to this and did so in September 2011. Ms Buzasi suggested that membership of the PCC was a natural next step for the Huffington Post UK as it had long abided by the terms of the Editors&#8217; Code of Practice. However, she expressed some frustration at that organisation&#8217;s lack of consideration for online publications and intimated that the process of joining revealed flaws inherent in the existing system.<?php footnoteRef('C',3,107); ?> She noted that the Huffington Post UK was eventually categorised by the PCC as a regional newspaper although it is in reality a national online publication with a substantive readership.<?php footnoteRef('C',3,108); ?></p>
  <?php paragraphLink('C',3,4,21); ?>By contrast, Ms Wright told the Inquiry that although she was aware of the PCC Code she saw no reason for Popbitch to be part of the system of self-regulation through the PCC. Instead, she said in response to questions from the Inquiry that she believed Popbitch &#8217;s own system of internal or personal regulation was more effective and better suited to the needs of the organisation.<?php footnoteRef('C',3,109); ?> With regard to a future system of regulation for the press, Ms Wright was equivocal as to whether such a system would be something that Popbitch would consider voluntarily signing up to, the detail of that system depending. Ms Wright said that she would need to determine whether that system of regulation would be useful to Popbitch .<?php footnoteRef('C',3,110); ?></p>
  <?php paragraphLink('C',3,4,22); ?>With regard to the oversight and regulation of content published by third parties, views of the Huffington Post UK to hosted and other user generated content on its site are broadly typical of other hosting sites. The Huffington Post UK does not pre-moderate or edit that content. Indeed, Ms Buzasi has said that:<?php footnoteRef('C',3,111); ?></p>
<blockquote>&#8220;We want to have their personalities shine through on their blogs but there is a framework to ensure that we&#8217;re &#8211; or our bloggers are complying with the law.&#8221; </blockquote>
  <?php paragraphLink('C',3,4,23); ?>Mu Buzasi said that a small number of comments were routed through a filter which may pick up certain word combinations or profanities. These were then directed to a moderator for review.<?php footnoteRef('C',3,112); ?> Comment that was flagged by users was also directed to a moderator for review.<?php footnoteRef('C',3,113); ?></p>
  <?php paragraphLink('C',3,4,24); ?>Ms Buzasi made clear that it was her firm belief that micro bloggers and small non-commercial bloggers should exist outside any formal system of regulation. She regards this freedom from regulation as a necessary condition for the nurture of creative talent and encouragement of new media enterprises, particularly if there are substantive costs associated with that system.<?php footnoteRef('C',3,114); ?></p>
  <?php paragraphLink('C',3,4,25); ?>Google is by some margin the largest publisher of third party content to have given evidence to the Inquiry. Specifically, Google hosts user generated content through its Blogger.com service. The service hosts blogging sites, and now hosts more than 1 trillion words. That total increases at rate of over 250,000 words every minute.<?php footnoteRef('C',3,115); ?> Its attitude towards the content it hosts is markedly similar to that of the Huffington Post UK. All content hosted through the service must comply with the terms of use. Beyond this, Google does not exercise any editorial control over the content it hosts on its blogger service.<?php footnoteRef('C',3,116); ?> It does, however, provide a notice and take down service. Google&#8217;s legal Director, Daphne Keller, has said that while a blogger service is available only through the .com domain, Google will take steps to ensure that content originating from a given jurisdiction is compliant with local law, if it receives a complaint about the content in question.<?php footnoteRef('C',3,117); ?></p>
  <h4>Funding models</h4>
 <?php paragraphLink('C',3,4,26); ?>Many blogs sites now run on a commercial basis. The largest blog sites are increasingly funded either in their entirety or in part by advertising, as is the case with both Popbitch and Guido Fawkes. Although the approach to what appears on the website or blog will vary from site to site, the technical costs associated with running a site of this sort are relatively low, and barriers to entry to the market for both new players, be they individuals or much larger firms, are similarly low. Effectively, anyone with access to the Internet can set up a blog and seek to reach readers.</p>
  <?php sectionAnchor('C',3,5); ?>Social networking sites</h2>
 <?php paragraphLink('C',3,5,1); ?>A social networking service is an online service, platform, or site that focuses on the building and reflecting of social networks or social relations among people who, for example, share interests and/or activities. A social network service essentially consists of a representation of each user (often a profile), his/her social links, and a variety of additional services. Most social network services are web-based, providing means for users to interact over the Internet, potentially through e-mail and instant messaging. Myspace, Facebook, Twitter, LinkedIn and Google+ are all social network sites.</p>
  <?php paragraphLink('C',3,5,2); ?>Although there is limited news provision in the terms that are relevant to this Inquiry on pure social networking sites, all social networks provide opportunities for individuals to disseminate and discuss news, information and comment. Indeed, everyday use of the Internet is increasingly characterised by the use of social networking sites and other social media. Their growth has been little short of phenomenal. Ten years ago there were no social networks; now the largest social networking site, Facebook, has over 800m users worldwide (although Facebook has recently suggested that as many of 100m of these accounts may be either dormant, fake or used for questionable purposes). The rise of Twitter has been similarly rapid. Founded in 2006, it now counts over 100 million active users each month, sending a billion tweets every four days.<?php footnoteRef('C',3,118); ?> Perhaps most astonishingly (and for this Inquiry of concern to those who may be the subject either of Tweets that breach privacy or indeed the criminal or civil law), is the speed with which a message might be propagated. Colin Crowell, Head of Global public Policy for Twitter Inc, noted that during the 2012 Superbowl, Twitter processed 12,000 tweets per second.<?php footnoteRef('C',3,119); ?></p>
  <?php paragraphLink('C',3,5,3); ?>Increasingly newspapers themselves not only use the pages of social networking sites to disseminate news, but also provide platform friendly applications, to enable the application to be accessed through the specific social media. However, it is worthy of note that despite their extraordinary growth, as with most blogs, in the main few tweets or social network pages are read by very large numbers of people. Although a very small number of tweeters are followed (though not necessarily read) by very large numbers of people, and such may at times have significant impact (the Inquiry has heard evidence from Stephen Abell of the PCC of the phenomenon of Fry-bombing),<?php footnoteRef('C',3,120); ?> it should not detract from the fact that most tweets are read by very few people. The television personality and actor, Stephen Fry, one of the most prolific celebrity tweeters has over 5 million Twitter followers.</p>
  <?php paragraphLink('C',3,5,4); ?>Although social networking sites are not obviously in competition with newspapers for audience, revenue or advertising, they may be used to publish information that would not be able to be published by a newspaper in conformity with the standards set by self-regulation. In a practical, though not a legal, sense they might also be used to publish information that a court has ruled should not be published with little likelihood of the publisher being identified and held to account. Indeed, there are clear and very recent examples of this practice that do not need to be repeated here.</p>
  <?php paragraphLink('C',3,5,5); ?>It is in this regard that Twitter has been the focus of some interest to the Inquiry because of the role played by users in identifying individuals who had been the subject of privacy injunctions. Twitter allows members to operate anonymously, or under a pseudonym,<?php footnoteRef('C',3,121); ?> and it is also possible that the company itself may not know the real identity of any member.<?php footnoteRef('C',3,122); ?> However, Twitter has told the Inquiry that its rules forbid members from using the service for any unlawful purpose,<?php footnoteRef('C',3,123); ?> and any material that is found by the company to contravene that policy can be taken down or removed.<?php footnoteRef('C',3,124); ?></p>
  <?php paragraphLink('C',3,5,6); ?>In this respect Twitter is similar to other social media. Most social networking sites and publishers of user generated content operate acceptable use policies (AUPs) which set down guidelines for user behaviour on those sites and cover issues such as posting of offensive content and bullying. Where a policy is breached, material is removed and in some cases the user&#8217;s profile is deleted.</p>
  <?php paragraphLink('C',3,5,7); ?>Most recent trends in social network technology have been towards the concept of &#8220;real- time web&#8221; and &#8220;location based&#8221; services. The real time web service allows users to generate content, that is broadcast as it is being uploaded &#8211; the concept is potentially analogous to and may indeed come to challenge live radio and television broadcasts as well as traditional print media.</p>
  <?php paragraphLink('C',3,5,8); ?>Indeed, the instant nature of social networking also differentiates it from more traditional media. Rebuttals and denials of allegations can take place instantly, helping if not to kill a story at least to provide the subject of the story with a voice and make users aware that the veracity of the allegation or story may be in doubt.</p>
  <h3>Consideration of the law</h3>
 <?php paragraphLink('C',3,5,9); ?>The major websites and providers of internet services, be they social networking sites or providers of other services or functionality, tend to operate under US law if that is where the company is based. However, as witnesses to the Inquiry representing Internet firms have sought to make clear, where services are targeted at a given jurisdiction, they will also seek to comply with local law. This can and does lead to conflicts of law, for example, where issues such as consideration of privacy and other related matters conflict with rights under the First Amendment of the American Constitution.</p>
  <h3>Blogs and the consideration of the law</h3>
 <?php paragraphLink('C',3,5,10); ?>The Inquiry has heard much evidence in this regard. Ms Wright said that as Popbitch is published in the UK it abides by general law. This includes making efforts to ensure that content is not defamatory.<?php footnoteRef('C',3,125); ?> Ms Wright was keen to emphasise, echoing points made by other witnesses representing online publishers and Internet businesses, that Popbitch sought to obey the local law in each of the jurisdictions in which it operated.<?php footnoteRef('C',3,126); ?> Asked by Counsel to the Inquiry whether she considered the privacy of individuals about whom she writes, Ms Wright said:<?php footnoteRef('C',3,127); ?></p>
<blockquote>&#8220;In era where injunctions have been such a much-talked about thing, that obviously has to be a consideration. I think if I could put it this way, Popbitch is an entertainment product, therefore we are trying to do no more than poke fun in the world of celebrity&#8230;.. We get a lot of stories in [sic] which we don&#8217;t print, which are things like somebody&#8217;s gone to rehab, somebody has cancer, or it&#8217;s about their children.&#8221; </blockquote>
  <?php paragraphLink('C',3,5,11); ?>Ms Wright also said that consideration of privacy issues was more important to Popbitch than it once was. In evidence she referred to the example of Victoria Beckham&#8217;s pregnancy, noting that at the time the pregnancy was widely discussed, and that although Popbitch were the first publishers to write about the story, the fact of that pregnancy was no secret. However, Ms Wright has said further:<?php footnoteRef('C',3,128); ?></p>
<blockquote>&#8220;I would be I think since then much more careful about making sure that a pregnancy was beyond twelve weeks before &#8211; in this case, this was that as well, but I would be very careful about doing that.&#8221; </blockquote>
  <?php paragraphLink('C',3,5,12); ?>Mr Staines provided different and interesting evidence in relation to legal accountability and enforcement, particularly in relation to legal jurisdictions, that illustrates well the problems in respect of the application of national law by online publishers. Mr Staines was candid about this. He said that the servers used by the Guido Fawkes site are located in the USA. The site was previously hosted by Google on the Google free blogger system but, as Mr Staines explained, was moved when Google &#8220;became more willing to give in to legal threats.&#8221;<?php footnoteRef('C',3,129); ?> Mr Staines said by way of further explanation:<?php footnoteRef('C',3,130); ?></p>
<blockquote>&#8220;I thought it be a good moment to switch from them to a hosting provider who was robust and would stand up for my First Amendment protections.&#8221; </blockquote>
  <?php paragraphLink('C',3,5,13); ?>This switch from Google to another blog host was made in order to make it more difficult for content Mr Staines had published to be challenged through the UK courts; he cited the experience of Wikileaks as a sufficient justification for this course of action.<?php footnoteRef('C',3,131); ?> Further, Mr Staines stated that although he had been threatened with legal action on a number of occasions, no such action had been successfully prosecuted. Mr Staines also made clear that he has ignored UK Court decisions without adverse consequences.<?php footnoteRef('C',3,132); ?></p>
  <?php paragraphLink('C',3,5,14); ?>He gave the specific example of a memorandum prepared by Merrill Lynch setting out concerns at the future prospects of Northern Rock which suggested that the eventual cost to the taxpayer might be as much as &#163;50bn.<?php footnoteRef('C',3,133); ?> Mr Staines said that he uploaded the memo in question onto a number of overseas servers to circumvent injunctions issued by the law firm Carter Ruck.<?php footnoteRef('C',3,134); ?></p>
  <?php paragraphLink('C',3,5,15); ?>The attitude of Mr Staines revealed in evidence with regard to compliance with national law was unique among witnesses from online businesses who have given evidence to the Inquiry. More typical were those of the Huffington Post UK, which have already been partly addressed. Ms Buzasi was clear that the Huffington Post UK abides by UK law. Under the terms of use, users of the Huffington Post UK comment boards and blogs must undertake not to post anything that might be illegal. Users must also provide personal details, which means that legal orders or proceedings can be enforced should either legal action be brought or an injunction be imposed.<?php footnoteRef('C',3,135); ?> However, she also explained that the Huffington Post UK was not able to review and &#8220;pre-moderate&#8221; potentially libellous or defamatory comment, a theme that was taken up by other witnesses to the Inquiry.<?php footnoteRef('C',3,136); ?> Ms Buzasi suggested that the inability of the Huffington Post UK to make adjudications in such matters is, to some extents, mitigated by provisions made for the correction of inaccurate or potentially actionable material through the prominent provision of &#8220;send a correction button&#8221;; the site also operates what Ms Buzasi has referred to as a &#8220;robust&#8221; notice and take down process.<?php footnoteRef('C',3,137); ?></p>
  <?php sectionAnchor('C',3,6); ?>Other providers</h2>
 <?php paragraphLink('C',3,6,1); ?>Mr Crowell made clear that it would be both technologically and physically impossible for Twitter to pre-moderate the user-generated content hosted by Twitter, in this case tweets, and adjudicate on their potential illegality.<?php footnoteRef('C',3,138); ?> In this respect, the position of Twitter is markedly similar to that of both Google and Microsoft in relation to user-generated content. Articulating the position of Google with regard to compliance in this area, Ms Keller explained that given the volume of material generated by third parties that Google either indexes, searches or hosts depending on the relevant Google service or function, it is impossible for Google to pre-moderate that content in any way or, to make adjudications as to whether content is legal or not.<?php footnoteRef('C',3,139); ?> Ms Keller has made clear that both the volume and nature of the content make such decision making practically impossible. She told the Inquiry that such filtering is also technically impossible and would also run the risk of legal challenge if content that had been posted entirely legally were removed inadvertently as a consequence of such filtering.<?php footnoteRef('C',3,140); ?></p>
  <?php paragraphLink('C',3,6,2); ?>However, Mr Crowell was keen to stress that recent technological changes since the start of 2012 have enabled Twitter to withhold tweets within a given jurisdiction. This will enable Twitter to comply more effectively with differences in local law in different jurisdictions.<?php footnoteRef('C',3,141); ?> Mr Collins also provided further evidence of Google&#8217;s evolving policies with regard to compliance with national law. He said that Google services targeted at a particular country comply with local law and that this applies as much to privacy and other related matters as it does to other areas of law.<?php footnoteRef('C',3,142); ?> By way of example, Mr Collins explained that Google policy on privacy in the UK was shaped through an ongoing dialogue with the ICO, which had provided relevant advice.<?php footnoteRef('C',3,143); ?> Ms Keller explained that the use of the .co.uk domain name underpinned the provision of services to the UK as well as compliance with the local law.<?php footnoteRef('C',3,144); ?></p>
  <?php paragraphLink('C',3,6,3); ?>Ms Keller also explained the number of routes through which an individual might seek to remove material made available through Google services. It is notable, and indeed unfortunate &#8211; although given the technological constraints understandable &#8211; that in each example the burden of effort lies with the injured party. Ms Keller explained that webmasters (those who author and maintain websites) are able to request that their site is not indexed and will therefore not appear in searches.<?php footnoteRef('C',3,145); ?> Ms Keller also said that this particular approach is in the view of Google the most effective means of getting content removed. Google also provides a &#8220;remove content from Google&#8221; service, which users may use to alert staff to potentially illegal content which will be taken down if it is understood not to comply with UK law.<?php footnoteRef('C',3,146); ?> Google has adopted a similar, expedited approach in relation to content that is in breach of copyright.<?php footnoteRef('C',3,147); ?></p>
  <?php sectionAnchor('C',3,7); ?>Enforcement</h2>
 <?php paragraphLink('C',3,7,1); ?>Despite the efforts made to comply with national law, it is clear that the enforcement of law and regulation online is problematic. Although the law with regard to online content is clear, and UK hosted content is by and large compliant, the ability of the UK to exercise legal jurisdiction over content on Internet services is extremely limited and dependent on many things (explored below) which are rarely aligned. These include: the location of the service provider; the location of the servers on which material is held; and international agreements and treaties.</p>
  <?php paragraphLink('C',3,7,2); ?>Internet Service Providers offering services to UK customers will block content that has been declared illegal. They are, however, understandably unwilling to make decisions on whether content may or may not be illegal or to take decisions where there are grey areas in law. This has been particularly apparent in cases of alleged defamation, where ISPs and content providers have historically been unwilling to remove content without a court decision. Whilst the position of the ISPs and content providers may be understandable &#8211; issues clearly arise as to their ability to decide on the veracity of an allegation &#8211; in some cases considerable damage may have been done to the subject of those allegations before a judgment has been reached and the defamatory content consequently removed.</p>
  <?php paragraphLink('C',3,7,3); ?>Most successful attempts to induce service providers of any sort to take enforcement action in relation to content are either through agreement, or dependant on case-specific court orders. In his evidence to the Inquiry, Mr Crowell (as well as representatives from Microsoft and Google) said that Twitter would enforce orders made by UK courts, in so far as they might apply to UK users, on a case by case basis.<?php footnoteRef('C',3,148); ?> In practice, this means that for Twitter to remove a defamatory tweet that was re-tweeted, a court order would be needed in relation to every relevant tweet by every individual unique user who repeated that defamatory content.<?php footnoteRef('C',3,149); ?></p>
  <?php paragraphLink('C',3,7,4); ?>Ms Keller has also made clear that, in cases of alleged defamation, it is Google policy in most cases only to remove material from a given service if the complainant was able to provide a legal judgment in support of their claim. However, Ms Keller acknowledged that while such material would be removed from a UK search, it might still be found through Google.com if the material in question was not in breach of American law.<?php footnoteRef('C',3,150); ?> This means in practice that, in order to have material removed from searches in multiple jurisdictions, a legal application would have to be made in each relevant jurisdiction. Ms Keller said in this respect that she hopes: &#8220;this would not be a difficult thing to do.&#8221;<?php footnoteRef('C',3,151); ?> It is notable that much as Twitter requires a court order in respect of each individual user, Google require such an order in relation to individual URLs.</p>
  <?php paragraphLink('C',3,7,5); ?>Both examples are also in counterpoint to the number of instances where UK legislation and decisions by UK courts are simply ignored, as they are unenforceable. Content providers headquartered in the United States will also strenuously defend rights to free speech under American law and indeed may themselves be at risk of prosecution if they remove allegedly defamatory or potentially illegal content ahead of a court decision. This position is not without legal underpinning under European Law. Under Article 15 of the European eCommerce Directive which sets out the regulatory framework for trade through the Internet, ISPs are not legally responsible for the content they carry over their pipes.<?php footnoteRef('C',3,152); ?> This defence is known as mere conduit. Mr Collins of Google described the apportionment of responsibilities between publishers and host thus:<?php footnoteRef('C',3,153); ?></p>
<blockquote>&#8220;Firstly, there is a very clear set of regulations which apply to technical intermediaries hosting platforms. It&#8217;s called the E-commerce Directive and it does place a number of responsibilities on us around removal of content. I know that you&#8217;re very aware of it. It&#8217;s important to make the distinction between &#8211; in the system that you&#8217;ve outlined, it&#8217;s important to make the decision between someone who provides a hosting platform for other people to create and post content, and a publisher. Blogger.com or other products that are &#8211; attempt to form a community around the product, YouTube, et cetera, they don&#8217;t make us a publisher; we remain a hosting platform. So I think whatever system that you devise, it&#8217;s important to retain that distinction, because not only is there already a very clear set of regulations around those principles placing responsibilities on us, but it retains a very essential balance online, which is: where does that responsibility lie? We have our responsibilities, which we fulfil; the person that produces and uploads that content has his or her responsibilities as well.&#8221; </blockquote>
  <?php paragraphLink('C',3,7,6); ?>Mr Staines also described with some colour the difficulties that an individual or company might encounter in trying to have content removed from the internet:<?php footnoteRef('C',3,154); ?></p>
<blockquote>&#8220;I think it is impossible for them to do anything, I would basically upload it to a free hosting service after the close of business hours, so if the law firm was contacting Yahoo India, they would find that there would be no one at home and it would be up on that website until the next day at the very least.&#8221; </blockquote>
  <?php sectionAnchor('C',3,8); ?>Press photographers</h2>
 <?php paragraphLink('C',3,8,1); ?>Press photographers are another source of news material. Their actions and conduct are covered elsewhere in this Report as appropriate, so I will restrict myself to a very few comments in this regard. Based on figures provided by the British Press Photographers Association (BPPA), it is estimated that there are around 800 press photographers in the UK. Of these around a quarter are directly employed by newspapers or agencies, around 12% are employed on fixed term or rolling contracts, around 18% work through agencies as freelancers and the remaining 45% are entirely freelance.<?php footnoteRef('C',3,155); ?></p>
  <?php paragraphLink('C',3,8,2); ?>Those photographers who are directly employed, whether by newspapers or by agencies, might expect to be subject to the Editors&#8217; Code of Practice. Indeed, the Inquiry has been told by witnesses both from picture agencies and newspapers that the expectation is that press photographers would abide by the terms of the Editors&#8217; Code of Practice.<?php footnoteRef('C',3,156); ?> Those who operate on a freelance basis are not subject to any regulation beyond the law, as it applies to everyone.</p>
  <?php paragraphLink('C',3,8,3); ?>Much of the work undertaken by press photographers involves arranged photo shoots of one sort or another. However, press photographers obviously do also work by waiting for potential subjects and hoping to get pictures of them. This inevitably gives rise to the risk that photographs will be taken in situations where the subject might prefer not to be photographed and, as is made clear<?php footnoteRef('C',3,157); ?> elsewhere in this report, may even be subject to harassment or distress.</p>
  <?php paragraphLink('C',3,8,4); ?>The death of Diana, Princess of Wales,<?php footnoteRef('C',3,158); ?> in an accident that occurred while the car in which she was travelling was being pursued at high speed by a number of press photographers in 1997 brought the role and behaviour of press photographers very much to public notice. Since then, UK newspaper editors have been committed by the Editors&#8217; Code of Practice not to publish images that are taken in contravention of the Code. The responsibility for checking whether the Code of Practice has been breached in relation to any specific image sits with the newspaper concerned.</p>
  <?php paragraphLink('C',3,8,5); ?>The market for celebrity and news photographs is now a global one. A picture that might be turned down by a UK editor as not being consistent with the Code might well be accepted by non-UK newspapers, broadcasters or websites. Recent cases involving Prince Harry and the Duchess of Cambridge are instructive and are described elsewhere in this Report.<?php footnoteRef('C',3,159); ?> The largely freelance nature of the press photography business means that there is a high level of competition among photographers to get the best picture.</p>
  </div>
  
 