<?php 
require_once('../../common.php');
levesonHeader('C',3); 
levesonNav('../../');
levesonBread('C',3);
require_once('content.php');
levesonFooterNav('C',3); 
require_once('footnotes.php');
LevesonCommonFooter();
?>