<!-- Footnotes-->
<div id="footnotes"> <?php footNote('F',5,1); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',5,2); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',5,3); ?> http://www.guardian.co.uk/uk/2011/jul/04/milly-dowler-family-phone-hacking</p>
 <?php footNote('F',5,4); ?> pp1-2, para 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Sally-Bob-Dowler.pdf">Witness-Statement-of-Sally-Bob-Dowler.pdf</a></p>
 <?php footNote('F',5,5); ?> p2, para 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Sally-Bob-Dowler.pdf">Witness-Statement-of-Sally-Bob-Dowler.pdf</a></p>
 <?php footNote('F',5,6); ?> p3, para 10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Sally-Bob-Dowler.pdf">Witness-Statement-of-Sally-Bob-Dowler.pdf</a></p>
 <?php footNote('F',5,7); ?> pp12-13, lines 23-10, Sally Dowler, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-21-November-2011.pdf">Transcript-of-Morning-Hearing-21-November-2011.pdf</a></p>
 <?php footNote('F',5,8); ?> p13, lines 7-8, Sally Dowler, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-21-November-2011.pdf">Transcript-of-Morning-Hearing-21-November-2011.pdf</a></p>
 <?php footNote('F',5,9); ?> p19, lines 14-21, Sally Dowler, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-21-November-2011.pdf">Transcript-of-Morning-Hearing-21-November-2011.pdf</a></p>
 <?php footNote('F',5,10); ?> p10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-9-May-2012.pdf">Transcript-of-Morning-Hearing-9-May-2012.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-DCI-John-Macdonald.pdf">Witness-Statement-of-DCI-John-Macdonald.pdf</a></p>
 <?php footNote('F',5,11); ?> p16, lines 1-6, Robert Jay QC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-9-May-2012.pdf">Transcript-of-Morning-Hearing-9-May-2012.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-DCI-John-Macdonald.pdf">Witness-Statement-of-DCI-John-Macdonald.pdf</a></p>
 <?php footNote('F',5,12); ?> p20, lines 6-10, Robert Jay QC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-9-May-2012.pdf">Transcript-of-Morning-Hearing-9-May-2012.pdf</a>; p7, para 17, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-DCI-John-Macdonald.pdf">Witness-Statement-of-DCI-John-Macdonald.pdf</a></p>
 <?php footNote('F',5,13); ?> pp30-31, lines 23-4, Robert Jay QC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-9-May-2012.pdf">Transcript-of-Morning-Hearing-9-May-2012.pdf</a>; p16, para 38, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-DCI-John-Macdonald.pdf">Witness-Statement-of-DCI-John-Macdonald.pdf</a></p>
 <?php footNote('F',5,14); ?> p34, lines 8-17, Gillian Phillips, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-9-May-2012.pdf">Transcript-of-Morning-Hearing-9-May-2012.pdf</a></p>
 <?php footNote('F',5,15); ?> http://www.parliament.uk/documents/commons-committees/culture-media-sport/Surrey-Police-to-Chairman-17-January-2012.pdf</p>
 <?php footNote('F',5,16); ?> for example, http://www.dailymail.co.uk/news/article-2073364/Police-reveal-theres-evidence-News-World-deleted-Milly-Dowler-voicemails.html</p>
 <?php footNote('F',5,17); ?> p14, lines 7-13, Gerry McCann, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-23-November-2011.pdf">Transcript-of-Afternoon-Hearing-23-November-2011.pdf</a></p>
 <?php footNote('F',5,18); ?> pp27-28, lines 6-3, Gerry McCann, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-23-November-2011.pdf">Transcript-of-Afternoon-Hearing-23-November-2011.pdf</a></p>
 <?php footNote('F',5,19); ?> there is an error in the transcript. This should of course read &#8216;Dr G. McCann&#8217;</p>
 <?php footNote('F',5,20); ?> p19, lines 17-22, Gerry McCann, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-23-November-2011.pdf">Transcript-of-Afternoon-Hearing-23-November-2011.pdf</a></p>
 <?php footNote('F',5,21); ?> pp16-17, lines 23-1, Gerry McCann, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-23-November-2011.pdf">Transcript-of-Afternoon-Hearing-23-November-2011.pdf</a></p>
 <?php footNote('F',5,22); ?> p13, paras 78-80,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Gerald-Patrick-McCann.pdf">Witness-Statement-of-Gerald-Patrick-McCann.pdf</a>; In July 2008 proceedings were commenced against Associated Newspapers Ltd in respect of 67articles published in the Daily Mail and the Evening Standard over a five month period, as well as over 18 articles onthe latter&#8217;s website. These proceedings were compromised by the payment of a substantial donation to the Madeleinesearch fund and the publication of an apology in the Evening Standard. The Daily Mail were willing to publish a numberof &#8216;free adverts&#8217; to aid the search, but refused to publish any apology, claiming that the supportive articles they hadwritten counter-balanced the others. As Dr McCann explained, by that stage he did not wish to embark on a protracteddispute with the newspaper, particularly given the need to maintain good relations with the press in continuing topublicise the search for Madeleine </p>
 <?php footNote('F',5,23); ?> p37, lines 3-16, Gerry McCann, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-23-November-2011.pdf">Transcript-of-Afternoon-Hearing-23-November-2011.pdf</a></p>
 <?php footNote('F',5,24); ?> p38, line 23, Gerry McCann, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-23-November-2011.pdf">Transcript-of-Afternoon-Hearing-23-November-2011.pdf</a></p>
 <?php footNote('F',5,25); ?> pp39-40, lines 22-1, Robert Jay QC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-23-November-2011.pdf">Transcript-of-Afternoon-Hearing-23-November-2011.pdf</a></p>
 <?php footNote('F',5,26); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',5,27); ?> http://www.publications.parliament.uk/pa/cm200910/cmselect/cmcumeds/362/362i.pdf</p>
 <?php footNote('F',5,28); ?> p4, paras 22-23, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-David-Pilditch.pdf">Witness-Statement-of-David-Pilditch.pdf</a></p>
 <?php footNote('F',5,29); ?> p62, lines 16-22, David Pilditch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-21-December-20111.pdf">Transcript-of-Morning-Hearing-21-December-20111.pdf</a></p>
 <?php footNote('F',5,30); ?> p20, line 6, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,31); ?> p20, line 9-17, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,32); ?> pp83-84, Dawn Neeson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-12-January-2012.pdf">Transcript-of-Morning-Hearing-12-January-2012.pdf</a>;</p>
 <?php footNote('F',5,33); ?> pp20-21, lines 25-2, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,34); ?> p21, lines 13-15, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,35); ?> p84, lines 18-23, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,36); ?> pp88-89, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,37); ?> p86, lines 3-19, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,38); ?> p64, lines 5-18, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,39); ?> p77, lines 15-17, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,40); ?> pp39-40, lines 15-5, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,41); ?> pp91-92, lines 23-5, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('F',5,42); ?> p26, lines 2-6, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,43); ?> p26, lines 12-23, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,44); ?> p24<em> passim,</em> p25, lines 18-23, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('F',5,45); ?> Exhibit PWH3 to the witness statement of Peter Hill (which included circulation figures for the Daily Express between1 January 2007 and 4 January 2009) was provided to the Inquiry on a confidential basis. It has not been published as itincludes commercially sensitive data</p>
 <?php footNote('F',5,46); ?> para 354, http://www.publications.parliament.uk/pa/cm200910/cmselect/cmcumeds/362/362i.pdf</p>
 <?php footNote('F',5,47); ?> paragraph 3.4 above</p>
 <?php footNote('F',5,48); ?> p17, para 103, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Gerald-Patrick-McCann.pdf">Witness-Statement-of-Gerald-Patrick-McCann.pdf</a></p>
 <?php footNote('F',5,49); ?> para 356, http://www.publications.parliament.uk/pa/cm200910/cmselect/cmcumeds/362/362i.pdf</p>
 <?php footNote('F',5,50); ?> pp84-87, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('F',5,51); ?> p85, lines 3-15, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('F',5,52); ?> Part J</p>
 <?php footNote('F',5,53); ?> http://www.publications.parliament.uk/pa/cm200910/cmselect/cmcumeds/362/362i.pdf</p>
 <?php footNote('F',5,54); ?> Daniel Sanderson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-15-December-20111.pdf">Transcript-of-Morning-Hearing-15-December-20111.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Daniel-Sanderson.pdf">Witness-Statement-of-Daniel-Sanderson.pdf</a></p>
 <?php footNote('F',5,55); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Daniel-Sanderson.pdf">Witness-Statement-of-Daniel-Sanderson.pdf</a></p>
 <?php footNote('F',5,56); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',5,57); ?> p14, para 84, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Gerald-Patrick-McCann.pdf">Witness-Statement-of-Gerald-Patrick-McCann.pdf</a></p>
 <?php footNote('F',5,58); ?> pp87-88, lines 12-9, Colin Myler, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Afternoon-Hearing-14-December-2011.pdf">Transcript-of-Afternoon-Hearing-14-December-2011.pdf</a></p>
 <?php footNote('F',5,59); ?> pp65-66, lines 20-4, Ian Edmondson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-9-February-2012.pdf">Transcript-of-Morning-Hearing-9-February-2012.pdf</a></p>
 <?php footNote('F',5,60); ?> pp67-68, lines 8-22, Ian Edmondson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-9-February-2012.pdf">Transcript-of-Morning-Hearing-9-February-2012.pdf</a></p>
 <?php footNote('F',5,61); ?> para 2.54,<?php internalChapterLink('../../','F',4); ?></p>
 <?php footNote('F',5,62); ?> p14, para 86, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Gerald-Patrick-McCann.pdf">Witness-Statement-of-Gerald-Patrick-McCann.pdf</a></p>
 <?php footNote('F',5,63); ?> pp73-74, lines 23-12, Professor Brian Cathcart, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-8-December-20111.pdf">Transcript-of-Morning-Hearing-8-December-20111.pdf</a></p>
 <?php footNote('F',5,64); ?> p4, paras 20-21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Christopher-Jefferies.pdf">Witness-Statement-of-Christopher-Jefferies.pdf</a></p>
 <?php footNote('F',5,65); ?> p5, para 25, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Christopher-Jefferies.pdf">Witness-Statement-of-Christopher-Jefferies.pdf</a></p>
 <?php footNote('F',5,66); ?> para 37, http://www.bailii.org/ew/cases/EWHC/Admin/2011/2074.html</p>
 <?php footNote('F',5,67); ?> para 34, http://www.bailii.org/ew/cases/EWHC/Admin/2011/2074.html</p>
 <?php footNote('F',5,68); ?> The Sun, the Daily Mirror, the Sunday Mirror, the Daily Record, The Daily Mail, the Daily Star, The Scotsman and theDaily Express</p>
 <?php footNote('F',5,69); ?> p5, para 26, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Christopher-Jefferies.pdf">Witness-Statement-of-Christopher-Jefferies.pdf</a></p>
 <?php footNote('F',5,70); ?> http://www.guardian.co.uk/media/greenslade/2011/jul/29/joanna-yeates-national-newspapers</p>
 <?php footNote('F',5,71); ?> p10, para 29, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Christopher-Jefferies.pdf">Witness-Statement-of-Christopher-Jefferies.pdf</a></p>
 <?php footNote('F',5,72); ?> p11, para 30, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Christopher-Jefferies.pdf">Witness-Statement-of-Christopher-Jefferies.pdf</a></p>
 <?php footNote('F',5,73); ?> p52, lines 4-24, Ryan Parry, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-24-January-2012.pdf">Transcript-of-Afternoon-Hearing-24-January-2012.pdf</a></p>
 <?php footNote('F',5,74); ?> p77, lines 2-3, Dominic Mohan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-24-January-2012.pdf">Transcript-of-Afternoon-Hearing-24-January-2012.pdf</a></p>
 <?php footNote('F',5,75); ?> pp82-83, lines 3-6, Stephen Waring, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-24-January-2012.pdf">Transcript-of-Afternoon-Hearing-24-January-2012.pdf</a></p>
 <?php footNote('F',5,76); ?> p86, lines 18-25, Stephen Waring, <em>ibid</em></p>
 <?php footNote('F',5,77); ?> p65, lines 6-10, Stephen Waring, <em>ibid</em></p>
 <?php footNote('F',5,78); ?> p67, lines 4-5, Stephen Waring, <em>ibid</em></p>
 <?php footNote('F',5,79); ?> pp65-66, Stephen Waring, <em>ibid</em></p>
 <?php footNote('F',5,80); ?> p4, para 8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Chief-Constable-Colin-Port.pdf">Witness-Statement-of-Chief-Constable-Colin-Port.pdf</a></p>
 <?php footNote('F',5,81); ?> pp72-73, lines 12-19, Richard Wallace, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a></p>
 <?php footNote('F',5,82); ?> <?php internalChapterLink('../../','F',7); ?></p>
 <?php footNote('F',5,83); ?> http://www.thesun.co.uk/sol/homepage/news/73335/Browns-baby-has-cystic-fibrosis.html</p>
 <?php footNote('F',5,84); ?> pp137-138, lines 14-23, Dominic Mohan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-7-February-2012.pdf">Transcript-of-Afternoon-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('F',5,85); ?> http://www.thesun.co.uk/sol/homepage/news/3691926/The-Sun-exposes-the-allegation-that-we-hacked-into-Gordon-Browns-family-medical-records-as-FALSE-and-a-smear.html</p>
 <?php footNote('F',5,86); ?> pp32-33, lines 14-8, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-11-May-2012.pdf">Transcript-of-Afternoon-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('F',5,87); ?> pp27-28, lines 11-16, Gordon Brown, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-11-June-2012.pdf">Transcript-of-Morning-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('F',5,88); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-GB9-to-Witness-Statement-of-Gordon-Brown-MP-Black.pdf">Exhibit-GB9-to-Witness-Statement-of-Gordon-Brown-MP-Black.pdf</a></p>
 <?php footNote('F',5,89); ?> p9, paras 31-32, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-Rebekah-Brooks.pdf">Closing-Submission-from-Rebekah-Brooks.pdf</a></p>
 <?php footNote('F',5,90); ?> http://www.pcc.org.uk/assets/696/Code_of_Practice_2012_A4.pdf</p>
 <?php footNote('F',5,91); ?> pp29-31, lines 12-2, Gordon Brown, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-11-June-2012.pdf">Transcript-of-Morning-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('F',5,92); ?> pp41-43, lines 10-12, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-11-May-2012.pdf">Transcript-of-Afternoon-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('F',5,93); ?> p34, lines 18-19, Gordon Brown, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-11-June-2012.pdf">Transcript-of-Morning-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('F',5,94); ?> p34, lines 21-22, Gordon Brown, <em>ibid</em></p>
 <?php footNote('F',5,95); ?> http://www.thesun.co.uk/sol/homepage/news/3691926/The-Sun-exposes-the-allegation-that-we-hacked-into-Gordon-Browns-family-medical-records-as-FALSE-and-a-smear.html</p>
 <?php footNote('F',5,96); ?> see discussion of the Daily Mail&#8217;s allegation of a &#8220;mendacious smear&#8221; by Hugh Grant at Section 6 below</p>
 <?php footNote('F',5,97); ?> pp34-36, lines 19-24, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-11-May-2012.pdf">Transcript-of-Afternoon-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('F',5,98); ?> Section 6 below</p>
 <?php footNote('F',5,99); ?> Section 10 of <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',5,100); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',5,101); ?> p4, para 11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Hugh-Grant.pdf">Witness-Statement-of-Hugh-Grant.pdf</a></p>
 <?php footNote('F',5,102); ?> <em>ibid</em></p>
 <?php footNote('F',5,103); ?> p4, para 11, <em>ibid</em></p>
 <?php footNote('F',5,104); ?> pp7-9, lines 22-21, Hugh Grant, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-21-November-2011.pdf">Transcript-of-Afternoon-Hearing-21-November-2011.pdf</a></p>
 <?php footNote('F',5,105); ?> p5, para 17, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Second-Supplemental-Witness-Statement-of-Hugh-Grant1.pdf">Second-Supplemental-Witness-Statement-of-Hugh-Grant1.pdf</a></p>
 <?php footNote('F',5,106); ?> pp85-86, lines 18-17, Paul Dacre, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-6-February-20121.pdf">Transcript-of-Afternoon-Hearing-6-February-20121.pdf</a></p>
 <?php footNote('F',5,107); ?> p3, para 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Jemima-Khan.pdf">Witness-Statement-of-Jemima-Khan.pdf</a></p>
 <?php footNote('F',5,108); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Supplemental-Witness-Statement-of-Liz-Hartley.pdf">Supplemental-Witness-Statement-of-Liz-Hartley.pdf</a></p>
 <?php footNote('F',5,109); ?> pp87-88, lines 5-25, Paul Dacre, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Afternoon-Hearing-6-February-20121.pdf">Transcript-of-Afternoon-Hearing-6-February-20121.pdf</a></p>
 <?php footNote('F',5,110); ?> <?php internalChapterLink('../../','F',6); ?></p>
 <?php footNote('F',5,111); ?> in order to protect the privacy of the Bowles family to such extent as is possible, and notwithstanding the fact thatthe information is, at least to a large extent, in the public domain and available, this Report will not publish referencesto their names, the precise articles or photographs or other family details</p>
 <?php footNote('F',5,112); ?> p113, line 24, Giles Crown, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-26-June-2012.pdf">Transcript-of-Morning-Hearing-26-June-2012.pdf</a></p>
 <?php footNote('F',5,113); ?> Both the picture editor and the work experience intern were perfectly entitled to pose for this photograph if theywished: given the likely anxiety that a 21 year old girl on work experience might have to secure full time employment,the fact that she was asked or permitted to do so raises issues not dissimilar to those discussed in <?php internalChapterLink('../../','F',6); ?>relating to pressure on staff</p>
 <?php footNote('F',5,114); ?> as reported in The Times, 24 August 2012</p>
 <?php footNote('F',5,115); ?> <em> Douglas v Hello! Ltd</em> [2006] QB 125</p>
 <?php footNote('F',5,116); ?> <?php internalChapterLink('../../','D',2); ?></p>
 <?php footNote('F',5,117); ?> On 15 November 2012 the PCC published guidance, http://pcc.org.uk/news/index.html?article=ODEwNw==</p>
 <?php footNote('F',5,118); ?> 16 September 2012</p>
 <?php footNote('F',5,119); ?> although it is to be noted that Northern and Shell which is a part owner of the Irish Daily Star issued a statementexpressing its disappointment that the decision to publish had been taken without reference to the company or to RichardDesmond. That raises a question about the role of proprietors in editorial decisions but where issues of reputation arise,different considerations may apply</p>
 </div>
