<?php 
require_once('../../common.php');
levesonHeader('X',2);
levesonNav('../../');
levesonBread('X',2);
require_once('content.php');
levesonFooterNav('X',2); 
require_once('footnotes.php');
LevesonCommonFooter();
?>