<div class="content" id="contentPartBChapter1">
<h1 id="top">CHAPTER 1<br/>INTRODUCTION</h1>
 <?php paragraphLink('B',1,1,1); ?>This Part of the Report alludes to some of the fundamental principles which must provide the context for any consideration of the role of the press in the United Kingdom. It does so principally for the purpose of brief overview and explanation, and to set the scene for the narrative, analysis and recommendations which follow.</p>
  <?php paragraphLink('B',1,1,2); ?>The principles which are set out are not simply derived from philosophical or jurisprudential writings. Proprietors, editors and journalists wrote and spoke about the importance of what they do for all of us in the UK, and the value it has for our common life. Politicians described the principles informing their own relationship with the media, including as policy-makers. Commentators suggested the matters that the Inquiry should bear particularly in mind in approaching its task. This brief overview seeks to distil, without necessarily fully rehearsing, the essence of the points of principle which were put before the Inquiry.</p>
  <?php paragraphLink('B',1,1,3); ?>Without seeking, or needing, to do full justice to the fine nuances of opinion which it is possible to hold and debate about such matters, this Part of the Report aims simply to set out a framework of understanding which is relatively uncontroversial. It is therefore the intention simply to underline, to put beyond doubt, the extent to which the Inquiry has itself proceeded on the basis of the perspectives set out, and to do so in terms with which I believe that most of the public would be able broadly to agree.</p>
  <?php paragraphLink('B',1,1,4); ?>It is also the intention of this Part of the Report to clarify some of the strands of thought which have been woven through a great deal of the evidence the Inquiry has received. Concepts such as the freedom of the press, freedom of expression and the public interest have been much referred to in the course of the evidence. These are potent expressions, and powerful and important concepts; commensurate clarity and care is needed in their deployment in the context of a Report on the culture, practices and ethics of the press. They are concepts which are capable of being, and have been, used both rhetorically and analytically to explain and support a range of different perspectives, arguments and conclusions.</p>
  <?php paragraphLink('B',1,1,5); ?>Attempting an all-embracing definition of concepts of this sort, even within the limitations of the Inquiry&#8217;s Terms of Reference, is neither necessary nor appropriate. Some measure of clarification is nevertheless attempted, both to underline the importance of these concepts and also to indicate the traps they can sometimes set for the unwary. This is not intended to make any claims to an especial authority in doing so, but only to give some indication of why they are important, and the limits of the uses and justifications to which they can be put. These are precious and fundamental principles, to which great respect must be paid; at the same time, they must be handled thoughtfully and with care.</p>
  <?php paragraphLink('B',1,1,6); ?>The Inquiry was considerably assisted in this respect not only by the way that the issue has been put by so many journalists but, in particular by the expert witness evidence it received, in both written and oral form.<?php footnoteRef('B',1,1); ?> I recognise that I have freely borrowed from their observations in some of what follows and I am grateful to them. In doing so and while acknowledging this debt, I should make clear, that the analysis set out here is entirely that of the Inquiry and is not to be taken to be representative of the entirety of the views of the expert witnesses, collectively or individually. As with other aspects of the evidence that I have sought to summarise, I can only commend those interested to the original evidence: any summary cannot attempt to do full justice to it.</p>
  </div>

