<div class="content" id="contentPartGChapter2">
<h1 id="top">CHAPTER 4<br/>THE PRESS AND THE POLICE: CONCLUSIONS AND RECOMMENDATIONS</h1>
  <?php sectionAnchor('G',4,1); ?>Introduction</h2>
 <?php paragraphLink('G',4,1,1); ?>The subject-matter of Module Two of the Inquiry was the contacts and the relationship between the press and the police, and the conduct of each. At the heart of this issue was the straightforward question (which is the same as will be discussed in respect of politicians): did the relationship become too close? In order to arrive at a fair and comprehensive picture, the Inquiry has examined many facets of that way in which press and police interact. It has done so by looking at the overlapping issues of &#8216;tip offs&#8217;, &#8216;taking media on operations&#8217;, &#8216;off-the- record&#8217; briefings, leaks, whistleblowing, gifts and hospitality, entertainment etc.</p>
  <?php paragraphLink('G',4,1,2); ?>This list is lengthy but the issues underlying each of these areas have been similar. The words &#8216;integrity&#8217; and &#8216;perception&#8217; are common refrains. Putting the matter at its lowest, if a police officer tips off a member of the press, the perception may well be that he or she has done so in exchange for past favours or in the expectation of some future benefit. At its highest, the issue becomes one of integrity for the police officer: his or her professional standing may be put under scrutiny. And the issue is exactly the same for off-the-record briefings and leaks (to cite just two of these foregoing examples), although separate points &#8211; in essence discrete matters of detail &#8211; arise in each individual case.</p>
  <?php paragraphLink('G',4,1,3); ?>Integrity lies at the heart of policing by consent, and it is damaging enough if there is even the perception that a police officer may not be discharging his or her duty with complete transparency and disinterest. Ultimately, problems of perception lie at the heart of the public concerns regarding the police investigation into phone hacking up to January 2011 and the commencement of Operation Weeting. The full history has been examined at length above,<?php footnoteRef('G',4,1); ?> and my conclusions need not be restated here; but what is inescapable is that the harm to the reputation of the Metropolitan Police Service (MPS) in general and certain individual police officers in particular has been immense. I have already referred to the fact that a very damaging perception was created that the NoTW exercised an inappropriate degree of influence over the MPS, including a number of senior police officers and other employees. Public confidence is in the process of being restored by the work of the MPS since January 2011 and, I hope, the transparent process of this Inquiry.</p>
  <?php paragraphLink('G',4,1,4); ?>I mention the MPS specifically in the context of the investigation into phone hacking, but I am able to go further. The problems in the relationship between the police and the press covered by the evidence adduced during the course of Module Two of the Inquiry almost exclusively related to the MPS; save for isolated examples, typically arising when an event of national newsworthiness arose in the regions, the 43 police forces<?php footnoteRef('G',4,2); ?> outside the metropolis enjoy sound relationships with the press, and the conduct of each gives rise to no concern. I will touch on possible explanations for this later.</p>
  <?php paragraphLink('G',4,1,5); ?>I will examine each of the issues I have identified above in turn, and set out my conclusions and recommendations under separate headings, but at this stage I dwell on common or generic matters. There are a number of interrelated considerations which need to be set out. First, the scale of the problem needs to be kept in proportion. The Inquiry has not unearthed extensive evidence of police corruption (noting, as it has done, the current position in relation to Operation Elveden which is concerned with payments to public officials generally); nor is there evidence satisfying the standard of proof I am applying to findings of fact in this Inquiry, namely the balance of probabilities, that significant numbers of police officers lack integrity in one or more of the respects I have examined earlier.<?php footnoteRef('G',4,3); ?> Speculation, suspicion and legitimate perceptions may abound, and troubling evidence has been identified in a limited number of cases, but the notion that this may be a widespread problem as a matter of fact is not borne out.</p>
  <?php paragraphLink('G',4,1,6); ?>Having made that important point, I recognise that breaches of professional standards of the nature under consideration are extremely difficult to prove. Journalists protect their confidential sources, particularly if a briefing is off-the-record; tip offs may be suspected (in some cases, going so far as to generate a reasonable inference) but clear-cut evidence is usually lacking. Further, the difficulties inherent in conducting an effective leak inquiry are legion. These are all factors which I need to continue to bear in mind when examining the issue on a generic rather than a case-specific basis, and I do not overlook the fact that the Terms of Reference require me to approach my responsibilities, so far as is possible, at a reasonably high level of generality.</p>
  <?php paragraphLink('G',4,1,7); ?>Another highly relevant consideration is the need to find the right balance between relationships that are overly close and those which are non-existent. The importance of the free-flow of information (that is to say, appropriate information) between the police and the press cannot be overstated. The press have an important role in holding the police to account, and this entails building up relationships of trust with police officers thereby allowing the free exchange of information within relevant guidelines. Further, the whole concept of policing by consent requires the engagement of the public, and very often this will be best achieved through the mediation of the press.</p>
  <?php paragraphLink('G',4,1,8); ?>There are many respects in which off-the-record briefings operate against the public interest, but in some, the public interest will be well served. By way of example, trusted journalists will benefit from a &#8216;background&#8217; briefing which enables reporting on specific topics to be placed in their proper context; the press may be warned off pursuing certain lines of inquiry or publishing a story on a particular occasion through concern that a police investigation may be prejudiced. Further, albeit in a different context, although generally speaking drinking alcohol in a professional context amounts to poor judgment, and should not happen, there may well be occasions, admittedly relatively rare, on which it is unobjectionable. The point I am making is a short and simple one; I am addressing the need to find the right balance, the mid-course between policies and practices which are overly prescriptive one way or the other.</p>
  <?php paragraphLink('G',4,1,9); ?>In many cases the straightforward application of common sense will be a sufficient guide: the Chief Constable of Avon and Somerset, Colin Port, referred to this as &#8216;the blush test&#8217;. Yet, although that may work perfectly well for the vast majority of police officers working hard and conscientiously in the public interest, some may blush less readily than others. Furthermore, there remains a need for written policy guidance which is clear and directive, and caters for the majority of situations. One issue which the Inquiry has focused on is the variability of such guidance across the Police Service as a whole. There is a need for greater consistency in certain instances, and for an overarching set of principles. I appreciate that both Her Majesty&#8217;s Inspectorate of Constabulary (HMIC) and the Association of Chief Police Officers (ACPO) are addressing this issue, but further work needs to be done.</p>
  <?php paragraphLink('G',4,1,10); ?>Another factor which I bear in mind, and this harks back to what I said about the MPS, is that senior police officers working in London are expected to have a public face: they speak for the organisation as a whole in the public domain, often on issues of huge importance and concern, and in so doing will necessarily engage with the press. I do not overlook the fact that Chief Constables will also need to form professional relationships with their regional titles, but the pressures and expectations are not quite the same. Furthermore, there has been an understandable tendency for senior police officers operating in London &#8211; those at the rank of Assistant Commissioner and above &#8211; legitimately to regard themselves as akin to political figures in the sense that the nature of their work can regularly place them in the public eye. As I have already pointed out, a number of Commissioners of the MPS have deliberately courted professional relationships with the press, amongst other reasons, in an effort to enhance the standing of the service in the minds of the public. But the distinction between endeavouring to improve the standing of the Service on the one hand, and working in the pursuit of self-interest on the other, may be a fine one.</p>
  <?php paragraphLink('G',4,1,11); ?>The Police Service is also a hierarchical organisation with clear command structures and delineations of authority. This has at least two consequences. First and foremost, junior officers will look up to their seniors for professional and ethical guidance; not necessarily by expressly seeking advice, but rather for the example they might set. If a highly ranked officer is known to be wined and dined in expensive restaurants by representatives of the press, that has the potential to set the standard for those underneath him or her. Leading from the front carries with it both its privileges and its responsibilities. Secondly, and even more problematically, the chain of command makes it difficult for junior officers to report their seniors for breaches of professional standards, and at the very least there will be a perception that those in command of the Professional Standards Divisions (PSDs) of police forces may naturally be disinclined to approach concerns drawn to their attention regarding officers of a higher rank, if only because of the natural assumption that senior officers know what they are doing and doubtless can fully justify what, in a more junior officer, might be open to challenge. All this is human nature, and to that extent completely understandable; and pragmatic solutions need to be devised to address potentially intractable problems of this nature.</p>
  <?php paragraphLink('G',4,1,12); ?>Another factor I bear in mind is the risk of over-reaction. Lord Condon, a former Commissioner of the MPS, spoke of twenty year cycles, being something akin to &#8220;scandal, inquiry, remedial action, relaxation, complacency, scandal, inquiry.&#8221;<?php footnoteRef('G',4,4); ?> What he did not state expressly is that the &#8216;remedial action&#8217; has the potential of going too far in the direction of disengagement or, speaking more colloquially, battening down the hatches. Again, this is no more and no less than human nature, but one needs to identify the potential risk in order to guard against it.</p>
  <?php paragraphLink('G',4,1,13); ?>Before turning to examine the specific matters which were addressed above,<?php footnoteRef('G',4,5); ?> I need to put all of this into perspective by drawing attention to one answer Neil Wallis gave when pressed by Counsel to the Inquiry about his relationship with Lord Stevens when the latter was Commissioner of the MPS:<?php footnoteRef('G',4,6); ?></p>
 <blockquote>&#8220;A. This is really difficult, because I just find it&#8211; John Stevens is an officer who worked for 40-odd years in the police. He lived his life, 20 years, as a target for IRA assassination as he carried out the Stevens 3 Inquiries. He was the man who was the gangbuster in Northumbria. He came down here. He bust corruption in the Met. So the suggestion is that this man of integrity, of experience, of immense crime-fighting ability, is going to be seduced by me taking him down to Cecconi&#8217;s and having steak and chips and a nice bottle of wine? I just can&#8217;t begin to see where this comes from. All I&#8217;m saying is: have you ever had a working lunch? Have you ever had a working lunch with somebody more than once? Have you ever had a drink at that working lunch? You may well have not. I guarantee everybody in this room just about has and it is the way of the world. That is all I&#8217;m saying. I&#8217;m not suggesting &#8211; I certainly won&#8217;t accept the idea that me going for dinner with a police officer is any different from a civil servant going for dinner with a businessman. I see no difference in it at all. I might be wrong, but &#8211; <br/>
 LORD JUSTICE LEVESON: I&#8217;m not sure you are wrong.<br/>
  A. I&#8217;m certain I&#8217;m not.&#8221;</blockquote>
  <?php paragraphLink('G',4,1,14); ?>For ease of reference and understanding, I will set out my conclusions, and then my recommendations, in relation to the specific matters covered above.<?php footnoteRef('G',4,7); ?> Often, I will draw on my earlier analysis, expanding it only where I need to place my conclusions into context. I should record that I have had regard to the detailed and helpful closing submissions lodged by the Core Participants in relation to Module Two (as with the other modules): save in isolated instances, I do not refer to these expressly, but they have aided the development of my thinking on these matters.</p>
  <?php sectionAnchor('G',4,2); ?>Tip offs</h2>
 <?php paragraphLink('G',4,2,1); ?>By way of overview, the evidence that the Inquiry received on this issue could fairly be described as &#8216;light&#8217; in relation to specific incidents (ie it would rarely discharge the standard of proof I am applying to findings of fact), but it is reasonably compelling at a higher level of generality. Looking at the bigger picture, a critical mass of convergent evidence begins to be persuasive. Furthermore, putting the jigsaw together, rather more general inferences may be drawn; these cannot always be explained away by coincidence or invoking some other explanation.</p>
  <?php paragraphLink('G',4,2,2); ?>Tip offs are but one aspect of the wider problem of leaks. I have made the point, both in this context and elsewhere, that the more robust the systems and processes in place to mitigate the risks of leaks from within an organisation the better. I have also said<?php footnoteRef('G',4,8); ?> that it is sensible to go one stage further. It should be a matter of serious professional concern to the police that information about their activities which should be kept confidential remains so. The presence of the press at a high profile arrest may provide positive coverage although, unless very carefully handled, it may also give rise to difficult issues of fairness within the criminal justice process. Obviously, if for good reason, a decision has been taken to brief the press about a forthcoming arrest and to allow representative attendance, the risks (and the responsibilities to the target of an arrest) should have been calibrated and taken into account. If there is no such authority, however, and there is a legitimate inference that someone (whether police officer or civilian employee of the police) has leaked the information to the press generally or a journalist specifically, I do not take the view that this is &#8216;just one of those things&#8217;. It should not have happened.</p>
  <?php paragraphLink('G',4,2,3); ?>The professionalism required of police officers must be sufficiently robust to instil the mindset that such leaks about forthcoming arrests or the involvement of the famous in the criminal justice system are not in the public interest, and that the provision of appropriate briefing as to police activity should only be handled through open and transparent procedures which have taken account of all relevant circumstances: they should not be by the back door.</p>
  <?php paragraphLink('G',4,2,4); ?>I do not have any individual recommendations to make which are specific to the issue of tip offs, as opposed to the related issue of leaks. However, police forces should bear in mind what I have said about the importance of adherence to professional obligations and the need for these decisions to be made in a formal and transparent manner, not clandestinely still less involving self-interest.</p>
  <?php sectionAnchor('G',4,3); ?>Involvement of the press on operations</h2>
 <?php paragraphLink('G',4,3,1); ?>Here, there are none of the evidential issues I have mentioned in the context of tip offs, in the sense that the fact of a press presence at an arrest or similar operation will be obvious. Nor do I have a sense that such problems that have existed in the past give rise to special concern. Nonetheless, I do recognise that there are issues which could arise of privacy under Article 8 and fair trial under Article 6 of the European Convention on Human Rights (ECHR), particularly in the sort of high-profile case which may be of the most interest to the press. There are also issues of perception and favouritism, although the evidence I have heard falls short of suggesting anything close to an exchange of favours.</p>
  <?php paragraphLink('G',4,3,2); ?>I have already pointed out that there is existing ACPO Guidance<?php footnoteRef('G',4,9); ?> and formal MPS policy<?php footnoteRef('G',4,10); ?> on this issue. The question arises as to whether these documents are sufficient to assuage public concerns in this respect. As I have made clear above,<?php footnoteRef('G',4,11); ?> I detected in much of the reflective evidence I heard on this issue a sense that there needs to be a further tightening of the current approach.</p>
  <?php paragraphLink('G',4,3,3); ?>Overall I would endorse the general views of the Commissioner, Bernard Hogan-Howe, and Chief Constable Andrew Trotter, of the British Transport Police, on this issue. Police forces must weigh very carefully the public interest considerations of taking the media on police operations against the rights of the individuals who are the subject of such an operation. Forces must also have directly in mind a consideration of any potential and consequential impact on the victims in such cases. More generally, I think that the current guidance in this area needs to be strengthened. For example, I think that it should be made abundantly clear that save in exceptional and clearly identified circumstances (for example, where there may be an immediate risk to the public), the names or identifying details of those who are arrested or suspected of a crime should not be released to the press or the public: these details are not routinely announced by way of press release; that the press were present at the arrest should make no difference.</p>
  <?php sectionAnchor('G',4,4); ?>Off-the-record briefings</h2>
 <?php paragraphLink('G',4,4,1); ?>It has already been noted that this terminology generates a degree of confusion, which in itself has the capability to undermine adherence to professional standards. Given the room for debate about the meaning of this term and others describing the status to be accorded to information supplied by police officers, it is unsurprising that the current &#8216;Interim ACPO Guidance for Relationships with the Media&#8217; seeks to define the widely deployed terminology expressly:<?php footnoteRef('G',4,12); ?></p>
<blockquote>&#8220;On the record &#8211; means that a journalist can report, quote and name their source. Where possible, all conversations should be on this basis and it should always be assumed that a conversation is on the record unless expressly agreed otherwise in advance. Background/guidance &#8211; means that information provided can be reported without it being attributed to a source, whether named or not. This is sometimes used to provide further context around an on the record statement. Off-the-record &#8211; means that use of information provided is restricted altogether. Occasionally there may be a legitimate reason for an off-the-record conversation or briefing to take place, such as where news reporting may have an impact on a current investigation or as a means of preventing inaccuracies or misunderstanding.&#8221; </blockquote>
  <?php paragraphLink('G',4,4,2); ?>I have already recognised that the use of off-the-record briefings, properly understood, may be a valuable resource in the context of an established, trusting relationship between a police officer and a journalist. Without seeking to revisit the terminological debate, background/ guidance briefings are also capable of working in the public interest, as opposed to the private interests of the police officer or the journalist. On the other hand, risks clearly exist and these are of a similar nature to those already highlighted in Sections 2 and 3 above: the potential for confidential information to be disseminated and then published; the perception that inappropriate relationships will be created and favours exchanged.</p>
  <?php paragraphLink('G',4,4,3); ?>I have already pointed out that Elizabeth Filkin in her report into the ethics of the press and police relationship, agreed that there was value for the Police Service in the limited and responsible use of &#8216;off-the-record&#8217; communications. She was specific about this:<?php footnoteRef('G',4,13); ?></p>
<blockquote>&#8220;&#8230;I have no doubt that the police will have to occasionally do off-the-record briefing, because otherwise they would jeopardise an investigation, and a reporter may have got a bit of a story which, if they ran it, would be very harmful, and the only way to prevent that being run, in a sensible fashion, would be to give them an off-the-record briefing and to tell them that you would inform them as soon as you could when it was possible to let that get out onto the public airwaves.&#8221; </blockquote>
  <?php paragraphLink('G',4,4,4); ?>I certainly agree that, in the circumstances outlined above, and for example in the context of counter-terrorism operations or other sensitive police investigations, some form of non- reportable or confidential briefing mechanism should continue to be available as a limited tool for the Police Service in their interaction with the media. I am not sure that any more specific guidance from me in this area is necessary or would be helpful.</p>
  <?php paragraphLink('G',4,4,5); ?>However, I would make the following observations. Given the confusion that clearly exists between journalists and police officers and police staff alike in relation to the term off-the- record, I believe that serious consideration should be given to its removal from the lexicon of police and media contact. Aside from the confusion in actual meaning, a negative connotation has also developed which implies that any exchange of information through &#8216;off-the-record&#8217; contact is being done on a surreptitious basis. In my view, greater clarity of thought and consistency of application would be achieved if two descriptors were used. What is critical is that there should be no doubt about the status of all that passes from the officer to the press.  I recommend that the term &#8216;off-the-record&#8217; briefing should be discontinued. The  term &#8216;non-reportable briefing&#8217; should be used to cover a background briefing  which is not to be reported, and the term &#8216;embargoed briefing&#8217; should be used to  cover a situation where the content of the briefing may be reported but not until  a specified event or time.<?php footnoteRef('G',4,14); ?> In my judgment, these terms more neutrally describe  what are legitimate police and media interactions.</p>
  <?php paragraphLink('G',4,4,6); ?>In their written submissions at the conclusion of Module Two, the MPS set out its position as follows:<?php footnoteRef('G',4,15); ?>

 <blockquote>&#8220;The current thinking of the MPS is that there should be a requirement that a record be made of every contact between an MPS officer and a journalist. The purpose of that requirement would be to make it possible to ascertain, if the need ever arises, the nature and frequency of the contact, the level of contact and reason for contact. This, it is anticipated, would serve both as an incentive for personal discipline and a means for discovering and discouraging the unauthorised release of information. The guiding principle for the future regulation of contact with the media should be one of openness, allowing the Police Service to engage constructively with the media whilst ensuring that it can be held to account for its relationship with its media&#8221;</blockquote>

  <?php paragraphLink('G',4,4,7); ?>I welcome and endorse almost the whole of this contribution, save for the qualification that I would distinguish between a requirement and good practice in relation to the recording of contact between junior officers and journalists. I would also endorse the comments both of Roger Baker,<?php footnoteRef('G',4,16); ?> Her Majesty&#8217;s Inspector of Constabulary, and Mrs Filkin in relation to the need for transparency in this area. If the police are simply seeking to correct an inaccuracy within a story, for example, then I can see no legitimate reason why that contact should not normally be considered to be &#8216;on-the-record&#8217; (there may be rare occasions when the correction needs to be &#8216;off-the-record&#8217; to avoid identifying an individual suspect).</p>
  <?php paragraphLink('G',4,4,8); ?>More generally, although I would also encourage junior officers and staff to do the same (principally for their own protection),  I recommend that it should be mandatory for ACPO rank officers to record all of  their contact with the media, and for that record to be available publically for  transparency and audit purposes. This record need be no more than a very brief  note to the effect that a conversation has taken place and the subject matter of  that conversation. Where the discussion involves a more significant operational  or organisational matter, then it may be sensible for a more detailed note to be  retained. Finally, in circumstances where policy or organisation matters may be on  the agenda for discussion, it is good practice for a press officer also to be present.</p>
  <?php paragraphLink('G',4,4,9); ?>Given the important role that the press play in assuring police legitimacy and in protecting the public interest I certainly do not want to discourage contact between the police (at all levels) and the media. It also remains important that the appropriate degree of contact is maintained between the press and junior officers. Subject to what I have already said, the latter should be trusted to use their judgment to do what is right and not to do what is wrong, and be accountable for the consequences. However, where there is an incident of unauthorised disclosure, the lack of any record may in itself be a determining factor when assessing the propriety of what has happened in the context of an internal police leak investigation (assuming that there is other probative evidence which links the police officer to the leak).</p>
  <?php paragraphLink('G',4,4,10); ?>Finally, and most importantly in my view, police officers at all levels must only communicate with the media within their own area of competence. I would entirely endorse and, thus,  I recommend as good practice the simple rule included within the &#8216;Interim ACPO  Guidance for Relationships with the Media&#8217; which is:<?php footnoteRef('G',4,17); ?></p>
<blockquote>&#8220;Police officers and staff should ask: &#8216;am I the person responsible for communicating about this issue and is there a policing purpose for doing so?&#8217; If the answer to both parts of this question is &#8216;yes&#8217;, they should go ahead.&#8221; </blockquote>
  <?php sectionAnchor('G',4,5); ?>Leaks of information</h2>
 <?php paragraphLink('G',4,5,1); ?>This issue shares many themes in common with the previous topics &#8211; in particular, the disclosure of unauthorised, if not confidential, information to the press &#8211; but there is often an added dimension, namely a less than selfless motive. Leaks may take place because a police officer genuinely believes that this may be the best way of placing misconduct or impropriety into the public domain, but sometimes the motive is little other than personal disgruntlement or the desire to wound colleagues. Putting to one side the instances where such motives are in play, the issue of leaks clearly overlaps with the issue of whistleblowing which I address in Section 8 below, but at this stage I am looking at the matter more broadly.</p>
  <?php paragraphLink('G',4,5,2); ?>I fully accept and understand that the issue is much more nuanced than the foregoing short summary conveys, and I invite attention to my detailed examination of this topic above.<?php footnoteRef('G',4,18); ?></p>
  <?php paragraphLink('G',4,5,3); ?>As with &#8216;tip-offs&#8217;, there are serious evidential issues. Leaks are notoriously difficult to investigate, and often a suspected leak turns out to be something different: the press may have obtained relevant information from some other source, or may simply have indulged successfully in an exercise in speculation. More specifically, Mr Baker suggested that leak investigations can be made more difficult &#8220;by the fact that there is a sloppiness of rules around what is permissible and what isn&#8217;t&#8230;&#8221;.<?php footnoteRef('G',4,19); ?> HMIC, through its report &#8216;Without fear or favour &#8211; a review of police relationship, also stressed the need for national standards in this area.<?php footnoteRef('G',4,20); ?> I would fully endorse that recommendation and I have dealt with the ongoing response of Police Service fully above.<?php footnoteRef('G',4,21); ?></p>
  <?php paragraphLink('G',4,5,4); ?>In Section 4 above, I have recommended that it should be mandatory for ACPO rank officers to record all of their contact with the media, and good practice for junior officers and staff (for their own protection). I entirely accept that this in itself will not prevent a determined individual from leaking. However, as Commissioner Hogan-Howe pointed out,<?php footnoteRef('G',4,22); ?> a record of that individual&#8217;s account would be a starting place for an investigation.</p>
  <?php paragraphLink('G',4,5,5); ?>A degree of lack of transparency in this area is inevitable given the often understandable desire of the media to protect the identity of their sources. Given the reputational damage that can be caused, I can also readily understand the frustration of the Police Service in circumstances where a &#8216;police source&#8217; is quoted but it then transpires that the information came from an outside individual. There is a balance here and, although I recognise the critical importance of protecting sources, I would certainly encourage the press to be as transparent as possible when using the term &#8216;source&#8217;, so that, where possible, the general provenance of the information is more easily understood: furthermore, to assert that there is a source when, in truth, there is not, both potentially damages the police and is, in any event, misleading on the part of the journalist.</p>
  <?php paragraphLink('G',4,5,6); ?>I turn to address the related issue of misuse of the Police National Computer (PNC). This was of particular concern to the Core Participant Victims and I am grateful for their written submissions on this topic. Overall, notwithstanding the problems that there have been, I am satisfied that the MPS and the wider Police Service now treat this issue with sufficient seriousness. However, it is equally clear that there can be no room for complacency in this area given that misuse of the PNC continues to be a problem for the service as a whole. With this in mind,</p>
  <div class="recommend">
  <p>I recommend that the Police Service should re-examine the rigour of the auditing  process and the frequency of the conduct of audits in relation to access to the  Police National Computer (PNC). Additional consideration should also be given  to the number of people given access to the PNC and the associated rules which  govern its usage.</p>
  </div>
  <?php sectionAnchor('G',4,6); ?>Gifts, hospitality and entertainment</h2>
 <?php paragraphLink('G',4,6,1); ?>These topics can be addressed under the same heading, although the issue of entertainment in particular has attracted significant public interest and concern. In many ways it is emblematic of the issues of perception which surround, if not encase, the relationship between the MPS and News International (NI) and the history of the investigation of phone hacking between 2006 and January 2011. The mention of expensive restaurants and bottles of champagne has done nothing to enhance the reputation of the MPS in the public mind.</p>
  <?php paragraphLink('G',4,6,2); ?>Apart from the evidence bearing directly on the relationship between the MPS and NI, which it is not necessary to recapitulate at this stage, the Inquiry heard of a wide range of approaches and house styles. Much of the variability is no doubt attributable to differing personalities and temperaments, but as Mrs Filkin has concluded more generally, &#8220;[t]here has been wide variation in how the senior team interpreted policy on dealing with the media and receiving gifts and hospitality. In some instances this interpretation is seen as inappropriate. There has been no clear standard set by the senior team for police officers and staff to use as a guide for their own behaviour and in some instances the standards set have been poor and have led to consequent damage.&#8221;<?php footnoteRef('G',4,23); ?> Mrs Filkin recommended that the MPS senior team &#8220;must signal a change in culture and set a consistent example for all staff on the ethical standards they expect, including how they relate to the media and the interpretation of the gifts and hospitality register.&#8221;<?php footnoteRef('G',4,24); ?> I would certainly endorse this finding.</p>
  <?php paragraphLink('G',4,6,3); ?>The recent ACPO Guidance<?php footnoteRef('G',4,25); ?> sets out the circumstances in which hospitality may, or may not, be accepted. I have set this out in full elsewhere.<?php footnoteRef('G',4,26); ?></p>
  <?php paragraphLink('G',4,6,4); ?>I have made it clear that I would certainly endorse the key principles contained within this guidance. Without wanting to be overly prescriptive or puritanical on this issue, in the circumstances </p>
  <div class="recommend">
  <p>I recommend that the recent ACPO Guidance should more specifically spell out the  dangers of consuming alcohol in a setting of casual hospitality (without necessarily  specifying a blanket ban).</p>
  </div>
  <p> It also strikes me that the concept of an &#8220;industry norm&#8221; in this context may still allow for a variance in practice from force to force, and may tend to assume what needs to be established. However, I would certainly adopt in full the guidance provided to police officers (at all levels) and police staff in helping them to determine the boundaries of what is acceptable: </p>
  <blockquote>&#8220;Is it genuine? Is the offer made for reasons of genuine appreciation for something I have done? Why is the offer being made? What are the circumstances? Have I solicited this offer in any way or does the donor feel obliged to make this offer? Is it independent? Would the offer or acceptance be seen as reasonable in the eyes of the public? Would a reasonable bystander be confident I could remain impartial and independent in all of the circumstances? Is it free? Will I feel obliged to do something in return? How do I feel about the propriety of the offer? What are the donor&#8217;s expectations of me should I accept? Is it transparent? Would I be comfortable if my acceptance of this offer was transparent to colleagues, the force, and the public or if it was reported publicly? What could be the outcome for the force if this offer was accepted or declined.&#8221;<?php footnoteRef('G',4,27); ?></blockquote>
  <?php paragraphLink('G',4,6,5); ?>It is also vital that transactional change in the form of new policies and guidance is aligned with real cultural change. As the evidence has made clear, leadership can be the key determining factor in this regard. Given this, it is important that a challenging and transparent environment exists within each force area so that staff at all levels, including those at ACPO rank, understand what is expected of them in terms of issues of integrity.</p>
  <?php sectionAnchor('G',4,7); ?>Media employment</h2>
 <?php paragraphLink('G',4,7,1); ?>I have examined this topic from two opposing perspectives: first, from the viewpoint of journalists being recruited to work for the police service; and second, the other way round. Unsurprisingly, the second issue is far more sensitive and problematic than the first.</p>
  <?php paragraphLink('G',4,7,2); ?>In brief, I do not believe that there should be any restriction on journalists being recruited to work for the Police Service, save that the process should be conducted in line with the procedures of the Government Communication Network (GCN) in an open and transparent manner. It may in fact be good practice, for the purposes of transparency, for individual forces to publish details ofthemake-up of their PRor communications departments in genericterms, but I consider that to be a matter for them. There is clearly a need for media expertise and the Police Service should be free to choose the best person for the job in a competitive free market. That is not to say &#8211; as a freestanding observation -<!--not a hyphen--> that forces should not examine their existing media relations training and awareness with a view to increasing skill levels, in relation to which Surrey Police have derived much benefit.<?php footnoteRef('G',4,28); ?></p>
  <?php paragraphLink('G',4,7,3); ?>The issue of police officers leaving to work for the media is, I have already said, more difficult. That issue may be sub-divided into two segments. Taking first the position of junior officers, I have concluded that it would be wrong to place restrictions, for example in the form of a &#8216;cooling off&#8217; period, on police officers and staff below ACPO rank leaving the Police Service, perhaps to return to a career in the media. In practice, the evidence suggests that journalists leaving the police service for an employed job rarely return to journalism. In addition, any restrictions would clearly have to be balanced against the right of any individual to seek employment as and where he or she wishes. In these circumstances, I believe that it would be contrary to the public interest to impose any restrictions of the type described.</p>
  <?php paragraphLink('G',4,7,4); ?>The position is different as regards senior officers of ACPO rank. The Inquiry received a considerable body of evidence which reflected public concern of very senior officers taking media jobs (usually on retirement), or writing articles for the press; I do not touch the question of books or memoires. This issue is intertwined in the public mind with the broader perceptual questions surrounding the relationship between senior officers of the MPS and NI, a topic which I have covered fully elsewhere.<?php footnoteRef('G',4,29); ?></p>
  <?php paragraphLink('G',4,7,5); ?>Whilst mindful of the concerns expressed by a number of witnesses, including Sir Paul Stephenson, the former Commissioner of the MPS, and Chief Constable Stephen House, of Strathclyde Police, in particular, on balance I have come to the conclusion that consideration should be given to the terms on which ACPO rank officers are engaged and, in particular to whether these terms should be amended to prevent employment by media organisations in much the same way as the previous Metropolitan Police Authority (MPA) contracts prevented employment by those with a contractual relationship with the MPS. I appreciate that regard must be had to issues of restraint of trade, to the right to seek employment, to freedom of expression, and, additionally, to the public interest in receiving information. But there are counterbalancing public interests that are also important. With this in mind, it seems to me that a time bar of twelve months would be sufficient to provide an appropriate balance between the rights of the individual and public interest concerns relating to future employment by the media.</p>
  <?php paragraphLink('G',4,7,6); ?>I am not in a position to consider all the ramifications of such a proposal; my recommendation is, therefore, limited. In the circumstances,</p>
  <div class="recommend">
  <p>I recommend that consideration should be given to the terms upon which ACPO  rank officers are appointed and, in particular, whether these terms should include  some limitation upon the nature of any employment within or by the media that  can be undertaken without the approval of the relevant authority for a period of 12  months following the cessation of the appointment.</p>
  </div>
  <p>I understand that should this recommendation be accepted then it may also require a change in the regulations governing the Police Service.</p>
  <?php sectionAnchor('G',4,8); ?>Corruption, whistleblowing and related matters</h2>
 <?php paragraphLink('G',4,8,1); ?>I appreciate that the topics of whistleblowing and corruption raise issues which are common to neither, but for the purposes of this Inquiry there is much common ground. It is for that reason that I take them together. Doing so also makes it easier to follow the series of recommendations which I set out below.</p>
  <?php paragraphLink('G',4,8,2); ?>I take corruption first. The Inquiry has not been the place to examine the broader issue of corruption within the Police Service; the focus has rightly been on corruption in the specific context of media relations. Additionally, the current position in relation to Operation Elveden has inevitably hampered the ability of the Inquiry to delve into the issue in any depth. Nonetheless, I bear in mind the frank evidence I have heard from senior police officers which has given me a clear sense of the seriousness and scale of the problem. No one underestimates the gravity of the issue as a matter of generality, but it would be wrong for anyone to believe that corruption is endemic in the Police Service.</p>
  <?php paragraphLink('G',4,8,3); ?>As I have already pointed out, training and guidance are obviously important preventive tools in seeking to address this issue. The relevant overarching guidance in this area is provided, first, through the ACPO Counter Corruption Advisory Group (ACCAG), whose &#8216;Guidance for the Investigation of Corruption&#8217; was first published in 2003 and last formally revised in 2006; this guidance has been adopted by all chief officers.<?php footnoteRef('G',4,30); ?> Second, the recognised &#8216;Standards of Professional Behaviour&#8217; are set out in the Schedule to the Police (Conduct) Regulations 2008 and the related Home Office guidance (026/2008) on police unsatisfactory performance and misconduct procedures, and Standards of Professional Behaviour for Police staff, as agreed by the Police Staff Council. This guidance has also been adopted by all police forces, including the MPS.<?php footnoteRef('G',4,31); ?> Both sets of guidance are currently under review and are dealt with in more detail elsewhere.<?php footnoteRef('G',4,32); ?></p>
  <?php paragraphLink('G',4,8,4); ?>Evidenced bytheguidance and training currentlyin place,and thevigourwith which individual police officers and police staff are pursued where criminality is identified, it is clear that the Police Service takes this issue seriously. There are, however, gaps and weaknesses in the collective approach to the issue a number of which have been identified by HMIC. Having said that, I am in no doubt that the Police Service is genuine in its desire to tackle corruption head on, with the ACPO led response to the HMIC report being particularly important in this regard. For my part, I would whole heartedly adopt the HMIC recommendations relating to the need for consistent national standards and guidance, enhanced training and awareness, and more robust corporate governance arrangements. From the stand-point of sanctions, corruption is a criminal offence with serious penalties, I do not feel it necessary therefore, to recommend any additional statutory or regulatory tools to assist in dealing with this important issue.</p>
  <?php paragraphLink('G',4,8,5); ?>The Home Secretary, the Rt Hon Theresa May, confirmed this last point and provided the Inquiry with her summary of the key findings. She said:<?php footnoteRef('G',4,33); ?></p>
<blockquote>&#8220;I think the key findings that come out of this in many ways chime in with those previous work that&#8217;s been done, particularly by the HMIC, about the need for greater clarity both for the public in terms of what&#8217;s police corruption and therefore what is appropriate to bring to the IPCC, but also greater clarity in terms of &#8211; perhaps greater consistency in recording incidents that have taken place from force to force. They identify that different forces appear to have&#8230;different levels of reporting of complaints about corruption and the question is raised as to whether that&#8217;s because of a different definition being used rather than the behaviour in relation to the forces. Crucially, it refers again to the issue of additional powers and also about resources, and these are issues that we intend, when legislative time allows, to be able to make changes to the powers to the IPCC and we are looking at the case that they&#8217;ve put forward in relation to additional resources.&#8221; </blockquote>
  <?php paragraphLink('G',4,8,6); ?>I certainly support these proposed changes and share the view of the IPCC that, in order for the system to work as it should, it is vital that all police forces are both alert to allegations of corruption and are capable of dealing with them effectively and appropriately.<?php footnoteRef('G',4,34); ?> I also agree that this is an area where independent oversight is essential, particularly from the standpoint of public perception, not least because the confidence of the public in the police is fundamental to its legitimacy and to the absolutely critical cooperation and compliance that, as an organisation, it needs both to expect and also to achieve.</p>
  <?php paragraphLink('G',4,8,7); ?>The issue of corruption overlaps with that of whistleblowing for the obvious reason that the latter is often the route to the former being exposed. I recognise that there are other routes, including of course robust investigative journalism (undeniably in the public interest) as well as the persistent endeavours of leaders within the Police Service, but for present purposes I am focusing on disclosures from within the organisation.</p>
  <?php paragraphLink('G',4,8,8); ?>I recognise and understand the sensitivity of this issue, and the sentiment expressed by many that the press is a safety valve for genuine grievances and concerns within the Police Service as a whole. However, there remains an important point of principle which I need to come back to: that information which is confidential should remain so, unless there really are exceptional circumstances justifying the placing of that information into the public domain. Additionally, and looking at this more widely, the ends do not usually or, at least necessarily, justify the means.</p>
  <?php paragraphLink('G',4,8,9); ?>My overall assessment is that a series of pragmatic solutions need to be devised to maximise the chance that genuine whistle-blowers will use confidential avenues in which they may have faith, rather than feel it necessary to break confidences by bringing about much wider public dissemination through disclosures to the media. In my view, this strikes the right balance between the competing interests at stake.</p>
  <?php paragraphLink('G',4,8,10); ?>As I have already said, the starting point for any police officer or member of police staff wishing to report an issue of concern should be that they first look to their internal procedures, which are buttressed by the law governing protected disclosures. I appreciate that all police forces already have a whistleblowing line of reporting direct to the PSD of that force: typically, this will be headed by a detective chief superintendent &#8211; in other words, a senior officer capable of holding the respect of the majority of police ranks. Nonetheless, I also recognise that Mrs Filkin identified a general lack of confidence in the ability of these departments to address their concerns across the board. There may also be some legitimate concern as to the ability (if not the overall willingness) of PSDs challenging the most senior on issues concerning integrity </p>
  <?php paragraphLink('G',4,8,11); ?>Apart from the PSDs, the present position is that the Independent Police Complaints Commission (IPCC) already has a Public Interest Disclosure Act telephone line which is available for use in these circumstances, but it does not enjoy a sufficiently high profile. As and when whistle blowers use it, I understand that the IPCC&#8217;s practice, if at all possible, is to conduct an interview, in order better to inform its assessment of the merits of the concern being expressed.</p>
  <?php paragraphLink('G',4,8,12); ?>Given the apparent lack of trust in the current process, a more independently operated system should be considered. I strongly believe that a more developed structure is required to ensure that the public have absolute confidence that issues of integrity will be appropriately addressed at all levels within the Police Service, and that whistle blowers also have the confidence that their grievances will be addressed.</p>
  <?php paragraphLink('G',4,8,13); ?>As I explain below, I have in mind an enhanced role for both the IPCC and HMIC. For a number of reasons I am not in a position to descend into the detail of the structure I have in mind not least because of the changing landscape surrounding police policy and its implementation. I am simply not in a position to forecast precisely how the responsibilities of the newly elected Police and Crime Commissioners (PCCs) will fit into the overall picture alongside the work of the newly created National Crime Agency, ACPO (howsoever designated) or the National Police Improvement Agency (to be superseded by the College of Policing). Neither is it clear to me how the work of the HMIC will be affected, or what (if any) impact there will be on the IPCC. All that I can do is to describe the architecture, and others will need to take it forward by inserting the building-blocks as relationships and responsibilities are established. I recognise that each of the bodies I have mentioned will wish to contribute to that debate and a number have not given evidence to the Inquiry.</p>
  <div class="recommend">
  <?php paragraphLink('G',4,8,14); ?>In the circumstances, I recommend that an enhanced system for protection of whistle  blowers and for providing assistance for the Police Service on general ethical issues  should at least comprise the following: 
  <ol type="a"> 
<li>greater prominence should be given to the IPCC&#8217;s PIDA telephone line; </li>
<li>there should be an &#8216;ethics line&#8217; to the IPCC, available for all serving Police Officers,  providing general ethical guidance; </li>
<li>to avail those at Chief Officer level (Assistant Commissioner level within the  MPS), HMIC should identify one of its members, a former Chief Constable, as the  designated point of contact for confidential ethics guidance. The Chief Officer  seeking and obtaining that advice would be able to refer to it should any issue  subsequently arise on a complaint to a PSD, a PCC, or indeed the IPCC itself. The  advice would not be determinative of the complaint, but the fact that it was  sought and received, as well as its content, would be a matter to be taken into  account; </li>
<li>within the IPCC itself, there is a need for an enhanced &#8216;filter system&#8217; whereby  the nature of complaints are appropriately addressed at an early stage so that  (a) they can be investigated at the right level, and (b) sufficient structures are put  in place to maintain confidentiality of the complaint, and differentiate as soon  as is appropriate between genuine whistle blowers and those who are merely  ventilating a personal grievance; </li>
<li>the former Chief Constable referred to under sub-paragraph (c) above should  also be the recipient of complaints about Chief Constables made to the IPCC. In  the event that he or she may already have given informal advice in relation to  the subject-matter of the complaint, as per sub-paragraph (c) above, a substitute  HMI would be deputed to act; and </li>
<li>Chief Officers should also be the subject of regular independent scrutiny by  HMIC, including through unannounced inspections.</li>
  </ol>
  </p>
  </div>
  <?php paragraphLink('G',4,8,15); ?>As I have said, and for the reasons I have given, I am not addressing the actual mechanics of such a system in this Report. But allied to this, I would also consider it prudent for PCCs and Chief Officers quickly to reassess the corporate governance arrangements in place within each force area to ensure that they are fit for purpose. This would obviously be an important part of ensuring that each of their specific roles and responsibilities in this area are clearly delineated.</p>
  <?php sectionAnchor('G',4,9); ?>Conclusion</h2>
 <?php paragraphLink('G',4,9,1); ?>It is clear that the Police Service as a whole has responded positively and proactively in the wake of the public concerns which led to the setting up of this Inquiry in July 2011. I welcome the thoroughness and good sense of the changes which have been recommended to date, and the spirit in which the Police Service has demonstrated willingness for implementing appropriate and judicious enhancements of the existing regimes. Ultimately, the Police Service in general and the MPS in particular has understood the importance of such a positive response in terms of allaying public concerns and correction legitimate perceptions.</p>
  <?php paragraphLink('G',4,9,2); ?>In taking its existing work forward, as supplemented by the recommendations I have made in this Chapter, I fully endorse the judicious contribution made by the Home Secretary to the Inquiry and, in particular, her emphasis on the need for a country-wide series of policies coordinated through or by ACPO. The majority of the issues at stake here are of universal application. The &#8216;blush test&#8217; will continue to work as a sound guide for the vast majority but clear leadership and the setting of the tone from the top is vital. Finally, clear and direct policy guidance is necessary to reinforce these common sense messages.</p>
  </div>

