<div class="content" id="contentPartKChapter2">
<h1 id="top">CHAPTER 1<br/>CRITERIA FOR A REGULATORY SOLUTION</h1>
 <?php sectionAnchor('K',1,1); ?>Introduction</h2>
 <?php paragraphLink('K',1,1,1); ?>In order to make recommendations for a new more effective regulatory regime, as required by the Terms of Reference of the Inquiry, it is essential first to consider what a regulatory regime should be seeking to achieve. There are three aspects to this question: first, what a regulatory regime should do; second, how it should be structured to achieve that; and third, the detailed rules that are put in place to achieve the objectives. The &#8216;what&#8217; is about outcomes and the &#8216;how&#8217; is about processes, structures and accountabilities. The detailed rules should be dealt with in the substance of any code or regulations. These three aspects of a regulatory regime need to be considered separately as they are not necessarily dependent on each other and it may be possible to achieve the desired objectives by different combinations of solutions.</p>
  <?php paragraphLink('K',1,1,2); ?>This chapter is specifically about the &#8216;what&#8217;. In May 2012 I published on the Inquiry website a set of draft criteria for a regulatory solution that aimed to set out what any regulatory solution should seek to achieve. This was not concerned with how those outcomes should be achieved, or the structures through which they should be achieved, but simply what the outcomes should be. Those draft criteria were: </p>
  <blockquote> <h5>1. Effectiveness</h5>
  <p> 1.1 Any solution must be perceived as effective and credible both by the press as an industry and by the public: </p>
  <ol style="list-style-type:lower-alpha;"> 
  <li>It must strike a balance, capable of being accepted as reasonable, legitimate and in the public interest by all. </li>
  <li>It must recognise the importance for the public interest of a free press in a democracy, freedom of expression and investigative journalism, the rule of law, personal privacy and other private rights, and a press which acts responsibly and in the public interest. </li>
  <li>It must promote a clear understanding of &#8216;the public interest&#8217; which would be accepted as reasonable by press, industry and public alike. </li>
  <li>It must be durable and sufficiently flexible to work for future markets and technology, and be capable of universal application. </li>
  </ol> 
  <h5>2. Fairness and objectivity of Standards</h5> 
  <p> 2.1 There must be a statement of ethical standards which is recognised as reasonable by the industry and credible by the public. This statement must identify enforceable minimum standards as well as articulating good practice that should be aimed for.</p>
  <p> 2.2 All standards for good practice in journalism should be driven by the public interest and must be benchmarked in a clear objective way to the public interest.</p>
  <p> 2.3 The setting of standards must be independent of government and parliament, and sufficiently independent of media interests, in order to command public respect.</p>
  <h5>3. Independence and transparency of enforcement and compliance</h5> <p> 3.1 Enforcement of ethical standards, by whatever mechanism, must be operationally independent of government and parliament, and sufficiently independent of media interests, in order to command public respect.</p>
  <p> 3.2 In particular all relevant appointments processes must be sufficiently independent of government, Parliament and media interests to command public support.</p>
  <p> 3.3 Compliance must be the responsibility of editors and transparent and demonstrable to the public.</p>
  <h5>4. Powers and remedies</h5> <p> 4.1 The system must provide credible remedies, both in respect of aggrieved individuals and in respect of issues affecting wider groups in society.</p>
  <p> 4.2 The regulatory regime must have effective investigatory and advisory powers.</p>
  <p> 4.3 The system should also actively support and promote compliance by the industry, both directly (for example by providing confidential pre-publication advice) and indirectly (for example by kitemarking titles&#8217; own internal systems).</p>
  <p> 4.4 The system should be a good fit with other relevant regulatory and law enforcement functions.</p>
  <h5>5. Cost</h5> <p> 5.1 The solution must be sufficiently reliably financed to allow for reasonable operational independence and appropriate scope, but without placing a disproportionate burden on either the industry, complainants or the taxpayer.&#8221; </p>
  </blockquote> </p>
  <?php paragraphLink('K',1,1,3); ?>I sought comments on these draft criteria. Most of those who have submitted evidence on regulation have accepted the criteria without comment. Some, including Ofcom,<?php footnoteRef('K',1,1); ?> made substantive comments on the criteria, suggesting that further consideration was needed on a number of areas. Where appropriate, I address these comments later in this Chapter. I am, however, satisfied that the broad categories are correct and they continue to form the basis of what I would hope could be achieved through the recommendations set out later in this part of the Report.</p>
  <?php sectionAnchor('K',1,2); ?>Effectiveness</h2>
 <?php paragraphLink('K',1,2,1); ?>The ultimate test of any new regime is that it must work in practice, in terms of ensuring that the press comply with agreed standards. But that simple statement itself begs three questions. The first is what is meant by &#8216;ensuring&#8217;; the second, what is meant by &#8216;the press&#8217;; and the third is what is meant by &#8216;agreed standards&#8217;. I address all of these points in this section of the report. The Inquiry has heard over and over again that aspects of the current PCC based regime may be good in principle but that they simply do not work in practice. The essential flaws of the current regime have been examined elsewhere.<?php footnoteRef('K',1,2); ?> At one fundamental level, the current &#8216;self-regulatory&#8217; regime has failed to achieve continued universal coverage of the main national newspaper titles with the withdrawal of Northern and Shell. I do not consider that it is possible for a regime to be considered effective if a major national newspaper group can choose to sit outside it without consequences. This should not be a controversial view, as it essentially echoes Lord Hunt&#8217;s opinion that:<?php footnoteRef('K',1,3); ?>
<blockquote>&#8220;the credibility of the new system could be fatally undermined if any genuinely big fish seek to escape the net.&#8221; </blockquote>Lord Hunt went on to confirm that Northern and Shell would qualify as a &#8216;big fish&#8217; in this context.<?php footnoteRef('K',1,4); ?> The very fact that the industry has sought to put forward what it believes to be a new and fundamentally different approach to self-regulation constitutes a clear recognition that the existing regime is no longer effective.</p>
  <?php paragraphLink('K',1,2,2); ?>Other aspects of external regulation, including the criminal and the civil law, have significant structural weaknesses, as is more fully discussed elsewhere in the Report.<?php footnoteRef('K',1,5); ?> An effective regulatory regime will need to take account of those shortcomings and find ways of rectifying them or otherwise dealing with them as far as possible.</p>
  <?php paragraphLink('K',1,2,3); ?>There are a number of different aspects of effectiveness. Views on what constitutes effectiveness vary, but the broad headings included within the draft criteria have not been contested. The draft criteria indicated that, in order to be effective, a regulatory regime for the press must be accepted as credible both by the press and the public and this proposition has not been seriously disputed by anyone. This does not mean that either the industry or interest groups should have a veto over the solution, but it is important that the regime should be grounded in an understanding of the industry, the law, the rights and freedoms of both individuals and the press, and the public interest in its widest sense. A regime that fails to take any of those factors fully into account will fail to meet the expectations and needs of the public.</p>
  <?php paragraphLink('K',1,2,4); ?>The draft criteria set out a broad perspective on the public interest. As with the concept of effectiveness, there are many different aspects to the public interest in this context. The public interest in the freedom of the press and freedom of expression, including the public interest in a diverse and vibrant press, are the most obvious. Any regulatory regime that compromised the freedom of the press to hold authority to account, or to investigate wrongdoing by the powerful, would not qualify as effective according to any reasonable person&#8217;s definition of that term. The public interest in the rule of law is also important. The law applies to journalists and the press as it applies to everybody else. This is not to say that journalists cannot sometimes break the law in the pursuit of public interest journalism, but that does not override the general public interest in the rule of law: on the contrary, it recognises that a clear countervailing public interest must be identified before the rule of law may yield. Finally, there is a public interest in the protection of the private rights of individuals, including the right to privacy, which falls to be weighed in the balance against the public interest in free speech. Providing this requisite balance is one of the most difficult challenges for any regulatory regime.</p>
  <?php paragraphLink('K',1,2,5); ?>The Inquiry has heard evidence that different editors weigh up these countervailing public interests in different ways. That may not be unreasonable looking at individual cases alone, but from an enforcement perspective it is only fair for both the public and the press themselves that each relevant enforcement authority should be clear about the basis on which they will reach such judgments. It also seems reasonable that, if there is to be a body adjudicating on press or media standards, such a body should set out for the public and the industry some guidance on what might be meant by the public interest in this context. The PCC Code, as most recently revised, sets out the following non-exhaustive definition of the public interest:<?php footnoteRef('K',1,6); ?> <?php footnoteRef('K',1,7); ?> <blockquote> <h5>The public interest</h5> <p> There may be exceptions to the clauses marked * where they can be demonstrated to be in the public interest.</p>
  <ol> <li>The public interest includes, but is not confined to:</li>
 <ol style="list-style-type:lower-roman";> <li>Detecting or exposing crime or serious impropriety.</li>
 <li>Protecting public health and safety.</li>
 <li>Preventing the public from being misled by an action or statement of an individual or organisation.</li>
 </ol> <li>There is a public interest in freedom of expression itself.</li>
 <li>Whenever the public interest is invoked, the PCC will require editors to demonstrate fully that they reasonably believed that publication, or journalistic activity undertaken with a view to publication, would be in the public interest and how, and with whom, that was established at the time.</li>
 <li>The PCC will consider the extent to which material is already in the public domain, or will become so.</li>
 <li>In cases involving children under 16, editors must demonstrate an exceptional public interest to over-ride the normally paramount interest of the child.</li>
 </ol> </blockquote> </p>
  <?php paragraphLink('K',1,2,6); ?>There are a number of references to the public interest in the Ofcom Broadcasting Code.<?php footnoteRef('K',1,8); ?> There is no definition of the public interest as such, but the code does provide this</p>
<blockquote>&#8220;Examples of public interest would include revealing or detecting crime, protecting public health or safety, exposing misleading claims made by individuals or organisations or disclosing incompetence that affects the public.&#8221;</blockquote>
  <?php paragraphLink('K',1,2,7); ?>The BBC includes a definition of the public interest in its editorial guidelines:<?php footnoteRef('K',1,9); ?></p>
<blockquote><h5>The Public Interest</h5> <p> Private behaviour, information, correspondence and conversation should not be brought into the public domain unless there is a public interest that outweighs the expectation of privacy. There is no single definition of public interest. It includes but is not confined to: </p>
  <ul>
 <li>exposing or detecting crime <li>exposing significantly anti-social behaviour <li>exposing corruption or injustice <li>disclosing significant incompetence or negligence <li>protecting people&#8217;s health and safety <li>preventing people from being misled by some statement or action of an individual or organisation <li>disclosing information that assists people to better comprehend or make decisions on matters of public importance. </ul>
 There is also a public interest in freedom of expression itself.<br/>
  When considering what is in the public interest we also need to take account of information already in the public domain or about to become available to the public. When using the public interest to justify an intrusion, consideration should be given to proportionality; the greater the intrusion, the greater the public interest required to justify it.
  </blockquote>
  <?php paragraphLink('K',1,2,8); ?>Although these definitions, or examples, have a lot in common there are naturally some differences. Views have been advanced on each of them, but it is not for this Inquiry to draft a comprehensive working definition: this would be both an overly ambitious and inappropriate exercise. However, given that this is the <strong>public</strong> interest, and that it must explicitly relate to interests outside those of the media enterprise concerned, it must be reasonable to conclude that whatever interpretation of the public interest is to be used in a new regulatory regime, it should be recognised, understood and accepted by both the media and the public.</p>
  <?php paragraphLink('K',1,2,9); ?>Finally on the question of effectiveness, the criteria spoke of a durable solution, and one sufficiently flexible to work in the future. It is, of course, the case that, as many witnesses have told the Inquiry, the media market is changing. Rupert Murdoch predicted that the printed press might coexist with online news sources for possibly 20 years, but he also commented that others estimated that the print versions may not survive for more than five or ten years.<?php footnoteRef('K',1,10); ?> Without needing to take a view on how long the printed press will survive, it is unquestionably the case that a large proportion of people now receive at least some of their news and current affairs content, and their entertainment, from the internet. Ofcom estimated that 41% of people today use the internet for news and current affairs coverage, and that the internet accounts for 21% of news and current affairs consumption; this compares with 53% of adults using a newspaper, but newspapers account for only 11% of news and current affairs consumption.<?php footnoteRef('K',1,11); ?> Furthermore, the trend towards online consumption is rising. This makes it abundantly clear that, for a regulatory regime to be effective, it must be capable of delivering any perceived benefits to online publication as much as to print.</p>
  <?php paragraphLink('K',1,2,10); ?>The Inquiry has also received evidence that a single regulatory regime across all media would be desirable.<?php footnoteRef('K',1,12); ?> The Inquiry has heard some evidence on the nature and effectiveness of the existing statutory regulatory framework for broadcast media; but this has been largely for the purposes of comparison with the regime currently in place for print and to learn any relevant lessons. I have not sought to take evidence on the adequacy of the regime for the broadcast sector and, accordingly, it is not my intention to examine the fitness of that regulatory regime, or to make any recommendations as to how the broadcast sector should be regulated.</p>
  <?php paragraphLink('K',1,2,11); ?>Ofcom correctly commented that the published draft criteria did not mention membership.<?php footnoteRef('K',1,13); ?> The criteria aimed to set out what a new regulatory regime should achieve, not the means by which it should be achieved. The draft criteria provide that a new solution should be &#8216;capable of universal application&#8217;. My starting point, as set out above, is that any regime which did not at the very least cover all major national newspapers and their online presence, would not be effective. The Inquiry has received submissions suggesting that standards regulation might be limited to those of a particular size or with particular economic power.<?php footnoteRef('K',1,14); ?> Ofcom say:<?php footnoteRef('K',1,15); ?>
<blockquote>&#8220;Committed participation by the whole of industry would be fundamental to a successful new regulatory regime&#8221; </blockquote>It has been made abundantly clear in the proposals presented during Module Four of the Inquiry that the vast majority of interested parties agreed with that. All the proposals that have come to the table have sought to compel or entice the whole of industry into the tent. Any disagreement has been about whether compelling or enticing is the best way to achieve the objective of committed participation, coupled with what have been described as principled concerns about the use of legislation to compel any part of the press to do anything. I have no doubt that committed participation by the whole of industry is fundamental to an effective new regime.</p>
  <?php paragraphLink('K',1,2,12); ?>My conclusion is that Criteria 1 as originally drafted continues to reflect the essential elements of a new effective regime.</p>
  <?php sectionAnchor('K',1,3); ?>Fairness and objectivity of standards</h2>
 <?php paragraphLink('K',1,3,1); ?>The draft Criteria set out three aspects of fairness and objectivity of standards which I considered were fitting attributes of a new regulatory regime. The first was that there should be a statement of ethical standards which is recognised as reasonable by the industry and as credible by the public. This statement must identify enforceable minimum standards as well as articulating the good practice that should be targeted.</p>
  <?php paragraphLink('K',1,3,2); ?>The Inquiry has not undertaken a full systematic examination of the existing Editors&#8217; Code but it has identified some deficiencies that have been identified in evidence presented to the Inquiry.<?php footnoteRef('K',1,16); ?> Many witnesses have maintained that it is a good Code; others have argued that it has weaknesses. In this context I simply note that the current Editors&#8217; Code appears to be a mix of broad statements of principle (for example &#8220;the press, whilst free to be partisan, must distinguish clearly between comment, conjecture and fact&#8221; ); specific requirements (for example &#8220;even where the law does not prohibit it, journalists must not use for their own profit financial information they receive in advance of its general publication to others, not should they pass such information to others&#8221; ); and requirements that can sometimes be disregarded (e.g. &#8220;the press must not identify victims of sexual assault or publish material likely to contribute to such identification unless there is adequate justification and they are legally free to do so&#8221; ). In addition, there are examples of each of these types of statement which can be disapplied where doing so can be demonstrated to be in the public interest. Professor Megone commented that a code of practice needs to be presented in the context of the specific critical contribution that a free press can make to the public interest. Overall, there is room for improvement of the current Code.<?php footnoteRef('K',1,17); ?></p>
  <?php paragraphLink('K',1,3,3); ?>Second under this broad heading, the draft Criteria specified</p>
<blockquote>&#8220;All standards for good practice in journalism should be driven by the public interest and must be benchmarked in a clear objective way to the public interest.&#8221;</blockquote>
  <?php paragraphLink('K',1,3,4); ?>Associated News Limited (ANL) have raised a concern about this, stating that the press should be free to publish material of their choice without always having to justify it on grounds of public interest. I accept entirely that the vast majority of material published in most newspapers and magazines will not infringe other peoples&#8217; rights or the law and has no need to be justified on public interest, or any other, grounds. It was not the intention in these draft criteria to suggest that all material in a newspaper should be able to pass a public interest test. However, ANL also raised the issue of &#8220;information which might be thought to constitute a low-level interference with personal privacy&#8221; and, in the same context, observed that standards of this sort &#8220;would constrain newspapers from providing the broad mix of newspaper that&#8230;&#8230;.ensures the very survival of the industry.&#8221;<?php footnoteRef('K',1,18); ?> Here, the authorities do recognise that a minimum threshold of interference must be attained before the right itself may be said to be infringed. Exactly how this should be formulated would be for any future code-maker to consider. Subject to that, any infringement of the substantive right must be justified.</p>
  <?php paragraphLink('K',1,3,5); ?>Finally under this heading, the criteria specified that the setting of standards must be independent of Government and Parliament, and sufficiently independent of media interests in order to command public respect. In some ways this has sparked the most debate. Whilst there is universal agreement on the principle of the independent setting, there are also many proposals that would see Parliament laying down some basic criteria which such standards must attain. This is the case with, for example, the Irish Defamation Act, which has been cited by many as a successful example of how Government can incentivise independent regulation. There is also disagreement about what constitutes &#8216;sufficient&#8217; independence of media interests. Lord Black on behalf of the industry proposed a system in which serving editors still had a majority on the committee which set the standards,<?php footnoteRef('K',1,19); ?> whereas Ofcom, by contrast, considered it to be &#8220;unimaginable&#8221; to have anyone currently active within the industry as part of the standards setting body.<?php footnoteRef('K',1,20); ?></p>
  <?php paragraphLink('K',1,3,6); ?>It would therefore appear that, whilst everyone is willing to support the theory of independence, it is difficult to find any particular consensus on what independence looks like in practice.</p>
  <?php paragraphLink('K',1,3,7); ?>My conclusion is that Criteria 2 as drafted remains the right articulation of fairness and objectivity of standards, but with an explicit recognition that not all material published in newspapers would or should need to satisfy a public interest test as opposed to providing material which merely entertains or interests the public. The standards must, however, recognise that any infringement of individual rights should only be acceptable where there is a sufficient public interest rationale.</p>
  <?php sectionAnchor('K',1,4); ?>Independence and transparency of enforcement and compliance</h2>
 <?php paragraphLink('K',1,4,1); ?>The draft Criteria provided that enforcement of ethical standards must be operationally independent of Government and Parliament and sufficiently independent of media interests. This, by contrast with the setting of standards, has proved relatively uncontroversial. All the proposals put forward to the Inquiry included an independent approach to complaint handling, and most attempted to describe a broader independent standards enforcement role. There were, inevitably, different views on what constitutes independence, but at a level of principle this seems to be genuinely uncontentious.</p>
  <?php paragraphLink('K',1,4,2); ?>The draft Criteria also provided that all relevant appointments processes must be sufficiently independent of Government, Parliament and media interests. This raises the basic conundrum of who appoints the appointers. None of those who have provided evidence to the Inquiry have suggested that the appointments processes should not be sufficiently independent of the interests listed, but there are differences around what constitutes &#8216;sufficiently&#8217;, and at what level the independence needs to be demonstrated. By way of example, in the proposal from Tim Suter, the Ofcom Content Board would need to approve the independence of the appointment process for any self-regulator, whilst the Content Board<?php footnoteRef('K',1,21); ?> itself is appointed by the Ofcom Board, which is appointed by Government.<?php footnoteRef('K',1,22); ?> Lord Black&#8217;s proposal, on the other hand, would rely on an appointment committee composed half and half of industry appointees and lay members to appoint the Chair of a new regulator. I do not accept that an appointment procedure that allows an effective veto to the industry could be considered to be sufficiently independent. Similarly, it must be the case that in relation both to specific enforcement and overarching standards compliance the operation and decisions of the regulator are fully independent from those being regulated.</p>
  <?php paragraphLink('K',1,4,3); ?>Finally under this heading, the draft Criteria specified that compliance must be the responsibility of editors, and must be transparent and demonstrable to the public. One of the strong themes emerging from the proposals submitted to the Inquiry was the emphasis on the need for companies to take more responsibility internally for compliance and for dealing with complaints about standards. This is addressed in Lord Black&#8217;s proposal through the presumption that all complaints should be dealt with in the first instance by the company concerned, the requirement for a named senior executive to have responsibility for compliance and the requirement for each regulated entity to provide an annual compliance report. There may be some question as to whether it is specifically the editor, as opposed for instance to the managing editor, who should be responsible for compliance; but the Inquiry has seen nothing to suggest that the principle underlying this criteria has anything other than full support.</p>
  <?php paragraphLink('K',1,4,4); ?>My conclusion is that Criteria 3 as drafted remains an appropriate benchmark for independence.</p>
  <?php sectionAnchor('K',1,5); ?>Powers and remedies</h2>
 <?php paragraphLink('K',1,5,1); ?>The draft Criteria indicated that an effective new regime must provide credible remedies, both in respect of individuals and of issues affecting wider groups in society. The concept of &#8216;credible remedies&#8217; has been the subject of some debate. For many, the publication of an agreed correction or apology constitutes a credible remedy; for others it does not. The draft Criteria made no mention of sanctions, as opposed to remedies, but there have been representations suggesting that a new regulatory regime should include sanctions, including power to fine, as well as remedies in respect of particularly serious or systemic breaches.<?php footnoteRef('K',1,23); ?> I freely accept the argument that sanctions are different in kind to remedies, in that the former aim to punish and deter breaches of standards, whilst the latter aim to provide solace for the individual affected. I further accept that an effective regulatory regime must have some form of sanction, at least for systemic or egregious breaches of standards.</p>
  <?php paragraphLink('K',1,5,2); ?>There is broad agreement that there must be a system of credible remedies for individuals who have been adversely affected by a breach of standards. However, there are widely differing views when it comes to the rights of third parties or groups of people to make complaints or have access to remedies. In relation to third parties, there is a clear, and reasonable, concern about the risk of such persons or groups making a complaint where the individual directly concerned either is not troubled by the article or, more realistically, would prefer to let the matter drop. Some have argued that the subject of an article should have a veto on the consideration of a complaint. Plainly, a number of issues arise here. If the system is based solely on remedies then there is little point in taking a complaint from anyone for whom the range of potential remedies would not be meaningful. Ofcom has argued that, if there has been a breach of regulatory standards, then the regulator should have the discretion to investigate regardless of whether the subject of the relevant article wishes to take the matter further. In this context the issue is one of industry standards, not abuse of personal rights; but this is pertinent only to the extent that the regulator can issue some kind of adjudication, guidance or sanction that will inform subsequent behaviour, as well as seeking to provide redress to an individual who has suffered harm.</p>
  <?php paragraphLink('K',1,5,3); ?>The British and Irish Ombudsman Association has pointed out that for practical reasons there needs to be some limitation on who can bring a complaint. This has been echoed by others, who fear that in allowing third party complaints, and in particular group complaints, the standards regime could be hijacked by groups wanting to fight political battles on the pretext of complaining about standards. In particular, ANL has argued:<?php footnoteRef('K',1,24); ?>
<blockquote>&#8220;This would potentially subvert the purpose of the regulatory system, which is to protect the rights of those affected by the press and promote high standards. It is not to provide a means by which special interest groups can seek to impose their views on society at large by controlling what is written in the press about them and the interests they represent.&#8221; </blockquote>  </p>
  <?php paragraphLink('K',1,5,4); ?>I am confident that, at some level, it must be possible within any effective new system for breaches of the relevant code to be drawn to the attention of the enforcement body by those affected by the breach, whether in the form of a direct personal reference or more indirectly. There is clearly room for debate as to precisely how this may be achieved and what sort of remedies or sanctions might be appropriate should a breach of standards be found. I do not believe that it is right to characterise the desire of groups to see agreed standards upheld as an attempt to &#8220;impose their views on society at large by controlling what is written in the press about them&#8221;.<?php footnoteRef('K',1,25); ?> If a title has agreed to conform to certain standards then it is a reasonable expectation that they should do so without any group who maintains that those standards are not being upheld being accused of trying to interfere with freedom of expression.</p>
  <?php paragraphLink('K',1,5,5); ?>The draft Criteria indicated that a new regime must have effective investigatory and advisory powers. Inevitably, there will be disagreement about what constitutes &#8216;effective&#8217; in this context, but overall this has proved particularly uncontentious in principle, with most proposals including investigatory powers of some sort.</p>
  <?php paragraphLink('K',1,5,6); ?>The draft Criteria also proposed that any new system should actively support and promote compliance with standards. Again, at a level of generality this has not proved to be a contentious issue, although quite who would be responsible for taking a proactive approach to promoting compliance varies from model to model. In this context, the draft Criteria suggested a few examples of ways in which active support and promotion of standards might happen. One of these was kitemarking; the provision of a kitemark is widely seen as an important part of any voluntary self-regulatory scheme. Some have suggested that the commercial value of a kitemark would be limited, but others believe that the public would want to buy a product that advertised its commitment to standards.</p>
  <?php paragraphLink('K',1,5,7); ?>The draft Criteria also mentioned the example, under this rubric, of providing confidential pre-publication advice to editors. This has proved somewhat controversial, but it was not the intention of the Inquiry by including this feature in the draft criteria to advance any specific proposal. In the event, proposals have been submitted to the Inquiry under which some facet of a new regulatory system could offer confidential advice to editors, in advance of publication, on the merits of any public interest arguments that might later be relied on in actions relating to breach of privacy or breach of standards. Such advice would not be binding in any way, but the fact that advice had been sought (and either followed or ignored) could be taken into account in any subsequent enforcement action.<?php footnoteRef('K',1,26); ?></p>
  <?php paragraphLink('K',1,5,8); ?>Concerns have been advanced about such proposals on the grounds that any intervention pre- publication is a fundamental breach of freedom of expression.<?php footnoteRef('K',1,27); ?> For example, ANL contend that &#8220;for a regulator to involve itself in pre-publication decisions is to trespass on the editor&#8217;s role&#8221;.<?php footnoteRef('K',1,28); ?> There are additional questions to be answered about who the appropriate body would be to provide such advice, the relationship between that body and the enforcement body. Notwithstanding the concerns which have been expressed, for reasons which will be elaborated subsequently it remains my view that the provision of pre-publication advice to editors, on request, would be a useful service for a regulatory body to provide.</p>
  <?php paragraphLink('K',1,5,9); ?>Finally under this heading, the draft Criteria indicated that the new regime would need to be a good fit with other relevant regulatory and law enforcement functions. This, as one might have expected, is completely uncontroversial at the level of principle, but may prove more difficult to implement in practice. There have been a number of concerns raised about the boundary between whatever new regime is proposed in this context and the existing broadcasting regulation. Some suggestions envisaged bringing together all media under a unitary approach to regulation, although no-one has gone as far as suggesting a single regulator for all media. Others have expressed concern about the jurisdictional difficulties of regulating online content, and yet others about the boundary with the statutory requirements on online TV-like services imposed by the Audio Visual Media Services Directive. I share these concerns and consider that it will be important that the coverage of any new regime is clearly articulated and avoids any overlap between media regulators.<?php footnoteRef('K',1,29); ?></p>
  <?php paragraphLink('K',1,5,10); ?>The Inquiry has heard little about the need for any new standards system to fit within an overall effective regime, including criminal and civil law enforcement, although that is obviously essential, indeed, some witnesses have suggested that effective criminal law enforcement would be a sufficient answer to the problems exposed by the Inquiry. I have set out earlier in the report why this is not, and never will be, a credible solution. I do not see any reason why, where standards and the criminal law overlap, there should not be an expectation that the regulator would continue to perform its core regulatory functions as it would in respect of any other standards.<?php footnoteRef('K',1,30); ?></p>
  <?php paragraphLink('K',1,5,11); ?>My conclusion is that Criteria 4 as drafted provides a satisfactory set of requirements in relation to powers and remedies, subject to the introduction of a further point that the regime should include appropriate and proportionate sanctions for systemic or egregious breaches of standards.</p>
  <?php sectionAnchor('K',1,6); ?>Cost</h2>
 <?php paragraphLink('K',1,6,1); ?>The draft Criteria stipulated that the solution must be sufficiently reliably financed to allow for reasonable operational independence and appropriate scope, without placing a disproportionate burden either on the industry, complainants or the taxpayer. As drafted, it is difficult for anyone to disagree with that proposition and no-one has sought to do so. However, it is very difficult at this point to predict what the cost of any of the various approaches that have been put forward to the Inquiry might be. Lord Black estimates that his proposal would cost in the region of &#163;2.25m<?php footnoteRef('K',1,31); ?> but many editors, in particular from the regional press and magazines, have expressed concerns about the robustness of this estimate and whether the industry will be able to afford the attendant costs.<?php footnoteRef('K',1,32); ?> Other proposals have suggested that Government funding for part of a new regulatory regime might be reasonable, though it is worth noting that this is rejected by Lord Black as a matter of principle.<?php footnoteRef('K',1,33); ?></p>
  <?php paragraphLink('K',1,6,2); ?>Ofcom has argued that fixed term funding settlements are necessary to provide the level of operational independence that any regulatory body would need.<?php footnoteRef('K',1,34); ?> Any funding approach which relied on year by year agreement of the regulator&#8217;s budget would allow too much potential for the funding body to influence the approach to compliance and enforcement taken by the body.</p>
  <?php paragraphLink('K',1,6,3); ?>A common theme running through these proposals is that it should be free for persons aggrieved to bring complaints. Obvious questions have been raised about the risk of frivolous or vexatious complaints but, making due allowance for the fact that mechanisms can be put in place to deal with those issues, essentially this is another area on which the Inquiry has seen consensus.</p>
  <?php paragraphLink('K',1,6,4); ?>My conclusion is that Criteria 5 as drafted is an appropriate measure, albeit recognising that &#8216;reliability&#8217; of funding means multi-year settlements to protect the independence of the regulator from undue influence from those funding it.</p>
  <?php sectionAnchor('K',1,7); ?>Accountability</h2>
 <?php paragraphLink('K',1,7,1); ?>Ofcom suggested that a further criteria for the accountability of the new regime should be added. Specifically, they contended that there should be an independent review of whatever new regime is put in place after three years. Arguably, this is of particular relevance in the context of the history of press self-regulation which demonstrates that historically it has been difficult to secure any lasting effective change.<?php footnoteRef('K',1,35); ?> I agree that an independent review of any new regulatory regime would be an important benchmark in testing effectiveness.</p>
  </div>

