<!-- Footnotes-->
<div id="footnotes"> <?php footNote('K',1,1); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Covering-Letter-from-Ofcom.pdf">Covering-Letter-from-Ofcom.pdf</a></p>
 <?php footNote('K',1,2); ?> particularly in <?php internalChapterLink('../../','J',5); ?></p>
 <?php footNote('K',1,3); ?> p14, para 42, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Lord-Hunt-of-Wirral.pdf">Submission-by-Lord-Hunt-of-Wirral.pdf</a></p>
 <?php footNote('K',1,4); ?> p1, lines 15-17, Lord Hunt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Morning-Hearing-10-July-2012.pdf">Transcript-of-Morning-Hearing-10-July-2012.pdf</a></p>
 <?php footNote('K',1,5); ?> Part J, Chapters 2 and 3</p>
 <?php footNote('K',1,6); ?> pp8-9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Professor-Roy-Greenslade-of-City-University.pdf">Submission-by-Professor-Roy-Greenslade-of-City-University.pdf</a></p>
 <?php footNote('K',1,7); ?> PCC code, http://www.pcc.org.uk/cop/practice.html</p>
 <?php footNote('K',1,8); ?> Ofcom&#8217;s Broadcasting Code, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/08/Exhibit-OFCOM11.pdf">Exhibit-OFCOM11.pdf</a></p>
 <?php footNote('K',1,9); ?> BBC Editorial guidelines, http://www.bbc.co.uk/guidelines/editorialguidelines/page/guidelines-privacy-introduction</p>
 <?php footNote('K',1,10); ?> p76, lines 17-20, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-26-April-2012.pdf">Transcript-of-Morning-Hearing-26-April-2012.pdf</a></p>
 <?php footNote('K',1,11); ?> p16, para 4.5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Ofcom-Measuring-Media-Plurality1.pdf">Submission-by-Ofcom-Measuring-Media-Plurality1.pdf</a></p>
 <?php footNote('K',1,12); ?> pp6-7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Sumission-from-Jeremy-Hunt-MP.pdf">Sumission-from-Jeremy-Hunt-MP.pdf</a>; p8,para 3.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Tim-Suter-of-Perspective-Associates.pdf">Submission-by-Tim-Suter-of-Perspective-Associates.pdf</a></p>
 <?php footNote('K',1,13); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Covering-Letter-from-Ofcom.pdf">Covering-Letter-from-Ofcom.pdf</a></p>
 <?php footNote('K',1,14); ?> p6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/10/Further-submission-from-the-Media-Standards-Trust.pdf">Further-submission-from-the-Media-Standards-Trust.pdf</a>; p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Coordinating-Committee-for-Media-Reform.pdf">Submission-by-Coordinating-Committee-for-Media-Reform.pdf</a></p>
 <?php footNote('K',1,15); ?> p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Covering-Letter-from-Ofcom.pdf">Covering-Letter-from-Ofcom.pdf</a></p>
 <?php footNote('K',1,16); ?> <?php internalChapterLink('../../','J',5); ?></p>
 <?php footNote('K',1,17); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/10/Further-Submission-from-Professor-Christopher-Megone.pdf">Further-Submission-from-Professor-Christopher-Megone.pdf</a></p>
 <?php footNote('K',1,18); ?> p18, para 40, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-Associated-Newspapers-Ltd.pdf">Closing-Submission-from-Associated-Newspapers-Ltd.pdf</a></p>
 <?php footNote('K',1,19); ?> p41, para 80, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Lord-Black-of-Brentwood1.pdf">Submission-by-Lord-Black-of-Brentwood1.pdf</a></p>
 <?php footNote('K',1,20); ?> pp101-102, lines 7-9, Dr Colette Bowe and Ed Richards, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Morning-Hearing-12-July-2012.pdf">Transcript-of-Morning-Hearing-12-July-2012.pdf</a></p>
 <?php footNote('K',1,21); ?> p2, para 7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Tim-Suter-of-Perspective-Associates.pdf">Submission-by-Tim-Suter-of-Perspective-Associates.pdf</a></p>
 <?php footNote('K',1,22); ?> p24, para 38, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Lord-Black-of-Brentwood1.pdf">Submission-by-Lord-Black-of-Brentwood1.pdf</a></p>
 <?php footNote('K',1,23); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Covering-Letter-from-Ofcom.pdf">Covering-Letter-from-Ofcom.pdf</a>; p10, para  23,<a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Lord-Black-of-Brentwood1.pdf">Submission-by-Lord-Black-of-Brentwood1.pdf</a>; p8,para 4, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Submission-by-Carnegie-Trust.pdf">Submission-by-Carnegie-Trust.pdf</a>; p20, para3.35, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Submission-by-MediaWise1.pdf">Submission-by-MediaWise1.pdf</a>; p11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Michelle-Stanistreet-on-behalf-of-the-National-Union-of-Journalists.pdf">Submission-by-Michelle-Stanistreet-on-behalf-of-the-National-Union-of-Journalists.pdf</a>; p13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Coordinating-Committee-for-Media-Reform.pdf">Submission-by-Coordinating-Committee-for-Media-Reform.pdf</a> </p>
 <?php footNote('K',1,24); ?> p18, para 42, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-Associated-Newspapers-Ltd.pdf">Closing-Submission-from-Associated-Newspapers-Ltd.pdf</a> p8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Submission-by-Paul-Dacre1.pdf">Submission-by-Paul-Dacre1.pdf</a></p>
 <?php footNote('K',1,25); ?> p19, para 42, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-Associated-Newspapers-Ltd.pdf">Closing-Submission-from-Associated-Newspapers-Ltd.pdf</a></p>
 <?php footNote('K',1,26); ?> p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Max-Mosley.pdf">Submission-by-Max-Mosley.pdf</a>; pp3-4, para 6,<a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Media-Regulation-Round-Table.pdf">Submission-by-Media-Regulation-Round-Table.pdf</a></p>
 <?php footNote('K',1,27); ?> p43, para 14, Sir Charles Gray, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Afternoon-Hearing-12-July-2012.pdf">Transcript-of-Afternoon-Hearing-12-July-2012.pdf</a></p>
 <?php footNote('K',1,28); ?> p19, para 43, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Closing-Submission-from-Associated-Newspapers-Ltd.pdf">Closing-Submission-from-Associated-Newspapers-Ltd.pdf</a></p>
 <?php footNote('K',1,29); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Tim-Suter-of-Perspective-Associates.pdf">Submission-by-Tim-Suter-of-Perspective-Associates.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Sumission-from-Jeremy-Hunt-MP.pdf">Sumission-from-Jeremy-Hunt-MP.pdf</a></p>
 <?php footNote('K',1,30); ?> <?php internalChapterLink('../../','J',2); ?></p>
 <?php footNote('K',1,31); ?> p45, para 94, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/10/Fourth-Witness-Statement-of-Lord-Black.pdf">Fourth-Witness-Statement-of-Lord-Black.pdf</a></p>
 <?php footNote('K',1,32); ?> p2, para 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Witness-statement-of-Ian-Stewart1.pdf">Witness-statement-of-Ian-Stewart1.pdf</a>; p3, para 9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Second-WS-of-Rosie-Nixon2.pdf">Second-WS-of-Rosie-Nixon2.pdf</a>; p2,para 6c, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Adrian-Faber-in-response-to-Module-4-Questions.pdf">Submission-by-Adrian-Faber-in-response-to-Module-4-Questions.pdf</a>; p3, para 6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-from-Peter-Charlton-Yorkshire-Post-Newspapers.pdf">Submission-from-Peter-Charlton-Yorkshire-Post-Newspapers.pdf</a></p>
 <?php footNote('K',1,33); ?> pp70-71, lines 23-3, Lord Black, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Morning-Hearing-9-July-2012.pdf">Transcript-of-Morning-Hearing-9-July-2012.pdf</a></p>
 <?php footNote('K',1,34); ?> p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Covering-Letter-from-Ofcom.pdf">Covering-Letter-from-Ofcom.pdf</a></p>
 <?php footNote('K',1,35); ?> <?php internalChapterLink('../../','D',1); ?></p>
 </div>
