<?php 
require_once('../../common.php');
levesonHeader('X',4);
levesonNav('../../');
levesonBread('X',4);
require_once('content.php');
levesonFooterNav('X',4); 
require_once('footnotes.php');
LevesonCommonFooter();
?>