<!-- Footnotes-->
<div id="footnotes"> <?php footNote('J',4,1); ?> Guy Black, as he then was, was director of the PCC until 2003, but his evidence did not cover this part of his career. Ihave no reason to exempt him from the observations I make about his successors</p>
 <?php footNote('J',4,2); ?> <em> The Independent</em>, &#8216;PM signals end of Press Complaints Commission&#8217;, 8 July 2011, http://www.independent.co.uk/news/media/press/pm-signals-end-of-press-complaints-commission-2309210.html; pp58-60, lines 19-4, DavidCameron MP, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14- June-2012.pdf">Transcript-of-Afternoon-Hearing-14- June-2012.pdf</a> </p>
 <?php footNote('J',4,3); ?> p4, para 18, and p18, para 85, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-Nick-Clegg-MP2.pdf">Witness-Statement-of-Nick-Clegg-MP2.pdf</a>; pp10-11, lines 15-24, Nick Clegg MP, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-13-June-2012.pdf">Transcript-of-Morning-Hearing-13-June-2012.pdf</a></p>
 <?php footNote('J',4,4); ?> pp17-18, Ed Miliband, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-EM-22.pdf">Exhibit-EM-22.pdf</a></p>
 <?php footNote('J',4,5); ?> p37, lines 12-24, Paul Ashford, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a>; pp73-77, lines 25-2, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('J',4,6); ?> p46, lines 20-21, Lionel Barber, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-10-January-2012.pdf">Transcript-of-Morning-Hearing-10-January-2012.pdf</a></p>
 <?php footNote('J',4,7); ?> p7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Submission-by-Trans-Media-Watch.pdf">Submission-by-Trans-Media-Watch.pdf</a></p>
 <?php footNote('J',4,8); ?> pp45-46, lines 20-12, Steve Coogan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-22-November-20111.pdf">Transcript-of-Afternoon-Hearing-22-November-20111.pdf</a></p>
 <?php footNote('J',4,9); ?> pp42-45, lines 9-19, Mark Thomson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-24-November-2011.pdf">Transcript-of-Morning-Hearing-24-November-2011.pdf</a></p>
 <?php footNote('J',4,10); ?> pp62-64, lines 15-9, Graham Shear, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-21-November-2011.pdf">Transcript-of-Morning-Hearing-21-November-2011.pdf</a></p>
 <?php footNote('J',4,11); ?> pp35-36, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Media-Standards-Trust.pdf">Submission-by-Media-Standards-Trust.pdf</a></p>
 <?php footNote('J',4,12); ?> p171, para 247, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,13); ?> Having paid fulsome tribute to Mr Abell&#8217;s witness statement, I should also record my admiration for the MediaStandard Trust&#8217;s work in this area. The relevant material and submissions is on the Inquiry website. Given its comprehensiveness, I have sought to boil the issues down somewhat</p>
 <?php footNote('J',4,14); ?> p26, lines 10-22, Dr Martin Moore, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Afternoon-Hearing-10-July-2012.pdf">Transcript-of-Afternoon-Hearing-10-July-2012.pdf</a></p>
 <?php footNote('J',4,15); ?> p69, lines 3-6, Professor Brian Cathcart, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-8-December-20111.pdf">Transcript-of-Morning-Hearing-8-December-20111.pdf</a>; p63, lines 1-5, Graham Shear, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-21-November-2011.pdf">Transcript-of-Morning-Hearing-21-November-2011.pdf</a></p>
 <?php footNote('J',4,16); ?> p5, para 6.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Tim-Toulmin.pdf">Witness-Statement-of-Tim-Toulmin.pdf</a> ; p6, para 25, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-Giles-Crown.pdf">Witness-Statement-of-Giles-Crown.pdf</a></p>
 <?php footNote('J',4,17); ?> p 17, para 103, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Gerald-Patrick-McCann.pdf">Witness-Statement-of-Gerald-Patrick-McCann.pdf</a></p>
 <?php footNote('J',4,18); ?> pp4-5, para 25, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,19); ?> p p218-221, paras 304-314, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,20); ?> p28, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Submission-by-Trans-Media-Watch.pdf">Submission-by-Trans-Media-Watch.pdf</a></p>
 <?php footNote('J',4,21); ?> p6, para 37, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,22); ?> p46, lines 9-15, Lord Grade, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-31-January-2012.pdf">Transcript-of-Afternoon-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,23); ?> p40, lines 3-6, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,24); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Professor-Roy-Greenslade-of-City-University.pdf">Submission-by-Professor-Roy-Greenslade-of-City-University.pdf</a></p>
 <?php footNote('J',4,25); ?> p6, para 38, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,26); ?> pp6-7, paras 39 and 40, <em>ibid</em></p>
 <?php footNote('J',4,27); ?> p1, paras 3 and 4, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-S11.pdf">Exhibit-SA-S11.pdf</a></p>
 <?php footNote('J',4,28); ?> p8, para 30, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Second-Witness-Statement-of-Lord-Wakeham.pdf">Second-Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,29); ?> p511, para 110, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,30); ?> pp15-16, lines 17-13, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('J',4,31); ?> p9, para 31, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Second-Witness-Statement-of-Lord-Wakeham.pdf">Second-Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,32); ?> p17, lines 6-12, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('J',4,33); ?> p4, lines 4-16, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a>; p35, lines 5-24, Baroness Buscombe, http://www.levesoninquiry.org.uk/wp- content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf </p>
 <?php footNote('J',4,34); ?> p2, Sir Christopher Meyer, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-%E2%80%93-D8.pdf</p>
 <?php footNote('J',4,35); ?> pp7-8, lines 24-2, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,36); ?> p59, lines 1-5, Lord Hunt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-31-January-2012.pdf">Transcript-of-Afternoon-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,37); ?> p61, <em>ibid</em></p>
 <?php footNote('J',4,38); ?> p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B35.pdf">SA-B35.pdf</a></p>
 <?php footNote('J',4,39); ?> p33, lines 5-12, Lord Grade, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-31-January-2012.pdf">Transcript-of-Afternoon-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,40); ?> p54, para 120, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a>; p4, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Sir-Christopher-Meyer.pdf">Witness-Statement-of-Sir-Christopher-Meyer.pdf</a> ; p17, lines 4-8, Paul Dacre, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-  of-Afternoon-Hearing-6-February-20121.pdf">Transcript-  of-Afternoon-Hearing-6-February-20121.pdf</a>; pp86-87, lines 25-29, Tina Weaver, http://www.levesoninquiry.org.uk/  wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf </p>
 <?php footNote('J',4,41); ?> Not quite equivalent to the legal doctrine of<em> stare decisis</em> which is more rigidly applied</p>
 <?php footNote('J',4,42); ?> pp 99-153, para 239, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,43); ?> p61, lines 3-14, Dr Collette Bowe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-1-February-2012.pdf">Transcript-of-Morning-Hearing-1-February-2012.pdf</a></p>
 <?php footNote('J',4,44); ?> p42, lines 16-25, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,45); ?> p47, line 17, p48, line 14, Lord Grade, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-31-January-2012.pdf">Transcript-of-Afternoon-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,46); ?> p44, lines 21-25, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,47); ?> I acknowledge that three of the lay commissioners have recently submitted evidence that they or their families hadin the past been the subject of press attention. However, there has been no suggestion that they were the subject ofthe kind of intrusive reporting which has proved most damaging to victims; and which the PCC failed to tackle</p>
 <?php footNote('J',4,48); ?> pp48-49, lines 25-2, Lionel Barber, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-10-January-2012.pdf">Transcript-of-Morning-Hearing-10-January-2012.pdf</a></p>
 <?php footNote('J',4,49); ?> The example is often given of doctors serving on Disciplinary Committees of the General Medical Council. If an  ENTsurgeon from, say, Newcastle, sits on a Disciplinary Committee in respect of an ENT surgeon whom he does not knowand has had no contact with from, say, London, he will be able to bring his expertise to bear in a completely impartialway. If one of a dozen or so national editors sits on a PCC panel in relation to a competitive title, it is almost inevitablethat he or she will know the editor extremely well and is likely to have a view about the balance of Articles 8 and 10:a complainant may well not feel that such an editor could be entirely impartial. As appears from the analysis of theposition of Northern and Shell, the converse might also be true </p>
 <?php footNote('J',4,50); ?> p5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Michelle-Stanistreet.pdf">Witness-Statement-of-Michelle-Stanistreet.pdf</a></p>
 <?php footNote('J',4,51); ?> p90, lines 1-10, Tina Weaver, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-16-January-2012.pdf">Transcript-of-Morning-Hearing-16-January-2012.pdf</a>; p42, lines 17-23, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-30-January-2012.pdf">Transcript-of-Afternoon-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,52); ?> pp101-102, lines 7-9, Ed Richards, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Morning-Hearing-12-July-2012.pdf">Transcript-of-Morning-Hearing-12-July-2012.pdf</a></p>
 <?php footNote('J',4,53); ?> p26, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Witness-Statement-of-Alastair-Campbell.pdf">Witness-Statement-of-Alastair-Campbell.pdf</a></p>
 <?php footNote('J',4,54); ?> p235, para 350, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,55); ?> pp1-2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Lord-Wakeham-Letter-to-Inquiry.pdf">Lord-Wakeham-Letter-to-Inquiry.pdf</a></p>
 <?php footNote('J',4,56); ?> pp1-2, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-M7.pdf">Exhibit-SA-M7.pdf</a></p>
 <?php footNote('J',4,57); ?> p 1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T278.pdf">Exhibit-SA-T278.pdf</a></p>
 <?php footNote('J',4,58); ?> pp91-92, lines 1-11, Ed Richards, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-1-February-2012.pdf">Transcript-of-Morning-Hearing-1-February-2012.pdf</a></p>
 <?php footNote('J',4,59); ?> For example, p37, lines 12-24, Paul Ashford, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('J',4,60); ?> pp4-5, paras 12 - 13, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Ian-Hislop.pdf">Witness-Statement-of-Ian-Hislop.pdf</a></p>
 <?php footNote('J',4,61); ?> p 3, para 12, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-Wakeham.pdf">Witness-Statement-of-Lord-Wakeham.pdf</a> ; p12, paras 103-109, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Jack-Straw-MP.pdf">Witness-Statement-of-Jack-Straw-MP.pdf</a></p>
 <?php footNote('J',4,62); ?> p14, para 45, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Second-Witness-Statement-of-Lord-Wakeham.pdf">Second-Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,63); ?> p15, para 45, <em>ibid</em> ; pp46-47, lines 3-13, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('J',4,64); ?> p16, para 48, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Second-Witness-Statement-of-Lord-Wakeham.pdf">Second-Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,65); ?> p15, para 47, <em>ibid</em></p>
 <?php footNote('J',4,66); ?> p2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Lord-Wakeham-Exhibit-E.pdf">Lord-Wakeham-Exhibit-E.pdf</a></p>
 <?php footNote('J',4,67); ?> pp95-97, lines 23-2, Tony Blair, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-28-May-2012.pdf">Transcript-of-Morning-Hearing-28-May-2012.pdf</a></p>
 <?php footNote('J',4,68); ?> pp4 &#8211; 5, para 17, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-Smith.pdf">Witness-Statement-of-Lord-Smith.pdf</a></p>
 <?php footNote('J',4,69); ?> <em>ibid</em></p>
 <?php footNote('J',4,70); ?> p45, lines 11-20, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('J',4,71); ?> p5, para 1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-Smith.pdf">Witness-Statement-of-Lord-Smith.pdf</a></p>
 <?php footNote('J',4,72); ?> p15, para 47, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Second-Witness-Statement-of-Lord-Wakeham.pdf">Second-Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,73); ?> HL Hansard, Series 6, Vol 305, Col 463, http://www.publications.parliament.uk/pa/ld199798/ldhansrd/vo980202/text/80202-09.htm</p>
 <?php footNote('J',4,74); ?> p2, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E1.pdf">Exhibit-SA-E1.pdf</a></p>
 <?php footNote('J',4,75); ?> <em>ibid</em></p>
 <?php footNote('J',4,76); ?> <em>ibid</em></p>
 <?php footNote('J',4,77); ?> PCC, http://www.pcc.org.uk/news/index.html?article=Mzk</p>
 <?php footNote('J',4,78); ?> PCC, http://www.pcc.org.uk/news/index.html?article=Mzk</p>
 <?php footNote('J',4,79); ?> PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-S21.pdf">Exhibit-SA-S21.pdf</a></p>
 <?php footNote('J',4,80); ?> p61, lines 4-21, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,81); ?> pp61-62, lines 24-1, <em>ibid</em></p>
 <?php footNote('J',4,82); ?> p63, lines 11-23, <em>ibid</em></p>
 <?php footNote('J',4,83); ?> p1, Press Board of Finance, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Exhibit-Pbof-55.pdf</p>
 <?php footNote('J',4,84); ?> p1, para 8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-S11.pdf">Exhibit-SA-S11.pdf</a></p>
 <?php footNote('J',4,85); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T180.pdf">Exhibit-SA-T180.pdf</a></p>
 <?php footNote('J',4,86); ?> <?php internalChapterLink('../../','D',1); ?></p>
 <?php footNote('J',4,87); ?> pp1-9, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-&#8211;-D8.pdf">Exhibit-SA-&#8211;-D8.pdf</a></p>
 <?php footNote('J',4,88); ?> p p42-44, para 86, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,89); ?> p11, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E1.pdf">Exhibit-SA-E1.pdf</a></p>
 <?php footNote('J',4,90); ?> p7, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E2.pdf">Exhibit-SA-E2.pdf</a> ; p11, StephenAbell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E1.pdf">Exhibit-SA-E1.pdf</a></p>
 <?php footNote('J',4,91); ?> pp67-68, paras 164-169, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,92); ?> So that there is no doubt about the matter, I do not in any sense criticise the way in which the Charter Commissionerand Charter Compliance Panel went about the work: my concern is the limit of their power and responsibility</p>
 <?php footNote('J',4,93); ?> p275, para 425, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,94); ?> p244, para 356, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,95); ?> p4, paragraph 21, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,96); ?> <em>ibid</em></p>
 <?php footNote('J',4,97); ?> p p47-48, paras 99-102, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,98); ?> pp 67-69, paras 164-174, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,99); ?> pp50-51, lines 14-21, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,100); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B-258.pdf">SA-B-258.pdf</a></p>
 <?php footNote('J',4,101); ?> pp51-57, lines 22-24, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,102); ?> p6, PPC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V22.pdf">Exhibit-SA-V22.pdf</a></p>
 <?php footNote('J',4,103); ?> pp39-41, lines 22-22, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,104); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T172.pdf">Exhibit-SA-T172.pdf</a> ; p1,Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T181.pdf">Exhibit-SA-T181.pdf</a>; p1, StephenAbell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T277.pdf">Exhibit-SA-T277.pdf</a>; pp1 &#8211; 2, Stephen Abell,<a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T2821.pdf">Exhibit-SA-T2821.pdf</a></p>
 <?php footNote('J',4,105); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Third-Submission-by-Media-Standards-Trust.pdf">Third-Submission-by-Media-Standards-Trust.pdf</a></p>
 <?php footNote('J',4,106); ?> pp1-5, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T1125.pdf">Exhibit-SA-T1125.pdf</a></p>
 <?php footNote('J',4,107); ?> PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-J31.pdf">Exhibit-SA-J31.pdf</a></p>
 <?php footNote('J',4,108); ?> p32, para 63, House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200203/cmselect/cmcumeds/458/458.pdf</p>
 <?php footNote('J',4,109); ?> pp75-83, lines 18-5, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,110); ?> p11, para 32 House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200203/cmselect/cmcumeds/458/458.pdf</p>
 <?php footNote('J',4,111); ?> <em>ibid</em></p>
 <?php footNote('J',4,112); ?> p78, lines 15-19, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,113); ?> pp46-47, lines 18-3, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a>; p95, lines 9-17, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a>; pp43-45, lines 11-24, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a> </p>
 <?php footNote('J',4,114); ?> p14, lines 13-14, Lord Black, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-1-February-2012.pdf">Transcript-of-Morning-Hearing-1-February-2012.pdf</a></p>
 <?php footNote('J',4,115); ?> p1, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-Wakeham.pdf">Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,116); ?> p3, para 8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-Wakeham.pdf">Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,117); ?> p2, lines 18-25, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-31-January-2012.pdf">Transcript-of-Afternoon-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,118); ?> p4, lines 17-25, <em>ibid</em></p>
 <?php footNote('J',4,119); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B58.pdf">SA-B58.pdf</a></p>
 <?php footNote('J',4,120); ?> Julian Petley, New Left Project,<em> Press Regulation? &#8211; Now There&#8217;s an Idea</em>, 24 August 2011, http://www.newleftproject.org/index.php/site/article_comments/press_regulation_now_theres_an_idea</p>
 <?php footNote('J',4,121); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B-270.pdf">SA-B-270.pdf</a></p>
 <?php footNote('J',4,122); ?> <em> Lord Hunt appointed as new Chair of the PCC</em>, http://pcc.org.uk/news/index.html?article=NzQwMA</p>
 <?php footNote('J',4,123); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B88.pdf">SA-B88.pdf</a></p>
 <?php footNote('J',4,124); ?> p2, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-David-Yelland.pdf">Witness-Statement-of-David-Yelland.pdf</a></p>
 <?php footNote('J',4,125); ?> p6, para 35, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,126); ?> p405, para 725.7, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,127); ?> p 7, para 23, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Lord-Black1.pdf">Witness-Statement-of-Lord-Black1.pdf</a></p>
 <?php footNote('J',4,128); ?> pp82-83, lines 17-19, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,129); ?> p76, lines 4-25, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a>; pp39-40, lines 9-5, Paul Ashford, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a>; pp3-4, paras 6-8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Paul-Ashford1.pdf">Witness-Statement-of-Paul-Ashford1.pdf</a></p>
 <?php footNote('J',4,130); ?> p63, lines 5-10, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,131); ?> p7, para 43, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,132); ?> pp86-88, paras 194-198, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a>; pp1-9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Louise-Hayman.pdf">Witness-Statement-of-Louise-Hayman.pdf</a>; p4, para 8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Tom-Crone.pdf">Witness-Statement-of-Tom-Crone.pdf</a>; p5, para 14, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Tony-Gallagher.pdf">Witness-Statement-of-Tony-Gallagher.pdf</a> ; pp1-2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-James-Harding.pdf">Witness-Statement-of-James-Harding.pdf</a>; p2, para 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Liz-Hartley.pdf">Witness-Statement-of-Liz-Hartley.pdf</a></p>
 <?php footNote('J',4,133); ?> pp86-87, para 194, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,134); ?> p5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Michelle-Stanistreet.pdf">Witness-Statement-of-Michelle-Stanistreet.pdf</a> ; pp2, 5-9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/First-Submission-by-Media-Standards-Trust.pdf">First-Submission-by-Media-Standards-Trust.pdf</a> </p>
 <?php footNote('J',4,135); ?> p66, lines 6-10, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,136); ?> pp47-48, lines 23-7, Lionel Barber, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-10-January-2012.pdf">Transcript-of-Morning-Hearing-10-January-2012.pdf</a></p>
 <?php footNote('J',4,137); ?> p5, para 26, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,138); ?> p13, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-A2641.pdf">Exhibit-SA-A2641.pdf</a></p>
 <?php footNote('J',4,139); ?> <em>ibid</em></p>
 <?php footNote('J',4,140); ?> <em>ibid</em></p>
 <?php footNote('J',4,141); ?> <em> &#8216;In carrying out its functions in relation to complaints the Commission shall have regard to generally</em>  established freedoms including freedom of expression and the public&#8217;s right to know, and defence of the press from improper pressure&#8217; </p>
 <?php footNote('J',4,142); ?> See Tim Toulmin&#8217;s discussion of this provision: pp22-24, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,143); ?> p24, lines 1-12, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('J',4,144); ?> p75, lines 3-14, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,145); ?> p2, Irish Traveller Movement in Britain, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-from-The-Irish-Traveller-Movement-April-20121.pdf">Submission-from-The-Irish-Traveller-Movement-April-20121.pdf</a></p>
 <?php footNote('J',4,146); ?> p13, lines 4-23, Lord Hunt, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Transcript-of-Afternoon-Hearing-9-July-2012.pdf">Transcript-of-Afternoon-Hearing-9-July-2012.pdf</a></p>
 <?php footNote('J',4,147); ?> p4, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-R27.pdf">Exhibit-SA-R27.pdf</a></p>
 <?php footNote('J',4,148); ?> p6, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-&#8211;-D8.pdf">Exhibit-SA-&#8211;-D8.pdf</a></p>
 <?php footNote('J',4,149); ?> p3, para 8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-Wakeham.pdf">Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,150); ?> p22, lines 3-11, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a>; pp38-41, lines 16-5, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a> ; Ofcom is precluded frominvestigating complaints whilst civil proceedings are ongoing: see section 114 of the Broadcasting Act 1999, asamended by section 132(2) of the Communications Act 2003. The position is the same as regards the FSA</p>
 <?php footNote('J',4,151); ?> pp84-88, lines 7-25, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,152); ?> pp1-4, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T2100.pdf">Exhibit-SA-T2100.pdf</a> ;pp1-6, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-X26.pdf">Exhibit-SA-X26.pdf</a> ; pp1 &#8211; 5,Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-T1151.pdf">Exhibit-SA-T1151.pdf</a> ; pp1-2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-S41.pdf">Exhibit-SA-S41.pdf</a> </p>
 <?php footNote('J',4,153); ?> See for example PCC, pp1 &#8211; 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U12.pdf">Exhibit-SA-U12.pdf</a>; pp9-13, lines 13-6, Peter Hill, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('J',4,154); ?> Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-&#8211;-D4.pdf">Exhibit-SA-&#8211;-D4.pdf</a></p>
 <?php footNote('J',4,155); ?> Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-F1.pdf">Exhibit-SA-F1.pdf</a></p>
 <?php footNote('J',4,156); ?> Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-F2.pdf">Exhibit-SA-F2.pdf</a></p>
 <?php footNote('J',4,157); ?> pp86-88, paras 194-198,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a>; pp1-9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Louise-Hayman.pdf">Witness-Statement-of-Louise-Hayman.pdf</a>; p4, para 8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Witness-Statement-of-Tom-Crone.pdf">Witness-Statement-of-Tom-Crone.pdf</a>; p5, para 14, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Tony-Gallagher.pdf">Witness-Statement-of-Tony-Gallagher.pdf</a> ; pp1-2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-James-Harding.pdf">Witness-Statement-of-James-Harding.pdf</a> ; p2, para 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Liz-Hartley.pdf">Witness-Statement-of-Liz-Hartley.pdf</a> </p>
 <?php footNote('J',4,158); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B183.pdf">SA-B183.pdf</a>; p10, para 12,<a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,159); ?> p56, para 129, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,160); ?> p10, paras 12-16, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a>; p1, para 1.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Tim-Toulmin.pdf">Witness-Statement-of-Tim-Toulmin.pdf</a></p>
 <?php footNote('J',4,161); ?> Of which there were approximately six a year, usually reserved for cases of undue delay and failing to publish adjudications with due prominence: see the evidence of Tim Toulmin; p27, lines 11-18, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,162); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/RPC_DOCS1-12374597-v1-PAUL_DACRE_S_SEMINAR_SPEECH.pdf">RPC_DOCS1-12374597-v1-PAUL_DACRE_S_SEMINAR_SPEECH.pdf</a></p>
 <?php footNote('J',4,163); ?> p47, lines 9-22, Lionel Barber, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-10-January-2012.pdf">Transcript-of-Morning-Hearing-10-January-2012.pdf</a></p>
 <?php footNote('J',4,164); ?> p23, lines 2-20, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,165); ?> p5, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-&#8211;-D8.pdf">Exhibit-SA-&#8211;-D8.pdf</a></p>
 <?php footNote('J',4,166); ?> pp39-40, lines 13-22, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('J',4,167); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-I26.pdf">Exhibit-SA-I26.pdf</a></p>
 <?php footNote('J',4,168); ?> p58, lines 4-19, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,169); ?> pp57-58, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,170); ?> PCC,<em> Editors&#8217; Code of Practice</em>, clause 1(ii), http://www.pcc.org.uk/assets/696/Code_of_Practice_2012_A4.pdf</p>
 <?php footNote('J',4,171); ?> The available evidence is covered in <?php internalChapterLink('../../','C',3); ?> above</p>
 <?php footNote('J',4,172); ?> p10, para 34, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Second-Witness-Statement-of-Lord-Wakeham.pdf">Second-Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,173); ?> <em>ibid</em></p>
 <?php footNote('J',4,174); ?> Morgan, P,<em> The Insider</em>, p82</p>
 <?php footNote('J',4,175); ?> Morgan, P,<em> The Insider,</em> p82</p>
 <?php footNote('J',4,176); ?> pp97-101, lines 23-2, Piers Morgan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Afternoon-Hearing-20-December-2011.pdf">Transcript-of-Afternoon-Hearing-20-December-2011.pdf</a></p>
 <?php footNote('J',4,177); ?> pp60-61, lines 11-14, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-26-April-2012.pdf">Transcript-of-Morning-Hearing-26-April-2012.pdf</a></p>
 <?php footNote('J',4,178); ?> p80, lines 1-8, Richard Desmond, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-12-January-2012.pdf">Transcript-of-Afternoon-Hearing-12-January-2012.pdf</a></p>
 <?php footNote('J',4,179); ?> p11, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Exhibit-Annex-2-to-Chris-Atkins-Supp.pdf">Exhibit-Annex-2-to-Chris-Atkins-Supp.pdf</a></p>
 <?php footNote('J',4,180); ?> p44, para 238, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,181); ?> pp62-63, lines 18-4, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,182); ?> p18, para 9(e), <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Witness-Statement-of-Dr-Neil-Manson.pdf">Witness-Statement-of-Dr-Neil-Manson.pdf</a></p>
 <?php footNote('J',4,183); ?> For example pp4-5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Submission-by-Professor-Roy-Greenslade-of-City-University.pdf">Submission-by-Professor-Roy-Greenslade-of-City-University.pdf</a>; and <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Sixth-Submission-by-Media-Standards-Trust.pdf">Sixth-Submission-by-Media-Standards-Trust.pdf</a>, passim </p>
 <?php footNote('J',4,184); ?> For example in 2009 there were 18 adverse adjudications by the PCC; p11, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E72.pdf">Exhibit-SA-E72.pdf</a></p>
 <?php footNote('J',4,185); ?> <?php internalChapterLink('../../','D',2); ?></p>
 <?php footNote('J',4,186); ?> In relation to barristers, sets of Chambers are required to operate complaints&#8217; systems and complainants are alsoobliged to take their cases to these in the first instance</p>
 <?php footNote('J',4,187); ?> pp92-98, paras 219-235,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a>; Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E1.pdf">Exhibit-SA-E1.pdf</a> ; Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E2.pdf">Exhibit-SA-E2.pdf</a>; StephenAbell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E3.pdf">Exhibit-SA-E3.pdf</a>; Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E4.pdf">Exhibit-SA-E4.pdf</a>; Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E4.pdf">Exhibit-SA-E4.pdf</a>; Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E5.pdf">Exhibit-SA-E5.pdf</a>; Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E6.pdf">Exhibit-SA-E6.pdf</a>; Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E72.  pdf ; Stephen Abell, http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E8.pdf">Exhibit-SA-E72.  pdf ; Stephen Abell, http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E8.pdf</a>; Stephen  Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-E9.pdf">Exhibit-SA-E9.pdf</a>; pp1 &#8211; 33, http://www.  levesoninquiry.org.uk/wp-content/uploads/2012/02/Second-Submission-by-Media-Standards-Trust.pdf </p>
 <?php footNote('J',4,188); ?> p57, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,189); ?> p4, para 1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-S5.pdf">Exhibit-SA-S5.pdf</a></p>
 <?php footNote('J',4,190); ?> see Table D2.2, <?php internalChapterLink('../../','D',2); ?></p>
 <?php footNote('J',4,191); ?> pp34-35, lines 24-5, Lord Wakeham, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-15-May-2012.pdf">Transcript-of-Morning-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('J',4,192); ?> pp36-37, lines 23-12, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,193); ?> See p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-C15.pdf">Exhibit-SA-C15.pdf</a> p1, PCC <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-C16.pdf">Exhibit-SA-C16.pdf</a> pp2-3, PCC <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-S31.pdf">Exhibit-SA-S31.pdf</a></p>
 <?php footNote('J',4,194); ?> in particular Part H</p>
 <?php footNote('J',4,195); ?> pp119-120, lines 25-3, Richard Thomas, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-9-December-2011.pdf">Transcript-of-Morning-Hearing-9-December-2011.pdf</a></p>
 <?php footNote('J',4,196); ?> p106, lines 8-11, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,197); ?> p1, Richard Thomas, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Exhibit-RJT61.pdf">Exhibit-RJT61.pdf</a></p>
 <?php footNote('J',4,198); ?> p89, lines 25-20, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,199); ?> p118, line 9, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,200); ?> p111, lines 23-24, <em>ibid</em></p>
 <?php footNote('J',4,201); ?> p117, <em>ibid</em></p>
 <?php footNote('J',4,202); ?> p88, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,203); ?> PCC,<em> Data Protection Act, Journalism and the PCC Code</em>, http://www.pcc.org.uk/advice/editorials-detail.html?article=ODg</p>
 <?php footNote('J',4,204); ?> pp84-85, lines 10-2, Tim Toulmin, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-30-January-2012.pdf">Transcript-of-Morning-Hearing-30-January-2012.pdf</a></p>
 <?php footNote('J',4,205); ?> pp88-89, lines 23-15, <em>ibid</em></p>
 <?php footNote('J',4,206); ?> p107, lines 3-5, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-31-January-2012.pdf">Transcript-of-Morning-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,207); ?> p1, Sir Christopher Meyer, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-31-January-2012.pdf">Transcript-of-Afternoon-Hearing-31-January-2012.pdf</a></p>
 <?php footNote('J',4,208); ?> p1, lines 22-25, <em>ibid</em></p>
 <?php footNote('J',4,209); ?> p2, lines 5-18, <em>ibid</em></p>
 <?php footNote('J',4,210); ?> p4, lines 1-20, <em>ibid</em></p>
 <?php footNote('J',4,211); ?> pp4-5, lines 21-24, <em>ibid</em></p>
 <?php footNote('J',4,212); ?> p2, para 4, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-Wakeham.pdf">Witness-Statement-of-Lord-Wakeham.pdf</a></p>
 <?php footNote('J',4,213); ?> p13, para 82, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,214); ?> p13, para 83, <em>ibid</em></p>
 <?php footNote('J',4,215); ?> p68, para 20, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-R11.pdf">Exhibit-SA-R11.pdf</a></p>
 <?php footNote('J',4,216); ?> p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U1.pdf">Exhibit-SA-U1.pdf</a></p>
 <?php footNote('J',4,217); ?> pp377-378, paras 638-639, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Witness-Statement-of-Stephen-Abell.pdf">Witness-Statement-of-Stephen-Abell.pdf</a></p>
 <?php footNote('J',4,218); ?> p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U3.pdf">Exhibit-SA-U3.pdf</a></p>
 <?php footNote('J',4,219); ?> <em>ibid</em></p>
 <?php footNote('J',4,220); ?> See sentencing remarks of Mr Justice Gross in R v Glenn Mulcaire and Clive Goodman, 2007, Central Criminal Court</p>
 <?php footNote('J',4,221); ?> p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U2.pdf">Exhibit-SA-U2.pdf</a></p>
 <?php footNote('J',4,222); ?> pp1-2, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U4.pdf">Exhibit-SA-U4.pdf</a></p>
 <?php footNote('J',4,223); ?> p9, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U5.pdf">Exhibit-SA-U5.pdf</a>, Colin Myler&#8217;sevidence, p42, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Transcript-of-Morning-Hearing-15-December-20111.pdf">Transcript-of-Morning-Hearing-15-December-20111.pdf</a></p>
 <?php footNote('J',4,224); ?> p1-5, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U5.pdf">Exhibit-SA-U5.pdf</a></p>
 <?php footNote('J',4,225); ?> p4, paras 4.5-4.6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U11.pdf">Exhibit-SA-U11.pdf</a></p>
 <?php footNote('J',4,226); ?> p5, para 4.9, PCC, <em>ibid</em></p>
 <?php footNote('J',4,227); ?> p1, para 1.6, PCC, <em>ibid</em></p>
 <?php footNote('J',4,228); ?> PCC,<em> City Slickers ruling</em>, http://www.pcc.org.uk/news/index.html?article=MTc4NQ</p>
 <?php footNote('J',4,229); ?> p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U9.pdf">Exhibit-SA-U9.pdf</a></p>
 <?php footNote('J',4,230); ?> p 9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Sir-Christopher-Meyer.pdf">Witness-Statement-of-Sir-Christopher-Meyer.pdf</a></p>
 <?php footNote('J',4,231); ?> p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-U10.pdf">Exhibit-SA-U10.pdf</a></p>
 <?php footNote('J',4,232); ?> p7, para 6.3, Press Board of Finance, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Exhibit-Pbof-54.pdf</p>
 <?php footNote('J',4,233); ?> p8, para 6.7, Press Board of Finance, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Exhibit-Pbof-54.pdf</p>
 <?php footNote('J',4,234); ?> p11, para 10.5, <em>ibid</em></p>
 <?php footNote('J',4,235); ?> p11, para 10.4, <em>ibid</em></p>
 <?php footNote('J',4,236); ?> Stephen Brook,<em> News of the World in the clear over Clive Goodman case</em>, 18 May 2007, http://www.guardian.co.uk/media/2007/may/18/newsoftheworld.pressandpublishing</p>
 <?php footNote('J',4,237); ?> p2, Press Board of Finance, https://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Exhibit-Pbof-79.pdf</p>
 <?php footNote('J',4,238); ?> Published in the<em> Guardian</em> on 08 July 2009, in the online edition, available at: Nick Davies,<em> Revealed: Murdoch&#8217;s &#163;1m bill for hiding dirty tricks ,</em> 09 July 2009, http://www.nickdavies.net/2009/07/09/murdochs-1m-bill-for-hiding-dirty-tricks </p>
 <?php footNote('J',4,239); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B164.pdf">SA-B164.pdf</a></p>
 <?php footNote('J',4,240); ?> PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V21.pdf">Exhibit-SA-V21.pdf</a></p>
 <?php footNote('J',4,241); ?> pp48-49, lines 10-2, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,242); ?> p51, lines 4-10, <em>ibid</em></p>
 <?php footNote('J',4,243); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V12.pdf">Exhibit-SA-V12.pdf</a></p>
 <?php footNote('J',4,244); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V15.pdf">Exhibit-SA-V15.pdf</a></p>
 <?php footNote('J',4,245); ?> pp1-16, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V14.pdf">Exhibit-SA-V14.pdf</a></p>
 <?php footNote('J',4,246); ?> p2, PCC, <em>ibid</em></p>
 <?php footNote('J',4,247); ?> pp3-4, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V14.pdf">Exhibit-SA-V14.pdf</a></p>
 <?php footNote('J',4,248); ?> p3, PCC, <em>ibid</em></p>
 <?php footNote('J',4,249); ?> p267, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V19.pdf">Exhibit-SA-V19.pdf</a></p>
 <?php footNote('J',4,250); ?> p1, Stephen Abell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/SA-B182.pdf">SA-B182.pdf</a></p>
 <?php footNote('J',4,251); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V110.pdf">Exhibit-SA-V110.pdf</a></p>
 <?php footNote('J',4,252); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V16.pdf">Exhibit-SA-V16.pdf</a></p>
 <?php footNote('J',4,253); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V17.pdf">Exhibit-SA-V17.pdf</a></p>
 <?php footNote('J',4,254); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V111.pdf">Exhibit-SA-V111.pdf</a></p>
 <?php footNote('J',4,255); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V19.pdf">Exhibit-SA-V19.pdf</a></p>
 <?php footNote('J',4,256); ?> pp5, 7-8, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V21.pdf">Exhibit-SA-V21.pdf</a></p>
 <?php footNote('J',4,257); ?> p2, para 5, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V112.pdf">Exhibit-SA-V112.pdf</a></p>
 <?php footNote('J',4,258); ?> p118, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V112.pdf">Exhibit-SA-V112.pdf</a></p>
 <?php footNote('J',4,259); ?> p1, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V18.pdf">Exhibit-SA-V18.pdf</a></p>
 <?php footNote('J',4,260); ?> p9, para 13.2, PCC, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V21.pdf">Exhibit-SA-V21.pdf</a></p>
 <?php footNote('J',4,261); ?> <em>ibid</em></p>
 <?php footNote('J',4,262); ?> <em>ibid</em></p>
 <?php footNote('J',4,263); ?> PCC, p10, para 13.5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V21.pdf">Exhibit-SA-V21.pdf</a></p>
 <?php footNote('J',4,264); ?> PCC, p9, para 13.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V21.pdf">Exhibit-SA-V21.pdf</a></p>
 <?php footNote('J',4,265); ?> pp50-51, Baroness Buscombe, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Transcript-of-Morning-Hearing-7-February-2012.pdf">Transcript-of-Morning-Hearing-7-February-2012.pdf</a></p>
 <?php footNote('J',4,266); ?> pp95-96, lines 25-24, Nick Davies, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-29-November-2011.pdf">Transcript-of-Morning-Hearing-29-November-2011.pdf</a></p>
 <?php footNote('J',4,267); ?> pp1-10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Exhibit-SA-V22.pdf">Exhibit-SA-V22.pdf</a></p>
 <?php footNote('J',4,268); ?> Specifically the 2009 report in relation to Mr Coulson&#8217;s appointment in May 2010; p118, lines 5-21, David Cameron,<a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('J',4,269); ?> p40, 42, paras 165-166, 179-180, Joint Committee on Privacy and Injunctions, http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf</p>
 <?php footNote('J',4,270); ?> p38, para 86, House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200203/cmselect/cmcumeds/458/458.pdf</p>
 <?php footNote('J',4,271); ?> para 41, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-Baroness-Buscombe1.pdf">Witness-Statement-of-Baroness-Buscombe1.pdf</a></p>
 <?php footNote('J',4,272); ?> p p40-42, paras 92-95, House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200203/cmselect/cmcumeds/458/458.pdf</p>
 <?php footNote('J',4,273); ?> p89, paras 364-365, House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200910/cmselect/cmcumeds/362/362i.pdf</p>
 <?php footNote('J',4,274); ?> p91, para 374, <em>ibid</em></p>
 <?php footNote('J',4,275); ?> p39, para 160, Joint Committee on Privacy and Injunctions, http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf</p>
 <?php footNote('J',4,276); ?> p30, para 58, House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200203/cmselect/cmcumeds/458/458.pdf</p>
 <?php footNote('J',4,277); ?> pp36-38, paras 77-85, <em>ibid</em></p>
 <?php footNote('J',4,278); ?> pp 31-33, paras 65-72, House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200607/cmselect/cmcumeds/375/375.pdf; pp44-45, paras 193-202, Joint Committee on Privacyand Injunctions, http://www.publications.parliament.uk/pa/jt201012/jtselect/jtprivinj/273/273.pdf</p>
 <?php footNote('J',4,279); ?> pp29-30, para 57, House of Commons Culture, Media and Sport Select Committee, http://www.publications.parliament.uk/pa/cm200203/cmselect/cmcumeds/458/458.pdf</p>
 </div>
