<?php 
require_once('../../common.php');
levesonHeader('J',4); 
levesonNav('../../');
levesonBread('J',4);
require_once('content.php');
levesonFooterNav('J',4); 
require_once('footnotes.php');
LevesonCommonFooter();
?>