<div class="content" id="contentPartJChapter1">
<h1 id="top">CHAPTER 1<br/>INTRODUCTION</h1>
 <?php paragraphLink('J',1,1,1); ?>This Part of the Report returns to the conduct of the press and provides the context in which the conduct of the press in any particular case can be challenged. A broad outline of the criminal and civil law in so far as it might impact on journalists is set out in Appendix 4 but the substantive law only goes so far.</p>
  <?php paragraphLink('J',1,1,2); ?>For the criminal law, it is important also to consider the practical difficulties which reduce the prospect of a criminal investigation being started, let alone continue to fruition and result in prosecution. Chapter 2 identifies the argument that has been advanced by some that the matters giving rise to this Inquiry are a consequence of a failure of criminal law enforcement rather than anything else, and outlines what I consider to represent the reality of modern policing and the investigation of crime. It deals with the circumstances in which criminal investigations are instigated and the issues that are likely to be faced in the gathering of evidence.</p>
  <?php paragraphLink('J',1,1,3); ?>The Chapter then goes on to analyse the role that acting in the public interest should play within the criminal law. This is first in relation to the decision to prosecute: after the issue was raised by the Inquiry, the Director of Public Prosecutions consulted on the topic and then issued a formal guideline. It also considers the way in which the public interest might impact on later aspects of the criminal process as a consequence of judicial management, the jury and (if a conviction is recorded) sentence.</p>
  <?php paragraphLink('J',1,1,4); ?>Possible changes for the future are then considered. These include the preparation of guidelines should the maximum sentence for offences under s55 of the Data Protection Act 1998 be increased along with the submissions made by the Deputy Commissioner of the Metropolitan Police in relation to the Police and Evidence Act 1984.</p>
  <?php paragraphLink('J',1,1,5); ?>Chapter 3 concerns the civil law. Here the focus is not on the substantive law but, rather, on the impact of different costs regimes on the civil justice system and, in particular, the consequences of proposed changes in the law surrounding funding that are likely substantially to affect litigation against the press.</p>
  <?php paragraphLink('J',1,1,6); ?>On the basis that the costs regime is about to change to the disadvantage of those wishing to pursue civil litigation with the benefit of a Conditional Fee Agreement (which has led to an increase in the award of general damages in personal injury litigation), damages for defamation, breach of privacy and other media torts also fall for review, as does the issue of aggravated and exemplary damages. The other procedural law issue discussed concerns the mechanism for introducing incentives in relation to the costs of litigation if a regulator provides a system of arbitration.</p>
  <?php paragraphLink('J',1,1,7); ?>Chapter 4 is different and does not look to the future. The Terms of Reference require the Inquiry to consider the extent to which the current regulatory framework has failed. That requires a detailed consideration of the operation of the Press Complaints Commission.</p>
  </div>

