<?php 
require_once('../../common.php');
levesonHeader('J',1); 
levesonNav('../../');
levesonBread('J',1);
require_once('content.php');
levesonFooterNav('J',1); 
require_once('footnotes.php');
LevesonCommonFooter();
?>