<?php 
require_once('../../common.php');
levesonHeader('A',4); 
levesonNav('../../');
levesonBread('A',4);
require_once('content.php');
levesonFooterNav('A',4); 
require_once('footnotes.php');
LevesonCommonFooter();
?>