<!-- Footnotes-->
<div id="footnotes"> <?php footNote('I',4,1); ?> On the basis that current relationships between the press and the Prime Minister have been the subject ofconsiderable recent interest &#8211; and have each been ventilated at length during the course of the Inquiry &#8211; this sectionis considerably longer than those covering other periods of time and administrations where the issues are lessimmediate</p>
 <?php footNote('I',4,2); ?> p5, para 12, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,3); ?> p4, lines 6-12, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,4); ?> See paragraphs 3.18-19 and 3.38 below</p>
 <?php footNote('I',4,5); ?> p21, para 60, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,6); ?> pp4-5, lines 16-2, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,7); ?> p5, para 12, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,8); ?> p22, lines 13-18, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,9); ?> p30, para 94, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,10); ?> p4, para 9, <em>ibid</em></p>
 <?php footNote('I',4,11); ?> pp12-13, para 33, <em>ibid</em></p>
 <?php footNote('I',4,12); ?> p50, lines 8-24, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,13); ?> p24, para 71, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,14); ?> p24, para 71, <em>ibid</em></p>
 <?php footNote('I',4,15); ?> p24, para 71, <em>ibid</em></p>
 <?php footNote('I',4,16); ?> pp24-25, para 18, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Witness-statement-of-Andrew-Neil.pdf">Witness-statement-of-Andrew-Neil.pdf</a></p>
 <?php footNote('I',4,17); ?> p47, lines 7-13, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,18); ?> p46, lines 14-20, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,19); ?> pp46-47, lines 21-4, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,20); ?> p47, lines 14-23, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,21); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-2.pdf">Exhibit-DC-2.pdf</a></p>
 <?php footNote('I',4,22); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-3.pdf">Exhibit-DC-3.pdf</a></p>
 <?php footNote('I',4,23); ?> p74, para 221, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,24); ?> p97, lines 8-15, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,25); ?> p98, lines 6-11, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,26); ?> p99, lines 19-23, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,27); ?> Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/AEC2.pdf">AEC2.pdf</a></p>
 <?php footNote('I',4,28); ?> p9, para 38, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a>; see also pp20-25, lines 17-15, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</p>
 <?php footNote('I',4,29); ?> p110, lines 17-21, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,30); ?> p110, lines 17-21, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,31); ?> pp9-10, para 39, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,32); ?> p5, para 7.5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,33); ?> p5, para 7.2, George Osborne, <em>ibid</em></p>
 <?php footNote('I',4,34); ?> p29, lines 8-18, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,35); ?> p5, para 7.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,36); ?> pp54-55, lines 19-19, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,37); ?> p56, lines 3-23, George Osborne, <em>ibid</em></p>
 <?php footNote('I',4,38); ?> pp113-114, lines 25-10, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,39); ?> p74, para 222, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,40); ?> p30, lines 16-24, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,41); ?> p32, lines 5-7, Andy Coulson, <em>ibid</em></p>
 <?php footNote('I',4,42); ?> p8, para 32, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,43); ?> p6, para 7.7, 52 <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,44); ?> p7, para 29, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,45); ?> p62, lines 15-22, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,46); ?> p104, lines 5-7, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,47); ?> p75, para 224, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,48); ?> p7, para 30, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,49); ?> p8, para 31,<em> bid</em></p>
 <?php footNote('I',4,50); ?> p8, para 31, <em>ibid</em></p>
 <?php footNote('I',4,51); ?> p6, para 7.6, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,52); ?> pp100-101, lines 25-3, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,53); ?> p75, para 225, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,54); ?> pp104-105, lines 18-1, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,55); ?> p107, line 3, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,56); ?> p75, para 227, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,57); ?> p8, para 31, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,58); ?> pp6-7, para 8.4, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,59); ?> p76, para 229, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,60); ?> p24, para 13.3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf">Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf</a></p>
 <?php footNote('I',4,61); ?> p7, para 8.5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,62); ?> p63, lines 2-4, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,63); ?> p113, lines 8-19, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,64); ?> p63, lines 18-23, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,65); ?> pp108-109, lines 23-15, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,66); ?> pp65-66, lines 16-1, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,67); ?> p102, lines 15-24, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,68); ?> p4, line 15, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a>; see also p27, para 111, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Keith-Rupert-Murdoch2.pdf">Witness-Statement-of-Keith-Rupert-Murdoch2.pdf</a></p>
 <?php footNote('I',4,69); ?> p98, lines 12-21, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,70); ?> pp57-58, lines 14-4, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,71); ?> pp11-13, paras 50-60, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,72); ?> Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/AEC1.pdf">AEC1.pdf</a></p>
 <?php footNote('I',4,73); ?> pp25-27, lines 24-24, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a>: The subject of the shares is discussed further below</p>
 <?php footNote('I',4,74); ?> p76, para 228, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,75); ?> paras 3.56-3.75 below</p>
 <?php footNote('I',4,76); ?> p38, lines 1-7, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,77); ?> pp8-10, lines 21-2, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,78); ?> p13, para 57, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,79); ?> p68, lines 2-14, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,80); ?> pp35-36, lines 9-4, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,81); ?> pp16-17, paras 72-77, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,82); ?> pp43-44, lines 20-2, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,83); ?> p16, para 78, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,84); ?> p50, lines 18-25, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,85); ?> p8, lines 10-14, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,86); ?> p17, para 79, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,87); ?> pp66-67, line 22-2, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,88); ?> pp48-49, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,89); ?> p48, lines 9-20, Andy Coulson, <em>ibid</em></p>
 <?php footNote('I',4,90); ?> pp82-83, line 24-9, Andy Coulson, <em>ibid</em></p>
 <?php footNote('I',4,91); ?> Aidan Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Appendix-D-to-Witness-Statement-of-Aidan-Barclay.pdf">Appendix-D-to-Witness-Statement-of-Aidan-Barclay.pdf</a></p>
 <?php footNote('I',4,92); ?> p1, Aidan Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-AB1B.pdf">Exhibit-AB1B.pdf</a></p>
 <?php footNote('I',4,93); ?> pp84-85, line 13 -1, Aidan Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-23-April-2012.pdf">Transcript-of-Afternoon-Hearing-23-April-2012.pdf</a></p>
 <?php footNote('I',4,94); ?> p71, lines 11-16, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,95); ?> pp59-60, line 15-8, Aidan Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-23-April-2012.pdf">Transcript-of-Afternoon-Hearing-23-April-2012.pdf</a>; p8, Aiden Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-AB1D.pdf">Exhibit-AB1D.pdf</a></p>
 <?php footNote('I',4,96); ?> p64, para 190, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,97); ?> p66, para 196, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,98); ?> Elisabeth Murdoch has her own substantial business interests in the form of Shine Limited</p>
 <?php footNote('I',4,99); ?> p1, lines 8-16, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,100); ?> p1, lines 15-16, <em>ibid</em></p>
 <?php footNote('I',4,101); ?> p65, para 193, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,102); ?> p54, lines 8-12, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,103); ?> Compare David Cameron: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-2.pdf">Exhibit-DC-2.pdf</a>and Rupert Murdoch&#8217;s schedule of contact with Opposition leaders: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-KRM-29.pdf">Exhibit-KRM-29.pdf</a></p>
 <?php footNote('I',4,104); ?> pp54-55, line 13-3, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,105); ?> p68, lines 6-15, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,106); ?> p3, lines 11-25, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,107); ?> pp6-8, line 15 -8, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,108); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-3.pdf">Exhibit-DC-3.pdf</a></p>
 <?php footNote('I',4,109); ?> p44, lines 3-11, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,110); ?> pp5-6, line 6 -1, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,111); ?> p3, lines 17-23, Rupert Murdoch, <em>ibid</em></p>
 <?php footNote('I',4,112); ?> p6, lines 11-13, Rupert Murdoch, <em>ibid</em></p>
 <?php footNote('I',4,113); ?> p6, lines 16-19, Rupert Murdoch, <em>ibid</em></p>
 <?php footNote('I',4,114); ?> pp32-33, line 9-4, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,115); ?> pp9-10, line 21-6, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,116); ?> p57, lines 18-21, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,117); ?> p67, para 199,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a>; Rupert Murdoch was missing from the list of people Mr Cameron listed in exhibit DC2 as havingbeen present on 16 August 2008 but he rapidly corrected this error (which arose at a time when the meeting wasalready in the public domain) in his oral evidence, pp56-57, line 14 &#8211;3, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a> </p>
 <?php footNote('I',4,118); ?> p59, line 11-17, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,119); ?> p26, para 107, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Keith-Rupert-Murdoch2.pdf">Witness-Statement-of-Keith-Rupert-Murdoch2.pdf</a>; p10, lines 1-6, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,120); ?> p10, lines 13-24, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,121); ?> p11, lines 11-14, Rupert Murdoch, <em>ibid</em></p>
 <?php footNote('I',4,122); ?> p49, lines 1-2, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,123); ?> p49, lines 17-19, Rebekah Brooks, <em>ibid</em>. Note that the transcript here records Mrs Brooks as saying that the durationof the stay was either an afternoon or an evening whereas she is earlier recorded as saying an afternoon and an evening. On any view it was a short stay.</p>
 <?php footNote('I',4,124); ?> p54, lines 8-12, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,125); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-2.pdf">Exhibit-DC-2.pdf</a>; JamesMurdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-JRJM-10.pdf">Exhibit-JRJM-10.pdf</a></p>
 <?php footNote('I',4,126); ?> p61, lines 4-10, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,127); ?> p64, lines 3-16, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,128); ?> p61, lines 10-12, James Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-24-April-2012.pdf">Transcript-of-Morning-Hearing-24-April-2012.pdf</a></p>
 <?php footNote('I',4,129); ?> p60, lines 15-22, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,130); ?> paras 2.138-2.159 and paras 2.120-2.137 below</p>
 <?php footNote('I',4,131); ?> p1, para 5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Rebekah-Brooks.pdf">Witness-Statement-of-Rebekah-Brooks.pdf</a></p>
 <?php footNote('I',4,132); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-2.pdf">Exhibit-DC-2.pdf</a>Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a></p>
 <?php footNote('I',4,133); ?> para 2.75 above</p>
 <?php footNote('I',4,134); ?> p41, lines 13-21, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,135); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-2.pdf">Exhibit-DC-2.pdf</a></p>
 <?php footNote('I',4,136); ?> p46, lines 1-9, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,137); ?> p5, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a> lists adinner on 2 October 2006 but not 1 October 2006</p>
 <?php footNote('I',4,138); ?> p5, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a>,</p>
 <?php footNote('I',4,139); ?> paras 2.14-2.42 above</p>
 <?php footNote('I',4,140); ?> p79, lines 14-23, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,141); ?> p49, lines 20-22, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,142); ?> http://www.dominicgrieve.org.uk/about-dominic-grieve</p>
 <?php footNote('I',4,143); ?> p110-111, lines 18-2, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,144); ?> p111, lines 3-7, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,145); ?> pp78-79, lines 19-5, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,146); ?> p71, para 209, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,147); ?> pp71-72, para 212, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,148); ?> p79, lines 1-5, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,149); ?> pp51-52, lines 17-20, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,150); ?> p77, line 9-13, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,151); ?> p51, line 1-7, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,152); ?> p80, line 1-6, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,153); ?> p80, line 12-17, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,154); ?> p1, lines 8-14, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,155); ?> p73, lines 20-22, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,156); ?> p79, lines 6-10, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,157); ?> p76, lines 1-4, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,158); ?> pp81-82, lines 23-10, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a>, and <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Letter-from-Linklaters-regarding-Rebekah-Brooks-communications-with-Prime-Ministers.pdf">Letter-from-Linklaters-regarding-Rebekah-Brooks-communications-with-Prime-Ministers.pdf</a></p>
 <?php footNote('I',4,159); ?> pp82-83, lines 19-5, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,160); ?> p83, lines 8-18, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,161); ?> p p83-84, lines 22-9, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,162); ?> p84, lines 10-13, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,163); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-2.pdf">Exhibit-DC-2.pdf</a></p>
 <?php footNote('I',4,164); ?> p6, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a></p>
 <?php footNote('I',4,165); ?> p75, lines 1-2, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,166); ?> p74, lines 6-10, Rebekah Brooks, <em>ibid</em></p>
 <?php footNote('I',4,167); ?> p75, lines 7-12, Rebekah Brooks, <em>ibid</em></p>
 <?php footNote('I',4,168); ?> See above at paras 2.85 &#8211; 2.87</p>
 <?php footNote('I',4,169); ?> See above at para 2.74</p>
 <?php footNote('I',4,170); ?> p52, lines 1-2, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a> ; http://www.thesun.co.uk/sol/homepage/news/campaigns/our_boys/2611351/Dont-you-know-theres-a-bloody-war-on.html</p>
 <?php footNote('I',4,171); ?> p18, para 8.6, James Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf">Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf</a>; pp55-56, lines 25-3, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,172); ?> p51, para 20-22, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,173); ?> p63, lines 1-10, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,174); ?> pp64-65, lines 3-1, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,175); ?> p67, James Murdoch, lines 2-5, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-24-April-2012.pdf">Transcript-of-Morning-Hearing-24-April-2012.pdf</a></p>
 <?php footNote('I',4,176); ?> p66, lines 20-23, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,177); ?> http://www.thesun.co.uk/sol/homepage/news/2661063/The-Sun-Says-Labours-lost-it.html</p>
 <?php footNote('I',4,178); ?> p21, para 100, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,179); ?> p60, lines 14-17, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,180); ?> p67, lines 15-17, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,181); ?> p90, lines 6-11, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-25-April-2012.pdf">Transcript-of-Morning-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,182); ?> p29, para 120, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Keith-Rupert-Murdoch2.pdf">Witness-Statement-of-Keith-Rupert-Murdoch2.pdf</a></p>
 <?php footNote('I',4,183); ?> p18, para 8.6, James Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf">Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf</a></p>
 <?php footNote('I',4,184); ?> pp94-95, lines 21-2, James Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-24-April-2012.pdf">Transcript-of-Morning-Hearing-24-April-2012.pdf</a></p>
 <?php footNote('I',4,185); ?> pp55-56, lines 25-3, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,186); ?> p60, lines 13-17, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,187); ?> pp51-60, lines 10-18, Rebekah Brooks,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a>; pp58-69, lines 10-11, Dominic Mohan, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-9-January-2012.pdf">Transcript-of-Afternoon-Hearing-9-January-2012.pdf</a>; p20, para 9.9, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf">Witness-Statement-of-James-Rupert-Jacob-Murdoch.pdf</a>; p90,lines 3-11, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-25-April-2012.pdf">Transcript-of-Morning-Hearing-25-April-2012.pdf</a> </p>
 <?php footNote('I',4,188); ?> pp71-72, lines 5-7, Lord Mandelson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-21-May-20121.pdf">Transcript-of-Afternoon-Hearing-21-May-20121.pdf</a></p>
 <?php footNote('I',4,189); ?> Mandelson, P,<em> The Third Man,</em> 2010, p489</p>
 <?php footNote('I',4,190); ?> pp74-75, lines 25-12, Lord Mandelson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-21-May-20121.pdf">Transcript-of-Afternoon-Hearing-21-May-20121.pdf</a></p>
 <?php footNote('I',4,191); ?> p24, lines 4-6, Gordon Brown, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-11-June-2012.pdf">Transcript-of-Morning-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,192); ?> pp37-38, lines 22-15, Gordon Brown, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-11-June-2012.pdf">Transcript-of-Morning-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,193); ?> p39, lines 6-11, Gordon Brown, <em>ibid</em></p>
 <?php footNote('I',4,194); ?> Gordon Brown, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-GB8-to-Witness-Statement-of-Gordon-Brown-MP.pdf">Exhibit-GB8-to-Witness-Statement-of-Gordon-Brown-MP.pdf</a></p>
 <?php footNote('I',4,195); ?> pp87-88, lines 11-17, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,196); ?> <?php internalChapterLink('../../','I',6); ?></p>
 <?php footNote('I',4,197); ?> p31, para 99, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a>; p176, http://www.general-election-2010.co.uk/2010-general-election-manifestos/Conservative-Party-Manifesto-2010.pdf</p>
 <?php footNote('I',4,198); ?> p31, para 100, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,199); ?> p32, para 103, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,200); ?> p40, para 117, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a> ; p4 of Plurality in a new media age </p>
 <?php footNote('I',4,201); ?> p69, para 203, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,202); ?> http://www.conservatives.com/News/Speeches/2009/01/Ed_Vaizey_BBC_must_not_drive_up_stars_salaries.aspx</p>
 <?php footNote('I',4,203); ?> pp33-35, para 107, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,204); ?> p36, para 109, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,205); ?> pp36-37, para 110, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,206); ?> p39, para 114, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,207); ?> p40, para 119, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,208); ?> p89, lines 14-21, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,209); ?> p90, lines 1-12, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,210); ?> pp23-24, lines 20-15, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,211); ?> p25, lines 20-24, George Osborne, <em>ibid</em></p>
 <?php footNote('I',4,212); ?> pp38-39, para 113, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,213); ?> pp92-93, lines 23-14, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,214); ?> pp25-26, lines 25-11, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,215); ?> p94, lines 11-20, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,216); ?> pp27-28, para 20, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/07/Witness-statement-of-Andrew-Neil.pdf">Witness-statement-of-Andrew-Neil.pdf</a></p>
 <?php footNote('I',4,217); ?> p66, lines 2-9, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,218); ?> p66, lines 15-21, George Osborne, <em>ibid</em></p>
 <?php footNote('I',4,219); ?> p50, lines 15-24, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,220); ?> pp51-52, lines 11-4, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,221); ?> pp53-54, lines 17-1, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,222); ?> pp12-14, lines 25-4, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,223); ?> pp6-7, lines 22-11, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,224); ?> pp7-8, lines 14-7, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,225); ?> pp22-23, lines 5-11, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,226); ?> p2, para 2.2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,227); ?> pp33-34, lines 18-12, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,228); ?> pp34-35, lines 23-8, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,229); ?> pp10-11, para 28, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,230); ?> p10, para 26, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,231); ?> pp39-40, lines 14-9, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,232); ?> p41, lines 2-9, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,233); ?> p26, para 79, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,234); ?> David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a></p>
 <?php footNote('I',4,235); ?> p3, Aidan Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Appendix-D-to-Witness-Statement-of-Aidan-Barclay.pdf">Appendix-D-to-Witness-Statement-of-Aidan-Barclay.pdf</a>; p4, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a></p>
 <?php footNote('I',4,236); ?> p70, para 206, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,237); ?> p3, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Appendix-D-to-Witness-Statement-of-Aidan-Barclay.pdf">Appendix-D-to-Witness-Statement-of-Aidan-Barclay.pdf</a>; p7, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a></p>
 <?php footNote('I',4,238); ?> p11, lines 16-18, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,239); ?> p8, Aidan Barclay, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-AB1B.pdf">Exhibit-AB1B.pdf</a></p>
 <?php footNote('I',4,240); ?> p7, Aidan Barclay, <em>ibid</em></p>
 <?php footNote('I',4,241); ?> p72, lines 15-24, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,242); ?> <?php internalChapterLink('../../','I',8); ?></p>
 <?php footNote('I',4,243); ?> p70, para 207, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,244); ?> p27, para 110, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Witness-Statement-of-Keith-Rupert-Murdoch2.pdf">Witness-Statement-of-Keith-Rupert-Murdoch2.pdf</a></p>
 <?php footNote('I',4,245); ?> p14, line 14, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('I',4,246); ?> p19, para 91, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,247); ?> pp70-71, para 208, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,248); ?> p13, lines 5-14, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Afternoon-Hearing-25-April-2012.pdf">Transcript-of-Afternoon-Hearing-25-April-2012.pdf</a>; David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a></p>
 <?php footNote('I',4,249); ?> p70, para 206, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,250); ?> p4, Rupert Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-KRM-27.pdf">Exhibit-KRM-27.pdf</a></p>
 <?php footNote('I',4,251); ?> p19, para 92, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,252); ?> p7, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a>; p2, JamesMurdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-JRJM-9.pdf">Exhibit-JRJM-9.pdf</a></p>
 <?php footNote('I',4,253); ?> p8, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a>; p2, JamesMurdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Exhibit-JRJM-9.pdf">Exhibit-JRJM-9.pdf</a></p>
 <?php footNote('I',4,254); ?> pp68-69, lines 23-5, James Murdoch, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-24-April-2012.pdf">Transcript-of-Morning-Hearing-24-April-2012.pdf</a></p>
 <?php footNote('I',4,255); ?> pp24-25, lines 25-6, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,256); ?> pp25-26, lines 13-1, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,257); ?> p3, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a></p>
 <?php footNote('I',4,258); ?> pp4, 6-7, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a>; p3,Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a></p>
 <?php footNote('I',4,259); ?> p87, lines 1-19, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,260); ?> p6, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a></p>
 <?php footNote('I',4,261); ?> p8, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Exhibit-DC-1.pdf">Exhibit-DC-1.pdf</a>; p4, RebekahBrooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a></p>
 <?php footNote('I',4,262); ?> p26, lines 7-13, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,263); ?> pp88-89, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,264); ?> p12, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Exhibit-RMB-11.pdf">Exhibit-RMB-11.pdf</a></p>
 <?php footNote('I',4,265); ?> p97, lines 16-22, Theresa May, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-29-May-2012.pdf">Transcript-of-Morning-Hearing-29-May-2012.pdf</a></p>
 <?php footNote('I',4,266); ?> p98, lines 1-15, Theresa May, <em>ibid</em></p>
 <?php footNote('I',4,267); ?> pp98-99, lines 22-7, Theresa May, <em>ibid</em></p>
 <?php footNote('I',4,268); ?> p99, lines 13-16, Theresa May, <em>ibid</em></p>
 <?php footNote('I',4,269); ?> p86, line 6, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,270); ?> pp85-86, lines 11-2, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,271); ?> p86, lines 9-20, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,272); ?> pp78-79, lines 22-3, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,273); ?> p80, lines 22-25, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,274); ?> p80, lines 10-16, Rebekah Brooks, <em>ibid</em></p>
 <?php footNote('I',4,275); ?> p10, lines 1-8, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,276); ?> pp7-8, lines 6-2, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,277); ?> pp6-7, lines 2-24, Rebekah Brooks, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-11-May-2012.pdf">Transcript-of-Morning-Hearing-11-May-2012.pdf</a></p>
 <?php footNote('I',4,278); ?> pp95-96, lines 10-20, Nick Clegg, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-13-June-2012.pdf">Transcript-of-Morning-Hearing-13-June-2012.pdf</a></p>
 <?php footNote('I',4,279); ?> p3, lines 3-21, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,280); ?> p78, para 236, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,281); ?> p66, lines 9-19, Lord O&#8217;Donnell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-14-May-2012.pdf">Transcript-of-Morning-Hearing-14-May-2012.pdf</a></p>
 <?php footNote('I',4,282); ?> p79, para 240, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,283); ?> p19, Question 30, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Lord-ODonnell.pdf">Witness-Statement-of-Lord-ODonnell.pdf</a></p>
 <?php footNote('I',4,284); ?> pp5-6, lines 8-3, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,285); ?> Letter, Lord O&#8217;Donnell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Addendum-to-evidence-of-Lord-ODonnell-Letter-from-Cabinet-Office-on-vetting-of-officials.pdf">Addendum-to-evidence-of-Lord-ODonnell-Letter-from-Cabinet-Office-on-vetting-of-officials.pdf</a></p>
 <?php footNote('I',4,286); ?> p68, lines 7-24, Lord O&#8217;Donnell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-14-May-2012.pdf">Transcript-of-Morning-Hearing-14-May-2012.pdf</a></p>
 <?php footNote('I',4,287); ?> Letter, Lord O&#8217;Donnell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Addendum-to-evidence-of-Lord-ODonnell-Letter-from-Cabinet-Office-on-vetting-of-officials.pdf">Addendum-to-evidence-of-Lord-ODonnell-Letter-from-Cabinet-Office-on-vetting-of-officials.pdf</a></p>
 <?php footNote('I',4,288); ?> p70, lines 11-18, Lord O&#8217;Donnell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-14-May-2012.pdf">Transcript-of-Morning-Hearing-14-May-2012.pdf</a></p>
 <?php footNote('I',4,289); ?> p54, lines 13-16, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,290); ?> p72, lines 7-10, Lord O&#8217;Donnell, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-14-May-2012.pdf">Transcript-of-Morning-Hearing-14-May-2012.pdf</a></p>
 <?php footNote('I',4,291); ?> p11, para 46, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,292); ?> pp54-55, lines 22-1, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,293); ?> p55, para 2-7, Andy Coulson, <em>ibid</em></p>
 <?php footNote('I',4,294); ?> http://www.nytimes.com/2010/09/05/magazine/05hacking-t.html?pagewanted=all</p>
 <?php footNote('I',4,295); ?> p7, lines 10-15, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a>; note that although the transcript at p6 refers to an article dated 1 December2010, the article was in fact dated 1 September 2010, see the footnote above for a link to the article</p>
 <?php footNote('I',4,296); ?> p7, lines 21-24, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,297); ?> pp8-9, lines 3-1, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,298); ?> http://www.guardian.co.uk/media/2010/feb/24/andy-coulson-news-of-the-world</p>
 <?php footNote('I',4,299); ?> p84, para 261, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,300); ?> p84, para 260, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,301); ?> p83, para 259, David Cameron, <em>ibid</em></p>
 <?php footNote('I',4,302); ?> p9, lines 4-21, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-14-June-2012.pdf">Transcript-of-Afternoon-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,303); ?> p15, para 68, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,304); ?> p69, lines 7-10, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a>; p6, para 7.8, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,305); ?> p18, para 86, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,306); ?> p49, lines 12-14, Andy Coulson, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-10-May-2012.pdf">Transcript-of-Afternoon-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('I',4,307); ?> p19, para 94, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Witness-Statement-of-Andy-Coulson.pdf">Witness-Statement-of-Andy-Coulson.pdf</a></p>
 <?php footNote('I',4,308); ?> p7, para 9.2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a> ; see also p57, lines 2-9, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,309); ?> pp109-110, lines 16-4, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,310); ?> p7, para 9.1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-George-Osborne-MP.pdf">Witness-Statement-of-George-Osborne-MP.pdf</a></p>
 <?php footNote('I',4,311); ?> p4, para 10, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Witness-Statement-of-DAC-Sue-Akers.pdf">Witness-Statement-of-DAC-Sue-Akers.pdf</a></p>
 <?php footNote('I',4,312); ?> p1, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/Second-Witness-Statement-of-DAC-Sue-Akers1.pdf">Second-Witness-Statement-of-DAC-Sue-Akers1.pdf</a></p>
 <?php footNote('I',4,313); ?> p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-Ed-Miliband.pdf">Witness-Statement-of-Ed-Miliband.pdf</a></p>
 <?php footNote('I',4,314); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Exhibit-9-to-Mark-Thomson.pdf">Exhibit-9-to-Mark-Thomson.pdf</a></p>
 <?php footNote('I',4,315); ?> The article contains an inaccuracy, for which the Guardian has subsequently apologised, in that it is unlikely that theNews of the World caused the false hope moment described by Mrs Dowler in her evidence. However, the article wascorrect in its assertion that Milly Dowler&#8217;s voicemail was intercepted by the News of the World.</p>
 <?php footNote('I',4,316); ?> p1, para 2, Nick Clegg, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-Nick-Clegg-MP2.pdf">Witness-Statement-of-Nick-Clegg-MP2.pdf</a></p>
 <?php footNote('I',4,317); ?> p31, lines 9-18, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a></p>
 <?php footNote('I',4,318); ?> <?php internalChapterLink('../../','I',6); ?></p>
 <?php footNote('I',4,319); ?> p1, para 2, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a> ; http://www.publications.parliament.uk/pa/cm201011/cmhansrd/cm110713/debtext/110713-0001.htm#11071354000003</p>
 <?php footNote('I',4,320); ?> p43, para 128, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 <?php footNote('I',4,321); ?> p19, lines 16-24, George Osborne, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Afternoon-Hearing-11-June-2012.pdf">Transcript-of-Afternoon-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('I',4,322); ?> pp14-15, lines 21-5, David Cameron, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-14-June-2012.pdf">Transcript-of-Morning-Hearing-14-June-2012.pdf</a>; pp17,73, paras 47 and 218, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Witness-Statement-of-David-Cameron-MP.pdf">Witness-Statement-of-David-Cameron-MP.pdf</a></p>
 </div>
