<?php 
require_once('../../common.php');
levesonHeader('I',4); 
levesonNav('../../');
levesonBread('I',4);
require_once('content.php');
levesonFooterNav('I',4); 
require_once('footnotes.php');
LevesonCommonFooter();
?>