<?php 
require_once('../../common.php');
levesonHeader('C',1); 
levesonNav('../../');
levesonBread('C',1);
require_once('content.php');
levesonFooterNav('C',1); 
require_once('footnotes.php');
LevesonCommonFooter();
?>