<!-- Footnotes-->
<div id="footnotes">
<?php footNote('A',2,1); ?> s2(1) Inquiries Act 2005</p>
 <?php footNote('A',2,2); ?> The problems arising from the concurrent nature of the criminal investigation are described in my ruling on theApproach to Evidence: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Approaches-to-evidence-7-November-PDF-106KB.pdf">Approaches-to-evidence-7-November-PDF-106KB.pdf</a></p>
 <?php footNote('A',2,3); ?> The justification for proceeding in this way is explained in my Ruling on the role of the assessors: pp10-11, paras 32-36,<a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Ruling-on-the-role-of-the-assessors-PDF-102-KB.pdf">Ruling-on-the-role-of-the-assessors-PDF-102-KB.pdf</a></p>
 <?php footNote('A',2,4); ?> www.levesoninquiry.org.uk/news-and-events/</p>
 <?php footNote('A',2,5); ?> Mr Browne was later instructed to act on behalf of Trinity Mirror plc but I am entirely satisfied that his appearanceat the Seminar was as an expert in the field and not as counsel to a media group that was later to become a CoreParticipant</p>
 <?php footNote('A',2,6); ?> At the third seminar, Mr Dacre said: <q>While I abhor statutory controls, there&#8217;s one area where Parliament can help the press. Some way must be found to compel all newspaper owners to fund and participate in self-regulation.</q> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/RPC_DOCS1-12374597-v1-PAUL_DACRE_S_SEMINAR_SPEECH.pdf">RPC_DOCS1-12374597-v1-PAUL_DACRE_S_SEMINAR_SPEECH.pdf</a>. That is no longer his position: on 15 June 2012, he submitted: <q>In retrospect, after hearing some of the devastating evidence to the Inquiry in the third module, I regret this suggestion because I now fear that ANY parliamentary involvement would be the &#8220;thin edge of the wedge&#8221; which could result in fuller statutory control of the press</q> p5 <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Submission-by-Paul-Dacre1.pdf">Submission-by-Paul-Dacre1.pdf</a></p>
 <?php footNote('A',2,7); ?> http://www.levesoninquiry.org.uk/about/opening-remarks/</p>
 <?php footNote('A',2,8); ?> Module 1 rulings:  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Core-Participants-final-14.09.11.pdf">Core-Participants-final-14.09.11.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-judgement-relating-to-Elaine-Decoulos-4-October-PDF-50.2KB.pdf">Transcript-of-judgement-relating-to-Elaine-Decoulos-4-October-PDF-50.2KB.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Further-Ruling-on-Core-Participants-2-Novembr-2011.pdf">Further-Ruling-on-Core-Participants-2-Novembr-2011.pdf</a>. Module 2 rulings: p26, [line 4 et seq], <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Afternoon-Hearing-25-January-20121.pdf">Transcript-of-Afternoon-Hearing-25-January-20121.pdf</a> and <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Further-ruling-on-Core-Participants-17-February-2012.pdf">Further-ruling-on-Core-Participants-17-February-2012.pdf</a>. Module 3 rulings:<a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Further-Ruling-on-Core-Participants-Module-3-5-April-2012.pdf">Further-Ruling-on-Core-Participants-Module-3-5-April-2012.pdf</a> and <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Further-Ruling-on-Core-Participants-Government-4-May-2012.pdf">Further-Ruling-on-Core-Participants-Government-4-May-2012.pdf</a>. Module 4 rulings: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Amended-Ruling-in-relation-to-Core-Particpants-for-Module-42.pdf">Amended-Ruling-in-relation-to-Core-Particpants-for-Module-42.pdf</a>. Applications by Ms Decoulousto appeal each decision refusing her Core Participant status were refused by the Administrative Court (Module 1 on4 November 2011 by Moses LJ and Singh J: [2011] EWHC 3214(Admin); Module 2 on 14 March 2012 by Richards LJand Kenneth Parker J: CO/2320/2012; and Modules 3 and 4 on 17 July 2012 by Sir John Thomas PQBD and Silber J:CO/4182/2012, CO/7190/2012) </p>
 <?php footNote('A',2,9); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Approaches-to-evidence-7-November-PDF-106KB.pdf">Approaches-to-evidence-7-November-PDF-106KB.pdf</a></p>
 <?php footNote('A',2,10); ?> There are numerous references in the transcripts to this approach; see, for example, the ruling in relation to Rule 13of the Inquiry Rules 2006 [para 5], <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Application-of-Rule-13-of-the-Inquiry-Rules-2006.pdf">Application-of-Rule-13-of-the-Inquiry-Rules-2006.pdf</a></p>
 <?php footNote('A',2,11); ?> This includes the civil actions of Gordon Taylor and Sienna Miller which were of critical importance to the greater understanding of the truth behind the assertion of &#8216;one rogue reporter&#8217;, the many civil actions conducted before Vos Jand the public law review of the conduct of the Metropolitan Police in relation to Operation Caryatid</p>
 <?php footNote('A',2,12); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/231111-S19-restriction-order-HJK.pdf">231111-S19-restriction-order-HJK.pdf</a></p>
 <?php footNote('A',2,13); ?> This evidence included hearsay, anonymous material which Michelle Stanistreet the General Secretary of the National Union of Journalists sought to adduce from a number of journalists who feared for their careers if they spokeout in public. An application for this evidence to be heard was challenged by other Core Participants and subjectto &#8216;gateway&#8217; rulings by the Inquiry: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Anonymous-Witnesses-Ruling-PDF-64.5-KB.pdf">Anonymous-Witnesses-Ruling-PDF-64.5-KB.pdf</a> and <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Anonymous-Evidence-28-November-2011.pdf">Anonymous-Evidence-28-November-2011.pdf</a>. These were issued along with a protocol <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Protocol-regarding-Applications-for-Anonymity.pdf">Protocol-regarding-Applications-for-Anonymity.pdf</a>. The rulings were the subject ofunsuccessful challenge in the Administrative Court (Toulson LJ, Sweeney and Sharp JJ): see R (on the application of Associated Newspapers Ltd v. The Rt Hon Lord Justice Leveson as Chairman of the Leveson Inquiry [2012] EWHC 57  (Admin), http://www.judiciary.gov.uk/Resources/JCO/Documents/Judgments/assoc-news-v-chair-leveson-inquiry.pdf.  There was then a substantive ruling on the merits of the application which was granted: http://www.levesoninquiry.  org.uk/wp-content/uploads/2011/11/Anonymous-witnesses-ruling-7-Feb-2012.pdf </p>
 <?php footNote('A',2,14); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Key-Questions.pdf">Key-Questions.pdf</a></p>
 <?php footNote('A',2,15); ?> Beat; Big Brother Watch; British Psychological Society; Carbon Brief; Carnegie Trust; Democratic Society;  DisasterAction; Federation of Muslim Organisation; Federation of Poles in Great Britain; Full Fact; Howard League for PenalReform; Inclusion London; Irish Traveller Movement; Joint Council for the Welfare of Immigrants; Joint Enterprise: NotGuilty by Association (JENGbA); London Muslim Centre and the East London Mosque; Make Justice Work; Migrantand Refugee Communities Forum Mind and Rethink Mental Illness; National Aids Trust; Neuroimmune Alliance;Professionals Against Child Abuse; Refugee Council; Royal College of Psychiatrists; Runnymede Trust; Samaritans SenseAbout Science; Support After Murder and Manslaughter (National); Transparency International UK; UK Drug Policy Commission; United Communications Ltd; Wellcome Trust, Cancer Research UK and Association of Media Research(Joint Submission); Wish; Youth Media Agency </p>
 <?php footNote('A',2,16); ?> Other examples are discussed in the ruling concerning the evidence of Peter Tickner: see <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Ruling-of-26-March-2012.pdf">Ruling-of-26-March-2012.pdf</a></p>
 <?php footNote('A',2,17); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Key-Questions-Module-2.pdf">Key-Questions-Module-2.pdf</a></p>
 <?php footNote('A',2,18); ?> pp1-14, lines 1-17, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Afternoon-Hearing-15-May-2012.pdf">Transcript-of-Afternoon-Hearing-15-May-2012.pdf</a></p>
 <?php footNote('A',2,19); ?> One of the issues that arose in the House of Commons concerned the allegation that Mr Hunt had breached the terms of the Ministerial Code. As I have made consistently clear, my approach has been focussed on the relationship between the press and politicians and the conduct of each as a matter of generality; it is no part of my intention o rmy function to pass judgment on anything else and, in particular, I have not addressed the political (still less the party political) questions that have been asked</p>
 <?php footNote('A',2,20); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Key-Questions-Module-3.pdf">Key-Questions-Module-3.pdf</a></p>
 <?php footNote('A',2,21); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Draft-Criteria-for-a-Regulatory-Solution.pdf">Draft-Criteria-for-a-Regulatory-Solution.pdf</a></p>
 <?php footNote('A',2,22); ?> <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/12/Key-Questions-Module-4.pdf">Key-Questions-Module-4.pdf</a></p>
 <?php footNote('A',2,23); ?> p13, lines 12-22, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/leveson-inquiry-transcript-060911.pdf">leveson-inquiry-transcript-060911.pdf</a></p>
 <?php footNote('A',2,24); ?> This is one of the reasons why, given the concessions that were made by the press Core Participants, it was inappropriate to investigate the detail contained in the books seized from Steve Whittamore during Operation Motorman. For the purposes of Part 1 of the Terms of Reference, I concluded that it was necessary to go so farbut no further: this is dealt with below but, by way of cross reference, is evident from the rulings which sought toensure clarity of the position: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Ruling-In-Relation-to-Operation-Motorman-Evidence-11-June-20123.pdf">Ruling-In-Relation-to-Operation-Motorman-Evidence-11-June-20123.pdf</a>, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Operation-Motorman-and-ANL-10-July-2012.pdf">Operation-Motorman-and-ANL-10-July-2012.pdf</a>, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Ruling-on-Future-Direction-23-July-2012.pdf">Ruling-on-Future-Direction-23-July-2012.pdf</a> </p>
 <?php footNote('A',2,25); ?> p91, line 6 et seq, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/04/Transcript-of-Morning-Hearing-25-April-2012.pdf">Transcript-of-Morning-Hearing-25-April-2012.pdf</a></p>
 <?php footNote('A',2,26); ?> p59, line 23 et seq, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/06/Transcript-of-Morning-Hearing-11-June-2012.pdf">Transcript-of-Morning-Hearing-11-June-2012.pdf</a></p>
 <?php footNote('A',2,27); ?> For reasons which will become apparent, I take a slightly different view in relation to the disclosure of the medical condition of Mr Brown&#8217;s son: see <?php internalChapterLink('../../','F',5); ?></p>
 <?php footNote('A',2,28); ?> By way of example, p1, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/01/Transcript-of-Morning-Hearing-11-January-2012.pdf">Transcript-of-Morning-Hearing-11-January-2012.pdf</a></p>
 <?php footNote('A',2,29); ?> p10 line 15 et seq,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-14-November-2011.pdf">Transcript-of-Morning-Hearing-14-November-2011.pdf</a>, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-14-November-2011.pdf">Transcript-of-Afternoon-Hearing-14-November-2011.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Morning-Hearing-15-November-2011.pdf">Transcript-of-Morning-Hearing-15-November-2011.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-15-November-2011.pdf">Transcript-of-Afternoon-Hearing-15-November-2011.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-15-November-2011.pdf">Transcript-of-Afternoon-Hearing-15-November-2011.pdf</a>; <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Transcript-of-Afternoon-Hearing-16-November-2011.pdf">Transcript-of-Afternoon-Hearing-16-November-2011.pdf</a> </p>
 <?php footNote('A',2,30); ?> P6, p53 and p67 respectively, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/02/lev270212am.pdf">lev270212am.pdf</a></p>
 <?php footNote('A',2,31); ?> p62, <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2012/05/Transcript-of-Morning-Hearing-10-May-2012.pdf">Transcript-of-Morning-Hearing-10-May-2012.pdf</a></p>
 <?php footNote('A',2,32); ?> Ruling,  <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Ruling-on-Publication-of-Statements-7-December.pdf">Ruling-on-Publication-of-Statements-7-December.pdf</a> ; the Restriction Order made pursuant to s 19 of the Inquiries Act 2005 <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Amended-Section-19-Order.pdf">Amended-Section-19-Order.pdf</a> later amended <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Section-19-Order-26-April-2012.pdf">Section-19-Order-26-April-2012.pdf</a>; and the analysis of the circumstances in whicha newspaper published material which had been contained in a statement provided for the Inquiry: <a href="http://www.levesoninquiry.org.uk/wp-content/uploads/2011/11/Ruling-on-Publication-of-Statements-by-IoS-14-May-2012.pdf">Ruling-on-Publication-of-Statements-by-IoS-14-May-2012.pdf</a>.For the avoidance of all doubt, the purpose of these orders and rulings were to preserve the integrity of the Inquiry: Ido not consider that any of the concerns which are analysed should contribute to the conclusions that I have to reachabout the culture, practices or ethics of the press</p>
</div> 

