<div class="content" id="contentPartIChapter2">
<h1 id="top">CHAPTER 9<br/>PLURALITY AND MEDIA OWNERSHIP: CONCLUSIONS AND RECOMMENDATIONS</h1>
 <?php sectionAnchor('I',9,1); ?>Introduction</h2>
 <?php paragraphLink('I',9,1,1); ?>The Terms of Reference require me to make recommendations:
 <ol type="a">
<li>for a new more effective policy and regulatory regime which supports the integrity and freedom of the press, the plurality of the media, and its independence, including from Government, while encouraging the highest ethical and professional standards; and </li>
<li>for how future concerns about press behaviour, media policy, regulation and cross- media ownership should be dealt with by all the relevant authorities, including Parliament, Government, the prosecuting authorities and the police. </li>
</ol>
Specifically, in the context of plurality, I must therefore ensure that my recommendations would support media plurality and that I identify how concerns about cross media ownership should be dealt with, including by Parliament and Government. This does not amount to a requirement for a detailed prescription on what constitutes sufficient plurality or the technical means of achieving it. It is important to note that, within the broad constraints of the work that the Inquiry has had to undertake, there has been insufficient time to devote to a full scale review or to look in detail at these issues. My analysis and recommendations are therefore at the level of desirable outcomes and broad policy framework, rather than the technical means of achieving those outcomes.</p>
  <?php paragraphLink('I',9,1,2); ?><?php internalChapterLink('../../','C',4); ?> sets out the importance of plurality, what it means and the legislative framework in place currently to ensure sufficient plurality in the media. In this Chapter I look at the extent to which any change is required and if so, what that change should be.</p>
  <?php paragraphLink('I',9,1,3); ?>Although set out in <?php internalChapterLink('../../','C',4); ?>, it is worth repeating the goal by reference to the Ofcom definition of the desired outcome of a plural market: <ol type="a">
<li>&#8220;ensuring there is a diversity of viewpoints available and consumed across and within media enterprises; </li>
<li>preventing any one media owner or voice having too much influence over public opinion and the political agenda.&#8221;<?php footnoteRef('I',9,1); ?></li>
</ol>
 This approach to both the diversity of views available and the influence wielded seems to be generally accepted.</p>
  <h3>What are the questions that need to be answered?</h3>
 <?php paragraphLink('I',9,1,4); ?>That is more or less where the consensus ends. The Inquiry is required to recommend a regulatory and policy framework that supports plurality and to make recommendations for how future concerns in relation to cross-media ownership should be handled. These are rather partial questions in respect of plurality and do not invite or require the Inquiry to come up with a comprehensive or detailed plurality or media ownership framework.</p>
  <?php paragraphLink('I',9,1,5); ?>The questions that have emerged from the evidence are:
  <ol type="a"> 
<li>What should be considered to be the scope of any plurality policy? Does this apply just to news and current affairs or should it go wider? </li>
<li>How should plurality be measured? </li>
<li>What form should any requirements to support plurality take, and what sort of remedies should be available to deliver them? </li>
<li>Should such controls be triggered only by mergers and acquisitions or is there an argument for looking to closures and organic growth in the market? </li>
<li>Who should be responsible for measurement of plurality, decisions on whether remedies are required and decisions on what remedies to apply? The rest of this chapter seeks to answer each of these questions in turn.</li>
</ol>
</p>
  <?php sectionAnchor('I',9,2); ?>Scope</h2>
 <?php paragraphLink('I',9,2,1); ?>By &#8216;scope&#8217;, essentially, I mean the nature of the published content to which any plurality rules should relate. The media ownership rules apply at the moment to newspapers, analogue television and analogue radio. The governments of the day made it clear, in bringing forward the Broadcasting Act 1990 and the Communications Act 2003, that this was because of the scarcity of analogue spectrum and the limits that that placed on the number of channels that could be licensed. By contrast, they were clear that the same concerns would not apply in the multi-channel environment provided by digital broadcasting. In the analogue world, where there were only the Channel 3 commercial channels and Channel 5, it was obvious that the holder of any one licence would have a significant proportion of the broadcast voice. We are now in a wholly multi-channel world. Anyone with access to television in the UK now has access to over 40 channels providing a varied diet of news, entertainment, cultural output, drama and sport. Anyone with access to the internet in the UK has access to many providers of news and information, all the genres available on television and a whole host of other forms of digital content.</p>
  <?php paragraphLink('I',9,2,2); ?>Ofcom notes that both it, and other regulatory authorities, have concentrated to date on news and current affairs, but that this is not required by the legislative framework.<?php footnoteRef('I',9,2); ?> There are arguments for broadening the scope. Stephen Barnett, Professor of Communications at the University of Westminster, stressed that, in his opinion, plurality as a concept extends beyond the narrowly political to the wider cultural environment.<?php footnoteRef('I',9,3); ?> He eloquently explained why:<?php footnoteRef('I',9,4); ?></p>
<blockquote>&#8221;corporate cultures will have a direct bearing on decisions such as whether to prioritise celebrity stories, or invest in foreign news bureaux, or hire polemical columnists, or run a specific campaign (e.g. on Europe, sentencing policy in the criminal courts, or benefit levels) and [that] these in turn will impact on the national conversation. The greater number of such powerful organisations, the greater the opportunities for diversity of all forms of expression.&#8221; </blockquote>
  <?php paragraphLink('I',9,2,3); ?>Similarly, Claire Enders, founder of Enders Analysis, pointed out that because media enterprises tend to produce a mix of news and entertainment, not only is it difficult to separate them economically, but that in practice a media organisation that achieves a very large share of the entertainment market will have similarly high levels of economic power both inside and outside of that market.<?php footnoteRef('I',9,5); ?> Thus large media organisations have the power to shape the wider cultural agenda of the nation, as well as wielding significant economic power.</p>
  <?php paragraphLink('I',9,2,4); ?>It is worth looking at the issue of economic power in more detail. Many of the national newspaper groups are owned by companies or individuals with significant economic interests outside of the newspaper market. The business empires of the Barclay family, Lord Rothermere or the Lebedev family would never be capable of inclusion in any form of plurality measure. The position of NewsCorp is different because the vast majority of NewsCorp&#8217;s interests are in the media market. However, it is not obvious that all aspects of the media market will have an impact on plurality. BSkyB achieved its high proportion of television subscribers through its ability to offer exclusive access to premium sport and film content. It is difficult to see how sport coverage can have an impact on plurality of news provision, and the fact that a person can access television through a Sky box may have no impact whatsoever on what news or cultural channels they watch. Similarly, Richard Desmond owns some adult TV channels, which might be loosely considered to be in the media market but are unlikely to have any impact on plurality in the way we understand it. In order to be consistent, therefore, it is important, to consider economic power in relation only to the content that is considered relevant to plurality, not economic power more generally.</p>
  <?php paragraphLink('I',9,2,5); ?>A further point about economic power is the potential ability of a large media organisation to leverage its different distribution channels to cross promote products, or even to engage in predatory pricing in one part of the market to the disadvantage of a competitor in order to secure an advantage in another part of the market. These are real issues, though not ones for the Inquiry. I would urge both Ofcom and the Competition authorities to ensure that, when considering both plurality and competition issues in the media sector, the ways in which power is used across a media organisation&#8217;s interests is taken into account.</p>
  <?php paragraphLink('I',9,2,6); ?>The question to be addressed, then, is what content should be considered relevant to plurality. The media consultant Robin Foster agreed that there was a case for starting with a wide perspective and looking at wider cultural activity and output in the UK, as different aspects of culture and content can have an impact on the way in which we think about our society and our understanding of social and political issues. However, he concludes that in practical terms the most important focus is on news media and related current affairs, opinion and debate.<?php footnoteRef('I',9,6); ?> Similarly, Ofcom conclude that news and current affairs are the most relevant form of content for the delivery of public policy goals and they recommend that the scope of any plurality review should be limited to these.</p>
  <?php paragraphLink('I',9,2,7); ?>In his capacity as Secretary of State for Culture, Media and Sport, Jeremy Hunt adopted a similar approach, saying that he shared the view implicit in the guidance issued by the then Government in relation to the operation of the plurality provision in the 2003 Act, namely, that &#8220;plurality&#8221; should principally be concerned with the provision of news and current affairs as those are the main areas where owners could seek to influence opinions and control the political agenda.<?php footnoteRef('I',9,7); ?> As Secretary of State for Business, Innovation and Skills, Dr Vince Cable also agreed:<?php footnoteRef('I',9,8); ?></p>
<blockquote>&#8220;I apply the concept to news and current affairs primarily. There is an argument for a diversity of provision of sport, comedy, drama, religious affairs and other items and these issues are covered in significant measure by the public service obligation of terrestrial channels. But news and current affairs are different since they are of direct concern not just to the consuming public but to the functioning of democracy and the choice of governments.&#8221; </blockquote>
  <?php paragraphLink('I',9,2,8); ?>Whilst the complexity of the media market and public habits of consumption of news and entertainment make this a complex issue,</p>
  <div class="recommend">
  <p>I recommend that the particular public policy goals of ensuring that citizens are  informed and preventing too much influence in any one pair of hands over the  political process, are most directly served by concentrating on plurality in news and  current affairs. However, this focus should be kept under review.</p>
  </div>
  <?php paragraphLink('I',9,2,9); ?>The next question in relation to scope is what types of news and current affairs media are included in the measure. It is obvious that television, radio and newsprint should be included, as they are today. However, online consumption of news is already significant and is increasing, with 41% of adults in the UK regularly using the internet for news.<?php footnoteRef('I',9,9); ?> All the main UK broadcast and print news providers have an online presence, making the internet a very significant delivery channel and route to influence for them. In addition, there are new big players online, with Ofcom research showing that 19% of people who use the internet for news use Facebook and Google News.<?php footnoteRef('I',9,10); ?> In addition, of course, the internet provides access to a profusion of new, individual, smaller voices through, for example, blogs.</p>
  <?php paragraphLink('I',9,2,10); ?>Robin Foster points to the growth of news provision online, including through content aggregators, search engines, social networking sites and digital app stores, as a key development. The nature of these delivery mechanisms is such that they could, if they wished to do so, act as gatekeepers to the news that their users receive. Thus, the internet has an important role to play in distributing news to consumers but there are potential plurality risks as those models develop. Mr Foster is clear that online provision should not be ignored when considering plurality.<?php footnoteRef('I',9,11); ?></p>
  <div class="recommend">
  <?php paragraphLink('I',9,2,11); ?> Ofcom conclude that online should be included in any market assessment. I entirely  agree with this view and recommend that online publication should be included in  any market assessment for consideration of plurality.</p>
  </div>
  <?php paragraphLink('I',9,2,12); ?>Ofcom was also asked to consider whether the BBC should be included in any measure of plurality. They concluded that, as by some way the biggest provider of news, it must be included in any measure of plurality in the market, but that the governance controls in place to ensure internal plurality within the BBC, and the effect of the impartiality requirements, meant that its size gave rise to no plurality concerns. This is an interesting point. The Governance provisions of the BBC require a high degree of editorial independence within the Corporation, which, when working effectively, ensure that a diversity of voices and viewpoints from the different channels and programmes. This, perhaps, provides a model that would help to ensure plurality in relation to other large players in the media market.</p>
  <?php sectionAnchor('I',9,3); ?>Measuring plurality</h2>
 <?php paragraphLink('I',9,3,1); ?>Measuring plurality is far from straightforward. There are two outcomes sought: diversity of views, and the prevention of excessive influence, and neither is simple to measure. In relation to diversity of views, it is necessary not just to look for a proliferation of different voices but also for consumption of different voices. The measure must therefore include both a simple count of the number of voices available and some measure of the extent to which these voices are heard or consumed. In relation to excessive influence, the search must be some measure not just of how many people are exposed to the voice but also the extent of the influence that it has; this may depend on the audience reached, the trust they repose in it and the number of other sources that they consult.</p>
  <?php paragraphLink('I',9,3,2); ?>Ofcom was asked by the Secretary of State to set out options for measuring media plurality across platforms and to recommend the best approach.<?php footnoteRef('I',9,12); ?> They considered three different types of metrics: availability, consumption and impact. The first conclusion is that availability metrics &#8211; the number and range of titles and providers &#8211; have a role to play in measuring plurality but offer limited insight and on their own are not sufficient.<?php footnoteRef('I',9,13); ?></p>
  <?php paragraphLink('I',9,3,3); ?>Ofcom considered five different types of consumption metrics: the volume of consumption (how much time a consumer spends consuming the relevant content); cross-media consumption (the extent to which a single provider&#8217;s sources are consumed across the different media); revenue (a basic market share measure); reach (a measure of those who are exposed to the content) and multi-sourcing (a measure of how many sources a consumer uses).<?php footnoteRef('I',9,14); ?></p>
  <?php paragraphLink('I',9,3,4); ?>Of these Ofcom concludes that revenue is not particularly helpful, as most measures of revenue do not distinguish news and current affairs from other programming, and there is, in any case, a less direct relationship between revenue and influence than between revenue and economic power.<?php footnoteRef('I',9,15); ?></p>
  <?php paragraphLink('I',9,3,5); ?>In the event, Ofcom propose a complex set of measures based around share of consumption, which they believe provides a good proxy for measuring influence in the news media market, and reach and multi-sourcing, which provide a good proxy for measuring the diversity of viewpointsconsumed.<?php footnoteRef('I',9,16); ?> Claire Enders prefers a measure of share of consumption, arguing that the other measures have less value.<?php footnoteRef('I',9,17); ?> Mr Foster endorses Ofcom&#8217;s proposals on measurement but suggests, in addition, that more work be done on how to compare consumption across different media on a more consistent basis. Mr Foster also urges that a better understanding be developed of how audiences use their different sources of news and how they use news sources to form their views on matters of public debate.<?php footnoteRef('I',9,18); ?></p>
  <?php paragraphLink('I',9,3,6); ?>Ofcom&#8217;s consumption measure would be supplemented by a measure of impact. There is no single proxy for impact and Ofcom suggest that the importance that users attach to news sources, and their perceptions of the impartiality, reliability and quality of the news provided should be taken into account.<?php footnoteRef('I',9,19); ?> Ofcom also argue that contextual factors should also be taken into account. These include regulation and oversight; governance models; internal plurality; and the potential power or editorial control exerted by owners within commercial organisations.<?php footnoteRef('I',9,20); ?></p>
  <?php paragraphLink('I',9,3,7); ?>In relation to online news providers, Ofcom suggest that the share, and possibly reach, of the top news websites would be the best measure to use currently, and that, in any review of the measurement framework, the suitability of online measures should be looked at.<?php footnoteRef('I',9,21); ?></p>
  <?php paragraphLink('I',9,3,8); ?>It is clear that there is no single measure that will provide an adequate picture of plurality. The Ofcom model is complex and includes all the measures that have been put forward. In addition, Ofcom suggests that the measurement framework itself should be assessed regularly to ensure that it continues to capture the key elements of plurality.<?php footnoteRef('I',9,22); ?></p>
  <?php paragraphLink('I',9,3,9); ?>Ofcom have set out a comprehensive approach that is likely to provide as good a picture of the plurality in the media market as can be derived. However, its complexity is also a disadvantage, in that it will be difficult for most people to understand and could come under sustained attack from those media providers who feel that they may be the subject of plurality concerns. In that context it is significant that BSkyB objected to that methodology, used by Ofcom, in the public interest test on the NewsCorp/BSkyB bid.</p>
  <div class="recommend">
  <p>I recommend that Ofcom and the Government should work, with the industry, on  the measurement framework, in order to achieve as great a measure of consensus  as is possible on the theory of how media plurality should be measured before  the measuring system is deployed, with all the likely commercial tensions that will  emerge.</p>
  </div>
  <?php sectionAnchor('I',9,4); ?>Limits and remedies</h2>
 <?php paragraphLink('I',9,4,1); ?>If agreement can be reached on what is meant by plurality, plurality of what and how to measure that plurality, the next question is what constitutes sufficient or adequate plurality and what can or should be done to ensure maintenance of sufficient or adequate plurality.</p>
  <h3>Caps on market share</h3>
 <?php paragraphLink('I',9,4,2); ?>The starting point for some of the witnesses to the Inquiry has been that there should be a fixed limit on the percentage of revenue of the total cross-media market. Specifically, Ms Enders suggests that no single company should be able to acquire more than 15% of the media market by revenue.<?php footnoteRef('I',9,23); ?> In this context she defines the media market as including: national and regional newspapers; consumer magazines; video games; television advertising; television subscription fees; books (both physical and digital); cinema; video/DVD rental and purchase; internet subscriptions; internet advertising; and radio advertising.<?php footnoteRef('I',9,24); ?> In oral evidence Ms Enders explained that neither the 15% limit nor the market definition were specific proposals, but were rather designed as a starting point for discussion.<?php footnoteRef('I',9,25); ?></p>
  <?php paragraphLink('I',9,4,3); ?>Ms Enders said that the market definition was:<?php footnoteRef('I',9,26); ?>
<blockquote>&#8220;trying to draw a media market, not actually a market for plurality purposes.&#8221; </blockquote>It is interesting that, having said that a consumption measure was the best measure of plurality, her proposed solution depends entirely on a measure of revenue. She explained that her proposition was really about getting a debate started on how many big media players would be the right number for the UK. A limit of 15% would require at least 7 major players (or a very large number of small players). A limit of, 25% would allow consolidation to only 4 big media actors.<?php footnoteRef('I',9,27); ?> Ms Enders clarified that, to the extent that the idea of the cap was a proposal, the intention would be that it should operate in relation to mergers and acquisitions, not to organic growth.<?php footnoteRef('I',9,28); ?></p>
  <?php paragraphLink('I',9,4,4); ?>The Rt Hon Jeremy Hunt MP told the Inquiry that it was important that the approach to plurality should not stifle innovation or growth in the sector. One option would be to prescribe specific limits for media and cross-media ownership, but the regulator would need flexibility in operating them, whilst still providing sufficient certainty to business in order to encourage investment.<?php footnoteRef('I',9,29); ?></p>
  <?php paragraphLink('I',9,4,5); ?>The Rt Hon Harriet Harman MP suggested that there could be a cap on the percentage of revenue of the UK&#8217;s total cross media market that any one company or individual would be allowed to own, and that there should be a restriction, for example 30%, on the proportion of newspaper circulation that could be in the hands of one organisation.<?php footnoteRef('I',9,30); ?> In addition to the idea of a fixed upper cap Ms Harman suggested that transactions leading to a holding of between 20% and 30% of newspaper circulation should be subject to Ofcom approval and possible conditions.<?php footnoteRef('I',9,31); ?></p>
  <?php paragraphLink('I',9,4,6); ?>The Rt Hon Nick Clegg MP said that he was open to a percentage cap, or a figure at which an investigation might be triggered, but that he imagined that such a measure would prove difficult to define.<?php footnoteRef('I',9,32); ?> Similarly, the Rt Hon Dr Vince Cable MP felt that the current plurality test was too imprecise. He suggested that it might be possible to specify a limit, such as 25% of combined media markets, beyond which a plurality test should be applied.<?php footnoteRef('I',9,33); ?></p>
  <?php paragraphLink('I',9,4,7); ?>However, Ofcom take the view that absolute limits or prohibitions on market share, that would require automatic divestment if breached, leave no room for flexibility and give rise to the risk that it is not possible to address issues of commercial sustainability and innovation in an appropriate manner. They argue that such an interventionist approach should only be applied in a targeted manner to those issues of greatest concern.<?php footnoteRef('I',9,34); ?></p>
  <?php paragraphLink('I',9,4,8); ?>As well as a media-wide limit as suggested by Ms Enders, Ofcom consider the case for platform specific limits in relation to newspapers and television. In relation to newspapers, the Ofcom report notes that limitations on a declining market run counter to the need for newspaper groups to build market share in order to survive. In relation to television, the report suggests that the existing impartiality rules, and the existence of the BBC under public ownership, deliver sufficient regulation for impartiality and that a platform specific cap would have limited impact.<?php footnoteRef('I',9,35); ?></p>
  <h3>Sufficiency</h3>
 <?php paragraphLink('I',9,4,9); ?>Ofcom propose that, instead of fixed caps, there should be a concept of sufficiency of plurality against which to conduct a market review. Unlike a cap, a concept of sufficiency would not be precise. Ofcom suggest that a first step could be to set it out in qualitative terms:<?php footnoteRef('I',9,36); ?></p>
 <blockquote>
 <ol type="a">
<li>&#8220;There is a <u>diverse range of independent news media voices</u> across all platforms. </li>
<li>Overall <u>reach and consumption is relatively high</u> among all consumer demographics and across all of the UK&#8217;s nations and English regions. </li>
<li><u>Consumers actively multisource</u> &#8211; such that the large majority of individuals consume a range of different news sources. </li>
<li>Sufficiently low <u>barriers to entry</u> and competition between providers spurs quality and innovation in the gathering and dissemination of news. </li>
<li>Overall <u>investment and commercial returns</u> are sufficiently high to ensure sustainability, and guarantee high quality coverage, extensive newsgathering and investigative journalism. </li>
<li><u>No organisation or news source has a share of consumption</u> that is so high as to create a risk that consumers are exposed to a narrow set of viewpoints.&#8221;</li>
</ol>
</blockquote>
  <?php paragraphLink('I',9,4,10); ?>The report goes on to suggest that it may be possible to develop a set of the levels of each of the metrics to be used in measuring plurality that would provide an indication of a plurality concern. These would not be limits, but they would provide a degree of clarity to the market as to what levels of concentration would be likely to give rise to such concerns.<?php footnoteRef('I',9,37); ?></p>
  <?php paragraphLink('I',9,4,11); ?>Ms Enders also looks at what might be sufficient plurality. She quotes Professor Charlotte Brewer as concluding that &#8216;plurality&#8217; unambiguously meaning &#8216;a large number&#8217; and not a number more than one.<?php footnoteRef('I',9,38); ?> Ms Enders goes on to say that &#8220;when we talk of &#8216;plurality&#8217; we are talking of a profusion, a multiplicity and an abundance ,&#8221; and that it is reasonable to assume that Parliament had this in mind when the legislation was passed.<?php footnoteRef('I',9,39); ?></p>
  <?php paragraphLink('I',9,4,12); ?>Whether the approach involves a fixed limit or an indicative level, there needs to be some way of identifying the point at which concerns arise. Other than the 15% figure offered, but not defended, by Ms Enders, there have been no suggestions as to what level of plurality is sufficient. It will certainly be different in different markets: for example, in the many regions that have only one local newspaper, it is generally accepted that one is better than none and no remedies are applied to what is, by default, a monopoly position. The Inquiry has no basis on which to reach a conclusion on what constitutes sufficient plurality, though it seems reasonable to conclude that concerns about plurality would arise at lower levels of concentration than concerns about competition.</p>
  <h3>Structural remedies</h3>
 <?php paragraphLink('I',9,4,13); ?>Ofcom note that structural remedies offer clarity and certainty, can deliver long term benefits and do not require ongoing monitoring. They also note that such remedies may be ineffective if the divested interests are commercially unsustainable. Structural remedies can act as a disincentive to investment and innovation and represent a significant regulatory intervention and impose potentially significant transition and transaction costs on the parties concerned.<?php footnoteRef('I',9,40); ?></p>
  <h3>Behavioural remedies</h3>
 <?php paragraphLink('I',9,4,14); ?>Mr Foster suggests that it would be better to move away from structural remedies, such as caps on market share, and towards behavioural remedies. These could include requirements to invest in content; requirements to make space available for the inclusion of alternative viewpoints; effective right of reply procedures; and independent editorial boards.<?php footnoteRef('I',9,41); ?></p>
  <?php paragraphLink('I',9,4,15); ?>Ofcom identify three different forms of behavioural remedies that could be used. First, there are behavioural rules that may help to increase levels of internal plurality, for example by ensuring editorial independence for specific titles, channels or programmes. This approach may be less intrusive and more proportionate than structural remedies but would require complex ongoing monitoring and it does not have a particularly good reputation for effectiveness.</p>
  <?php paragraphLink('I',9,4,16); ?>Second, Ofcom point to behavioural remedies that improve standards. This might include requirements on fairness, or accuracy and completeness in what is reported. This approach would be objective and well understood, but would also require ongoing monitoring and there is a risk that such remedies, if applied too widely, would reduce diversity in content.</p>
  <?php paragraphLink('I',9,4,17); ?>Finally, Ofcom consider behavioural remedies to improve access. Must-carry obligations could require a distribution platform to distribute the content of news providers meeting specific criteria, while must-offer obligations could be used to ensure that news providers distribute their content via any platform meeting specified criteria. This is a good remedy to address specific concerns about discrimination by gatekeepers. It is unlikely to require active monitoring as those entitled to access will complain if it is not complied with. However, this approach can be susceptible to gaming and can become outdated in the light of market developments.<?php footnoteRef('I',9,42); ?> Robin Foster also considered access remedies, though specifically in the context of digital intermediaries. He suggested that a mixture of a guarantee that content would not be blocked, must-carry provisions, and an audit mechanism of some sort, might be considered should any relevant plurality concerns be identified.<?php footnoteRef('I',9,43); ?></p>
  <h3>Positive interventions to encourage more news provision</h3>
 <?php paragraphLink('I',9,4,18); ?>In addition to remedies designed to control excessive influence, Ofcom note that there is an option of taking action to encourage more news provision. This could take the form of public funding of news provision or placing obligations in relation to news and current affairs on existing providers in return for some benefit. The most obvious examples of this approach are the BBC and the public service broadcasting content obligations on Channel 3 and 5 licence holders. Remedies of this sort are particularly appropriate where commercial provision of the content required is not sustainable. Ofcom note that this approach does not penalise success as any of the structural or behavioural remedies might and, furthermore, could be a good way of promoting plurality. However, it would require both public funding and very careful design to minimise the effect of subsidies on market-based provision.<?php footnoteRef('I',9,44); ?> Professor Curran also sets out proposals for a system of funding for areas of the media underserved by the market.<?php footnoteRef('I',9,45); ?></p>
  <?php paragraphLink('I',9,4,19); ?>The argument for mechanically applied fixed caps or limits does not seem to me to be made out. Given the importance of having both public consensus on what constitutes sufficient plurality and sufficient clarity in the market to encourage investment, it would be sensible for Ofcom to carry out a consultative process designed to identify indicative levels of the various metrics that they are proposing to use that would give rise to plurality concerns. I am neither qualified, nor required, to give my own view on what such levels should be, and I have no intention of doing so. I do, however, accept that the importance of plurality of news and current affairs provision is a qualitatively different issue to those arising from general competition concerns.</p>
  <div class="recommend">
  <p>I therefore recommend that the levels of influence that would give rise to concerns in  relation to plurality must be lower, and probably considerably lower, than the levels  of concentration that would give rise to competition concerns.</p>
  </div>
  <div class="recommend">
  <?php paragraphLink('I',9,4,20); ?> Ofcom has presented the Inquiry and the Government with a full menu of potential  remedies, and I have not seen any arguments to suggest that any of them are  inappropriate in principle. Each of them might be appropriate in a given set of  circumstances and I recommend that the relevant regulatory authority should have  all of them in its armoury.</p>
  </div>
  <p> I can see that this might be difficult, because of the funding implications, in relation to measures actively to promote plurality. I am particularly drawn to behavioural remedies that would enforce standards, not least because it could add force to other aspects of standards covered in this Report. There are strong arguments for requiring a news provider with a substantial market share to ensure editorial independence both from the proprietor or owner and between titles or media outlets as a means of protecting plurality. There are also respectable arguments for requiring a news provider with a large share of consumption to adhere to accuracy standards and perhaps to have strong internal governance mechanisms to ensure that the organisation meets the highest standards of journalism, thus protecting the public, both as consumers of news and as potential subjects of reporting. It is, of course, possible that one way for an organisation to demonstrate that it was meeting any such requirement would be for it to be a member of a recognised self-regulatory body that required the same standards, and requiring such membership might form part of a package of remedies.</p>
  <?php sectionAnchor('I',9,5); ?>What should trigger a review?</h2>
 <?php paragraphLink('I',9,5,1); ?>Under the Communications Act 2003 the public interest in plurality can only be invoked when a relevant merger or takeover occurs. Ofcom provided advice to the Secretary of State as part of its Public Interest Test in relation to the BSkyB/NewsCorp merger that the current regime might no longer be equipped to deliver Parliament&#8217;s policy objective of ensuring sufficient plurality of media ownership because it was not capable of responding to certain types of market development such as market exits or organic growth.<?php footnoteRef('I',9,46); ?></p>
  <?php paragraphLink('I',9,5,2); ?>This concern about the need for the plurality regime to be able to take organic growth into account was echoed by other witnesses. Harriet Harman proposed both that Ofcom should carry out a regular plurality review,<?php footnoteRef('I',9,47); ?> and that it should have the power to ask the Competition Commission to instigate a review in between regular reviews should an issue of monopoly arise.<?php footnoteRef('I',9,48); ?></p>
  <?php paragraphLink('I',9,5,3); ?>Mr Clegg expressed a concern that the plurality considerations in the Communications Act 2003 are only triggered at the point of a merger or acquisition. He regards this as a significant gap in the protection of plurality as:<?php footnoteRef('I',9,49); ?></p>
<blockquote>&#8220;size isn&#8217;t just determined at the point of a transaction. It can, if you like, creep up on you through the success of a particular media group just increasing its market share.&#8221; </blockquote>
  <?php paragraphLink('I',9,5,4); ?>He suggested that it might be better to have a mechanism to allow an independent regulator to trigger a market review by the Competition Commission, taking into account plurality concerns.<?php footnoteRef('I',9,50); ?></p>
  <?php paragraphLink('I',9,5,5); ?>The Secretary of State asked Ofcom to consider what could trigger a plurality review in the absence of a merger. Ofcom identified two different potential types of trigger: a metric-based trigger, which would require a review to be carried out if a particular metric was breached; and a time-based trigger, which would require a review to be carried out automatically on a periodic basis.<?php footnoteRef('I',9,51); ?> A metric-based trigger would require agreement on both the metrics to be used and the level at which the trigger would act. Ofcom concluded that the complexity involved in setting a metric-based trigger was such that a time-based trigger would be better, providing a high degree of simplicity, transparency and certainty to the market.<?php footnoteRef('I',9,52); ?> In order to ensure that reviews take place sufficiently often to pick up significant changes, and with a sufficient gap to avoid the risk of a perpetual review cycle, Ofcom propose that regular media plurality reviews should take place every four or five years.<?php footnoteRef('I',9,53); ?></p>
  <?php paragraphLink('I',9,5,6); ?>Ofcom also considered whether event-based triggers, such as the closure of a media outlet, should be used. On the one hand, the effects of a closure may take some time to become apparent in the market. On the other hand, if an exit occurred soon after a periodic review the effects might not come under scrutiny for some time. Ofcom conclude that there might be merit in introducing an exit trigger if an appropriate mechanism can be designed.<?php footnoteRef('I',9,54); ?></p>
  <?php paragraphLink('I',9,5,7); ?>Ofcom also considered whether the existing merger-based trigger should remain. This raises questions about the risk of merger-based and time-based reviews overlapping. Ofcom also point out that, under the current regime, Ministers have discretion over whether a merger- based plurality review should take place or not. Again, this would need further thought in a system otherwise based around an automatic time-trigger.<?php footnoteRef('I',9,55); ?></p>
  <?php paragraphLink('I',9,5,8); ?>Finally, Ofcom considered whether they, or Ministers, should have discretion to trigger a review. The advantage of allowing discretion is that it introduces some flexibility into the system and provides the potential to target a review on a particular concern. The disadvantage is that discretion has the potential to be subjective and can lead to excessive lobbying and market uncertainty. Ofcom recommended against allowing either Ministers or the regulator to have discretion to trigger a review as long as a provision is introduced for periodic reviews every four or five years.<?php footnoteRef('I',9,56); ?></p>
  <h3>Alternative approach using the Competition Regime</h3>
 <?php paragraphLink('I',9,5,9); ?>There is also another possible approach to how and when to carry out a review. The Enterprise and Regulatory Reform Bill (ERR), currently before the House of Lords, makes changes to how public interest issues are to be dealt with in the context of markets (as opposed to mergers). This has the potential to be another way of addressing the issue of plurality concerns that could arise as a result of organic growth rather than a specific transaction.</p>
  <?php paragraphLink('I',9,5,10); ?>Where there are competition concerns about a market, or across markets, the Competition Commission can instigate a market study, which will look at whether there are competition issues in the market that need to be addressed. Under the new regime, if the Secretary of State considers that there may also be a public interest issue in the market he will be able to issue a public interest intervention notice which would have the effect of requiring the Competition and Markets Authority (CMA) to include the public interest issues in their market study report to the Secretary of State.</p>
  <?php paragraphLink('I',9,5,11); ?>When the Secretary of State receives the market study report, he or she is then in a position to decide if the public interest issue is relevant. If not the CMA proceeds as for an ordinary reference. If the public interest (PI) issue is relevant then the Secretary of State has three options. The first is that a &#8216;restricted PI reference&#8217; can be made, meaning that the CMA would look at the competition issues only, leaving the Secretary of State to make his own assessment of the PI issues. Secondly, a full PI reference can be instituted, meaning that the CMA looks at both competition and PI issues and makes recommendations on remedies. Finally, a full PI reference can be made and a PI expert, or experts, can be appointed to look at the PI issues and feed into the CMA report. The CMA report would then cover both competition and PI issues, taking account of the expert advice, and recommend remedies. In all these cases the Secretary of State is required to accept the CMA&#8217;s findings in respect of the competition issues but has the discretion to make a decision on whether to make a public interest finding and, if so, what remedies to implement. If the CMA concludes that there are no competition issues that require further examination, the matter goes no further.</p>
  <?php paragraphLink('I',9,5,12); ?>As currently drafted in the ERR Bill this regime has no application to media plurality. The only public interest issue that can be raised by the Secretary of State in relation to a markets investigation is national security. However, it would be possible for the need for media plurality to be introduced as an additional public interest issue. This would allow the CMA to look at media markets from a plurality perspective at any point when competition issues arise, and would ensure that the full range of competition remedies were available to deal with any problems identified. Such remedies could, for example, include a requirement to be a member of a recognised regulatory body.</p>
  <?php paragraphLink('I',9,5,13); ?>The potential disadvantage is that this process relies on the existence of a competition problem before the Secretary of State can take action to remedy a plurality concern. Given that I have accepted the argument that plurality is likely to become a matter for concern at lower levels of concentration than would necessarily give rise to competition concerns, it is also possible that relying on an approach of this sort could allow excessive loss of voice because a competition threshold was not breached. I also note that Ofcom argued that there would be market benefits from a regular plurality review, rather than a power to review when necessary, because of the risk of market uncertainty from ad-hoc reviews and the extremely political nature of the issue that would lead to constant lobbying for a review, recognising that the proposal for a regular plurality review is more closely focussed on plurality issues.</p>
  <h3>Conclusions on plurality reviews</h3>
 <?php paragraphLink('I',9,5,14); ?>These are largely technical regulatory issues on which I see no need to reach a definitive view. The need to have a mechanism to take account of organic growth and market exists seems unarguable, but the precise mechanism for doing so is essentially a technical issue on which the Inquiry is not best placed to reach a definitive conclusion. Ofcom&#8217;s suggestions about the nature of triggers for a review and the need for a regular review of plurality seem sensible. The possibility of using the competition regime may equally have merit. It does seem to me unlikely that the two regimes could co-exist without causing considerable uncertainty and the risk of competing reviews, run by different bodies, coming up with different recommendations. </p>
 <div class="recommend">
 <p>I therefore recommend that the Government should consider whether periodic  plurality reviews or an extension to the public interest test within the markets regime  in competition law is most likely to provide a timely warning of, and response to,  plurality concerns that develop as the result of organic growth recognising that the  proposal for a regular plurality review is more closely focussed on plurality issues.</p>
 </div>
  <?php sectionAnchor('I',9,6); ?>Who should be responsible for decisions?</h2>
 <?php paragraphLink('I',9,6,1); ?>Potentially the most significant of the questions on plurality is who should be responsible for decisions on what happens and when. Many of the politicians who gave evidence to the Inquiry had a view on this, some, of course, speaking from recent experience of the difficulties that the involvement of politicians in such decisions can give rise to. The majority view was that the very fact that plurality is a public interest consideration makes it important that Ministers continue to have the decision taking role.</p>
  <?php paragraphLink('I',9,6,2); ?>The Rt Hon Ed Miliband MP said:<?php footnoteRef('I',9,57); ?></p>
<blockquote>&#8220;My suggestion on this &#8211; I have a concrete suggestion on this &#8211; is that &#8211; I believe that there is a case for saying that if a politician wants to depart from the recommendations of the Competition Commission or Ofcom, whoever it is, that decision should be challengable by appeal. So in other words, if I&#8217;m the minister and I get recommendations from the Competition Commission that a bid should be blocked or should go ahead, and I take a different view, then there should be recourse to the Competition Appeals Tribunal to say not simply was it a reasonable decision but on the merits.&#8221; </blockquote>
  <?php paragraphLink('I',9,6,3); ?>Mr Clegg said:<?php footnoteRef('I',9,58); ?></p>
<blockquote>&#8220;So I think there is a big case to tighten up the remit given to a Secretary of State, but I nonetheless think at the end of the day it is a good thing in a Parliamentary democracy to have people who are accountable to Parliament who have to explain why that decision was taken and inasmuch as they have any discretion within what I hope will be tighter definitions, why they chose to exercise discretion one way or the other.&#8221; </blockquote>
  <?php paragraphLink('I',9,6,4); ?>Dr Cable also felt that politicians should have a role to play in these decisions:<?php footnoteRef('I',9,59); ?></p>
<blockquote>&#8220;I think it&#8217;s right that politicians are involved &#8211; elected politicians are involved in the process. As we described the first stage of my interview, there is a series of checks and balances built in, there is a major role for the regulators, but elected politicians, ministers, have a role in the process, and I think that&#8217;s absolutely right. I think it&#8217;s right because when we&#8217;re talking about matters of public interest, we&#8217;re making qualitative judgments. We&#8217;re not following a sort of quantitative metric, which is what one would normally do with, say, a competition case, and I think it&#8217;s right that those decisions be made by people who are &#8211; have legitimacy through the democratic process, who are accountable to Parliament.&#8221;<?php footnoteRef('I',9,60); ?> 
<br/>I think where we do have a genuine public interest choice to make, I think it is appropriate in a democracy that we involve the politicians rather than some kind of platonic guardians who are in some sense isolated from the political process.&#8221; </blockquote>
  <?php paragraphLink('I',9,6,5); ?>Mr Hunt, however, took a rather different view:<?php footnoteRef('I',9,61); ?></p>
<blockquote>&#8220;There is an argument that politicians should make decisions on media plurality because any such decision is, by its nature, more subjective than an economically based competition test. There is also a view that because of the importance of media plurality decisions should only be taken by elected politicians. I do not share this view. This is not because I believe it is impossible for politicians to act in an impartial manner &#8211; I believe I did. But even when they do it is almost impossible to persuade elements of the public that justice is being done and being seen to be done. I note that decisions on competition issues where there are no public interest considerations are now no longer taken by the politicians but by independent regulators, presumably to address the same issue. I believe serious consideration should be given to adopting the same approach with respect to decisions on media plurality.&#8221; </blockquote>
  <?php paragraphLink('I',9,6,6); ?>Mr Hunt, as Secretary of State for Culture, Media and Sport, asked Ofcom to consider what alternatives exist in relation to who should take the final decisions in relation to, for example, the application of remedies.<?php footnoteRef('I',9,62); ?> Ofcom refrained from providing a view on this matter, considering, very properly, that it is a matter for Parliament to decide, not for a regulator to opine on. The current regime places the trigger for a plurality review in the hands of the Secretary of State, who then has to take a decision on whether or not to refer the merger to the Competition Commission for a second stage review. The Secretary of State is also responsible, having received advice from the Competition Commission, for making a finding on whether the merger would operate against the public interest and whether to impose remedies and what those remedies should be.</p>
  <?php paragraphLink('I',9,6,7); ?>Ofcom take the view that, in relation to public interest merger reviews, it is important to retain a discretionary trigger in order to minimise the burden on industry. The report, however, sits firmly on the fence as to whether that trigger should be in Ministerial hands or elsewhere. On the one hand, it is argued, where a decision requires a high degree of judgement it may be more appropriate for a democratically-elected decision-maker to exercise the discretion rather than a regulatory body. This, says Ofcom, is a choice for Parliament to make.<?php footnoteRef('I',9,63); ?></p>
  <?php paragraphLink('I',9,6,8); ?>Along with other aspects of this Report, I agree that this is a choice for Parliament to make. However, bearing in mind the context within which this part of the Inquiry has been conducted, I consider that it is appropriate that I express a view for the Government and Parliament to consider. The public interest process relating to the NewsCorp/BSkyB merger has certainly demonstrated just how pressured the role of decision-maker is in this context. The volume of lobbying on both Secretaries of State involved, principally from NewsCorp but also from the coalition (known as the Alliance) ranged against the merger, was immense. The highly politicised nature of these decisions, precisely because they deal with media owners, means that they are always likely to be made in a fraught environment.</p>
  <?php paragraphLink('I',9,6,9); ?>Arguments have been made that every politician will have what might be termed baggage (whether as a result of prior dealings with the press or otherwise) in relation to the media market that could make them unable to carry out a quasi judicial function in this regard. First, I do not accept the assumption behind this proposition. Certainly, politicians may well have strong views in relation to the media market (as on many other issues), but it is entirely conceivable that they can put all irrelevant matters aside and exercise a quasi-judicial role in relation to the public interest: in relation to a large number of issues, it would be very disturbing if they could not. Second, it is surely false to hope that if the decision were to be remitted to a regulator, that the regulator would not also have similarly strong views. It is in the nature of large media organisations that every one of us is exposed to their output on a regular basis and we all have views (and, in some cases, perhaps prejudices) that might affect such a decision if allowed to do so.</p>
  <?php paragraphLink('I',9,6,10); ?>It seems to me that those who argue that a public interest decision is rightly for a democratically-elected decision-maker are right. It is that person who is accountable to Parliament and the electorate: that is the nature of our constitutional arrangements. However, having said that, it is equally clear that the current system is less than ideal. The experience of the NewsCorp/ BSkyB merger shows nothing if it does not reveal that fact. Under the current regime the Secretary of State makes his first referral decision without the benefit of any formal advice. Thereafter, advice is available from the independent regulators to provide a guide through the subsequent decisions.  </p>
  <div class="recommend">
  <p>I recommend that, before making a referral decision, the Secretary of State should  consult relevant parties as to the arguments for and against a referral, and should be  required to make public his reasons for reaching a decision one way or the other. This  would provide a buffer against the criticism that a referral might be made for purely  political reasons, and offer a welcome degree of transparency as to the concerns that  have led to any referral.</p>
  </div>
  <div class="recommend">
  <?php paragraphLink('I',9,6,11); ?> In relation to subsequent decisions, I recommend, likewise, that the Secretary of State  should remain responsible for public interest decisions in relation to media mergers.  However, as with the first stage, there would be an advantage in introducing a degree  of further transparency to the process. At present the Secretary of State simply  receives advice from Ofcom and the Competition Commission and then makes a  decision. I recommend that the Secretary of State should be required either to accept  the advice provided by the independent regulators, or to explain why that advice has  been rejected. At the same time, whichever way the Secretary of State decides the  matter, the nature and extent of any submissions or lobbying to which the Secretary of State and his officials and advisors had been subject should be published: the fact of having to record such contacts would itself act as a restraint both upon lobbyists and politicians and serve to remind each of the quasi-judicial nature of the decision being made.</p>
  </div>
  <?php paragraphLink('I',9,6,12); ?>On the surface, this might not appear to make much change to the current provision, but I believe that it does. If the Secretary of State is required to articulate and publish the submissions received and also the reasons for rejecting the independent advice of the regulator, thereby giving the opportunity to those adversely affected by the decision, if so advised, to mount a challenge by way of judicial review, it will ensure both the highest standards of probity and that a very rigorous test is applied to the reasoning behind the eventual position. This would not prevent a Secretary of State from rejecting the advice of the independent regulators if he or she believes, and can demonstrate and articulate, that it is in the public interest to do so, but it would require a real and convincing public interest explanation to exist.</p>
  </div>

