<?php 
require_once('../../common.php');
levesonHeader('I',9); 
levesonNav('../../');
levesonBread('I',9);
require_once('content.php');
levesonFooterNav('I',9); 
require_once('footnotes.php');
LevesonCommonFooter();
?>