<div class="content" id="contentPartEChapter2">
<h1 id="top">CHAPTER 3<br/>OPERATION MOTORMAN</h1>
 <?php sectionAnchor('E',3,1); ?>Introduction</h2>
 <?php paragraphLink('E',3,1,1); ?>The information arising from Operation Reproof caused the Office of the Information Commissioner (ICO) to focus attention on Steve Whittamore. As a result, on 8 March 2003, a team of investigators led by Alexander Owens from the ICO, and alongside police officers from Operation Reproof, searched the premises of the private detective agency run by Mr Whittamore. They seized a significant volume of documentation detailing an extensive trade in personal information. Mr Owens and his team then undertook a comprehensive analysis of the seized material and observed a clear audit trail between the requests, supply and payment for personal information relating to a range of subjects. The customers requesting and being supplied with personal information included a significant number of journalists, employed by a range of newspaper and magazine titles.</p>
  <?php paragraphLink('E',3,1,2); ?>Ultimately, the implications of this material were of sufficient significance that the ICO was prompted to lay before Parliament two reports setting out a summary of the evidence obtained as part of the investigation: <em>What Price Privacy?</em> and <em>What Price Privacy Now?</em> The reports also called for stricter penalties for those engaged in unlawful activities, in particular for breach of s55 of the Data Protection Act 1998 (DPA). This provision makes it an offence to obtain, disclose or procure the disclosure of confidential personal information, knowingly or recklessly, without the consent of the organisation holding the data.<?php footnoteRef('E',3,1); ?> This chapter explores the essential narrative surrounding this investigation and the evidence obtained during Operation Motorman.</p>
  <?php sectionAnchor('E',3,2); ?>The genesis of Operation Motorman</h2>
 <?php paragraphLink('E',3,2,1); ?>On 11 November 2002, during the course of the search of the premises of Data Research Ltd, as part of Operation Reproof, Mr Owens observed documents containing lists of Vehicle Registration Marks (VRMs) that appeared to have been checked for vehicle owners&#8217; personal details.<?php footnoteRef('E',3,2); ?> The documents recorded the owners&#8217; details alongside the VRMs and also contained times and dates when the searches had been carried out. Mr Owens contacted the Driver and Vehicle Licensing Agency (DVLA) with a number of the listed VRMs and the DVLA confirmed that all the numbers has been searched through the DVLA records by the same employee. Mr Owens also confirmed that the times and dates recorded on the seized documents corresponded with the times and dates when the DVLA records had been checked.<?php footnoteRef('E',3,3); ?> In the light of these facts, Mr Owens formed the view that a source within DVLA had been supplying information on request to the detective agency.<?php footnoteRef('E',3,4); ?> Further examination of the documents seized revealed that several hundreds of VRMs had been checked by the detective agency, and the results sold on to a number of companies and individuals.<?php footnoteRef('E',3,5); ?></p>
  <?php paragraphLink('E',3,2,2); ?>These discoveries led to two investigations. The ICO commenced Operation Motorman to investigate data protection offences and, in particular, to identify the customers of the agency who had commissioned the supply of information and the reasons why personal information of this nature had been sought.<?php footnoteRef('E',3,6); ?> Thereafter, the Metropolitan Police Service (MPS) commenced Operation Glade to identify potential corruption by police officers or civilian police employees.<?php footnoteRef('E',3,7); ?></p>
  <?php paragraphLink('E',3,2,3); ?>On closer examination of the documents seized from the premises of Data Research, Mr Owens observed that one of the VRM checks had been made against a &#8220;protected number&#8221;. Having previously served as a Special Branch police officer, Mr Owens appreciated that a protected number was likely to signify a vehicle owned by a sensitive individual or an undercover police vehicle. This was confirmed by the MPS and Mr Owens identified Mr Whittamore and his company, JJ Services, as having sought the information in relation to this vehicle. As a result of this, Mr Owens explained, &#8220;Stephen Whittamore immediately went to number 1 on [his] investigation list to be visited and interviewed.&#8221;<?php footnoteRef('E',3,8); ?> The ICO identified Mr Whittamore as a private detective running a business from his home address and, as has been explained above, on Saturday 8 March 2003, five ICO investigators searched Mr Whittamore&#8217;s premises pursuant to a search warrant issued under Schedule 9 of the DPA.<?php footnoteRef('E',3,9); ?></p>
  <?php sectionAnchor('E',3,3); ?>The search</h2>
 <?php paragraphLink('E',3,3,1); ?>A significant volume of documentation was seized during the search of Mr Whittamore&#8217;s premises. This included reports, workbooks, ledgers, invoices and in particular four hardback coloured notebooks which have become known as the &#8220;Blue book&#8221;, &#8220;Red book, &#8220;Green book&#8221; and &#8220;Yellow book&#8221;. These notebooks represented all the work that Mr Whittamore had done, and set out precise dealings between Mr Whittamore and his customers, including a number of journalists. The workbooks documented who had requested the personal information (both in terms of the newspaper concerned and the commissioning journalist), what information had been requested and supplied, how much had been charged for obtaining the information and how much was paid to associates who assisted in the supply of the information.<?php footnoteRef('E',3,10); ?> Invoices and remittance advices demonstrated the payments made by newspaper groups and how much money had been paid for each transaction.<?php footnoteRef('E',3,11); ?> As Mr Owens explained in his evidence, he was able to demonstrate a paper trail from identified journalists working for named newspaper groups, requesting information be obtained, through to the subsequent activities of the private investigators using sources or blaggers to obtain the information.<?php footnoteRef('E',3,12); ?></p>
  <?php paragraphLink('E',3,3,2); ?>Mr Owens, assisted by ICO Investigator Roy Pollitt, created a photo image of each of the documents and pages of the notebooks, and sent the documents to a forensic computer specialist to input the information into an electronic database, thus converting the contents of Mr Whittamore&#8217;s notebooks, invoices, remittance advices into an electronic format. On 30 November 2011 Mr Owens made a copy of the electronic database available to the Inquiry. Its broad accuracy was confirmed when the ICO produced Mr Whittamore&#8217;s hardback coloured notebooks.</p>
  <?php paragraphLink('E',3,3,3); ?>The highly confidential nature of the information contained within the database, and the need to protect the privacy of the subjects of the information requested, requires the confidentiality of the details of the database to be preserved and the subjects of the requests to remain anonymous. Similarly, the journalists who are identified by name in the database, but have not been interviewed or prosecuted by the ICO, have not been named during the course of the Inquiry. I heard submissions in private as to how to use this material and decided to make the database available to the Core Participants of the Inquiry, subject to confidentiality undertakings and on strict conditions. The purpose of making the material available was to permit Core Participants to evaluate their position in relation to this evidence. In due course it was conceded by all Core Participants that I could proceed on the basis that no positive case was to be mounted by them that the Motorman material did not reveal prima facie evidence of breaches by journalists of the DPA, and I have done so.<?php footnoteRef('E',3,13); ?> It has not been suggested by any Core Participant that, if necessary, I cannot go further and reach my own conclusions based on the Motorman evidence as to the culture, practices and ethics of the press.</p>
  <?php paragraphLink('E',3,3,4); ?>During Mr Owens&#8217; evidence, I observed that the records kept by Mr Whittamore, as illustrated in the database, contained, by reference to each request, the name of the newspaper group, the newspaper within that group, the journalist&#8217;s first and last names, the service requested, the nameof theperson retrieving the information (for example the blagger),the subject about whom the information was requested, the result of the search and various accompanying comments.<?php footnoteRef('E',3,14); ?> These aspects of the evidence are now considered in some detail.</p>
  <h4>Volume of requests made to Mr Whittamore</h4>
 <?php paragraphLink('E',3,3,5); ?>Mr Owens expressed the view that the notebooks contained in the region of 17,000 entries, or requests for information from the press.<?php footnoteRef('E',3,15); ?> These requests principally related to activities in the period between the end of 2000 and 8 March 2003 when the material was seized by the ICO; however the earliest entry was around 1997.<?php footnoteRef('E',3,16); ?> Richard Thomas, the Information Commissioner at the time, gave evidence that the total number of requests was 13,343.<?php footnoteRef('E',3,17); ?> This discrepancy is explained by their different approaches to multiple requests, and need not be resolved for present purposes. On any view, the figure involved is substantial, and demonstrates that Mr Whittamore was not simply engaged in obtaining the occasional ex- directory number, or in locating addresses on an infrequent basis, or in supplying personal information relating to simply a handful of individuals. Rather, he was engaged in a trade of personal information relating to hundreds of individual subjects, on an almost daily basis. The demand for this information from the press was constant.</p>
  <h4>Buyers/customers of information</h4>
 <?php paragraphLink('E',3,3,6); ?>It is important to acknowledge that the buyers or customers of the information were not, by any means, exclusively journalists. They included the media, insurance companies, lenders and creditors, parties involved in family disputes, criminals with what are likely to have been criminal or malicious intentions, including witness and juror intimidation, and estranged couples seeking details of their partner&#8217;s whereabouts.<?php footnoteRef('E',3,18); ?> However, the number of journalists requesting personal information from Mr Whittamore (for whatever reason, whether justifiable or not) indicates that it was not an isolated incident, or a handful of individuals engaging in the practice. The Parliamentary Report, <em>What Price Privacy Now?</em>, identified 333 journalists as having been named in the Motorman documents, as set out in the table below. Mr Thomas&#8217; witness statement identifies some 305 journalists as having been named in the Motorman material, and whilst, again, I note the discrepancy between the figures, nothing turns on this difference.<?php footnoteRef('E',3,19); ?></p>
  <h4>Suppliers of information</h4>
 <?php paragraphLink('E',3,3,7); ?>The documents seized disclosed that the information was either obtained directly by Mr Whittamore, or through associates who would be paid to obtain the information through either blagging or paying a source. Mr Whittamore would commonly outsource work to associates in return for a payment, and add a premium to the value of the information sold to the end buyer.<?php footnoteRef('E',3,20); ?> One example of a method used to obtain information is illustrated by BT ex-directory numbers. One of Mr Whittamore&#8217;s associates, Mr Jones, would ring BT or other phone companies, purporting to be an engineer; he would use a form of password which is given to BT employees (known as an EIN number) in order to identify himself as an engineer. Once he had obtained the information sought, he would telephone Mr Whittamore and pass on the relevant information. This modus operandi was elicited by Mr Owens from the relevant paperwork and by interviewing Mr Jones.<?php footnoteRef('E',3,21); ?></p>
  <h4>Subjects of requests for information</h4>
 <?php paragraphLink('E',3,3,8); ?>Turning to the journalists, the information sought related, in part, to a number of well-known celebrities and other figures in the public-eye, but equally included individuals who were only remotely connected with public figures, and some who had no obvious newsworthiness at all; one, for example was a self-employed painter and decorator who had once worked for a lottery winner.<?php footnoteRef('E',3,22); ?> In his evidence to the Inquiry Mr Owens confirmed that he had seen a reference to the Dowler family in the Operation Motorman material alongside a request for an ex-directory telephone number.<?php footnoteRef('E',3,23); ?> It also emerged in evidence that Mr Hugh Grant was amongst the celebrities whose personal information was sought by journalists.</p>
  <h3>Nature of information</h3>
 <?php paragraphLink('E',3,3,9); ?>The material seized evidenced the supply of a wide range of information including criminal record checks against the PNC, occupancy checks, voter searches, directors searches, VRM checks and vehicle owner details, ex-directory phone numbers, itemised telephone billing and mobile phone records, details of frequently dialled (&#8220;friends and family&#8221;) numbers, conversion of mobile telephone numbers into addresses and vice versa.<?php footnoteRef('E',3,24); ?> I emphasise immediately that at least some of this information could have been obtained lawfully, but that is not the case for all the types of information sought.</p>
  <?php paragraphLink('E',3,3,10); ?>By way of example of the type of information requested, in the course of Mr  Owens&#8217; evidence the Inquiry heard that one entry related to a request for specific calls from a telephone number between 16:00hrs and 17:00hrs on a given date. The price for obtaining this type of information was &#163;300-&#163;400. Mr Owens expressed the view that this information would be available on the subscriber&#8217;s telephone bill and this would only be available from the phone company.<?php footnoteRef('E',3,25); ?> Another entry related to a request for a &#8220;Phone bill for June 2011&#8221; for the price of &#163;800.<?php footnoteRef('E',3,26); ?></p>
  <?php paragraphLink('E',3,3,11); ?>These examples demonstrate that whilst some requests were more general, such as seeking to identify where an individual lived, other requests were highly specific in their terms.</p>
  <h4>Methods of obtaining information</h4>
 <?php paragraphLink('E',3,3,12); ?>Within the types of information requested, varying methods were used to obtain the  data. Thus, by its very nature, it appears clear that some types of information could only have been acquired from one possible source, for example the DVLA (VRM checks against owner details), the PNC (criminal record checks), or telephone companies (friends and family numbers). As Mr Owens explained in relation to friends and family numbers, &#8220;there&#8217;s no way you can get somebody&#8217;s list of family and friends lawfully, unless you actually know them and what&#8217;s on the list. The only way you&#8217;ll get them is from BT or whichever phone company&#8221;.<?php footnoteRef('E',3,27); ?> He further explained that criminal records checks could also not be obtained lawfully.<?php footnoteRef('E',3,28); ?> Mr Thomas in his evidence also confirmed that the PNC, and the list of friends and family numbers, cannot be obtained from information in the public domain.<?php footnoteRef('E',3,29); ?></p>
  <?php paragraphLink('E',3,3,13); ?>Similarly, in relation to obtaining the vehicle  owner&#8217;s details from the  DVLA, this information could only be obtained lawfully in a number of specifically defined circumstances set out by law. The DVLA has two separate databases holding information: the vehicle register and the driver register. The DVLA&#8217;s vehicle register holds information about each motor vehicle (e.g. registration mark, vehicle identification number, make/model, emissions, etc) and includes the name and address of the registered keeper, dates of acquisition and disposal, and the vehicle&#8217;s tax status. The driver register holds each driver&#8217;s name, address, date of birth, photograph, endorsements, convictions and relevant medical information that may affect a person&#8217;s ability to drive. The particulars from the register may be made available in a number of particular circumstances, for example to a police officer, or to a local authority to investigate an offence.<?php footnoteRef('E',3,30); ?> It may also be made available to a person who has &#8220;reasonable cause&#8221; for seeking particulars, for example following involvement in an accident, enforcement of road traffic legislation or tax collection. It appears very unlikely that requests made to the DVLA for owners&#8217; addresses to be supplied to journalists would fall within this category.</p>
  <?php paragraphLink('E',3,3,14); ?>Putting it at its lowest, in respect of these types of  information, namely VRMs checks against owner details, criminal record checks, or friends and family telephone numbers, I consider that the methods used to obtain this information by Mr Whittamore are highly likely to have been unlawful.</p>
  <?php paragraphLink('E',3,3,15); ?>It is right to observe that, in principle, other forms of information, for example  addresses, or ex-directory numbers, may be obtained through lawful means. For example, one can conceive of a laborious check of the full electoral register to identify an address. Similarly, searching through former telephone directories to locate a number that may have been notified before it became ex-directory may be possible. However, as was explained in <em>What Price Privacy?</em>, in many instances the sums charged for such information, for example the obtaining of a personal address, appeared to be too low to suggest that extensive hours of research had been undertaken to obtain this information. Mr Thomas expressed the view that it was highly likely that ex-directory numbers were obtained illegally.<?php footnoteRef('E',3,31); ?></p>
  <?php paragraphLink('E',3,3,16); ?>News International drew Mr Thomas&#8217; attention to the fact that there exist substantial databases of telephone numbers which may well have been obtained lawfully: one of the largest holds in the region of 50 million numbers, of which approximately 10 million may be inferred to be ex-directory.<?php footnoteRef('E',3,32); ?> However, it does not seem likely that Mr Whittamore had access to such a database between 1997 and 2003, and the way in which he recorded the information that he obtained does not suggest great computer literacy on his part. Further, it is difficult to see why newspapers (which, presumably, could access certain databases themselves) would have paid so highly for his services had such databases been his source.</p>
  <?php paragraphLink('E',3,3,17); ?>Taking all this evidence into account, and applying basic common sense to  it, the fairly obvious conclusion is that Mr Whittamore was obtaining the ex-directory numbers by unlawful means. The position is less clear cut in relation to the obtaining of addresses.</p>
  <h4>Public interest</h4>
 <?php paragraphLink('E',3,3,18); ?>In his evidence Mr Thomas acknowledged that there could, at least in  theory, be cases where the public interest fully justified obtaining personal data (with the result that no offence would be committed); and he also recognised that there could be questions concerning proof of intention or recklessness. In relation to the public interest, he gave the example of seeking the weekend telephone number of a minister who had recently resigned in order to contact him with a proposed story; however, when he was pressed by Mr Rhodri Davies QC for News International, he said: &#8220;But I have to say yet again, that was not typical, nothing like typical of the cases that we were seeing. And although you made the point that the majority of the cases were, in your language, only addresses or phone numbers, I would also say the vast majority were nothing to do with public interest considerations along the lines I&#8217;ve just mentioned.&#8221;<?php footnoteRef('E',3,33); ?> Mr Thomas expressed the opinion that the evidence obtained as part of Operation Motorman did not come near to being characterised as being in the public interest. He explained, &#8220;I haven&#8217;t seen a whiff of public interest. It was tittle-tattle. It was fishing. There may be one or two examples, but they would be exceptional&#8221;.<?php footnoteRef('E',3,34); ?> I can add that no example of a search for the weekend telephone number of a recently resigned minister has been shown to me.</p>
  <?php paragraphLink('E',3,3,19); ?>Given that no journalists were ever interviewed by the ICO in relation to Operation Motorman, the strength of any public interest defence is difficult to assess definitively and I do not propose to do so. However, it was suggested to the Inquiry by at least one press Core Participant that the newspaper required access to this data in order to be able to contact the subject of a story for his or her version of events; in other words, to facilitate the exercise of a right to reply. Expressed in these terms, a public interest defence has superficial attraction, but upon closer analysis its strength dissipates. In each case consideration needs to be given to the subject matter of the story which is proposed to be published. If the story has a potential freestanding public interest, then it is indeed arguable that, subject to a range of other factors, the journalist might need to contact the subject of the story for his or her account. But if, as Mr Thomas has suggested, there is not a whiff of public interest in the underlying story, it is not arguable that a public interest can be manufactured for the purposes of the defence under s55 of the DPA on the grounds that the subject needs to be contacted.</p>
  <?php paragraphLink('E',3,3,20); ?>In any event, regard must be paid to the nature of the information commonly being sought by journalists. Even assuming a journalist needed to contact the subject of a story, it is difficult to imagine why he or she should need to know the telephone details of the family and friends of the target. Even more difficult is to see the public interest in deceptively obtaining a criminal record check. In those circumstances, it is unlikely that a public interest defence under s55 of the DPA would have succeeded. Indeed, in only a small minority of the cases is it likely to have been even arguable.</p>
  <h4>Mental element</h4>
 <?php paragraphLink('E',3,3,21); ?>The case against a journalist instructing Mr Whittamore to obtain the relevant information is slightly different because, in order to establish guilt under s55, the prosecution would have to prove to the criminal standard that the journalist in question either knowingly or recklessly obtained or disclosed personal data or the information contained in personal data, s55(1)(a), or procured the disclosure to another person of the information contained in personal data, s55(1)(b). Again, the fact that no journalist was ever interviewed by the ICO renders difficult an assessment of whether this mental element could have been proved.</p>
  <?php paragraphLink('E',3,3,22); ?>It is, of course, possible to draw certain inferences from the available  material. That material includes, in particular, the type of data sought and obtained, the speed with which it was obtained, the amount of money paid for the information in question, and the sheer quantity of requests. There is certainly enough here to indicate prima facie (if not at a higher level) that many journalists either knew precisely how the information was being obtained or turned a Nelsonian eye to the obvious, or the close to obvious (with the result that there were, at least, reasonable prospects of proving recklessness). In that regard, I do no more than accept the concession that the press Core Participants made to that effect. It is not possible to go further than that, and (notwithstanding that the names of the journalists have not entered the public domain) it would be unfair to do so.</p>
  <?php sectionAnchor('E',3,4); ?>Prosecutions arising from Operation Motorman</h2>
 <?php paragraphLink('E',3,4,1); ?>The Information Commissioner formed the view that the material obtained during the course of Operation Motorman was of sufficient quality and quantity to bring criminal proceedings against the private detective Mr Whittamore and his associates involved in the blagging and obtaining of personal information. However, the evidence obtained by the ICO overlapped to some extent with the material obtained by the MPS and therefore the prosecutions led by the CPS in relation to the offences of corruption and conspiracy were given priority, being offences of a more serious nature.<?php footnoteRef('E',3,35); ?></p>
  <?php paragraphLink('E',3,4,2); ?>The evidence discovered by the MPS had highlighted the unauthorised supply of information from the PNC by a civilian police employee, and the CPS charged four individuals; namely Steve Whittamore, John Boyall, Alan King and Paul Marshall with corruption offences. 19 incidents were covered by the indictment, 12 in respect of Criminal Record Office offences and seven in relation to vehicle checks from the PNC. Two of the accused pleaded guilty to the corruption charges. On 6 April 2005, the Crown amended the indictment to include two offences under the DPA. Mr Whittamore and Mr Boyall pleaded guilty to offences under s55 of the DPA.<?php footnoteRef('E',3,36); ?></p>
  <?php paragraphLink('E',3,4,3); ?>On 15 April 2005, His Honour Judge Samuels QC, sitting at Blackfriars Crown Court, sentenced the four defendants. HHJ Samuels QC stated that: &#8220;the vice of the primary conspiracy was to make known to the press information which on any view ought to have been confidential, and was bound at its lowest to cause immense embarrassment to members of the public who required the state to maintain confidentiality in their affairs&#8221;.<?php footnoteRef('E',3,37); ?> However, the judge considered himself circumscribed by two factors. First, Paul Marshall had already been given a conditional discharge at an earlier trial in respect of unrelated offences, his mitigation being that he was seriously ill; in the court&#8217;s view, Mr Marshall could not now be given a higher sentence for a less serious offence, and his co-defendants could not be treated less leniently either. Second, the personal circumstances of each of the defendants (as argued before the judge) meant that the court considered that it could not impose a fine. Consequently, each defendant received a conditional discharge.</p>
  <?php paragraphLink('E',3,4,4); ?>Separate proceedings under s55 of the DPA had been commenced by the ICO against Mr Whittamore and five other private investigators. However, the proceedings were withdrawn when the CPS prosecutions resulted in a sentence of a conditional discharge.<?php footnoteRef('E',3,38); ?> The reasons for the discontinuance of the prosecutions are identified in the report <em>What Price Privacy?</em>; namely that the ICO was disappointed at the sentences imposed by the court and considered that it was not in the public interest to proceed with the ICO&#8217;s own prosecutions in these circumstances.<?php footnoteRef('E',3,39); ?> Given that the maximum sentence for a breach of s55 was a financial penalty, it cannot be said that this decision was unrealistic.</p>
  <?php sectionAnchor('E',3,5); ?>Publication of Parliamentary Reports in 2006</h2>
 <?php paragraphLink('E',3,5,1); ?>In 2006 the then Information Commissioner, Mr Thomas, published two Parliamentary reports documenting the widespread trade in confidential personal information.<?php footnoteRef('E',3,40); ?> The report <em>What Price Privacy?</em> The unlawful trade in confidential personal information was published on 13 May 2006 and the follow-up report <em>What Price Privacy Now?</em> was published on 13 December 2006.</p>
  <h4><em>What Price Privacy?</em></h4>
 <?php paragraphLink('E',3,5,2); ?>The Parliamentary Report published in May 2006 was not the first occasion on which the issue of the unlawful trade in personal information had been debated or discussed in public. What Price Privacy ? identified three newspaper articles in The Guardian, The Sunday Telegraph and The Times, written in the period between September 2002 and January 2003, which related to the obtaining of confidential information by private detectives and the sale of confidential information from government departments, namely the Inland Revenue, to outside agencies.<?php footnoteRef('E',3,41); ?> The report also noted that the House of Commons Select Committee on Culture, Media and Sport had conducted an investigation in early 2003 into privacy and media intrusion and concluded in its reports that &#8220;improper and intrusive gathering of data&#8221; had appeared in the press and that these methods amounted to a &#8220;depressing catalogue of deplorable practices&#8221;.<?php footnoteRef('E',3,42); ?></p>
  <?php paragraphLink('E',3,5,3); ?>The first report laid before Parliament claimed to reveal evidence of systematic breaches of privacy that amounted to an unlawful trade of confidential personal information. The purpose of the report was to put a stop to the trade by proposing the introduction of a custodial sentence for up to two years for persons convicted on indictment, or six months for summary convictions.<?php footnoteRef('E',3,43); ?></p>
  <?php paragraphLink('E',3,5,4); ?>Section 5 of <em>What Price Privacy?</em> set out the evidence collated by the ICO which illustrated the market in the unlawful supply of personal data. The report explained that: &#8220;documents seized during Operation Motorman and in other investigations have allowed the ICO to build up a clear picture of how the market in unlawful personal data operates. Case details provided evidence of who is buying the information and why, and who is obtaining and supplying the information. We also have some idea of how the suppliers operate and the prices they charge.&#8221;<?php footnoteRef('E',3,44); ?></p>
  <?php paragraphLink('E',3,5,5); ?>The report analysed the information seized at Mr Whittamore&#8217;s premises as falling into two categories of documentation. The primary documentation consisted of correspondence (reports, invoices, settlements of bills) between Mr Whittamore and many national newspapers and magazines, identifying the individual journalist seeking the information. The secondary documentation consisted of the detective&#8217;s own handwritten personal notes and a record of work carried out, about whom and for whom.</p>
  <?php paragraphLink('E',3,5,6); ?>In relation to methods, the report set out that there were two principal methods of obtaining information: corruption and deception.<?php footnoteRef('E',3,45); ?> Corrupt practices included paying employees of organisations, for example the DVLA, to access information available to them by virtue of their position, whilst deceptive practices included impersonating either the data subject or a third party (for example an employee of the same organisation) to obtain the information.<?php footnoteRef('E',3,46); ?></p>
  <?php paragraphLink('E',3,5,7); ?>The report also identified in broad terms a number of individuals who had been interviewed as part of the investigation, including celebrities, professional footballers and managers, broadcasters, a member of the Royal Household and also figures of less obvious public interest, including the sister of a partner of a local politician. The report set out the example of a mother whose show-business daughter had featured in a number of press stories. Details of the mother&#8217;s telephone calls and cars owned appeared in Mr Whittamore&#8217;s ledgers and records of financial transactions. Further, a number of those interviewed reported media intrusion after personal information had been passed to the press and all were confident that they had not willingly supplied the information nor consented to its release.<?php footnoteRef('E',3,47); ?></p>
  <?php paragraphLink('E',3,5,8); ?>Another aspect of the transactions that was analysed in the report was the issue of cost; that is to say how much the ultimate customers were charged for personal information and how much of this was profit once the agent sourcing the information had been paid. The prices charged to journalists ranged from &#163;17.50 for finding an address for a person on the electoral roll, to about &#163;70 to search for an ex-directory number, and up to &#163;500 for a criminal record check and &#163;750 to obtain mobile account details.<?php footnoteRef('E',3,48); ?> It seems likely that the figures reflected the mode of obtaining the information sought, in particular where other parties, for example blaggers, or employees, required payment for their role in the provision of the information.</p>
  <?php paragraphLink('E',3,5,9); ?>The total sum paid by newspapers for the items of information supplied in Operation Motorman is estimated to be between &#163;300,435 and &#163;547,160.<?php footnoteRef('E',3,49); ?> This gives an indication that the supply of personal information was, for those involved, a lucrative business.</p>
  <?php paragraphLink('E',3,5,10); ?>In the conclusion of the report, the ICO madea number of extremely pertinent  observations: &#8220;At a time when senior members of the press were publicly congratulating themselves for having raised journalistic standards across the industry, many newspapers were continuing to subscribe to an undercover economy devoted to obtaining a wealth of personal information forbidden to them by law. One remarkable fact is how well documented this underworld turned out to be&#8221;.<?php footnoteRef('E',3,50); ?> ....&#8220;The law relating to this offence is perfectly clear... it is framed in a way that applies to those who request the disclosure of personal data and those who supply it, including any intermediaries in the chain. The problem lies in the inadequacy of the penalties which the courts are able to impose&#8221;.<?php footnoteRef('E',3,51); ?></p>
  <?php paragraphLink('E',3,5,11); ?>The ICO sought custodial sentences in relation to the commission of offences under s55 DPA in order to deter this unlawful trade in information. The ways in which the ICO sought to achieve that end are dealt with in Part H of the Report.</p>
  <h3><em>What Price Privacy Now?</em></h3>
 <?php paragraphLink('E',3,5,12); ?>The Parliamentary Report  What Price Privacy Now? was published to chart the progress in the six months following the first report and to set out the responses to the recommendations set out in the first report.</p>
  <?php paragraphLink('E',3,5,13); ?>The report noted thata Freedom of Information Act request for further information about the 305 journalists identified in the Motorman material and referred to in <em>What Price Privacy?</em> had been considered and, on the basis that disclosure of the information was in the public interest, the employers of the journalists were set out in tabular form.</p>
  <?php paragraphLink('E',3,5,14); ?>This table is replicated below.<?php footnoteRef('E',3,52); ?> </p>
  <h4><a href="#tableE3-1" id="tableE3-1">Table E3.1</a></h4>
  <table>
  <tr>
 <th>No. of Transactions positively identified</th> <th>No. of Journalists or Clients using services</th> <th>Publication </th> </tr>  <tr>
<td>Daily Mail</td> <td>952</td> <td>58</td> </tr>  <tr>
<td>Sunday People</td> <td>802</td> <td>50</td> </tr>  <tr>
<td>Daily Mirror</td> <td>681</td> <td>45</td> </tr>  <tr>
<td>Mail on Sunday</td> <td>266</td> <td>33</td> </tr>  <tr>
<td>News of the World</td> <td>228</td> <td>23</td> </tr>  <tr>
<td>Sunday Mirror</td> <td>143</td> <td>25</td> </tr>  <tr>
<td>Best Magazine</td> <td>134</td> <td>20</td> </tr>  <tr>
<td>Evening Standard</td> <td>130</td> <td>1</td> </tr>  <tr>
<td>The Observer</td> <td>103</td> <td>4</td> </tr>  <tr>
<td>Daily Sport</td> <td>62</td> <td>4</td> </tr>  <tr>
<td>The People</td> <td>37</td> <td>19</td> </tr>  <tr>
<td>Daily Express</td> <td>36</td> <td>7</td> </tr>  <tr>
<td>Weekend Magazine (Daily Mail)</td> <td>30</td> <td>4</td> </tr>  <tr>
<td>Sunday Express</td> <td>29</td> <td>8</td> </tr>  <tr>
<td>The Sun</td> <td>24</td> <td>4</td> </tr>  <tr>
<td>Closer Magazine</td> <td>22</td> <td>5</td> </tr>  <tr>
<td>Sunday Sport</td> <td>15</td> <td>1</td> </tr>  <tr>
<td>Night and Day (Mail on Sunday)</td> <td>9</td> <td>2</td> </tr>  <tr>
<td>Sunday Business News</td> <td>8</td> <td>1</td> </tr>  <tr>
<td>Daily Record</td> <td>7</td> <td>2</td> </tr>  <tr>
<td>Saturday (Express)</td> <td>7</td> <td>1</td> </tr>  <tr>
<td>Sunday Mirror Magazine</td> <td>6</td> <td>1</td> </tr>  <tr>
<td>Real Magazine</td> <td>4</td> <td>1</td> </tr>  <tr>
 <td>Woman&#8217;s Own</td> <td>4</td> <td>2</td> </tr>  <tr>
 <td>The Sunday Times</td> <td>4</td> <td>1</td> </tr>  <tr>
 <td>Daily Mirror Magazine</td> <td>3</td> <td>2</td> </tr>  <tr>
 <td>Mail in Ireland</td> <td>3</td> <td>1</td> </tr>  <tr>
 <td>Daily Star</td> <td>2</td> <td>4</td> </tr>  <tr>
 <td>The Times</td> <td>2</td> <td>1</td> </tr>  <tr>
 <td>Marie Claire</td> <td>2</td> <td>1</td> </tr>  <tr>
 <td>Personal Magazine</td> <td>1</td> <td>1</td> </tr>  <tr>
 <td>Sunday World</td> <td>1</td> <td>1</td> </tr> </table> </p>
  <?php paragraphLink('E',3,5,15); ?>The table sets outa breakdown of the extent to which individual newspapers and magazines were implicated in the evidence produced by Operation Motorman and, in particular, the number of journalists employed by each newspaper or magazine which was identified as having requested the supply of personal information.</p>
  <?php paragraphLink('E',3,5,16); ?>It is worth underlining the view of the Information Commissioner, as set out in the text of  <em>What Price Privacy Now?</em>, that the figures in the table do not purport to set out the total number of offences committed by journalists, but rather the number of requests made by journalists for information. In his evidence to the Inquiry, Mr Thomas emphasised that it was not being said that every single transaction identified was an offence committed by a journalist, but rather that journalists were significant customers of information which appeared to have been obtained illegally.<?php footnoteRef('E',3,53); ?> However, Mr Thomas also expressed the view that it was likely that journalists were committing an offence.<?php footnoteRef('E',3,54); ?></p>
  <?php paragraphLink('E',3,5,17); ?>Two overriding observations can be made in relation to these figures. First, whilst the journalists engaged in buying personal information supplied through a private investigator were employed by a range of titles, including tabloid newspapers, broadsheet newspapers and magazines, there is significant variation in the extent to which journalists and titles engaged in the purchase of personal information from Mr Whittamore. For example, 58 journalists from the Daily Mail sought the supply of personal information on 952 occasions, whereas by contrast one journalist from The Sunday Times sought the supply of personal information on four occasions. Second, the numbers of individual journalists engaged in purchasing personal information from particular titles is higher than could be put down to certain individuals undertaking investigations which might or might not have been known about or authorised. Where dozens, or in some cases, over 50 journalists at a particular title have sought to purchase personal information, the inference that these practices were endemic within particular titles may be readily understood.</p>
  <?php sectionAnchor('E',3,6); ?>Conclusions</h2>
 <?php paragraphLink('E',3,6,1); ?>For the purposes of responding to a request by Lord Ashcroft under the Freedom of Information Act 2000, ICO investigation officers and an in-house lawyer analysed the source material collated as part of Operation Motorman. They documented some 13,343 transactions, or individual requests for information made of Mr Whittamore. These transactions were segregated by staff of the ICO into three separate categories in terms of their evidential value.<?php footnoteRef('E',3,55); ?> Of these, the ICO took the view that some 5,025 were actively investigated as part of Operation Motorman and positively known to constitute a breach of the DPA. More specifically, and put somewhat more carefully, it was the view of a lawyer employed by the ICO with extensive involvement in the prosecutions that the evidence in these cases would have been sufficient to lead to conviction.<?php footnoteRef('E',3,56); ?> A number of the requests in this category included PNC requests, friends and family requests and some ex-directory requests.<?php footnoteRef('E',3,57); ?></p>
  <?php paragraphLink('E',3,6,2); ?>A further 6,330 requests represented occupancy searches and are thought to have been information obtained from telephone service providers. The ICO considered that the obtaining of this information was likely to amount to breaches of the DPA; however, the nature of the transactions was not sufficiently known or understood for these to be characterised as a positive breach of the DPA, rather than probably illicit transactions.<?php footnoteRef('E',3,58); ?> Some 1,988 of the transactions were considered to lack sufficient identification or understanding of how the information had been obtained to determine whether they represented illicit transactions. The first category of transactions only was included with the Parliamentary Reports.<?php footnoteRef('E',3,59); ?></p>
  <?php paragraphLink('E',3,6,3); ?>Overall, it is not surprising that the Core Participants made the concessions recorded under paragraph 3.3 above: a detailed examination of many individual examples would, in my judgment, undeniably have established that this was the very lowest at which it could be put. For reasons which I well understand, the ICO would argue that the concession does not go far enough. Without condemning any journalist (none of whom were ever even interviewed by the ICO), it is sufficient for me to conclude that, at least in part, what has been revealed by some of the Operation Motorman evidence demonstrates an attitude to compliance with the law relating to data protection which can only be described as cavalier, if not worse: it is certainly revealing of what, at that time at least, were the practices of parts of the press. As will become apparent, the extent to which Mr Whittamore&#8217;s services continued to be used by some titles after his conviction is even more revealing.</p>
  </div>

 