<div class="content" id="contentPartKChapter2">
<h1 id="top">CHAPTER 8<br/>THE ALTERNATIVES</h1>
 <?php sectionAnchor('K',8,1); ?>The issue</h2>
 <?php paragraphLink('K',8,1,1); ?>I have indicated above that a new regulatory regime needs to cover all main news publishers if it is to be effective,<?php footnoteRef('K',8,1); ?> and I have recommended a model for an effective independent self-regulatory system which I very much hope will be taken forward by the industry and Government and which I hope will secure the support of the whole industry.</p>
  <?php paragraphLink('K',8,1,2); ?>However, should that not be the case, and only in those circumstances, there would be a need for some mechanism to ensure that the advantages that the press enjoy in the public interest are matched by responsibilities that are owed to the public. In other words, there should be some way that the press can be held to account on behalf of the public for the way it goes about its business. I have been clear that it is my hope and expectation that this situation will not arise. It can only do so if the press fails to deliver the independent regulation that is required and that the public have a right to demand. If, however, the industry were unwilling, or unable, to come forward with a credible proposal for independent regulation then it would have demonstrated sufficient disregard for the public interest to have established that self- organised regulation simply is not an effective option. This Chapter looks at the issues that would have to be addressed in order to provide such a mechanism and identifies the possible solutions.</p>
  <?php paragraphLink('K',8,1,3); ?>I ought to make it clear that I do not believe that an approach involving direct independent regulation necessarily constitutes a &#8220;freedom of expression Armageddon&#8221; (to use the Rt Hon Kenneth Clarke MP&#8217;s expression). I repeat that the issue arises only if the press deliberately refuse to set up a regulatory process that is undeniably independent of Government and Parliament but is, equally, independent of the press itself; or, if such a system is set up but does not have the support of the whole industry.</p>
  <?php paragraphLink('K',8,1,4); ?>I set out here a very brief analysis of the issues which I think logically arise in that eventuality. I do so for reasons of completeness, and so that no reader of this Report is unaware of the inescapable context which forms the background to the recommendations that I have made in the previous Chapter. There are no recommendations in this Chapter; it is simply a short overview of the logical alternatives, as I see them, to the implementation of the model I have put forward.</p>
  <?php sectionAnchor('K',8,2); ?>The questions</h2>
 <?php paragraphLink('K',8,1,5); ?>It is extremely easy to say that everyone must participate in a new regulatory system, and relatively easy to fall back on the idea that, if they refuse, some type of statutory provision may be necessary to ensure that outcome. It is more difficult to determine the shape and substance of that statutory provision. I note that very few of the witnesses to the Inquiry have addressed themselves to this question at all, even where they accept that legislation might well be needed. The first point to make is that any form of compulsion would require legislation. Undeniably, it is statutory regulation in stark form.</p>
  <?php paragraphLink('K',8,2,1); ?>There are essentially four questions that need to be addressed in considering what statutory provision might be required: 
  <ol type="a">
<li>what standards should be complied with? </li>
<li>what should be the consequences of failure to comply? </li>
<li>how should these consequences be applied? and; </li>
<li>who should these provisions apply to? </li></p>
</ol>
  <?php sectionAnchor('K',8,3); ?>What standards should be complied with?</h2>
 <?php paragraphLink('K',8,3,1); ?>I have already made it clear that I have no intention of trying to define the standards of press conduct and ethics that should be applied. That is rightly a matter for an independent regulatory body, acting with the advice of the industry and following consultation with the public and others with relevant interests. I have also made it clear that I expect the standards set by an independent regulatory body to cover governance and compliance procedures as well as conduct and ethical issues. The recommendations set out above establish the specific requirements that I consider should be met by an independent regulatory system in this regard.</p>
  <?php paragraphLink('K',8,3,2); ?>The issue considered here is the standard to be expected of those who choose to stay outside of a self-organised independent system that meets those criteria, or in the event that no such system emerged. There are a number of possible approaches.</p>
  <h4>Enforcing legal requirements</h4>
 <?php paragraphLink('K',8,3,3); ?>It has been argued that what is needed is not regulation of standards, but enforcement of the law. I have explained why simple enforcement of the law, either through the application of the criminal law or by civil proceedings through the courts, will not be a realistic solution to most of the problems identified by the Inquiry.<?php footnoteRef('K',8,2); ?> Having said that, those who argue for law enforcement alone are correct that, for the most part, the contents of any likely &#8216;standards code&#8217; are already, at a basic level, covered by the law.</p>
  <?php paragraphLink('K',8,3,4); ?>However, the virtue of an effective regulatory system is that, even if it does not seek to set standards at a level beyond the basic requirements of the law, it would be possible to enforce those rights in a way that is more flexible and may not otherwise be possible. Where a publisher declines to be part of an effective regulatory system, there is currently no mechanism for effective enforcement even of standards equivalent to the law beyond reporting the matter to the police (if there is a basis for contending that the complaint is one of crime) or commencing civil proceedings.</p>
  <?php paragraphLink('K',8,3,5); ?>Under this analysis, the harm that arises as a result of publications choosing to sit outside a regulatory system, or the lack of existence of a regulatory system, is that victims are obliged to fall back on the civil law process which is not designed to provide the type of speedy redress or rectification that is available to a regulator, but can be both slow and unsatisfactory; furthermore, it is unlikely to be a possible route for any other than the very rich and there is no external monitoring of compliance with civil and criminal legal requirements.</p>
  <?php paragraphLink('K',8,3,6); ?>It might reasonably be suggested that no publisher should be above the law, and that the simplest way of enforcing that principle would be for a standards code that simply looks to reflect the existing law in terms of standards to apply and then rigorously enforces those standards. Essentially, if that was to be the case, what is suggested is that a statutory regulator should be empowered to undertake regulatory enforcement of relevant civil rights and criminal wrongs with a zero-tolerance approach. By &#8216;regulatory enforcement&#8217; I mean that the statutory body would: establish a standards code that requires no more or less than compliance with legal obligations; determine whether standards have been breached; and apply appropriate sanctions. This rigorous regulatory enforcement would sit alongside the existing mechanisms of law enforcement but would be applied by the regulator, not the courts. All decisions taken by the regulator could be subject to appeal to the courts and would, in any case, be subject to challenge by judicial review.</p>
  <?php paragraphLink('K',8,3,7); ?>In order to be able to exercise such a role effectively the regulator responsible would need new statutory powers to set and enforce regulatory standards that do not exceed the limits of the law. In addition, it would need powers to obtain information about compliance. These powers could take the form of the ability to conduct an audit to examine and make recommendations about the compliance systems that a company has in place. The regulator would also need to be given investigatory powers in order to follow up complaints or reasoned suspicion of breach of law. These powers might include the power to call for documents and to hold hearings. In relation to enforcement powers, the regulator could be given the power to require publication of corrections and apologies in relation to defamatory material, and the power to impose regulatory fines (or civil penalties) in respect of defamation and other breaches of law.</p>
  <?php paragraphLink('K',8,3,8); ?>Some of these powers would be entirely new regulatory enforcement powers for existing law. Others, for example in relation to data privacy breaches, exist already, or would do so if the recommendations that I have made in relation to the reform of the Information Commissioner and the Data Protection Act are accepted. A good deal more work would be required to identify the specific areas of law that such powers should cover and precisely what powers such a regulator should have.</p>
  <?php paragraphLink('K',8,3,9); ?>A regulatory system would offer access to victims to pursue their rights, albeit without necessarily pursuing a claim for the compensation that the law might allow; it could provide a mechanism for standards oversight that criminal law enforcement cannot provide.</p>
  <h4>Enforcing independently set standards</h4>
 <?php paragraphLink('K',8,3,10); ?>Many of the examples of unacceptable press behaviour that the Inquiry has seen concern inaccuracy that is harmful to individuals or the public at large, and breaches of privacy of one sort or another. Most clauses of the current Editors&#8217; Code fall under one of those headings or the other. Those that do not (those relating, for example to reporting of crime and payment to witnesses and criminals) are in areas covered by criminal law. It might, therefore, be argued, that an ethical standards code is unlikely to offer the public any more protection than the civil and criminal law, taken together, already do. This is not strictly true.</p>
  <?php paragraphLink('K',8,3,11); ?>In the first place, the law only covers accuracy of published material to the extent that want of accuracy is defamatory (the threshold for which is presently under consideration in the Defamation Bill) or a contravention of the data protection regime. It is quite clear that the public interest in accuracy goes much wider than the case of personal information, and I would expect an independent standards code to set that expectation. There is, however, no legal mechanism to correct an inaccuracy other then when it is defamatory or a breach of the Data Protection Act. The current Editors&#8217; Code also makes provision for handling cases involving grief and shock in a sensitive way where there is no underlying legal requirement (unless a claim could be pursued for breach of privacy). In other areas, such as harassment, the current Code provisions cover ground where there are legal standards but the Code does not necessarily track those legal standards exactly, nor would it necessarily be desirable that it should do so. There are therefore gaps in the protection of the public interest, and in reasonable expectations of press standards, which the substantive law does not cover.</p>
  <?php paragraphLink('K',8,3,12); ?>Where a recognised independent regulatory system did exist, there would be one or more recognised independently-set standards codes in existence. These would have been subject to public consultation. It would be perfectly possible to apply the most appropriate of these directly to a publisher outside the system. This is broadly analogous to the model adopted by Ofcom in relation to the Advertising Standards Authority, where Ofcom will, if necessary, take enforcement action against broadcasters who are in breach of the ASA broadcasting code. If there were no such body at all, the regulator would have to issue its own code, doubtless having given the industry the opportunity to provide input from the start and, ultimately, following open and transparent consultation both with the industry and the public.</p>
  <?php sectionAnchor('K',8,4); ?>What consequences should apply for breach?</h2>
 <?php paragraphLink('K',8,4,1); ?>This is the main question that defines the impact of any compulsory regulation. What should apply, and to whom it should apply are, to some extent, matters of technical detail. What happens in respect of breach defines the nature of the statutory intervention. For some regulators, there is a power to disqualify or ban: it goes without saying that, if a publisher could be banned from publication as a result of breach, that would amount to a licensing regime for the press which would be entirely unacceptable.</p>
  <?php paragraphLink('K',8,4,2); ?>The options that I consider below are only those that I believe would be acceptable in a democratic society and all respect the right of any publisher to publish any material. There is nothing here that would apply any form of prior restraint, or require any permission, in relation to publication. None of the options includes any form of state intervention in the content published (save to the extent that a requirement to publish a correction impacts on content), or even in setting any standards that might apply to any content published.<?php footnoteRef('K',8,3); ?> These options relate solely to consequences after the event where standards (howsoever defined) have been breached.</p>
  <?php paragraphLink('K',8,4,3); ?>Other than the first, which is the absence of consequences and included simply for the sake of completeness, each of these approaches would rely on the existence of statutory backstop regulator of some kind. They are set out so that they can be considered by all concerned with this issue.</p>
  <h4>Rely solely on benefits from membership of a recognised body</h4>
 <?php paragraphLink('K',8,4,4); ?>If there is no backstop regulator, the only effect of non-membership of a recognised body would be the inability to access the benefits of that membership. Effectively, this would be a &#8216;do nothing&#8217; option. I have set out above<?php footnoteRef('K',8,4); ?> the statutory benefits that I consider should apply to membership of a recognised body. These include the recognition by the courts of a commitment to high standards of behaviour and practice in connection with the issues that arise in relation to aggravated and exemplary damages and also of a willingness to participate in a fair, low cost, scheme to arbitrate disputes which is relevant to issues of costs.</p>
  <?php paragraphLink('K',8,4,5); ?>Conversely, those who are not members of such a regulatory body would face the risk of failing to demonstrate a commitment to high standards of behaviour (which could provide material that justifies the award of aggravated or exemplary damages) and adverse costs consequences of failing to participate in a system which permitted claimants to pursue their rights in a fair, low cost system of alternative dispute resolution (ADR). Thus, if my earlier recommendations are accepted, non-members might find that the court exercises its discretion against making an order for costs even in the event that they had succeeded in a privacy or defamation defence.</p>
  <?php paragraphLink('K',8,4,6); ?>These are, of course, consequences of not joining a regulatory system; they are not consequences attached to specific breaches of standards. The only mechanism for an individual to challenge a publisher outside the regulatory system would be by legal challenges relating to defamation, privacy or data protection. In the context of the changes to conditional fees, this is unlikely to be a route open to most people, which is why I have recommended that if no such scheme is set up, the Government should revisit the proposals made by Lord Justice Jackson for one way qualified costs shifting.</p>
  <h4>Name and shame</h4>
 <?php paragraphLink('K',8,4,7); ?>The first and least intrusive approach for a backstop regulator would be no more than an obligation and ability to monitor the performance of non-member publishers against the relevant standards and governance requirements, and to make its findings public. In order to be able to make meaningful reports, such a body would need to have the power to hear complaints from individuals and reach conclusions on whether standards had been breached. In order to provide any broader standards oversight, the body would need to have the power to investigate serious or systemic breaches of standards and to require information from publishers to facilitate that.</p>
  <?php paragraphLink('K',8,4,8); ?>On this basis,the regulatory backstop would be unable to make any requirement of apublisher or impose any remedy for an individual: the only recourse for that individual would remain litigation. However, the body would itself be able to publish its conclusions on complaints and make public any concerns it had about standards in relevant publishers. A report of this sort could formally be made to Parliament.</p>
  <h4>Complainants champion</h4>
 <?php paragraphLink('K',8,4,9); ?>There is also the potential for an entirely different approach. In the absence of some sort of regulatory intervention, the only option open to an individual would be litigation, if that were appropriate. It is theoretically possible for a backstop regulator (who could assume the naming and shaming role identified above) to take on the role of supporting complainants in taking legal action. A more extreme approach would be for the backstop regulator to take legal action on behalf of complainants.</p>
  <?php paragraphLink('K',8,4,10); ?>There are, however, two rather obvious problems with this proposal. The first is the cost. Even with the cost proposals set out in Section 4, it is likely that this would be an expensive option. It is inevitable that sometimes claims would fail; indeed, it would be a poor service if the only claims the regulator pursued were those guaranteed to succeed. The regulator would need some means of determining which cases to pursue as it would be both impractical and improper to take forward any complaint, however unlikely to succeed.</p>
  <?php paragraphLink('K',8,4,11); ?>The second substantive problem here is that the state, however constituted, does not generally seek to enforce the civil rights of citizens and it is difficult to see why it should do so in this area, as opposed to many others. There are serious concerns about access to justice in a wide variety of contexts; the legal aid budget is already overstretched, with the areas of law in which legal assistance is provided under constant review. It is extremely difficult to see why the state should be prepared to enforce these (as opposed to many other) private law rights.</p>
  <h4>Apply standards with enforcement powers</h4>
 <?php paragraphLink('K',8,4,12); ?>The final level would simply be to apply standards to all news publishers in the same way. This could be achieved in one of two ways. The first would be to require all relevant publishers to be bound by a recognised independent regulatory body such as the type I have recommended. However, this approach is not itself without difficulty for a number of reasons.</p>
  <?php paragraphLink('K',8,4,13); ?>First, it is important to emphasise that if the press come together to organise an independent regulatory body (albeit in such a way that satisfied certain statutory requirements) the result is not itself a statutory body of any sort. It will be recognised by statute but it will not have any statutory powers. The Report does not propose statutory regulation of the press but, rather, self-organised independent regulation of the press, both elements of which (self organised and independent) are significant. It means that it would be wrong to give the body statutory jurisdiction of any sort. Equally, it would be wrong to require any individual publisher to become a member of a &#8216;self-organised&#8217; body organised by others.</p>
  <?php paragraphLink('K',8,4,14); ?>The alternative, second way is that some other regulatory body (a &#8216;backstop regulator&#8217;) should apply a standards code directly to press publishers who choose not to become part of a recognised system. Under this approach the backstop regulator would need, by statute, to be given enforcement powers to carry out investigations, to require publication and placement of corrections and apologies, and to levy fines in respect of serious or systemic breaches and in default of compliance with its orders. The backstop regulator would then be in a position to apply an appropriate level of regulation to those who do not voluntarily sign up to a recognised independent system. As described above, the standards applied could be a code that simply reflects the requirements of the law, or it could go further and apply the most appropriate code or, in default, a code that it had prepared after suitable consultation.</p>
  <?php paragraphLink('K',8,4,15); ?>It is important to repeat that no backstop regulator should be given any powers over published content, except in relation to apologies and corrections. At no point should the regulator be able to prevent publication of content. The regulator would have no right to see content ahead of publication and no right to require the publication of any content other than in respect of apologies and corrections. This would not be statutory regulation of what the press could publish; rather, it would represent an after the fact review of press behaviour.</p>
  <?php sectionAnchor('K',8,5); ?>How should any consequences be applied?</h2>
 <?php paragraphLink('K',8,5,1); ?>I identified earlier that all options (except for &#8216;do nothing&#8217;) would require a backstop regulatory body to undertake the proposed regulatory role. The role requires a strong, expert organisation, capable both of understanding the balance between Article 8 and Article 10 rights of the European Convention on Human Rights (ECHR) and of withstanding the pressure that the press would be bound to place on anyone in this position.</p>
  <?php paragraphLink('K',8,5,2); ?>An obvious answer would be that Ofcom should be given the responsibility of the role, not least because it is an established regulator, well able to understand the issues and address them. I am aware of the attitude of the press towards Ofcom but there is absolutely nothing in the way in which I have seen that it exercises its regulatory functions to suggest that it does not do so entirely appropriately and fully in accordance with its legislative mandate.</p>
  <?php paragraphLink('K',8,5,3); ?>Ofcom has an internationally high reputation<?php footnoteRef('K',8,5); ?> as a telecommunications regulator, and has been described by the Rt Hon Ed Vaizey MP, Minister for Culture, Communications and Creative Industries, as &#8216;doing an outstanding job&#8217;.<?php footnoteRef('K',8,6); ?> The broadcasters who have given evidence to the Inquiry have not suggested that Ofcom (which directly regulates the independent broadcasters, occupying a slightly different position in relation to the BBC) has ever exercised the slightest chilling effect in relation to the many examples of splendid investigative journalism that have been carried out over many years. For the avoidance of doubt, I am equally clear that Ofcom would have no difficulty approaching its task with an eye to the very different requirements of press regulation as contrasted with broadcast regulation, not least in relation to the difference of position as to political neutrality.</p>
  <?php paragraphLink('K',8,5,4); ?>Ofcom would have to take on additional expertise from print journalism to assist in the task but, given that many broadcast journalists have also worked in the press, I do not believe that Ofcom would be starting from a blank sheet. Much expertise is available to it and I have no doubt that it could perform the oversight task with a light touch but be ready to deal with egregious examples of conduct as and when it is necessary to do so. Both in the seminar and in evidence, the Chair, Dr Colette Bowe and Ed Richards, the chief executive of Ofcom, demonstrated a clear understanding of the line and I reject the suggestion that regulation by Ofcom would mean the end of the free press or descent into state control of content.</p>
  <?php paragraphLink('K',8,5,5); ?>Having identified Ofcom as the obvious answer, I must recognise that I have already recommended that Ofcom should act as that body responsible for recognition and audit of independent regulatory press standards bodies. It might be suggested, therefore, that it was undesirable for one body to be responsible both for advising on the adequacy of the model for independent regulation that has been set up (against the statutory requirements) and, ultimately, if all else fails, for delivering the regulation itself.</p>
  <?php paragraphLink('K',8,5,6); ?>The issue could be argued both ways. First, it might be said that Ofcom could reject an independent regulator in order to take on the role of direct regulation. Second, and in quite the opposite direction, it is just as plausible to argue that Ofcom might actually be inclined to approve any independent regulator that comes forward in order to avoid taking on highly controversial role of regulating the press directly.</p>
  <?php paragraphLink('K',8,5,7); ?>For my part, I do not believe that this dual role necessarily creates any real difficulty. I do not see why it should not be possible to require Ofcom at all times to aim for independent self-organised regulation, whilst nonetheless having to be able to demonstrate how any recognised regulator meets the statutory criteria. As a statutory regulator, Ofcom is required to operate with full transparency and could be obliged to publish not only its decisions on recognition, but also the reasoning for its decisions, thus ensuring that there is no opportunity for competing incentives in relation to a backstop regulatory role to influence a decision on recognition of an independent regulator.</p>
  <?php paragraphLink('K',8,5,8); ?>For the sake of completeness I should mention what could be the alternatives. First, it would be possible to extend the remit of the Information Commissioner. There are some advantages to this idea. The Information Commissioner&#8217;s Office (ICO) has many of the relevant powers already, as well as the expertise in balancing the considerations raised by Articles 8 and 10 of the ECHR. However, for the reasons I have set out in Part H, I do not see this as an obvious solution. Any attempt to give this role to the ICO would require restructuring and substantial strengthening of the office, together with giving the Information Commissioner new duties and responsibilities to ensure that sufficient priority was given to the role.</p>
  <?php paragraphLink('K',8,5,9); ?>The final option would be to create a new regulator to undertake the role. To my mind, this is the least satisfactory. Creating a new, self-standing, authority would take time. It would be likely to be the most expensive option; it would have no established authority or reputation. Without appropriate support, it would also be vulnerable to pressure.</p>
  <?php sectionAnchor('K',8,6); ?>To whom should any provision apply?</h2>
 <?php paragraphLink('K',8,6,1); ?>I have referred throughout this section to &#8216;news publishers&#8217;. In practice if there were to be any requirement for certain organisations to meet prescribed standards in carrying out their activities, then it would be necessary to define quite precisely who those organisations are. There are two elements to this question. The first, and most basic, is how it is possible to distinguish the types of organisation that it is considered should be included within a new regulatory system. The second, once a definition has been decided, is whether everyone within that definition should be covered, or whether there is an argument for some sort of size threshold. I will deal with these two issues separately.</p>
  <h4>Definitions</h4>
 <?php paragraphLink('K',8,6,2); ?>The Inquiry has had limited help on this matter from witnesses. Some have argued that the difficulty of defining who should be covered by any legislation is a sufficient argument in itself for not imposing a legislative solution.</p>
  <?php paragraphLink('K',8,6,3); ?>Current definitions are an obvious starting point. Membership of the PCC is purely voluntary and the PCC says<?php footnoteRef('K',8,7); ?> that it deals with editorially controlled material in UK newspapers and magazines and their websites. The PCC does not cover any newspapers or magazines that do not subscribe to the Press Board of Finance (PressBoF), and hence has not had to grapple with the issue of definitions in relation to whether a particular publication should be a member if it does not wish to do so. National newspapers pay the levy through the National Periodical Association, whilst regional newspapers and magazines are invoiced individually.<?php footnoteRef('K',8,8); ?> No evidence is available on how PressBoF identifies publications to invoice, though it seems likely that this is done via the relevant industry bodies, or what they do when publications do not choose to pay. There is no publicly available list of those publications that are covered by the PCC, nor any list of publications which are not.</p>
  <?php paragraphLink('K',8,6,4); ?>One, albeit partial, source would be a definition of &#8216;newspaper&#8217; or &#8216;the press&#8217;. Dictionary definitions of &#8216;a newspaper&#8217; tend to include reference to the fact that it is printed,<?php footnoteRef('K',8,9); ?> that it is published at regular intervals, and that content includes articles on the news, editorials, features, reviews and advertisements. Definitions of the &#8216;press&#8217; tend simply to refer to publications and periodicals. Definitions of the media go much more widely and bring in broadcasting and, sometimes, the internet. An approach based on defining terms of this sort does not, therefore, appear promising.</p>
  <?php paragraphLink('K',8,6,5); ?>An alternative approach, in seeking to identify the scope and coverage of a new regulatory system, would be to identify what activity it is that gives rise to the need for regulation. The harm that the Inquiry has heard described relates primarily to the process of gathering information about individuals, the use of private information and the publication of inaccurate information. It is these areas (conduct in the gathering of information, respect for privacy, and accuracy) that I have recommended should by covered by a standards code in the new regulatory system. It follows that the coverage of a new regulatory system should encompass those who undertake activities likely to involve those three processes. It may therefore be appropriate to attempt to build a definition based around: the gathering of information about people and current affairs, for the purpose of, or in relation to, publication of news and information; and the publication of information about people and current affairs.</p>
  <?php paragraphLink('K',8,6,6); ?>One way of looking at this would be to develop a concept of &#8216;press like services&#8217; along the model already used in relation to audiovisual media services, where regulation applies to &#8216;TV- like services&#8217;. Whether or not a service fell within the definition would be determined by any backstop regulator, but subject to appeal or review.<?php footnoteRef('K',8,10); ?></p>
  <?php paragraphLink('K',8,6,7); ?>A definition of this sort would be targeted on the behaviour that gives rise to concern and would certainly include newspapers and relevant magazines. Such a definition should also apply to those to whom information gathering is subcontracted, such as picture agencies and private investigators (although only when working for clients who would themselves be included by virtue of their publication activities).</p>
  <?php paragraphLink('K',8,6,8); ?>As set out above, however, the definition would also include broadcasters and internet sites which cover news or celebrity issues. Whilst it is important to ensure that the coverage of a new regulatory system is sufficiently wide to prevent it being evaded purely by restructuring or redefining what an organisation does, it is also important to avoid any conflict or unnecessary and unhelpful overlap between regulatory systems. In this context, it would be sensible to say that any activities that are regulated by Ofcom under the Broadcasting Code, or by the Authority for Television on Demand (ATVOD), under the Audio Visual Media Services (AVMS) Directive, should not fall to be regulated under the new system. It would clearly be very important, however, for the boundaries between those systems and the new system to be looked at very carefully, and for the relevant regulators to work together to avoid conflict or gaps in coverage.</p>
  <h4>A size threshold</h4>
 <?php paragraphLink('K',8,6,9); ?>Arguments have been made from two perspectives about the extent to which any regulatory system should apply to companies of all sizes engaged in &#8216;press like services&#8217;. First, and at a level of regulatory policy, a number of regulators have made the case that regulation should be proportionate and that some form of de minimis exemption would be appropriate to exempt those companies that are so small that the regulatory requirements would not be a proportionate response to the potential harm caused by unregulated behaviour.</p>
  <?php paragraphLink('K',8,6,10); ?>Second, it has been argued that it makes sense to concentrate any required remedies on large companies:<?php footnoteRef('K',8,11); ?>
<blockquote>&#8220;Large news publishers have voices far louder, with significantly greater impact than any individual. They have the power to frame and influence public opinion and public understanding. They also have exceptional power to seriously harm private citizens through their influence.&#8221; </blockquote>It is further argued that making some form of standards regulation compulsory only for large companies, as well as concentrating the remedy on the source of the harm, would distinguish between freedom of expression, which would remain entirely unconstrained, and &#8216;corporate speech&#8217; which &#8216;due to its power and influence ought to be accountable&#8217;.<?php footnoteRef('K',8,12); ?></p>
  <?php paragraphLink('K',8,6,11); ?>The arguments for some form of de minimis exemption are strong. There will be few who think that a parish magazine or small newsletter should be compulsorily subject to a regulatory system. Such publications will simply never have the resources to join a regulatory body, or to provide the sort of internal governance systems and compliance returns that are appropriate for much larger organisations. Equally, they are unlikely to give rise to the level of harm that a substantially larger publisher might. On the one hand, it is possible for a very small organisation to make some defamatory remark or breach privacy and they are, and should remain, subject to the law should they do so. However, the worst harm is done to an individual, or society, once those inaccuracies or defamations are published and read more widely. The most significant damage is done by the use of the megaphone and the power of large brands to influence public understanding and opinion.</p>
  <?php paragraphLink('K',8,6,12); ?>Thus the principle of setting a size related limit above which regulation should apply is simple enough. The difficult question, inevitably, is where that limit should be set.</p>
  <?php paragraphLink('K',8,6,13); ?>This could be looked at in two ways. First, a simple economic measure could be considered. This could take into account revenues, market share and circulation. The Media Standards Trust suggests that companies meeting the definition of a small company or group for the purposes of the Companies Act 2006 should remain outside regulation. Another suggestion was that any company not large enough to be required to register for VAT should be exempt from regulation.</p>
  <?php paragraphLink('K',8,6,14); ?>The alternative approach would be to consider a measure based more on the impact and influence of a publication. I have argued that a free press is important because of the influence that it can have over the nation&#8217;s understanding of issues and events.<?php footnoteRef('K',8,13); ?> That importance has attracted privileges that the press can rely on in terms of privileged access to Parliament and the courts, privileged protection for sources, privileged exemptions from the data protection regime and privileged defences in relation to defamation. It must also be the case that the influence and privileges of the press bring some form of accountability.</p>
  <?php paragraphLink('K',8,6,15); ?>The Inquiry has heard from editors that they are accountable to their readers, and, to no small extent, on a commercial basis to their shareholders or proprietors. But accountability to the paper&#8217;s own readership cannot be confused with accountability to the public more generally in relation to activities that go wider than their influence on readers: that is because the activities that are the subject of complaint relate to the treatment of third parties or the publication of inaccurate or defamatory material.</p>
  <?php paragraphLink('K',8,6,16); ?>Effective independent regulation would provide a level of accountability in relation to standards that would not in any way interfere with the freedom of an editor to publish any material that he or she wanted to publish, but would encourage governance systems, to avoid legal and standards breaches, and generate potential consequences should standards be breached.</p>
  <?php paragraphLink('K',8,6,17); ?>Using this rationale for independent standards regulation, it follows that, when considering who should not be able to opt out of standards regulation, the measure to be used should be a materiality threshold based on influence. The Report sets out elsewhere the issues involved in measuring the relevant parts of the media market to understand whether there is sufficient plurality in the market.<?php footnoteRef('K',8,14); ?></p>
  <?php paragraphLink('K',8,6,18); ?>In that Chapter, I refer to the various metrics that Ofcom proposes using to measure plurality, including availability, consumption and impact. It is entirely possible that some similar combination of measures of influence, in particular consumption and impact, would be appropriate in considering whether it would be proportionate for a news publisher to be expected not to be able to opt out of compliance with independently set standards.</p>
  <?php paragraphLink('K',8,6,19); ?>This is a complex and technical question and my only purpose is to identify the options. Either of these approaches might serve as a starting point, but, if the Government were to find it necessary to put a system of backstop regulation in place, I would recommend that they should conduct a detailed consultation on the matter of precisely where and how the line should be drawn: that is precisely the type of line that Ofcom would be able to draw.</p>
  <?php paragraphLink('K',8,6,20); ?>It is my clear view that, wherever the line is to be drawn, all the national daily and Sunday titles should fall within the regulatory system. Equally, regional and local titles with a significant readership should be included within the system. It is more difficult to be clear about what types of online service clearly should be inside or outside of a regulatory system. However, it would clearly be appropriate that websites providing news coverage aimed substantially at a UK audience, with a substantial stable audience should be covered by any new regulatory system.</p>
  <?php paragraphLink('K',8,6,21); ?>Any definitions would need to apply at the group level, to ensure that where there are many small publications under the control of one organisation they are potentially included within the regulatory system. This could place differential costs of regulatory compliance on independent local or regional titles and those of their competitors that are part of a larger group. Although I recognise the need for consultation, on the face of it, it is not unreasonable to expect a publishing group of any size to be able to institute appropriate governance mechanisms that might not be necessary or proportionate in the case of much smaller and simpler operations. The aim of putting a size threshold on the regulatory system would be to ensure that regulation was not disproportionate and did not act as a barrier to freedom of expression, not to provide a route to evasion for those who should be within the system.</p>
  <?php sectionAnchor('K',8,7); ?>My views</h2>
 <?php paragraphLink('K',8,7,1); ?>A backstop regulator would only be required if either the whole of the press industry had failed to accept the principle of independent regulation and thus failed to organise an independent body meeting the proposed statutory requirements or a significant proportion of the press (and, in particular, any of the national press) had refused to engage with an independent regulator. This would be a serious indictment of the ability and willingness of the industry to engage with standards regulation by any means short of direct compulsion and, as I have said, would undeniably reinforce the need for some statutory system of standards to be put in place.</p>
  <?php paragraphLink('K',8,7,2); ?>I repeat, as I have made very clear that, by a very long way, my preferred solution, and hence my recommendation, is that the industry should come together to construct a system of independent regulation that could be recognised. If it does so, there will be no need for a backstop regulator.</p>
  <?php paragraphLink('K',8,7,3); ?>However, if some or all of the industry were not prepared to adopt that position, I do not accept that they should expect the public to settle for less, much less escape standards regulation altogether. More significantly, if the possibility exists that a significant provider of press like services could avoid independent regulation without consequence, then there would simply be no incentive for an unwilling industry collectively to deliver it. My personal view, therefore, is that there may be a need for the realistic prospect of a backstop regulator being established.</p>
  <?php paragraphLink('K',8,7,4); ?>I think it is reasonable and proportionate to expect all publishers to comply with the standards of conduct required by the law. I also think it reasonable and proportionate to require the press, which enjoys many benefits in the public interest, to accept the obligations of the sort of public interest standards, over and above the minimum requirements of the law, which they have already described to some extent in their past codes, and which they purport to take seriously and live up to. These standards must reinforce the rights of free speech and of the press to pursue whatever stories that they consider appropriate in whatever way they see fit; they must also respect the legitimate rights and interests of the public, individually and collectively.</p>
  <?php paragraphLink('K',8,7,5); ?>Second, in relation to the consequences of failure to comply, I am sure that they would have to exist and must be real. I therefore do not consider that it would be appropriate to adopt the &#8216;do nothing&#8217; option, relying only on generic incentives to encourage membership of an independent regulatory body. Neither do I consider that simple publication by a regulator of an adverse judgment would be sufficient. The provision of a &#8216;complainants champion&#8217; service might be useful in relation to those who suffer breach of their civil rights by the media, but this would be an expensive and partial solution to the problems posed by standards breach. In my opinion it would be better that some statutory backstop regulator be given the powers to enforce standards, including powers to require publication of apologies and corrections, the power to investigate concerns of serious standards breach and the power to impose fines (proportionate to the gravity of any breach and the means to pay) in respect of serious or systemic breaches of standards (or failure to publish a required apology or correction).</p>
  <?php paragraphLink('K',8,7,6); ?>Third, in respect of who should apply these consequences, my clear expectation is that Ofcom would be given this role: it is by far and away the best placed to do so.</p>
  <?php paragraphLink('K',8,7,7); ?>Finally, in respect of these to whom provisions should apply, I would consider that the basic concept of &#8216;press like services&#8217; as described above should be considered. In addition, I do think it makes sense to apply backstop regulation, if required, only to those organisations of a sufficient size, and with sufficient impact, to make accountability to society an important issue. I would suggest that Ofcom would have to be tasked with developing appropriate metrics along the lines I have set out above.</p>
  </div>

